### ISSUE TITLE
Checks failed because of test_tracking

### ISSUE THREAD

**Issue by tonyke1993** [opencv/opencv_contrib#1005]
The checks of my pull requests always failed because of a test called "test_tracking". My changes have nothing to with this module. It leads to failure for different systems even for the same pull requests. It seems that this test fails randomly. Anyone knows what is going on?

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
Yes, we know about this sporadic test failure. Just ignore it, we will restart these builds.

**Comment by mshabunin** [comment]
Should be fixed in #1009
