### ISSUE TITLE
Bug in padding_layer.cpp

### ISSUE THREAD

**Issue by Madgeeno** [opencv/opencv_contrib#1007]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

I think I found a bug in `padding_layer.cpp` at `line 66`. 
The `int i` in the `for` loop hides previous declaration. I replaced it with the following code:

        for(int j = 0; j < srcDstRanges.size(); j++)
        {
            if(!srcDstRanges[j].first.empty())
            {
                srcRanges[dim] = srcDstRanges[j].first;
                dstRanges[dim] = srcDstRanges[j].second;
                Mat dst = outputs[i].matRef()(&dstRanges[0]);
                Mat src = inputs[i]->matRef()(&srcRanges[0]).clone();
                src.copyTo(dst);
            }
        }

**Comment by dkurt** [comment]
Hello, @Madgeeno ! It might be useful to know how you found it. What kind of model did you use? Or you can write a simple test by yourself where it appears.
