### ISSUE TITLE
Issue building dnn modules

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv/opencv_contrib#1012]
When building OpenCV contrib modules, especially dnn_modern, with latest versions of both master and contrib repo, I get the following error at 48% of build:

> /home/spu/Documents/github/opencv_contrib_dev/modules/dnn_modern/src/caffe_converter.cpp:185:33: error: no matching function for call to ‘tiny_dnn::network<tiny_dnn::sequential>::predict()’
>      auto result = net_->predict();
>                                  ^

Anyone has an idea on how to continue? For now I will disable the tiny_dnn inclusion.

Then when disabling, building breaks down at

```
Building CXX object modules/cudalegacy/CMakeFiles/opencv_test_cudalegacy.dir/test/TestDrawRects.cpp.o
/home/spu/Documents/github/opencv_dev/modules/stitching/src/cuda/multiband_blend.cu(93): error: Within a __device__/__global__ function, only __shared__ variables may be marked "static"

[ 90%] Built target opencv_test_cudaimgproc
1 error detected in the compilation of "/tmp/tmpxft_00004d79_00000000-7_multiband_blend.cpp1.ii".
```

From this[ Q&A](http://answers.opencv.org/question/128555/error-with-multiband_blendcu-compiling-opencv-320-on-ubuntu-1510-with-cuda-75/) it seems I am not the only one with this issue.

**Comment by elianlaura** [comment]
In my case, even with path of TINYDNN_INCLUDE_DIR,  previusly compiled, I got the same error.

**Comment by StevenPuttemans** [comment]
@elianlaura Same here!

**Comment by berak** [comment]
i'm pretty sure, that this is a typo, something went amiss [here](https://github.com/opencv/opencv_contrib/blob/master/modules/dnn_modern/src/caffe_converter.cpp#L185) . it should be:

    auto result = net_->predict(vec);

**Comment by StevenPuttemans** [comment]
@berak I will try the fix and see if it works!
