### ISSUE TITLE
TensorFlow example work in some PC and does not work in some other PC

### ISSUE THREAD

**Issue by pirahansiah** [opencv/opencv_contrib#1024]
I compile the latest version of OpenCV (GitHub) in two PC and run the TensorFlow example without any problem. Also, I clean install windows 10 without any cuda and compile OpenCV without change or modify anything in Cmake with visual studio 2017 and the tensorflow example work fine and give proper results.
 However, in some other PC the TensorFlow example give random result.

I tested with and without GPU
 I tested compile and copy dll files
 I tested with visual studio 2015 and 2017
 I tested with windows 7 and windows 10

in all cases work in some PC and does not work in another (random result).Is there any difference between 5 and 6 generation CPU

**Comment by pirahansiah** [comment]
OpenCL is the problem. You need to disable the OpenCL.

**Comment by arrybn** [comment]
OpenCL was disabled in the code. Now the module is passed through 39 tests on Win32&64, Linux and Mac and all is working - no problems
