### ISSUE TITLE
how to delete an object in a multitracker

### ISSUE THREAD

**Issue by macheski** [opencv/opencv_contrib#1025]
hi everyone:
   I have run the multitracker sample already.In my codes, an motion detection is implemented followed by the multitracker. When a new moving object is detected, i add the object into the tracker by using trackers.add(frame,objects),and it works too.
  But sometimes the tracking failed or tracked after another object, can i delete the wrong object and create a new one?But I have not found such an interface.
  Are there any other ways to solve the problem? 
 Even if the tracking is always right, but when the objects disappeared finally, is the object still maintained by the tracker or deleted automatically?
 Thanks! Waiting for the answers!   oRz

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Arroosh** [comment]
Hello @macheski 
I'm facing same problem. Have you solved this problem? If so, kindly share with me solution or some suggestions how to handle this situation.

Thanks in advance

**Comment by Arroosh** [comment]
Hello @macheski 
I'm facing the same problem. Please share with me solution or some suggestions how to handle this situation.

Thanks in advance

**Comment by inigolarranaga** [comment]
the same problem for me..
any solutions?

**Comment by bitcurian** [comment]
The multitracker class is a naive implementation. The only way to clear all the objects that're currently tracked by it is to use tracker.clear() and then instantiate a new instance with the objects to be tracked.

This needs to be fixed by adding a method to selectively `remove` specific objects.

**Comment by Damon2019** [comment]
I also met the same problem. Have you solved it?
