### ISSUE TITLE
Wrong allocFlags without OpenCL

### ISSUE THREAD

**Issue by pi-null-mezon** [opencv/opencv_contrib#1032]
It seems that there is a mistake in the last snapshot of the opencv_dnn module in [fully_connected_layer at line 76](https://github.com/opencv/opencv_contrib/blob/master/modules/dnn/src/layers/fully_connected_layer.cpp#L76):
```` c++
int allocFlags = useOpenCL ? Blob::ALLOC_UMAT : Blob::ALLOC_UMAT;
````
should be: 
```` c++
int allocFlags = useOpenCL ? Blob::ALLOC_UMAT : Blob::ALLOC_MAT; 
````

**Comment by arrybn** [comment]
Thank you! OpenCL was temporary disabled and all related stuff was removed from the code. So, I think it's possible to close this issue. We will keep this bug in mind
