### ISSUE TITLE
Module opencv_tracking disabled because opencv_dnn dependency can't be resolved!

### ISSUE THREAD

**Issue by Alberl** [opencv/opencv_contrib#1036]
I run opencv-3.2.0/platforms/ios/build_framework.py with command:
./build_framework.py --contrib ../../opencv_contrib ios

But "opencv2.framework" not generate tracking module, I find follow log:
-- Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags
-- Module opencv_tracking disabled because opencv_dnn dependency can't be resolved!

I want to use the KCF and TLD algorithm in opencv_tracking, how to use it on ios ?

**Comment by alalek** [comment]
Need to make `opencv_dnn` dependency optional for tracking module.

**Comment by Alberl** [comment]
Thank you very much! @alalek

**Comment by arvids-p** [comment]
Any workaround for this issue? I need to get OpenCV 3.2 working with tracking.
