### ISSUE TITLE
Compile error in module dnn_modern

### ISSUE THREAD

**Issue by bermond** [opencv/opencv_contrib#1070]
Found another compile error when trying to build OpenCV:

```
[ 40%] Building CXX object modules/dnn_modern/CMakeFiles/opencv_dnn_modern.dir/src/caffe_converter.cpp.o
In file included from /usr/include/tiny_dnn/network.h:39:0,
                 from /usr/include/tiny_dnn/tiny_dnn.h:30,
                 from /home/user/abs/opencv-noffmpeg-git/src/opencv_contrib/modules/dnn_modern/src/caffe_converter.cpp:48:
/usr/include/tiny_dnn/nodes.h:32:36: fatal error: cereal/types/utility.hpp: No such file or directory
 #include <cereal/types/utility.hpp>
                                    ^
```

##### System information (version)
- **OpenCV** => git master (currently at 3.2.0.r332.gc1007c7276)
- **OpenCV contrib modules** => git master (currently at 3.2.0.r160.g58f7afcb)
- **tiny-dnn** => 1.0.0a3
- **Operating System / Platform** => Arch Linux x86_64
- **Compiler** => gcc 6.3.1

##### Steps to reproduce
Attached. Complete output also provided.
I hope you're not annoyed in receiving these compile errors that I'm reporting :)

[opencv-dnn_modern-steps.txt](https://github.com/opencv/opencv_contrib/files/851928/opencv-dnn_modern-steps.txt)
[opencv-dnn_modern-output.txt](https://github.com/opencv/opencv_contrib/files/851922/opencv-dnn_modern-output.txt)

**Comment by alalek** [comment]
The same problem - this module doesn't track dependencies. It can be built with some exact version only. Any version is accepted of tiny-dnn, because there is no compatibility check during CMake stage.

**Comment by bermond** [comment]
Thank you.

**Comment by sovrasov** [comment]
@bermond This error is strange. `Cereal` dependency should be disabled in CMake. Try #1075. Probably it's better to integrate downloading of tiny-dnn's sources in CMake.

**Comment by bermond** [comment]
@sovrasov 
Thank you for the reply.

I have tiny-dnn installed (in `/usr/include` default system path). Although it's installed, it was needed to use `-DTINYDNN_ROOT` to point to where the downloaded tiny-dnn sources are located to be able to compile. Being so, this option seems mandatory for compilation. I was thinking that it was needed only for users that don't have it installed because I was getting `Looking for tiny_dnn.h - found` and `Found tiny-dnn in: /usr/include`. It really looks logical to integrate tindy-dnn sources into CMake download.

Actually, applying the patch from #1075 _breaked_ the achieved compilation, showing me this at final stage:
```
[100%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
[100%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
Generator error: unable to resolve base dnn2_BaseConverter for dnn2_CaffeConverter
Generator error: unable to resolve base dnn2_BaseConverter for dnn2_CaffeConverter
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:332: modules/python3/pyopencv_generated_include.h] Error 255
make[1]: *** [CMakeFiles/Makefile2:5401: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/build.make:332: modules/python2/pyopencv_generated_include.h] Error 255
make[1]: *** [CMakeFiles/Makefile2:5301: modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

Same CMake options as above, except for the CPU options that now cannot be used anymore.
OpenCV is now at version 3.2.0.r360.gf70cc29ed.

**Comment by sovrasov** [comment]
I've just forgot to add `CV_WRAP` at proper place. Dynamic library containing the module was built but python wrappers generator failed. Now it's fixed.

**Comment by ravispatil** [comment]
Hello, facing issue with building dnn_modern.
