### ISSUE TITLE
cv::ximgproc::weightedMedianFilter fails with mask containing 0's

### ISSUE THREAD

**Issue by llschloesser** [opencv/opencv_contrib#1086]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Mac OS X 64 Bit
- Compiler => Apple Clang

##### Detailed description

The function cv::ximgproc::weightedMedianFilter is happy only when the mask contains all non-zeros. I believe this is inherent to the implementation and has nothing to do with system parameters. Also note that this function might be better off as a class - fewer memory allocations, de-allocations. 

##### Steps to reproduce

 Use this function with any mask containing zeros.

**Comment by sovrasov** [comment]
I've wrapped the function into python and tried to process an image with non-trivial mask containing zeros:
```
img = cv2.imread(sys.argv[1])
mask = np.ones((img.shape[0], img.shape[1]), np.int8)
cv2.fillConvexPoly(mask, np.array([(100, 100), (140, 100), (100, 140), (200, 200)]), 0)
cv2.imshow('mask', mask)
filtered = cv2.ximgproc.weightedMedianFilter(img, img, 9, mask = mask)
filtered2 = cv2.ximgproc.weightedMedianFilter(img, img, 9)
cv2.imshow('filter', filtered - filtered2)
cv2.waitKey()
```
Output images are different, depending on mask, so I can't reproduce this problem. More details are required.

**Comment by llschloesser** [comment]
My use case is to smooth a disparity image. My guide image is the left camera image and the mask is generated from the invalid disparities where mask=0 if invalid and mask=1 if valid. I have verified that a mask so generated is correct. I am using the `cv::threshold` function to generate the mask. 

If I set the mask to all ones (what the function does anyway), then it does not crash. If I set the mask to all zeros, then the program crashes. If some of the pixels are zeros it also crashes. Unfortunately, I don't have my environment set up for diving deep into this (debugger, etc) at the moment, but I will try to set that up soon. The only other info I can offer is images, but I am not sure that is helpful.

```
//cv::Mat mask = cv::Mat::zeros( leftStereo.size(), CV_8U ); // bad!
cv::Mat mask = cv::Mat::ones( leftStereo.size(), CV_8U ); // good!
//cv::Mat mask;
//cv::threshold( disparity8, mask, 0, 1, cv::THRESH_BINARY ); // bad!
cv::Mat filtered;
cv::ximgproc::weightedMedianFilter( leftStereo, disparity8, filtered, 3, 20, cv::ximgproc::WMFWeightType::WMF_EXP, mask );
```

**Comment by sovrasov** [comment]
May be `leftStereo` and `disparity8` iamges can help to reproduce the problem.
Sample with a mask generated using `threshold` is also works for me:
```
img = cv2.imread(sys.argv[1])#3-channel BGR image
_, mask = cv2.threshold( img, 125, 1, cv2.THRESH_BINARY )
cv2.imshow('mask', (mask*255))
filtered = cv2.ximgproc.weightedMedianFilter(img, img, 9, mask = mask)
filtered2 = cv2.ximgproc.weightedMedianFilter(img, img, 9)
cv2.imshow('filter', filtered)
cv2.waitKey()
```

**Comment by sovrasov** [comment]
Update: I've reproduced the issue. The problem is likely to be in unitialized histogram when most of mask pixels are zeros.

**Comment by sovrasov** [comment]
@llschloesser try the latest commit from #1098.

**Comment by llschloesser** [comment]
@sovrasov I tried it, looks good. Thank you!
