### ISSUE TITLE
cv2.cpp compiler error

### ISSUE THREAD

**Issue by tofaa** [opencv/opencv_contrib#1087]
**## while compiling opencv 3.2.0 with visual studio 11 and cmake there only one error as shown 
please help fast
 what should i do ?** 

1>------ Build started: Project: opencv_python2, Configuration: Release Win32 ------
1>  cv2.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xmemory0(605): error C2129: static function 'PyObject *pyopencv_from<cv::Matx44d>(const T &)' declared but not defined
1>          with
1>          [
1>              T=cv::Matx44d
1>          ]
1>          C:\Users\tofaa\Downloads\Compressed\opencv\sources\opencv-3.2.0\opencv-3.2.0\modules\python\src2\cv2.cpp(207) : see declaration of 'pyopencv_from'
========== Build: 0 succeeded, 1 failed, 101 up-to-date, 0 skipped ==========
```

**Comment by alalek** [comment]
More details are required:
- CMake stdout (from clean build)

**Comment by jwarchol** [comment]
I'm seeing the same issue. Here's my cmake output. Very new to the project, so if there some other output you mean please point me in the right direction and I'll provide whatever I can. Thanks!

[cmake_output.txt](https://github.com/opencv/opencv_contrib/files/993181/cmake_output.txt)

**Comment by adelpit** [comment]
Yup, same exact issue for me too.  Any assistance would be greatly appreciated

```
1>------ Build started: Project: opencv_python2, Configuration: Release x64 ------
1>  cv2.cpp
1>D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xmemory0(605): error C2129: static function 'PyObject *pyopencv_from<cv::Matx44d>(const T &)' declared but not defined
1>          with
1>          [
1>              T=cv::Matx44d
1>          ]
1>          D:\opencv\opencv_master\modules\python\src2\cv2.cpp(207) : see declaration of 'pyopencv_from'
========== Build: 0 succeeded, 1 failed, 49 up-to-date, 0 skipped ==========
```

**Comment by adelpit** [comment]
FYI I found the [following info](https://stackoverflow.com/questions/43038410/opencv-python-build-error-on-visual-studio-11-and-windows-7/43313702#43313702?newreg=b1680209f6d249c8b989c183878c75c2) which helped resolve the issue for me.

An excerpt from Vadik's solution:

> This is because pyopencv_cv_ppf_match_3d_ppf_match_3d_ICP_registerModelToScene does not know what to do with 4x4 matrix when it calls pyopencv_from func. You need to add s stub(!) to modules/python/src2/cv2.cpp something like "code" below, until developer add real function.

```
//your do_not_forget comment here
template<>
PyObject* pyopencv_from(const Matx44d& m) 
{

    Mat temp, *p = (Mat*)&m;
    if(!p->u || p->allocator != &g_numpyAllocator)
    {
        temp.allocator = &g_numpyAllocator;
    }
    PyObject* o = (PyObject*)p->u->userdata;
    Py_INCREF(o);
    return o;
}
```
