### ISSUE TITLE
ximgproc compile chicken and egg

### ISSUE THREAD

**Issue by prlw1** [opencv/opencv_contrib#1090]
Compiling today's git master of opencv_contrib (in a 3.2.0 release opencv), I see:

In file included from /tmp/pkgsrc/graphics/opencv/work.x86_64/opencv-3.2.0/modules/ximgproc/opencv_perf_ximgproc_pch_dephelp.cxx:1:0:
/usr/src/local/opencv_contrib/modules/ximgproc/perf/perf_precomp.hpp:15:32: fatal error: opencv2/ximgproc.hpp: No such file or directory
compilation terminated.

Which sort of makes sense: ximgproc hasn't been built and installed yet, so won't be in the standard include path. I suspect that the rule in README.md:

$ cd <opencv_build_directory>
$ cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>

might not be quite that easy? (Need to add -I to uninstalled source?)

**Comment by alalek** [comment]
More details are required:
- CMake stdout (from clean build)
- failed command line via `make VERBOSE=1` (without any `-j` option)
- also try to disable precompiled headers (`cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...`) and build again

**Comment by StevenPuttemans** [comment]
Just to give a heads up, i just grabbed latest master of both repos and did a complete compilation with opencv_contrib. The building worked just fine on Ubuntu16.04 64 bit Release.

**Comment by prlw1** [comment]
Steven: when you did your full compilation, did that computer already have opencv installed (in which
case I would expect everything to work), or did you zap every trace of it first? (I mentioned chicken and egg...)

**Comment by alalek** [comment]
> already have opencv installed

This is not required to build OpenCV.
Moreover, "usage" of installed OpenCV (with unknown version) may provide broken binaries.
`make VERBOSE=1` will help you to find real reason.

**Comment by StevenPuttemans** [comment]
And to confirm, no, before I do a clean install, I manually remove all the opencv libs from my system. But as stated by @alalek this is not even necessary.
