### ISSUE TITLE
Build error: unable to download missing libraries

### ISSUE THREAD

**Issue by meder411** [opencv/opencv_contrib#1099]
##### System information (version)

- OpenCV => stable 3.2 tarball
- Operating System / Platform => Ubuntu 14.04
- Compiler => NA (CMake configuration issue)

For the contrib modules I am using the most recent git pull

##### Detailed description

I get this error when trying to build OpenCV:

>  CMake Error at /usr/local/src/opencv-3.2.0/cmake/OpenCVUtils.cmake:1043 (file):
>    file DOWNLOAD cannot open file for write.
>  Call Stack (most recent call first):
>    /usr/local/src/opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download)
>    /usr/local/src/opencv_contrib/modules/dnn/CMakeLists.txt:5 (include)
> 
> 
> 
>  CMake Error at /usr/local/src/opencv-3.2.0/cmake/OpenCVUtils.cmake:1047 (message):
>    Failed to download .  Status=
>  Call Stack (most recent call first):
>    /usr/local/src/opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download)
>    /usr/local/src/opencv_contrib/modules/dnn/CMakeLists.txt:5 (include)
> 

I checked the OpenCVFindLibProtobuf file in question and it appears a dead link may be the problem?

In this snippet of code (lines 27-40)

```
if(PROTOBUF_FOUND)
  # nothing
else()
  set(PROTOBUF_CPP_PATH "${OpenCV_BINARY_DIR}/3rdparty/protobuf")
  set(PROTOBUF_CPP_ROOT "${PROTOBUF_CPP_PATH}/protobuf-3.1.0")
  ocv_download(FILENAME "protobuf-cpp-3.1.0.tar.gz"
               HASH "bd5e3eed635a8d32e2b99658633815ef"
               URL
                 "${OPENCV_PROTOBUF_URL}"
                 "$ENV{OPENCV_PROTOBUF_URL}"
                 "https://github.com/google/protobuf/releases/download/v3.1.0/"
               DESTINATION_DIR "${PROTOBUF_CPP_PATH}"
               STATUS res
               UNPACK RELATIVE_URL)
```

The link that it tries to download from (                 "https://github.com/google/protobuf/releases/download/v3.1.0/") is dead. I get a 404 error trying to navigate there.

I also get a similar error from xfeatures2d

> 
>  CMake Error at /usr/local/src/opencv-3.2.0/cmake/OpenCVUtils.cmake:1043 (file):
>    file DOWNLOAD cannot open file for write.
>  Call Stack (most recent call first):
>    /usr/local/src/opencv_contrib/modules/xfeatures2d/cmake/download_boostdesc.cmake:22 (ocv_download)
>    /usr/local/src/opencv_contrib/modules/xfeatures2d/CMakeLists.txt:8 (download_boost_descriptors)
> 
>  CMake Error at /usr/local/src/opencv-3.2.0/cmake/OpenCVUtils.cmake:1047 (message):
>    Failed to download .  Status=
>  Call Stack (most recent call first):
>    /usr/local/src/opencv_contrib/modules/xfeatures2d/cmake/download_boostdesc.cmake:22 (ocv_download)
>    /usr/local/src/opencv_contrib/modules/xfeatures2d/CMakeLists.txt:8 (download_boost_descriptors)

Both these modules have been updated with merged PRs recently. Perhaps there's an incompatibility?

##### Steps to reproduce

contrib repo cloned to `/.../src/opencv_contrib`
OpenCV 3.2 unzipped to `/.../src/opencv/`
`mkdir build`
in .../src/opencv/build ---> called `ccmake ..`, set the `OPENCV_EXTRA_MODULES_PATH=/.../src/opencv_contrib/modules` and tried to configure.

**Comment by alalek** [comment]
> file DOWNLOAD cannot open file for write.
> /usr/local/src/opencv-3.2.0
> /usr/local/src/opencv_contrib

`/usr/local/src` is usually owned by root and it is write-protected.

OpenCV build system caches downloaded files in the source directory.
To move OpenCV download cache you should use `OPENCV_DOWNLOAD_PATH` CMake variable.

**Comment by meder411** [comment]
I executed everything as `sudo`

**Comment by alalek** [comment]
@meder411 Keep both opencv and opencv_contrib repositories up-to-date.
