### ISSUE TITLE
How to use Data Transformation in opencv ?

### ISSUE THREAD

**Issue by nelfy** [opencv/opencv_contrib#1103]
Hi, All,

I got two problems:

**1. how to use Data Transformation in OpenCV?** 

I trained a model with digits, and I've set the Data Transformation to "Pixel", 
it works very well in Digits After testing new images.

But in OpenCV, it doesn't work, always give me Class 0, I've used following codes

```
			cv::dnn::Blob inputBlob = cv::dnn::Blob(mat_resized);
			m_net.setBlob(".data", inputBlob);
			m_net.forward();

			cv::dnn::Blob blob = m_net.getBlob("softmax");
```

Then I trained a model without "Data Transformation" (set to none), the above codes work well.

So my question is how to use the "Data Transformation" in OpenCV dnn ?

2. OpenCV dnn forward is slow.

After searching, I found two solutions, one is to customize cv::gemm function, another one is using the Caffe windows binaries. 
I am using opencv 3.1, I saw 3.2 was out, any improvement? 

Thank you very much,

**Comment by sovrasov** [comment]
A lot of changes was introduced into dnn module since 3.1. Try to use latest master.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
