### ISSUE TITLE
how to compile the opencv_contrib  text module 

### ISSUE THREAD

**Issue by chrisjyw** [opencv/opencv_contrib#1106]
hey,

i want to use the opencv_contrib text module to achieve the scene text recognition , but when i compile the text module , it generate the error. and which directory should i put the file of trained_classifierNM1.xml?

**Comment by chrisjyw** [comment]
@hey everyone ， i am looking forward to your reply.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
