### ISSUE TITLE
about the module of text to achieve scene text recognition 

### ISSUE THREAD

**Issue by chrisjyw** [opencv/opencv_contrib#1107]
when  i use the module of text to achieve the scene text recognition .

after the compilation , i run the program  it generate errors , how could i fix it ?
![096d341bc42de02ee62f58f41a59197b](https://cloud.githubusercontent.com/assets/26089601/24608399/b6098b2e-1876-11e7-9632-379813d06132.png)

**Comment by chrisjyw** [comment]
@everyone ,  anyone could help me ? thanks a lot in advanced.

**Comment by catree** [comment]
Your file is [here](https://github.com/opencv/opencv_contrib/blob/3.2.0/modules/text/samples/trained_classifierNM1.xml). If you just want to run an example, you have the sample [textdetection.cpp](https://github.com/opencv/opencv_contrib/blob/3.2.0/modules/text/samples/textdetection.cpp).

**Comment by berak** [comment]
try to run the testcase from the text/samples folder (where trained_classifierNM1.xml is)

**Comment by sourabh2k15** [comment]
put the trained_classifierNM1.xml file from opencv_contrib/modules/text/samples folder in whichever folder your code is in

**Comment by alalek** [comment]
Try to uncomment [this line](https://github.com/opencv/opencv/blob/bd5a6f8af2413cab9833f7b2ef4eb5dc25440ce5/modules/ts/src/ts.cpp#L759) and rebuild OpenCV to "have fun".

These text tests work [fine](http://pullrequest.opencv.org/buildbot/builders/master-contrib-lin64/builds/10061).

**Comment by chrisjyw** [comment]
@alalek 
hey thanks a lot for your reply.  i use the opencv_contril  scene text recognition , and generate the executive file  end - to -end recognition , how could i use the webcamera to achieve the function that when i use the webcamera , it could recognize the scene texts.

**Comment by chrisjyw** [comment]
<img width="716" alt="ask" src="https://cloud.githubusercontent.com/assets/26089601/24676646/117314f4-1984-11e7-9e80-e2959ed59c05.png">
my file is like this . could i use the command  ./webcam_demo  to achieve the function recognize the scene texts directly ?

**Comment by chrisjyw** [comment]
@everyone
I try use the command , but it fails ...   my work environment is  virtualbox  ubuntu14.04
