### ISSUE TITLE
MSLIC has undeterministic behaviour

### ISSUE THREAD

**Issue by jexner** [opencv/opencv_contrib#1109]
##### System information (version)
- OpenCV => 3.x (master branch)
- Operating System / Platform => Ubuntu 16.04 LTS
- Compiler => gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

##### Detailed description
When rerunning the MSLIC implementation multiple times on the same image, it sometimes results in a very bad segmentation. To me the algorithm looks like it should be deterministic. But the implementation sometimes yields unreasonable bad results. I assume there is a problem with accessing invalid memory.

Expected and sometimes actual outcome:
![mslic_normal](https://cloud.githubusercontent.com/assets/5003917/24710951/e45d0920-1a1e-11e7-839d-1dc2eb73830d.png)

Bad result:
![mslic_bug](https://cloud.githubusercontent.com/assets/5003917/24710953/e68437e6-1a1e-11e7-8df2-29d859121cbe.png)

##### Steps to reproduce

Take any image and run MSLIC on it.

**Comment by cbalint13** [comment]
* Can your sample program you used ?

* My result on your image is fine:
![opencv-sample-mslic](https://cloud.githubusercontent.com/assets/3974360/24723521/91865c4c-1a50-11e7-96d3-03c88f89c364.png)

**Comment by cbalint13** [comment]
@jexner ,

  * You said "re-runing",  are you calling iterate() multiple times ? This is not possible, actually temporary state of internal engine is not saved, thus a re-call to iterate() would not work. I can fix this for all except SEEDS but will take a little time.

**Comment by jexner** [comment]
@cbalint13 With "re-running" I meant creating a new superpixel object or re-running a compiled program. I suspected an uninitialized variable and checked with valgrind. It reported access to uninitialized variables in [line 477](https://github.com/jexner/opencv_contrib/blob/698b6852a7fe5d9e852a47efa14edc93b014df70/modules/ximgproc/src/slic.cpp#L477) and [line 1447](https://github.com/jexner/opencv_contrib/blob/698b6852a7fe5d9e852a47efa14edc93b014df70/modules/ximgproc/src/slic.cpp#L1447). They're both accessing `m_iterations` which is never initialized. It seems like #1110 fixes the issue for me. Can you verify that `itrnum` is the correct value for `m_iterations`?

**Comment by jexner** [comment]
@cbalint13 My example code is pretty straight forward:
```.cpp
            cv::Ptr<cv::ximgproc::SuperpixelSLIC> slic = cv::ximgproc::createSuperpixelSLIC(
                        combined,
                        cv::ximgproc::MSLIC,
                        superpixel_size,
                        slic_ruler);
            slic->iterate(iterations);
            slic->enforceLabelConnectivity(superpixel_size);
            slic->getLabels(labels);
            nb_labels = slic->getNumberOfSuperpixels();
            slic->getLabelContourMask(contour_mask);
```
