### ISSUE TITLE
CMake Errors: dnn and xfeatures2d modules

### ISSUE THREAD

**Issue by rbfigueira** [opencv/opencv_contrib#1125]
I follow the steps and when I press configure the second time I get errors:

CMake Error at cmake/OpenCVUtils.cmake:1043 (file): file DOWNLOAD cannot open file for write. Call Stack (most recent call first): opencv_contrib-master/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download) opencv_contrib-master/modules/dnn/CMakeLists.txt:5 (include)

CMake Error at cmake/OpenCVUtils.cmake:1047 (message): Failed to download . Status= Call Stack (most recent call first): opencv_contrib-master/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download) opencv_contrib-master/modules/dnn/CMakeLists.txt:5 (include)

Configuring incomplete, errors occurred! See also "/Users/rbfigueira/Desktop/Crazyflie/opencv-3.2.0/build/CMakeFiles/CMakeOutput.log". See also "/Users/rbfigueira/Desktop/Crazyflie/opencv-3.2.0/build/CMakeFiles/CMakeError.log

CMake Error at cmake/OpenCVUtils.cmake:1043 (file):
  file DOWNLOAD cannot open file for write.
Call Stack (most recent call first):
  opencv_contrib-master/modules/xfeatures2d/cmake/download_boostdesc.cmake:22 (ocv_download)
  opencv_contrib-master/modules/xfeatures2d/CMakeLists.txt:8 (download_boost_descriptors)

CMake Error at cmake/OpenCVUtils.cmake:1047 (message):
  Failed to download .  Status=
Call Stack (most recent call first):
  opencv_contrib-master/modules/xfeatures2d/cmake/download_boostdesc.cmake:22 (ocv_download)
  opencv_contrib-master/modules/xfeatures2d/CMakeLists.txt:8 (download_boost_descriptors)

**Comment by alalek** [comment]
https://github.com/opencv/opencv_contrib/issues/1100#issuecomment-290340228

**Comment by zakaria-chahboun** [comment]
## (OpenCV 3.2.0)

For Solve ***("CMake Error at cmake/OpenCVUtils.cmake:1043  (file): ... ")*** Error In Cmake
Follow This Steps:

[1] Go to:
"C:\\<b>[PATH_TO_YOUR_OPENCV]</b>\sources\3rdparty\ffmpeg\downloads"

[2] Add Three Folders :

	-First Folder Name (MD5): f081abd9d6ca7e425d340ce586f9c090
		put into : opencv_ffmpeg.dll

	-Second Folder Name (MD5): a423363a6eb76d362ca6c406c96c8db6
		put into : opencv_ffmpeg_64.dll 

	-Third Folder Name (MD5): 5346ae1854fc7aa569a722e85af480ec
		put into : ffmpeg_version.cmake

[3] Check if MD5 of dlls/files is correct ^^

-------- IMPORTANT --------
[!] ***With Other Version of OpenCV***, You Can Follow The Same Steps But With ***"Different" MD5 Hash***.
You Can Know The MD5 Hash Code For Each File In This Path:

[-1-] "C:\\<b>[PATH_TO_YOUR_OPENCV]</b>\sources\3rdparty\ffmpeg\ffmpeg.cmake"

Open it, And You Get *Informaions About All Things*.

-------- Manually Download --------
Go To *[-1-] Section*, And Find This Line :

***FFMPEG_BINARIES_COMMIT*** "2a19d0006415955c79431116e4634f04d5eb5a74"

And Get *MD5* For Your Version, For Example Here I'm Get *"2a19d0006415955c79431116e4634f04d5eb5a74"*.

Finally, Put This *MD5* In The Link Below, 
And Replace ***[MD5_CODE]*** With  Your MD5 Code ^^
Also Replace The Name Of *Each File* Of Required List To Download In <b><em>[FILE]</em></b>.

**`https://raw.githubusercontent.com/opencv/opencv_3rdparty/MD5_CODE]/ffmpeg/[FILE]`**

-------- Examples &#x1F49C;--------
*opencv_ffmpeg.dll:*

`https://raw.githubusercontent.com/opencv/opencv_3rdparty/2a19d0006415955c79431116e4634f04d5eb5a74/ffmpeg/opencv_ffmpeg.dll`

*opencv_ffmpeg_64.dll:*
`https://raw.githubusercontent.com/opencv/opencv_3rdparty/2a19d0006415955c79431116e4634f04d5eb5a74/ffmpeg/opencv_ffmpeg_64.dll`

*ffmpeg_version.cmake:*
`https://raw.githubusercontent.com/opencv/opencv_3rdparty/2a19d0006415955c79431116e4634f04d5eb5a74/ffmpeg/ffmpeg_version.cmake`

**Comment by zakaria-chahboun** [comment]
This a complete answer ❤️ 

https://stackoverflow.com/questions/44943015/how-do-i-compile-opencv-ffmpeg-dll-file-using-mingw-on-windows-10-64-bit/47833262#47833262
