### ISSUE TITLE
softcascade training

### ISSUE THREAD

**Issue by kingloo2014** [opencv/opencv_contrib#1130]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => win7
- Compiler => visual studio

##### Detailed description

when I trained my own softcascade model using waldboost, the error will be happened definetely. So I debug the project, I found that when all negative sample consumed, it means the variant 'pos' equal to 0 at 320 line in file of waldboost.cpp, the bug will come out again.

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example
    //waldboost.cpp

 or attach as .txt or .zip file
-->

**Comment by StevenPuttemans** [comment]
@kingloo2014 there are several things missing

- the error, what is it exactly?
- waldboost is not the same as the original softcascade, which was removed due too licensing issues

**Comment by berak** [comment]
@kingloo2014 , you got the name wrong (waldboost is not related to softcascade or dpm)

but apart from that, this seems to be [still the same bug](https://github.com/opencv/opencv_contrib/issues/633) also [here](https://github.com/opencv/opencv_contrib/issues/741)
