### ISSUE TITLE
Is FaceRecognition is available in Java wrapper?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv_contrib#1133]
##### System information (version)

- OpenCV = 3.2
- Operating System / Platform = Windows 64 Bit
- Compiler = Visual Studio 2015

##### Detailed description

I want to use FaceRecognition class for training and recognizing faces, but I did see this class in the Java wrapper. Why it is no availble and how to solve this problem. Thanks!!

**Comment by berak** [comment]
java support for the face module is not enabled by default. you might try to do it manually, by 
changing [the cmakelists.txt here](https://github.com/opencv/opencv_contrib/blob/master/modules/face/CMakeLists.txt#L2) so it says:

    ocv_define_module(face opencv_core opencv_imgproc opencv_objdetect WRAP python java)

then re-run cmake && make && make install. 
good luck !

**Comment by Bahramudin** [comment]
@berak hmm... it make sense. Thank you for the reply! In the feature it will be better that the OpenCV team  enable the modules whenever they are available in Java, because there are a lot of modules when don't support Java, so the user don't know which is supported which is not. Thanks!

**Comment by Bahramudin** [comment]
@berak one more question, the face module in Java is fully supported or partly?

**Comment by berak** [comment]
> the face module in Java is fully supported or partly?

sorry, i have no idea. you're the first person to test this in a long time, i guess.

**Comment by berak** [comment]
@Bahramudin , any updates on this ? did it work ?

**Comment by Bahramudin** [comment]
@berak Yes it work, but not as good as I as expecting. There are lot of false recognition I don't know why.

**Comment by catapulveda** [comment]
@Bahramudin  You can help?
I have never used a compiler or visual studio. I use windows 10 x64 and am building opencv_contrib with the original OpencCV fonts. But I get an error in the Windows console:

C:\Users\Nelson Castiblanco\Desktop\opencv\build>cmake -DOPENCV_EXTRA_MODULES_PATH=C:\Users\Nelson Castiblanco\Desktop\opencv_contrib\modules "C:\Users\Nelson Castiblanco\Desktop\opencv\sources"

-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:127 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:127 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/Nelson Castiblanco/Desktop/opencv/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Nelson Castiblanco/Desktop/opencv/build/CMakeFiles/CMakeError.log".

**Comment by Bahramudin** [comment]
@catapulveda Hi, Do you want to build OpenCV from source for java?

**Comment by catapulveda** [comment]
@Bahramudin Si, pero no he podido compilar .jar y .dll con las nuevas clases para reconocimiento facil, el modulo "faces" desde opencv_contrib.

**Comment by berak** [comment]
@catapulveda can you move your question to http://answers.opencv.org/questions/ ? we can help you much better from there (you don't have a library bug, so your question should not go here)

@Bahramudin , what about closing this issue ? the answer was: "YES, it is possible".

**Comment by catapulveda** [comment]
Si, es posible.

**Comment by Bahramudin** [comment]
@berak  Yes, please close it.

**Comment by Bahramudin** [comment]
@catapulveda What are you saying, please write in English.

**Comment by catapulveda** [comment]
@Bahramudin  I Speak spanish. I From Colombia. I do not Speak spanish. I am use Google Traductor. I will publish my question in another new post. Thanks.

**Comment by berak** [comment]
@catapulveda please let's move this discussion to http://answers.opencv.org, finally

**Comment by PriteshDasInfomedia** [comment]
unknown faces not recognition in opencv 3.2.0
