### ISSUE TITLE
Extend current niBlackThreshold to handle general Local Adaptive Threshold algorithms, Sauvola at the least

### ISSUE THREAD

**Issue by saskatchewancatch** [opencv/opencv_contrib#1138]
I'd like to extend our current implementation of [Niblack's](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/niblack_thresholding.cpp) to implement Sauvola's binarization technique.

Current niBlackThreshold signature:

`void niBlackThreshold( InputArray _src, OutputArray _dst, double maxValue, int type, int blockSize, double delta )`

Desired signature that would minimally change niBlackThreshold and maintain backwards compatibility:

`void niBlackThreshold( InputArray _src, OutputArray _dst, double maxValue, int type, int blockSize, double delta, bool useSauola = false )`

Extremely desirable signature that would be slightly more substantial but would allow for newer Niblack-inspired binarization algos to be implemented in the future without much refactoring and moving around:

`void niBlackThreshold( InputArray _src, OutputArray _dst, double maxValue, int type, int blockSize, double delta, int method = NIBLACK )`, where `method` is an enum that specifies a couple of popular NIblack-inspired binarization techniques, like Wolf's and NICK.

The reason I focus on modifying niBlackThreshold is that the formula most people associate with Sauvola document binarization is very similar to Niblack's and another source just for Sauvola's seems unwarranted.

**Desired outcome:** At the least, I'd like to submit a PR for the first signature, but before doing that, I want to leave this Issue open to foster a little community discussion on such a change, take in other's ideas as well.

**Comment by saskatchewancatch** [comment]
Reference info:

1. Extremely desirable would be something like a fusion between what [mschoeneck](https://github.com/opencv/opencv_contrib/pull/181) has posted under the original Niblack PR and niBlackThreshold.

2. See [this paper](http://www.ppgia.pucpr.br/~facon/Binarizacao/NiblackComparison.pdf) for an overview of some Niblack-inspired algos and the formula for Sauvola as it's popularly employed for binarization of scanned documents.

**Comment by amroamroamro** [comment]
can be closed, PR #1146 is merged.

**Comment by saskatchewancatch** [comment]
Thanks all for the help with this one.
