### ISSUE TITLE
dnn.hpp: No such file or directory

### ISSUE THREAD

**Issue by Usernamezhx** [opencv/opencv_contrib#1148]
**the command line:** `cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_IPP=OFF -D OPENCV_EXTRA_MODULES=../opencv_contrib/modules -D CMAKE_INSTALL_PREFIX=/usr/local ..`

And I am sure the position of the opencv_contrib

this is the cmake information(part):
```
 --     3rdparty dependencies:
 --
 --   OpenCV modules:
 --     To be built:                 core flann imgproc ml objdetect photo video                                     imgcodecs shape videoio highgui superres ts features2d calib3d stitching videost                                    ab python2
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures                                    2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudaw                                    arping cudev java python3 viz
```
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => centos7
- Compiler => gcc
##### Detailed description
when i test a sample:
```
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
using namespace cv;
using namespace cv::dnn;
```
**The gcc command line:**  `gcc -I/usr/local/include/opencv -L/usr/local/lib/ -lopencv_highgui -lopencv_core -lopencv_imgcodecs  -lstdc++ classify.cpp -o classify`

**After that it will show that:**
`dnn.hpp: No such file or directory`
**+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++**

**+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++**
**I change the package opencv_contrib and then i cmake with the command:**

` cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_IPP=OFF -D OPENCV_EXTRA_MODULES=/root/opencv-build/opencv-master/opencv_contrib/modules -D CMAKE_INSTALL_PREFIX=/usr/local ..`

the cmake will show that:
`-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- Caffe:   NO
-- Protobuf:   YES
-- Glog:   YES
-- freetype2:   YES
-- harfbuzz:    YES
-- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
CMake Error at cmake/OpenCVDownload.cmake:56 (message):
  ERROR: ocv_download() unsupported arguments:
  PACKAGE;v3.1.0/protobuf-cpp-3.1.0.tar.gz;HASH;bd5e3eed635a8d32e2b99658633815ef;URL;https://github.com/google/protobuf/releases/download/;DOWNLOAD_DIR;/root/opencv-build/opencv-master/opencv_contrib/modules/dnn/.download
Call Stack (most recent call first):
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  opencv_contrib/modules/dnn/CMakeLists.txt:35 (include)

-- Configuring incomplete, errors occurred!
See also "/root/opencv-build/opencv-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/opencv-build/opencv-master/build/CMakeFiles/CMakeError.log". `

if that means the opencv_conrib was not installed ? 
thanks in advanced.

**Comment by dkurt** [comment]
Try to use `OPENCV_EXTRA_MODULES_PATH` instead `OPENCV_EXTRA_MODULES`.

**Comment by adrianosantospb** [comment]
I have a similar error. The build seems to work, but when I try to import (#include <opencv2/dnn.hpp>), I got the error message. 
So, I'm using a Dockerfile with the nvcr.io/nvidia/tensorrt:20.08-py3 image. 

The build log is:


-- General configuration for OpenCV 4.4.0 =====================================
--   Version control:               4.4.0
-- 
--   Extra modules:
--     Location (extra):            /workspace/opencv_contrib/modules
--     Version control (extra):     4.4.0
-- 
--   Platform:
--     Timestamp:                   2021-05-10T17:13:14Z
--     Host:                        Linux 5.4.0-72-generic x86_64
--     CMake:                       3.14.4
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               RELEASE
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--       SSE4_1 (17 files):         + SSSE3 SSE4_1
--       SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (31 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--       AVX512_SKX (7 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ standard:                11
--     C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
--     C++ flags (Release):         -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed  
--     Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed  
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          m pthread cudart_static -lpthread dl rt nppc nppial nppicc nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 alphamat cnn_3dobj cvv hdf java js julia matlab ovis python2 sfm viz
--     Applications:                tests perf_tests apps
--     Documentation:               NO
--     Non-free algorithms:         YES
-- 
--   GUI: 
--     GTK+:                        YES (ver 3.22.30)
--       GThread :                  YES (ver 2.56.4)
--       GtkGlExt:                  NO
--     OpenGL support:              NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
--     WEBP:                        build (ver encoder: 0x020f)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
--     JPEG 2000:                   build Jasper (ver 1.900.1)
--     OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2_2)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      YES (2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (57.107.100)
--       avformat:                  YES (57.83.100)
--       avutil:                    YES (55.78.100)
--       swscale:                   YES (4.8.100)
--       avresample:                YES (3.7.0)
--     GStreamer:                   YES (1.14.5)
--     v4l/v4l2:                    YES (linux/videodev2.h)
-- 
--   Parallel framework:            pthreads
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Intel IPP:                   2020.0.0 Gold [2020.0.0]
--            at:                   /workspace/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
--     Intel IPP IW:                sources (2020.0.0)
--               at:                /workspace/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
--     Lapack:                      NO
--     Eigen:                       NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
-- 
--   NVIDIA CUDA:                   YES (ver 11.0, CUFFT CUBLAS FAST_MATH)
--     NVIDIA GPU arch:             75
--     NVIDIA PTX archs:            75
-- 
--   cuDNN:                         YES (ver 8.0.2)
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                /workspace/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3 (ver 3.6.9)
--     Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.9)
--     numpy:                       /usr/local/lib/python3.6/dist-packages/numpy/core/include (ver 1.19.1)
--     install path:                lib/python3.6/dist-packages/cv2/python-3.6
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:                          
--     ant:                         NO
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Install to:                    /usr/local


My install file is:

#!/bin/sh
apt-get purge libopencv-dev *opencv* -y

# Note: It is best to install libraries in /prefix to make the use of docker multistage easier.
apt-get update
apt-get clean
apt-get install -y --no-install-recommends g++ git

# install OPENCV WITH GSTREAMER
apt-get purge *gstreamer* -y
apt-get install -y --no-install-recommends libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-ugly gstreamer1.0-libav

git clone --depth 1 --branch 4.4.0 https://github.com/opencv/opencv_contrib.git

git clone --depth 1 --branch 4.4.0 https://github.com/opencv/opencv
cd opencv
mkdir build && cd build

cmake \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D INSTALL_PYTHON_EXAMPLES=OFF \
  -D INSTALL_C_EXAMPLES=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D WITH_CUDA=ON \
  -D WITH_CUDNN=ON \
  -D OPENCV_DNN_CUDA=ON \
  -D ENABLE_FAST_MATH=1 \
  -D CUDA_FAST_MATH=1 \
  -D WITH_OPENGL=ON \
  -D CUDA_ARCH_BIN=7.5 \
  -D CUDA_ARCH_PTX=7.5 \
  -D WITH_CUBLAS=1 \
  -D BUILD_OPENCV_python3=ON \
  -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
  -D HAVE_opencv_python3=ON \
  ..

make -j$(nproc)
make install
ldconfig
pkg-config --modversion opencv4

cd .. && mkdir ../licenses/opencv && cp LICENSE ../licenses/opencv/
cd .. && rm -rf opencv

RVAL=false
OPENCV_FILE="/usr/local/lib/libopencv_core.so"
if [ ! -f $OPENCV_FILE ]; then
    echo "OPENCV was not correctly installed."
    exit 1
fi

**Comment by berak** [comment]
@Usernamezhx , @adrianosantospb 

please check the cmake output carefully, again.
it tries to download files, so you need a working network connection.
in the 1st case, it could not load the protobuf files, so the dnn module, depending on that, was excluded from the build

**Comment by AVOMIXS** [comment]
bonjour  : 
D'accorde Mais pourquoi pas on fait dans le system Windows Parcque je trouve pas le file dnn.hpp et
Merci.
