### ISSUE TITLE
ERROR: ocv_download() unsupported arguments:

### ISSUE THREAD

**Issue by Usernamezhx** [opencv/opencv_contrib#1149]
I want to install the opencv_contrib .
**and then i input the command line :** 
`cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_IPP=OFF -D OPENCV_EXTRA_MODULES=/root/opencv-build/opencv-master/opencv_contrib/modules -D CMAKE_INSTALL_PREFIX=/usr/local ..`

**The cmake will show that:**
`-- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
CMake Error at cmake/OpenCVDownload.cmake:56 (message):
  ERROR: ocv_download() unsupported arguments:
  PACKAGE;v3.1.0/protobuf-cpp-3.1.0.tar.gz;HASH;bd5e3eed635a8d32e2b99658633815ef;URL;https://github.com/google/protobuf/releases/download/;DOWNLOAD_DIR;/root/opencv-build/opencv-master/opencv_contrib/modules/dnn/.download
Call Stack (most recent call first):
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  opencv_contrib/modules/dnn/CMakeLists.txt:35 (include)

-- Configuring incomplete, errors occurred!
See also "/root/opencv-build/opencv-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/opencv-build/opencv-master/build/CMakeFiles/CMakeError.log".
`
 System information (version)
- OpenCV => 3.1
- Operating System / Platform => centos7
- Compiler => gcc
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**the next is the cmake erro log:**

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Determining if the include file sys/videoio.h exists failed with the following output:
Change Dir: /root/opencv-build/opencv-master/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec3578117361/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3578117361.dir/build.make CMakeFiles/cmTryCompileExec3578117361.dir/build
gmake[1]: Entering directory `/root/opencv-build/opencv-master/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/opencv-build/opencv-master/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3578117361.dir/CheckIncludeFile.c.o
/usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden  -O3 -DNDEBUG   -o CMakeFiles/cmTryCompileExec3578117361.dir/CheckIncludeFile.c.o   -c /root/opencv-build/opencv-master/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/root/opencv-build/opencv-master/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:25: fatal error: sys/videoio.h: No such file or directory
 #include <sys/videoio.h>
                         ^
compilation terminated.
gmake[1]: *** [CMakeFiles/cmTryCompileExec3578117361.dir/CheckIncludeFile.c.o] Error 1
gmake[1]: Leaving directory `/root/opencv-build/opencv-master/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec3578117361/fast] Error 2

**Comment by mshabunin** [comment]
If you want to use latest _opencv_contrib_, you should also update _opencv_ repository to the latest version (_master_).

**Comment by Usernamezhx** [comment]
@mshabunin  yeah it works . after that when i run make . it will show that:
Linking CXX shared library ../../lib/libopencv_tracking.so
[ 61%] Built target opencv_tracking
Linking CXX shared library ../../lib/libopencv_xphoto.so
[ 61%] Built target opencv_xphoto
Linking CXX static library ../../lib/libopencv_ts.a
[ 61%] Built target opencv_ts
make: *** [all] Error 2

many thanks

**Comment by Usernamezhx** [comment]
i forget that my opencv version is 3.2.0 so i download the 3.0.0 opencv_contrib

**Comment by mshabunin** [comment]
_opencv_contrib@3.0.0_ is not compatible with _opencv@3.2.0_, as I said you have to sync both repositories to the same tag (3.2.0, 3.1.0, 3.0.0 or master) and then do a clean build (in empty build directory).

**Comment by Usernamezhx** [comment]
thank you very much. i have had this question for two days. the most import thing i think is the "clean build" : )

**Comment by Usernamezhx** [comment]
I am so sorry that . I have to bother you again.
I test a sample:
`#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
using namespace cv;
using namespace cv::dnn;
`
And then i input the command line:
`gcc -I/usr/local/include/opencv -L/usr/local/lib/ -lopencv_highgui -lopencv_core -lopencv_imgcodecs  -lstdc++ classify.cpp -o classify
`
it will show that:
`fatal error: opencv2/dnn.hpp: No such file or directory`

I check the folder :/usr/local/include/opencv2 but i dont find the dnn.hpp.  i find the dnn.hpp was in the `/root/opencv-build/opencv-master/opencv_contrib/modules`
should I copy the dnn.hpp to the /usr/local/include/opencv2 ?
I am new . thanks very much.

**Comment by Usernamezhx** [comment]
the cmake output: 
To be built: cudev core cudaarithm flann imgproc ml objdetect video cudabgsegm cudafilters cudaimgproc cudawarping imgcodecs photo shape videoio cudacodec highgui ts features2d calib3d cudafeatures2d cudalegacy cudaobjdetect cudaoptflow cudastereo stitching superres videostab python2

if that means  the opencv_contrib was not installed?

**Comment by Usernamezhx** [comment]
you are right .the "sync " is just as important as the "clean build" . i install the opencv3.1.0 and the opencv_contrib 3.1.0 . yeah it works .thank you very much.
