### ISSUE TITLE
Bug in sfm or data incorrect ?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1154]
Hi,

I am able to use sfm module on windows. I can run all examples. But I have got a problem using reconstruct function. I have got this exception 

> OpenCV Error: Assertion failed (data && dims <= 2 && (rows == 1 || cols == 1) && rows + cols - 1 == n && channels() == 1) in cv::Mat::operator class cv::Vec<double,2>, file G:\Lib\opencv\modules\core\include\opencv2/core/mat.inl.hpp, line 1221

I think you can reproduce using this code : 
```
    vector<Mat> pt2d;
    pt2d.push_back((Mat_<double>(1, 16) << 64., 298., 560., 405., 271., 298., 514., 417., 651., 435., 561, 373., 497., 369., 350., 241));
    pt2d.push_back((Mat_<double>(1,16)<< 62., 272., 5.1840002441406250e+02, 4.1817602539062500e+02, 268.,266., 513., 359., 649., 371., 559., 227., 495., 229., 346., 205.));
    pt2d.push_back((Mat_<double>(1, 16) << 362., 185., 650., 304., 160., 248., 364., 192., 78., 146., 357.,176., 247., 402., 76., 149));
    pt2d.push_back((Mat_<double>(1, 16) << 668., 296., 5.9040000915527344e+01, 3.8880001831054688e+02,6.5520001220703125e+02, 2.6496002197265625e+02,
        4.9447909545898438e+02, 2.9382092285156250e+02,4.6800003051757813e+01, 9.9600006103515625e+01,5.1120001220703125e+02, 4.1280001831054688e+02,
        1.3080000305175781e+02, 2.4600001525878906e+02,2.6873861694335938e+02, 1.1197442626953125e+02 ));
    for (int i=0;i<pt2d.size();i++)
        pt2d[i]= pt2d[i].reshape(2);
    vector<Mat> Rs_est, ts_est, points3d_estimated
    Mat  K = (cv::Mat_<float>(3, 3) << 350, 0, 240, 0, 350, 360, 0, 0, 1);
    reconstruct(pt2d, Rs_est, points3d_estimated, K, true);

```
In debugging problem is [here ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/src/simple_pipeline.cpp#L62) and should be something like points2d[frame].col(track).at<Vec2d>(0)

There is also this [post ](http://answers.opencv.org/question/138230/wasteful-code/). I don't understand this [function](http://answers.opencv.org/question/138230/wasteful-code/)

**Comment by LaurentBerger** [comment]
@sovrasov thanks. Label is bug. Have you got a bug when you replace [line ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/src/simple_pipeline.cpp#L62) by Vec2d track_pt = pt2d[0].col(0).at<Vec2d>(0); ?

**Comment by sovrasov** [comment]
In the provided code `pt3d` is undefined. Does bug happen on any set of 3d points?

**Comment by LaurentBerger** [comment]
Sorry I forgot to update my code. Now I don't understand [thoses lines ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/src/simple_pipeline.cpp#L232-L248). How is it possible to copy a Vec3d in a Mat wint only one columm and one channel?

**Comment by sovrasov** [comment]
`Vec3d point3d` is converted into `Mat` first and then deep copy to `points3d[i]` is performed. `points3d[` is used here as `OutputArrayOfArrays`.

**Comment by LaurentBerger** [comment]
Thanks I don't know how it is possible but I will dig in source code. Now I think a PR is necessary with pt2d[0].col(0).at(0) and with[ thoses lines ](http://answers.opencv.org/question/138230/wasteful-code/)

**Comment by sovrasov** [comment]
Setting all indexes to zeros in `pt2d[0].col(0)` is strange approach. You will process the same data within the loop many times.

**Comment by LaurentBerger** [comment]
sorry I write const Vec2d track_pt = points2d[frame].col(track).at<Vec2d>(0); instead of const Vec2d track_pt = points2d[frame].col(track);

**Comment by LaurentBerger** [comment]
About first post finally datas are incorrect It must be a mat with two rows and N column (for N points). I close this comment.

**Comment by EnoahNetzach** [comment]
Sorry, is this still considered a bug?

It happens to me even when I simply copy the code from [this official tutorial](http://docs.opencv.org/3.2.0/d4/d18/tutorial_sfm_scene_reconstruction.html)..

**Comment by LaurentBerger** [comment]
My issue is not clear. I think you should forget it and not use it as a referrence. there was a bug in InitGoogleLogging() but if you clone opencv_contrib today (2017 june ) there is no problem. You should ask your question on answers.opencv.org before open a new issue

**Comment by EnoahNetzach** [comment]
@LaurentBerger thanks, but the last time I've rebuilt the docker container was yesterday, and it clones **opencv_contrib** every time.

I still have that exact message popping up...

**Comment by LaurentBerger** [comment]
What is exactly your programm and error message ?

**Comment by EnoahNetzach** [comment]
I just found out it was simply that [this official tutorial](http://docs.opencv.org/3.2.0/d4/d18/tutorial_sfm_scene_reconstruction.html) is a bit outdated, [this](https://github.com/opencv/opencv_contrib/blob/5e4d9b0be74b86db56af18075632ee201e027926/modules/sfm/samples/scene_reconstruction.cpp) being the correct, and working, one.

@LaurentBerger thanks, and sorry for the trouble.

**Comment by LaurentBerger** [comment]
No problem and tell me if you can reconstruct 3d scene without problem  : 
 `./example_sfm_scene_reconstruction image_paths_file.txt 350 240 360`

**Comment by atomoclast** [comment]
Is this still a bug?

I too am experiencing this same error.

I try to pass in a vector<Mat> as the first argument for the `reconstruct` function. 

I can run all the example code no issues.

**Comment by atomoclast** [comment]
@LaurentBerger Hi, I actually opened an issue on answers.opencv.org and [I belive you replied](http://answers.opencv.org/question/189300/dynamic-structure-from-motion-with-sfm-module-in-opencv_contrib/).

I'm getting this exact error, when I try and use the `reconstruct` function when I pass it a `vector<Mat>`, where every element is a greyscale image opened and loaded into a `Mat` data type. 

Perhaps I am using it wrong? 

When I try and pass it that that vector, I get: 

```
OpenCV(3.4.1) Error: Assertion failed (data && dims <= 2 && (rows == 1 || cols == 1) && rows + cols - 1 == n && channels() == 1) in operator cv::Vec<_Tp, m>, file /home/andrew/opencv_source/opencv/modules/core/include/opencv2/core/mat.inl.hpp, line 1282
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1) /home/andrew/opencv_source/opencv/modules/core/include/opencv2/core/mat.inl.hpp:1282: error: (-215) data && dims <= 2 && (rows == 1 || cols == 1) && rows + cols - 1 == n && channels() == 1 in function operator cv::Vec<_Tp, m>
```

What is confusing me is that one of the arguments is:

`InputArrayOfArrays     points2d`

and that's defined as:

`points2d   Input vector of vectors of 2d points (the inner vector is per image).`

Does that mean we flatten the Mat data type of each image into a vector of vectors or something? I don't get it.

Do I need to use a feature matcher and find matching features, then put those features in this vector?

Either I'm not understanding what it means properly, or the documentation is a bit confusing. I'm rather new to OpenCV in C++.

**Comment by LaurentBerger** [comment]
Like in this `https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/samples/match_reconstruct.cpp#L84`?

**Comment by atomoclast** [comment]
@LaurentBerger Exactly like in that. I'm not sure what you're putting in that data type exactly? 

I see in line 32 that it is defined as a `vector<Mat>`

[I am weak in C++ versus Python, so I'm trying to get better]

I may just post what I've done to modify the example and how I am trying to use it for some help.

**Comment by atomoclast** [comment]
This is the slightly modified version of the tutorial I am trying to work with.

I zipped it since it won't let me upload a C++ file directly. 

[SfM.cpp.zip](https://github.com/opencv/opencv_contrib/files/1911012/SfM.cpp.zip)

**Comment by LaurentBerger** [comment]
back to [question](http://answers.opencv.org/question/189300/dynamic-structure-from-motion-with-sfm-module-in-opencv_contrib/)
