### ISSUE TITLE
use dnn

### ISSUE THREAD

**Issue by mysayalHan** [opencv/opencv_contrib#1160]
I write code as http://docs.opencv.org/master/d5/de7/tutorial_dnn_googlenet.html
However, I got the problems as follows:
OpenCV Error: Assertion failed ((size_t)innerSize == innerSize0) in cv::dnn::FullyConnectedLayerImpl::allocate, file H:\opencv_new\opencv_contrib-master\modules\dnn\src\layers\fully_connected_layer.cpp, line 89
Who can help me? So much thanks!

**Comment by arrybn** [comment]
Hi, @mysayalHan. Maybe there is a input image size mismatch. Googlenet accepts 224x224 RGB images, so please check that you're feeding images of such size to the model.

**Comment by dkurt** [comment]
I think we can close it.
