### ISSUE TITLE
Error: `blobFromImage` was not declared in this scope

### ISSUE THREAD

**Issue by nitinkgp23** [opencv/opencv_contrib#1164]
In the tutorial described here
http://docs.opencv.org/trunk/d5/de7/tutorial_dnn_googlenet.html , 
```
Mat inputBlob = blobFromImage(img);   //Convert Mat to batch of images
net.setBlob(".data", inputBlob);        //set the network input
net.forward();                          //compute output
Mat prob = net.getBlob("prob");   //gather output of "prob" layer
```
an error comes 
```
error: ‘blobFromImage’ was not declared in this scope
Mat inputBlob = blobFromImage(img);   //Convert Mat to batch of images
```
```
In file included from /usr/local/include/opencv2/dnn.hpp:62:0,
                 from abc.cpp:2:
/usr/local/include/opencv2/dnn/dnn.hpp:248:22: note: candidate: void cv::dnn::Net::setBlob(cv::String, const cv::dnn::Blob&)
         CV_WRAP void setBlob(String outputName, const Blob &blob);
                      ^
/usr/local/include/opencv2/dnn/dnn.hpp:248:22: note:   no known conversion for argument 2 from ‘cv::Mat’ to ‘const cv::dnn::Blob&’
abc.cpp:64:27: error: conversion from ‘cv::dnn::Blob’ to non-scalar type ‘cv::Mat’ requested
     Mat prob = net.getBlob("prob");   //gather output of "prob" layer
```
I may understand the cause of the second error, but why is the function `blobFromImage` out of the scope, given that the line `Net net = dnn::readNetFromCaffe(modelTxt, modelBin);` doesn't throw any error?

Upon further examination, I found out that the functions which throw the same error, i.e. not defined in the scope, are
`cv::dnn::readNetFromTorch` , `cv::dnn::readNetFromTensorflow` , `cv::dnn::blobFromImage` , `cv::dnn::blobFromImages`
whereas, these functions throw no such error:
`cv::dnn::createTorchImporter` , `cv::dnn::readNetFromCaffe` , `cv::dnn::readTorchBlob` .

Being the functions of the same class, why is there such a difference?

##### System information (version)
Example
- OpenCV => 3.2
- Operating System / Platform => Ubuntu 16.04 LTS

**Comment by alalek** [comment]
Sample code is here: https://github.com/opencv/opencv_contrib/blob/master/modules/dnn/samples/caffe_googlenet.cpp

And it is compiled [successfully](http://pullrequest.opencv.org/buildbot/builders/master-contrib-lin64/builds/10100/steps/compile%20release/logs/stdio):
> canning dependencies of target example_dnn_caffe_googlenet
[ 38%] Building CXX object modules/dnn/CMakeFiles/example_dnn_caffe_googlenet.dir/samples/caffe_googlenet.cpp.o
Linking CXX executable ../../bin/example_dnn_caffe_googlenet
[ 38%] Built target example_dnn_caffe_googlenet

BTW, You should keep both opencv/opencv_contrib repositories "in sync".

**Comment by nitinkgp23** [comment]
I guess, there is some problem from my side. It doesn't compile in my system. Btw, what do you mean by keep both repositories "in sync"?

**Comment by alalek** [comment]
Both should have the same tag/branch(HEAD) or at least the same date of commits.

> /usr/local/include/opencv2/dnn.hpp

Also you should check that version was installed in your system.

**Comment by nitinkgp23** [comment]
Thanks :)

**Comment by dkurt** [comment]
It seems to me might be closed.
