### ISSUE TITLE
the error of layer Eltwise

### ISSUE THREAD

**Issue by tiankong1993** [opencv/opencv_contrib#1173]
I have meet this problem:OpenCV Error: Unspecified error (can't create layer "eltwise" of type "Eltwise") in cv::dnn:LayerData::getLayerData::getLayerInstance
Is it there is no network layer of eltwise?

**Comment by dkurt** [comment]
@tiankong1993, please provide more detailed description of the problem. How to reproduce it?

**Comment by tiankong1993** [comment]
I used the training model to extract the features and the program have the error that Unspecified error can't create layer "eltwise" of the type Eltwise.I want to ask is it the dnn of opencv have not the eltwise layer？

**Comment by dkurt** [comment]
@tiankong1993 , thank you! I mean what kind of network you use? What element-wise layers are there (sum, product)? What framework did you use for training?

**Comment by tiankong1993** [comment]
The framework is caffe .the model and deploy is downlad from https://github.com/AlfredXiangWu/face_verification_experiment/tree/master/model and https://github.com/AlfredXiangWu/face_verification_experiment/tree/master/proto respectively.LightenedCNN_B_deploy.prototxt and LightenedCNN_B.caffemodel is used.  And the element-wise layers are :
eltwise_param {
	operation: MAX
  }.
I used the training model of GoogleNet to extract the features but when i use his model the program have the error.can you help me work it out?

**Comment by dkurt** [comment]
Please could you check that your local opencv_contrib source code is actual according to GitHub repository?

**Comment by dkurt** [comment]
@tiankong1993 , please let us to help with your problem. If it was solved, we are going to close the issue.
