### ISSUE TITLE
DNN module now can not work with 1-channel input images

### ISSUE THREAD

**Issue by pi-null-mezon** [opencv/opencv_contrib#1184]
##### System information (version)
- OpenCV => 3.2 (snaphot at 24.05.2017)
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

@arrybn, thanks to the new [dnn::blobFromImage](https://github.com/opencv/opencv_contrib/blob/master/modules/dnn/src/dnn.cpp#L71) implementation all networks with the single-channel input (data blob) can not work now! Can you bring back this possibility?

P.S. It is also starnge that if you pass 3-channel image into the dnn::blobFromImage then last 4-th layer of the output blob could contain arbitrary noise not related with the input image. So, why this 4-layers blobs are used?

##### Steps to reproduce
You can reproduce issue by means of this networks [protos](https://github.com/AlfredXiangWu/face_verification_experiment/blob/master/proto) and [caffemodels](https://github.com/AlfredXiangWu/face_verification_experiment/tree/master/model)

**Comment by arrybn** [comment]
Hi, @pi-null-mezon. Thanks for reporting the issue. I'm working on a fix for it. Blobs with 4 dimensions need for batching when you want to process several images at one model launch

**Comment by pi-null-mezon** [comment]
Great news. Let me know if I can help.

**Comment by arrybn** [comment]
@pi-null-mezon, I've watched issue closely. It isn't necessary to use blobFromImage() function in your case. You can set your 1-channel Mat directly as input of model. Just pass it to Net::setBlob() function. blobFromImage() function is for reordering channels in 3-channel image which has been loaded by imread()

**Comment by arrybn** [comment]
I've got what's the problem. You need to create 4-dimensional blob from 1-channel image. I added this possibility to blobFromImage() function

**Comment by pi-null-mezon** [comment]
@arrybn I wanted to set gray image (1 channel) as input blob for "DeepFace_set003_net"
````
input: "data"
input_dim: 1
input_dim: 1
input_dim: 128
input_dim: 128
````
So, it seems that Net::setBlob() should work. I will check

**Comment by arrybn** [comment]
Try fix from this [PR](https://github.com/opencv/opencv_contrib/pull/1185)

**Comment by pi-null-mezon** [comment]
What if i pass one grayscale image inside modified [dnn::blodFromImages(...)](https://github.com/opencv/opencv_contrib/pull/1185/commits/b9f4141af9d99fa39d85e4ed7e9ba736f79633a3#diff-8dbd68358d1e92d5a7fbfa9536247868L94)? I mean your blob have 4 layers but I am pass data for only one of them. Do this 3 empty layers affect network output?

**Comment by arrybn** [comment]
I think you're talking about dimensions not layers. Network you're using accepts 4-dimensional blobs as inputs:
```
name: "DeepFace_set003_net"
input: "data"
input_dim: 20
input_dim: 1
input_dim: 128
input_dim: 128
```
So, you should create such 4-dim blob.
Dimensions are only a way of considering data. For example, you have continuous data block for 1024 float numbers. You can treat this data as blob with dimensions {1024} - 1-dim vector, {1;1024} - 2-dims matrix, {2;512} - also 2-dim matrix, {1;2;512} - also 2-dim matrix, but with specified channels, {2;4;8;64} - 2 elements of 4-channel matrices with spatial dimensions 8x64. As far as count of elements is constant, there is no effect on stored data. Transforming grayscale image into 4D blob in blobFromImages() doesn't change actual data, it just changes representation of this data.

**Comment by pi-null-mezon** [comment]
Thanks! I have read your code and now all everything fell into place in my head.

**Comment by pi-null-mezon** [comment]
@arrybn привет. Наконец я установил обновления для dnn модуля. И вот что я выяснил. Функция dnn::blobFromImage() теперь работает с одноканальными изображениями. Но! Дальше Cv_Assert валится уже отсюда:
````
OpenCV Error: Assertion failed (1 <= blobs.size() && blobs.size() <= 2) in cv::dnn::FullyConnectedLayerImpl::FullyConnectedLayerImpl, file C:\Programming\3rdParties\opencv321\opencv_contrib\modules\dnn\src\layers\fully_connected_layer.cpp, line 58
````
как с этим бороться?

**Comment by arrybn** [comment]
@pi-null-mezon 
I think I've faced such issues already. You're trying to load caffe model. And there is fully-connected layer in the end of the model. The problem is in .caffemodel file - it doesn't contain blob with weights for this FC layer. Caffe handles this case by initializing layer with random values and it happens in the beginning of training. But I think it isn't appropriate behavior in your case because you need trained model. See my answer [here](https://github.com/opencv/opencv_contrib/issues/912).
DNN module loads .caffemodel file - this file contains kind of a map with blob name as key and blob data as value. It's highly likely that there is a blob with trained weights in .caffemodel file, but it has another name. How can you know the name for a blob? You need to view content of this map in debug mode (debug CaffeImporter::extractBinaryLayerParms() function and see content of netBinary). It's highly likely that you find entry with name which is very similar to the problem FC layer name. Rename FC layer in .prototxt to name from .caffemodel file.

**Comment by lovemory** [comment]
[ERROR:0] global ../../../../modules/dnn/src/dnn.cpp (3268) getLayerShapesRecursively OPENCV/DNN: [Convolution]:(conv_0): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=1
[ERROR:0] global ../../../../modules/dnn/src/dnn.cpp (3271) getLayerShapesRecursively     input[0] = [ 1 1 416 416 ]
[ERROR:0] global ../../../../modules/dnn/src/dnn.cpp (3279) getLayerShapesRecursively     blobs[0] = CV_32FC1 [ 16 3 3 3 ]
[ERROR:0] global ../../../../modules/dnn/src/dnn.cpp (3281) getLayerShapesRecursively Exception message: OpenCV(4.3.0) ../../../../modules/dnn/src/layers/convolution_layer.cpp:341: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 1 in function 'getMemoryShapes'

terminating with uncaught exception of type cv::Exception: OpenCV(4.3.0) ../../../../modules/dnn/src/layers/convolution_layer.cpp:341: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 1 in function 'getMemoryShapes'

**Comment by alalek** [comment]
Message says that you should pass **color** image.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by namnguyendanh** [comment]
Now, opencv version 4.5.2, this error still. blobFromImage with 1-channels image can not work (gray image) :(

**Comment by dkurt** [comment]
@namnguyendanh, that's not true: https://github.com/opencv/opencv/blob/68d15fc62edad980f1ffa15ee478438335f39cc3/modules/dnn/src/dnn.cpp#L402
