### ISSUE TITLE
dnn: fix setBlob() for sucessive forward() calls in a loop

### ISSUE THREAD

**Issue by pleskovsky** [opencv/opencv_contrib#1189]
##### System information (version)

- OpenCV =>3.2
- Module = opencv_contrib\dnn
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

In a loop, where the Net::setBlob( ".data", cv::dnn::blobFromImage(...)); and Net::forward() are run consecuently, the forward() call breaks on the first layer set after the input layer.
It is due to input/output layer matching between the input data layer and the subsequent layer, which is caused upon the second call to Net::setBlob(...).

In order to set new input image, 
call to
    ```
ld.outputBlobs[pin.oid] = blob_.clone(); 
    ```
is used. The clone() function forwards the data pointer of the blob to the ld.outputBlobs[...] breaking any connections between the layer in an already configured (and allocated) Net.
Moreover, it does not effectively reuse the memory already allocated for the input layer.

It is suggested to use the cv::Mat::copyTo(...) function instead, or to fix the output blob dependences for the subsequent layers.
Suggestion 1 (dnn.cpp):

    void Net::setBlob(String outputName, const Mat &blob_)
    {
    ...
    //--- ld.outputBlobs[pin.oid] = blob_.clone(); 
    //--- impl->netWasAllocated = impl->netWasAllocated && prevShape == shape(blob_);
    impl->netWasAllocated = impl->netWasAllocated && prevShape == shape(blob_);
    if (impl->netWasAllocated)
       blob_.copyTo(ld.outputBlobs[pin.oid]);
    else
       ld.outputBlobs[pin.oid] = blob_.clone();     
     }

##### Steps to reproduce

    while (true){
       cv::Mat input = cv::mat::zeros(30,30, CV_8UC1);
       net->setBlob( ".data", cv::dnn::blobFromImage(input)  ); 
       net->Net::forward();
    }

**Comment by dkurt** [comment]
@pleskovsky , thank you for your attention! I've tried reproduce this issue with the latest versions of opencv and opencv_contrib. I haven't faced breaks or data freezes. Please, could you check that your local source code is actual?

**Comment by pleskovsky** [comment]
Hi, my DNN version was SHA-1: 78fabfe606d99e1dd1083c340457fe0e9d889a56
from 25/5/2017 17:50 (thus the evening before I wrote the patch).

The OpenCV was SHA-1: 19464a3ed826eb0d9865a102a5601f1833acffe8
from 23/5/2017 23:46.

**Sorry**, may be **I forgot** to mention that my first layer after the input was **elementwise layer**. I see the forward function includes the check:
'''
            CV_Assert(src.ptr() == dst.ptr() && src.isContinuous());
'''
Here, src is the input layer, dst is the prealocated memory from the first run of forward that also included the allocation and further dnn::Net set-up.

The issue is that on setBlob(...) the data changes just for the current (input) layer. In the subsequent layer (the elemenwise in my case), no data pointer update is made and thus the pointers do not match any more and forward() breaks. I didn't had time to check how the update of the subsequent layers should be done.

In any case, should the size of the input not change, then I believe that there is no need to call the clone() function. Instead, the copy to may be used and in principle you save one cv::Mat initialization.

Cheers!

**Comment by dkurt** [comment]
In some of PRs we have the future fix of it. i.e. https://github.com/opencv/opencv_contrib/pull/1105/files#diff-8dbd68358d1e92d5a7fbfa9536247868R891.
Please, could you try to apply this `setBlob` locally?

**Comment by pleskovsky** [comment]
Yes, it does work for me!
[note that I only updated the ``` setBlob ``` function]

**Comment by dkurt** [comment]
@pleskovsky , thanks! I'll notify you when changes will be merged.

**Comment by pleskovsky** [comment]
Thank you!

**Comment by dkurt** [comment]
@pleskovsky, Hi! PR #1205 with proposed changes was merged. Also added more usage with memory management. I would like if you could test it with your network. Thank you!

**Comment by pleskovsky** [comment]
I can confirm there are no problems.
