### ISSUE TITLE
Sfm and Viz in sample scene reconstruction

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1193]
Opencv 3.2.0-dev Windows 10 VS 2015 VTK 7.1.0

I cannot retrieve camera pose in sample [scenereconstruction ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/samples/scene_reconstruction.cpp)of module sfm.
In images given in folder data it is not easy to see problem. I use my own data in[ this folder](https://github.com/LaurentBerger/opencv_contrib/tree/sfmdata/modules/sfm/samples/data/images)
@PhilLab @edgarriba 
If you run sample : 
sfm-example-scene_reconstruction.exe imagessfm.txt 2763 517 501 for left camera  I can see this in viz window for left camera: 
![screenshot-1495976925](https://cloud.githubusercontent.com/assets/3591626/26529007/0030ca66-43b8-11e7-9a7d-dbc5dc454c8e.png)

I think it is wrong there is no image with this pose im my image list. 
Now If I change this line in  [scenereconstruction ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/samples/scene_reconstruction.cpp#L115)
`path.push_back(Affine3d(Rs_est[i],ts_est[i]));`
in
`path.push_back(Affine3d(Rs_est[i],ts_est[i]).inv());`

Now questions Does problem in image given exist or Is it me ?
If problem exist What is wrong matrix camera pose or pose must be inversed for viz?

Thanks for your answer.

**Comment by PhilLab** [comment]
The camera pose rendering always crashes on my system (Win x64 Visual Studio 2013) so I had to comment it out.
I also had problems with the [Sagrada Familia tutorial](http://docs.opencv.org/3.2.0/d4/d18/tutorial_sfm_scene_reconstruction.html) getting a completely wrong reconstruction (points collapsed to two clusters) using all four images and an okayish result when only using three (I cannot remember which three I used).

With my own scenes I was never able to get a plausible reconstruction. Before #1169 I always had the points collapse to several clusters and after this PR, they are a little more scattered but still not meaningful.

**Comment by LaurentBerger** [comment]
Before your PR it was possible. But that's not the problem. You want this parameter true and me false. I think a new method is necessary.  

If you want I can help you to solve your problem. Sfm in opencv is good tool (VS 2015 windows 10) and I haven't got problem using my intrinsic and distorsion parameters.
I inserted a new example [without matching ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/samples/match_reconstruct.cpp)have you try it?

**Comment by PhilLab** [comment]
Tried it but had to comment one of the cv::reconstruct because I built OpenCV before your PR #1159 . Result looks good for both reconstructions but camera rendering still crashes.

**Comment by LaurentBerger** [comment]
No message for me.  SFM Dependancy version are : 

> No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
> Found installed version of gflags: C:/Program Files/gflags/CMake
> Detected gflags version: 2.2.0
> Found required Ceres dependency: Eigen version 3.3.0 in G:/Lib/eigen-eigen
> No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
> Found installed version of glog: F:/lib/glog
> Detected glog version: 0.3.4
> Found required Ceres dependency: Glog in 
> Found Ceres version: 1.12.0 installed in: C:/Program Files/Ceres with components: [LAPACK, SchurSpecializations, OpenMP]
> Checking SFM deps... TRUE
> 

> C:\Users\Laurent.PC-LAURENT-VISI>G:\Lib\opencv\dll2015\bin\Debug\sfm-example-match_reconstruct.exe
> 
> ----------------------------
> 
> Reconstruction:
> ============================
> Estimated 3D points: 108
> Estimated cameras: 4
> Refined intrinsics:
> [1428, 0, 640;
>  0, 1428, 480;
>  0, 0, 1]
> 
> 3D Visualization:
> ============================
> Recovering points  ... [DONE]
> Recovering cameras ... [DONE]
> Rendering points   ... [DONE]
> Rendering Cameras  ... [DONE]
> 
> Press 'q' to close each windows ...

**Comment by PhilLab** [comment]
Okay, the difference seems to be the Ceres build:
```
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: C:/Program Files/gflags/CMake
-- Detected gflags version: 2.2.0
-- Found required Ceres dependency: Eigen version 3.3.2 in C:/DEVELOPMENT/3rdparty.git/Eigen/3.3.2
-- Found required Ceres dependency: glog
-- Found installed version of gflags: C:/Program Files/gflags/CMake
-- Detected gflags version: 2.2.0
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.12.0 installed in: C:/DEVELOPMENT/3rdparty.git/Ceres/1.12 with components: [CXSparse, SparseLinearAlgebraLibrary, SchurSpecializations, OpenMP]
-- Checking SFM deps... TRUE
```

Yours is
``Ceres with components: [LAPACK, SchurSpecializations, OpenMP]``
and mine
``Ceres/1.12 with components: [CXSparse, SparseLinearAlgebraLibrary, SchurSpecializations, OpenMP]``
Do you have better experience with LAPACK?

**Comment by LaurentBerger** [comment]
I have got Intel® Math Kernel Library 2017 Update 2 for Windows*	Downloaded	(it is free for personnal use) Lapack is inside
In opencv cmake I have : 
```
LAPACK(MKL): LAPACK_LIBRARIES: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_sequential.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib
LAPACK(MKL): Support is enabled.
```

and in ceres-solver cmake output

> Detected Ceres version: 1.12.0 from G:/Lib/ceres-solver/include/ceres/version.h
> -- Found Eigen version 3.3.0: G:/Lib/eigen-eigen
> 
>    ===============================================================
>    Disabling the use of Eigen as a sparse linear algebra library.
>    This does not affect the covariance estimation algorithm 
>    which can still use the EIGEN_SPARSE_QR algorithm.
>    ===============================================================
> 
> A library with BLAS API found.
> -- Found LAPACK library: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017.0.109/windows/mkl/lib/intel64_win/mkl_intel_ilp64_dll.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017.0.109/windows/mkl/lib/intel64_win/mkl_sequential_dll.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017.0.109/windows/mkl/lib/intel64_win/mkl_core_dll.lib
> -- Found BLAS library: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017.0.109/windows/mkl/lib/intel64_win/mkl_intel_ilp64_dll.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017.0.109/windows/mkl/lib/intel64_win/mkl_sequential_dll.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017.0.109/windows/mkl/lib/intel64_win/mkl_core_dll.lib
> -- Building without SuiteSparse.
> -- Building without CXSparse.
>    ===============================================================
>    Compiling without any sparse library: SuiteSparse, CXSparse 
>    & Eigen (Sparse) are all disabled or unavailable.  No sparse 
>    linear solvers (SPARSE_NORMAL_CHOLESKY & SPARSE_SCHUR)
>    will be available when Ceres is used.
>    ===============================================================
> No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
> Found installed version of gflags: C:/Program Files/gflags/CMake
> Detected gflags version: 2.2.0
> -- Found Google Flags header in: C:/Program Files/gflags/Include, in namespace: google
> No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
> Found installed version of glog: F:/lib/glog
> Detected glog version: 0.3.4
> -- Building with OpenMP.
> Looking for C++ include unordered_map
> Looking for C++ include unordered_map - found
> Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
> Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
> -- Found unordered_map/set in std namespace.
> Looking for C++ include memory
> Looking for C++ include memory - found
> Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
> Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
> -- Found shared_ptr in std namespace using <memory> header.
> -- Building Ceres as a static library.
> Enabling CERES_NO_SUITESPARSE in Ceres config.h
> Enabling CERES_NO_CXSPARSE in Ceres config.h
> Enabling CERES_USE_OPENMP in Ceres config.h
> Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
> -- Build the examples.
> Configuring done
> Generating done

**Comment by CWB1999** [comment]
> Opencv 3.4.13 Windows 10 VS 2017 VTK 8.2.0
>  I also get this problem in this example.
> I can see some points in the scene,and can turn around or zoom ,but I can not turn to the camera view in sample [scenereconstruction ]
And i dont change any code in the example.  It seems that the code "window.setViewerPose(path[0])" dont work. 
And i think maybe it is a bug in VTK or it is the vtk verison's problem.
Have someone solved this problem? please give me a hand.


> Thanks for your answer.

**Comment by CWB1999** [comment]
> Opencv 3.4.13 Windows 10 VS 2017 VTK 8.2.0
>  I also get this problem in this example.
> I can see some points in the scene,and can turn around or zoom ,but I can not turn to the camera view in sample [scenereconstruction ]
And i dont change any code in the example.  It seems that the code "window.setViewerPose(path[0])" dont work. 
And i think maybe it is a bug in VTK or it is the vtk verison's problem.
Have someone solved this problem? please give me a hand.

> Thanks for your answer.
