### ISSUE TITLE
Minor Bug in Deep Flow 

### ISSUE THREAD

**Issue by ceroytres** [opencv/opencv_contrib#1218]
Hi

In the member function [buildPyramid](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/src/deepflow.cpp#L95) of deepflow,  the variable "i" is never incremented in the while loop hence the while loop never terminates as a result of the termination condition instead it terminates as a result of the minSize breaking condition.

Best Regards!

**Comment by StevenPuttemans** [comment]
@ceroytres fastest way to solve this is to provide a PR with the suggested fix.

**Comment by ceroytres** [comment]
@StevenPuttemans I submitted a pull request.
