### ISSUE TITLE
error: ‘v_reduce_sum4’ was not declared in this scope

### ISSUE THREAD

**Issue by fireresistance** [opencv/opencv_contrib#1228]
Hello! Found this issue
How can i solve it?
opencv_contrib/modules/dnn/src/layers/convolution_layer.cpp: In member function ‘virtual void cv::dnn::ConvolutionLayerImpl::ParallelConv::operator()(const cv::Range&) const’:
opencv_contrib/modules/dnn/src/layers/convolution_layer.cpp:444:75: error: ‘v_reduce_sum4’ was not declared in this scope s0 += v_reduce_sum4(vs00, vs01, vs02, vs03);

**Comment by alalek** [comment]
You need to update both repositories: opencv / opencv_contrib.
