### ISSUE TITLE
Unable to use Algorithm::load for face module

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1235]
Hi,

In doc http://docs.opencv.org/master/dd/d65/classcv_1_1face_1_1FaceRecognizer.html herited from algorithm as [RTrees ](http://docs.opencv.org/master/d0/d65/classcv_1_1ml_1_1RTrees.html).
If i write this line : 
`Ptr<ml::RTrees> modelTrees = Algorithm::load<ml::RTrees>("a.yml");`

it is OK but I have got errors when I write : 

 ```
       Ptr<face::BasicFaceRecognizer> modelFisher = Algorithm::load<face::BasicFaceRecognizer>("b.yml");
        Ptr<face::LBPHFaceRecognizer> modelLBPHF = Algorithm::load<face::LBPHFaceRecognizer>("c.yml");

```

> >G:\Lib\opencv\modules\core\include\opencv2/core.hpp(3081): error C2039: 'create' : is not a member of 'cv::face::BasicFaceRecognizer'
> 1>G:\Lib\opencv\modules\core\include\opencv2/core.hpp(3081): error C2039: 'create' : nis not a member of 'cv::face::LBPHFaceRecognizer'
> 

Is it possible to use Algorithm::load for face module?

- OpenCV => 3.2.0-dev
- Operating System / Platform => Windows 10-64 Bit
- Compiler => Visual Studio 2015

**Comment by sovrasov** [comment]
`load` is just a template:
```c++
template<typename _Tp> static Ptr<_Tp> load(const String& filename, const String& objname=String())
    {
        FileStorage fs(filename, FileStorage::READ);
        FileNode fn = objname.empty() ? fs.getFirstTopLevelNode() : fs[objname];
        if (fn.empty()) return Ptr<_Tp>();
        Ptr<_Tp> obj = _Tp::create();
        obj->read(fn);
        return !obj->empty() ? obj : Ptr<_Tp>();
    }
```
You need to have `create` and `read` methods implemented in `BasicFaceRecognizer` to use `Algorithm::load<face::BasicFaceRecognizer>`.
