### ISSUE TITLE
opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download) file not exist

### ISSUE THREAD

**Issue by Wociao** [opencv/opencv_contrib#1250]
when compiling opencv_contrib, there is link can not be found.
opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download)
could not be found from the website. 
It could not be found even you open the link from the web browser.

**Comment by alalek** [comment]
Check `CMakeDownloadLog.txt` from build folder for file URLs.
Also keep up-to-date both opencv/opencv_contrib repositories (they should be synchronized).
