### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MultiTracker_create'

### ISSUE THREAD

**Issue by Walid-Ahmed** [opencv/opencv_contrib#1271]
Hello,
Single Tracker worked just fine but
the multi tracker 
`tracker = cv2.MultiTracker_create()`
`
gave me error:-

> AttributeError: 'module' object has no attribute 'MultiTracker_create'

Can you please help?

**Comment by kevinali1** [comment]
Check your version. You may be using opencv 3.2. the MultiTracker_create class appears to be present in the master version (3.3 I think). There is a sample file in version 3.2 that perhaps has the code sample you're looking for.

[(https://github.com/opencv/opencv_contrib/blob/3.2.0/modules/tracking/samples/multitracker.py)]

**Comment by Sodininkas** [comment]
My open cv version - 3.3.1 the function not existing, how this thread closed

**Comment by nex0ma** [comment]
cv.__version__  = '4.1.0'

tracker = cv2.MultiTracker_create()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-0c4e5323b1ef> in <module>
      1 cv2.namedWindow("tracking")
      2 camera = cv2.VideoCapture ('08.00.mp4')
----> 3 tracker = cv2.MultiTracker_create()

AttributeError: module 'cv2.cv2' has no attribute 'MultiTracker_create'
