### ISSUE TITLE
Does the bgsegm module available in Java?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv_contrib#1272]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed Description
I want to use the background segmentation algorithms which are in bgsegm module of opencv_contrib.
In the module CMakeLists.txt file there is no wrapper for Java. Is it possible to add Java in the line below?
`ocv_define_module(bgsegm opencv_core opencv_imgproc opencv_video WRAP python java)`

**Comment by sovrasov** [comment]
It's always possible but produced wrappers can be unusable. I've looked through the code of the module and all the interfaces looks appropriate to be wrapped. You can try to enable java wrappers and if they are working, create a PR with the changes in CMake.

**Comment by Bahramudin** [comment]
@sovrasov  I think it will be better whenever any of the opencv_contrib modules become available in Java also, modify the CMakeLists.txt file also, so the users cannot be confused for the modules availabilities in the other languages such as Java. I say this because the face module is available now in Java wrapper and also useable, but in the CMakeLists.txt of the face module there, no Java added to be wrapped while compiling. So it will better to be added by the authors instead of users.

**Comment by sturkmen72** [comment]
Please close the issue.
