### ISSUE TITLE
opencv_contrib build error - selectROI not found?

### ISSUE THREAD

**Issue by jburton2** [opencv/opencv_contrib#1277]
##### System information (version)

- OpenCV => 3.2.0 + opencv_contrib (as of 07/12/2017)
- Operating System / Platform => RHEL 7.3
- Compiler => g++ 4.8.5

##### Detailed description
I am trying to get tracking working on a RHEL 7.3 (RedHat Linux) system. I downloaded OpenCV 3.2.0 and I downloaded the "opencv_contrib" master branch from https://github.com/opencv/opencv_contrib I downloaded the opencv contrib yesterday (July 13, 2017) in case I missed something before. I first started trying to do this back in the middle of May, but have not had any success. Obviously I am doing something wrong, or not including something, can you help?

I make sure that the opencv_contrib path is set for cmake. When I go to build opencv, I get the following error:

I have included the tracking portion of the OpenCV build output where the error occurs in the following file

[OpenCV Build Error.txt](https://github.com/opencv/opencv_contrib/files/1148889/OpenCV.Build.Error.txt)

Since multiple sources have stated that selectROI is in the tracking API, then there should be some definition of it in the source files, correct? So I do a "grep -r selectROI" on the entire opencv_contrib directory. I can find where source code uses selectROI, but no definition of selectROI - I've included the grep output in the following file:
[OpenCV Contrib grep.txt](https://github.com/opencv/opencv_contrib/files/1148893/OpenCV.Contrib.grep.txt)

Obviously I am doing something wrong here, any suggestions?

**Comment by alalek** [comment]
> downloaded the **opencv contrib** yesterday

You should download fresh version of **opencv** repository too.
`selectorROI` is moved [here](https://github.com/opencv/opencv/blob/master/modules/highgui/src/roiSelector.cpp).
