### ISSUE TITLE
Load multi caffe model error

### ISSUE THREAD

**Issue by caiqi** [opencv/opencv_contrib#1279]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

When loading multi caffe models, the later one always fails.

##### Steps to reproduce

	Net net1= dnn::readNetFromCaffe(upper_model_txt, upper_model_bin);
	std::cerr << net1.empty() << std::endl;

	Net net2 = dnn::readNetFromCaffe(base_model_txt, base_model_bin);
	std::cerr << net2 .empty() << std::endl;

the net2.empty() is always ture. Does opencv only support load one model per time. Thanks.

**Comment by dkurt** [comment]
I can't reproduce it. The first model is AlxeNet, the second one is GoogLeNet (both from opencv_extra).

**Comment by dkurt** [comment]
Closed because of there is no response here.
