### ISSUE TITLE
add_subdirectory "src/libmv_light" does not exist

### ISSUE THREAD

**Issue by alexge233** [opencv/opencv_contrib#1280]
Hi,

I am using the latest version of opencv (`master`) and running cmake with the `opencv_contrib` option passed. However, the opencv cmake fails with the following error:

```
CMake Error at /home/alex/codez/opencv_contrib/modules/sfm/CMakeLists.txt:116 (add_subdirectory):
  add_subdirectory given source "src/libmv_light" which is not an existing
  directory.
Call Stack (most recent call first):
  modules/world/CMakeLists.txt:13 (include)
  modules/world/CMakeLists.txt:32 (include_one_module)
```

I've tried with a clean directory three times, and what's puzzling is that the specific directory does indeed exist.

PS: if this is not an issue with `opencv_contrib` please let me know and I'll move it to `opencv`.

**Comment by alalek** [comment]
sfm doesn't support "world" build.
You need to disable sfm module (`-DBUILD_opencv_sfm=OFF`) or world (`-DBUILD_opencv_world=OFF`) via CMake.

**Comment by alexge233** [comment]
That's funny because I did turn off opencv_world, I'll try with sfm off as well.
Many thanks!
