### ISSUE TITLE
i try to execute  "opencv_contrib/modules/text/samples/textdetection.py/" but it show error in line no 48:

### ISSUE THREAD

**Issue by allenkallz** [opencv/opencv_contrib#1281]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by allenkallz** [comment]
error is 

 File "textdetection.py", line 48, in <module>     rects = cv2.text.erGrouping(img,channel,[r.tolist() for r in regions]) cv2.error: /opt/opencv/modules/imgproc/src/floodfill.cpp:510: error: (-211) Seed point is outside of image in function floodFill

**Comment by allenkallz** [comment]
@alalek what you need please tell me but i am getting error when try to execute sample code   "opencv_contrib/modules/text/samples/textdetection.py"

and  i run following command in terminal   " python textdetection.py scenetext_word01.jpg "

**Comment by srinidhiprabandham** [comment]
@allenkallz I believe that you cannot just run this as any other python program. This has to be compiled and Build with opencv (Please refer README) with this package as additional modules. And then we can run it like how you describe.

**Comment by alalek** [comment]
I can confirm this issue and reproduce this error message.

**Comment by allenkallz** [comment]
@srinidhiprabandham I already compile and Build with opencv after that i am try to execute this file but it show same error
