### ISSUE TITLE
Error compiling opencv_dnn

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1289]
Hi,

I'm trying to compile opencv_dnn and I have got errors : 

```
4>  caffe_converter.cpp
4>F:\Install\protobuf\include\google/protobuf/io/coded_stream.h(864): Warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
4>F:\Install\protobuf\include\google/protobuf/io/coded_stream.h(868): Warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
4>g:\lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn\io\caffe\caffe.pb.h(2855): error C2059: syntax error: 'constant'
4>g:\lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn\io\caffe\caffe.pb.h(2856): error C2238: unexpected token(s) preceding  ';'
4>g:\lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn\io\caffe\caffe.pb.h(10019): error C2059:  syntax error: 'constant'
4>g:\lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn\io\caffe\caffe.pb.h(10020): error C2238: unexpected token(s) preceding  ';'
4>G:\Lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn/io/caffe/layer_factory_impl.h(347): warning C4267: 'argument' : conversion de 'size_t' en 'int', perte possible de données
4>G:\Lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn/io/caffe/layer_factory_impl.h(348): warning C4267: 'argument' : conversion de 'size_t' en 'int', perte possible de données
4>G:\Lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn/io/caffe/layer_factory_impl.h(392): warning C4267: 'argument' : conversion de 'size_t' en 'int', perte possible de données
4>G:\Lib\opencv\dll2015\3rdparty\tinydnn\tiny-dnn-1.0.0a3\tiny_dnn/io/caffe/layer_factory.h(90): warning C4457: la déclaration de 'layer' masque le paramètre de fonction

```

Error is at this line : 
`  static const DimCheckMode STRICT =
    ParamSpec_DimCheckMode_STRICT;
`
and this one : 
`  static const DimCheckMode STRICT =
    V1LayerParameter_DimCheckMode_STRICT;
`
I installed  protobuf my version is 2017-04-05 version 3.3.0 (C++/Java/Python/PHP/Objective-C/C#/Ruby/JavaScript)

- OpenCV => 3.3.0-rc
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
-->
STRICt is already define in c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\minwindef.h 

I post same issue on tiny_dnn

**Comment by nyanp** [comment]
Hi, 
Maybe this is a bug in dnn_modern.

Inserting ```#define NO_STRICT``` in the top of caffe_converter will solve the problem.


https://github.com/tiny-dnn/tiny-dnn/blob/master/examples/caffe_converter/caffe_converter.cpp#L13


https://msdn.microsoft.com/en-us/library/windows/desktop/aa383679(v=vs.85).aspx

**Comment by LaurentBerger** [comment]
I have inserted [#define NO_STRICT](https://github.com/opencv/opencv_contrib/blob/master/modules/dnn_modern/src/caffe_converter.cpp#L44) and problem is solved.
Thanks you
