### ISSUE TITLE
Error while installing Face detection Module in openCV framework

### ISSUE THREAD

**Issue by demonarola** [opencv/opencv_contrib#1294]
I got file missing error while I am using face detection algorithm of openCV framework.
![screen shot 2017-07-26 at 10 44 03 am](https://user-images.githubusercontent.com/931673/28606601-6c033d94-71f5-11e7-9980-d9a968fd4c68.png)

openCV framework’s official site suggest me to install extra modules of openCV framework.  

But I have faced an issue while installing extra modules on openCV in swift.
I am installing that modules using cmake.
i follow this steps as mentioned in this link : 
[https://github.com/opencv/opencv_contrib/tree/3.0.0-beta]

While executing “make - j5” command in terminal I got  Fatal Error as below : 
	
	

> **### /Users/nc2-27/Downloads/opencv-facerec-tutorial-ios-master/opencv2.framework/opencv-3.0.0-beta/modules/videoio/src/cap_qtkit.mm:46:9: fatal error: 
>       'QTKit/QTKit.h' file not found
> #import <QTKit/QTKit.h>**
>         		^
> 1 error generated.
> make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
> make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
> make: *** [all] Error 2
![screen shot 2017-07-26 at 10 40 16 am](https://user-images.githubusercontent.com/931673/28606618-84921376-71f5-11e7-89cd-b5b4354c793f.png)

I tried to install modules using CMake - GUI version but I got same error. 
Does anyone have idea about this kind of error?
Give me a suggestion please.

**Comment by demonarola** [comment]
@alalek what are the solution of this problem?
Can you help me please?

**Comment by alalek** [comment]
> 3.0.0-beta

Outdated OpenCV versions are not supported/maintained.

> QTKit

This is MacOSX issue - QTKit was removed with recent Apple updates. You can find several filled issues about this problem in `opencv` repo.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by demonarola** [comment]
@alalek what OSX required for install latest version of  openCV?
