### ISSUE TITLE
faild to build sfm for no header found for module dnn

### ISSUE THREAD

**Issue by boyob** [opencv/opencv_contrib#1305]
......
[ 98%] Generating Matlab source files
Traceback (most recent call last):
  File "/home/master/opencv-3.1.0/opencv_contrib-3.1.0/modules/matlab/generator/gen_matlab.py", line 182, in <module>
    mwg.gen(args.moduleroot, args.modules, args.extra, args.outdir)
  File "/home/master/opencv-3.1.0/opencv_contrib-3.1.0/modules/matlab/generator/gen_matlab.py", line 47, in gen
    raise Exception('no header found for module %s!' % module)
Exception: no header found for module dnn!
modules/matlab/CMakeFiles/opencv_matlab_sources.dir/build.make:60: recipe for target 'modules/matlab/generate.proxy' failed
make[2]: *** [modules/matlab/generate.proxy] Error 1
CMakeFiles/Makefile2:20408: recipe for target 'modules/matlab/CMakeFiles/opencv_matlab_sources.dir/all' failed
make[1]: *** [modules/matlab/CMakeFiles/opencv_matlab_sources.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

ubuntu 16.04LTS opencv310(but the file".../opencv_contrib-3.1.0/modules/sfm/src/libmv_capi.h" came from opencv_contrib3.3.0-rc)

**Comment by alalek** [comment]
> opencv-3.1.0
> opencv_contrib3.3.0-rc

I see a mess of OpenCV versions. Keep these versions synchronized.
