### ISSUE TITLE
dnn_moden is not building 

### ISSUE THREAD

**Issue by ravispatil** [opencv/opencv_contrib#1309]
Hello, facing issue with building dnn_modern. Its disabled because its not getting protoc executable and protobuf library. How to give protoc executable/protobuflib path.

-DTINYDNN_ROOT=/home/abuild/rpmbuild/BUILD/cmake-3.8/opencv-3.2/tiny-dnn-master -DTINYDNN_USE_OMP=ON -DOPENCV_EXTRA_MODULES_PATH=/home/abuild/rpmbuild/BUILD/cmake-3.8/opencv-3.2/contrib/modules -DBUILD_opencv_dnn_modern=ON

Below is cmake output:
 -- Looking for tiny_dnn.h
 -- Looking for tiny_dnn.h - found
 -- Found tiny-dnn in: /home/abuild/rpmbuild/BUILD/cmake-3.8/opencv-3.2/tiny-dnn-master
 -- The protocol buffer compiler is not found (PROTOBUF_PROTOC_EXECUTABLE='Protobuf_PROTOC_EXECUTABLE-NOTFOUND')

**Comment by dkurt** [comment]
Have you protobuf library in your system? In example, `/usr/lib/x86_64-linux-gnu/libprotobuf.so`. Can you execute `protoc` from command line?

**Comment by dkurt** [comment]
Issue was closed because of no response.
