### ISSUE TITLE
opecv_contrib DNN Build issue.

### ISSUE THREAD

**Issue by ravispatil** [opencv/opencv_contrib#1315]
Hello,
I am building opencv_contrib dnn module. But in cmake command getting below error.

----------------
You have called ADD_LIBRARY for library libprotobuf without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE - Success
CMake Error: CMake can not determine linker language for target: libprotobuf
CMake Error in opencv_contrib/modules/dnn/3rdparty/protobuf/CMakeLists.txt:
  Exporting the target "libprotobuf" is not allowed since its linker language
  cannot be determined

CMake Error: CMake can not determine linker language for target: libprotobuf
CMake Error in opencv_contrib/modules/dnn/3rdparty/protobuf/CMakeLists.txt:
  Exporting the target "libprotobuf" is not allowed since its linker language
  cannot be determined
-------------------------------
If I disable dnn then cmake command is successful.

**Comment by ravispatil** [comment]
Hello, I resolved this issue with setting -DPROTOBUF_CPP_PATH=<path to protobuf 3.1.0 code >

**Comment by dkurt** [comment]
@ravispatil, please use http://answers.opencv.org for build/install questions. This is a tracker for bug issues or enhancement proposals. Read https://github.com/opencv/opencv/wiki/How_to_contribute for details and follow the hints during issues creation. Thanks!
