### ISSUE TITLE
make error for libopencv_core.so.3.2.0 undefined reference

### ISSUE THREAD

**Issue by HellerFang** [opencv/opencv_contrib#1325]
When make in build with opencv contrib:

Linking CXX executable ../../../../bin/opencv_waldboost_detector
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dpotrf_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesv_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `sgels_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesv_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `sposv_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dgetrf_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `sgetrf_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dgels_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dgeqrf_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `spotrf_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `sgeqrf_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesdd_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesdd_'
../../../../lib/libopencv_core.so.3.2.0: undefined reference to `dposv_'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_waldboost_detector] Error 1
make[1]: *** [modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Why ?

**Comment by mshabunin** [comment]
Please make sure you are using consistent versions of OpenCV and contrib, both should be synced to the same tag or branch.

**Comment by alalek** [comment]
https://github.com/opencv/opencv/issues/7970

**Comment by HellerFang** [comment]
Thank you @alalek

**Comment by HellerFang** [comment]
I make all with the suggested method, it's "cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>", that had no any error (like undefined reference), and the OpenBlas was not installed correctly before.
