### ISSUE TITLE
sinusoidal_pattern.cpp exported to Python side in C++ code?

### ISSUE THREAD

**Issue by pettaa123** [opencv/opencv_contrib#1327]
Hello,

I cant find the sinusoidal_pattern in the contrib python projects, like [here](https://github.com/skvark/opencv-python) only graycode.

`>>> help(cv2.structured_light)
Help on module cv2.structured_light in cv2:

NAME
    cv2.structured_light

FUNCTIONS
    GrayCodePattern_create(...)
        GrayCodePattern_create(width, height) -> retval
        .   @brief Constructor
        .   @param parameters GrayCodePattern parameters GrayCodePattern::Params: the width and the height of the projector.

DATA
    DECODE_3D_UNDERWORLD = 0
    FAPS = 2
    FTP = 0
    PSP = 1

FILE
    (built-in)`

**Comment by sovrasov** [comment]
@pettaa123 try the fix from #1328
