### ISSUE TITLE
CMake errors on opencv_contrib master

### ISSUE THREAD

**Issue by mihaibujanca** [opencv/opencv_contrib#1351]
##### System information (version)
- OpenCV => 3.2.0. Also tried with master
- Operating System / Platform => Ubuntu 16.04 64-bit
- OpenCV_contrib => master

##### Detailed description

When trying to build opencv with opencv contrib, the following error comes up when executing cmake:
```
 CMake Error at opencv_3.2/cmake/OpenCVUtils.cmake:1005 (file):
   file MD5 failed to read file
   "opencv_3.2/build/3rdparty/tinydnn/": Success
 Call Stack (most recent call first):
opencv_contrib/modules/dnn_modern/CMakeLists.txt:18 (ocv_download)

 CMake Error at opencv_3.2/cmake/OpenCVUtils.cmake:1043 (file):
   file DOWNLOAD cannot open file for write.
 Call Stack (most recent call first):
   opencv_contrib/modules/dnn_modern/CMakeLists.txt:18 (ocv_download)

 CMake Error at opencv_3.2/cmake/OpenCVUtils.cmake:1047 (message):
   Failed to download .  Status=
 Call Stack (most recent call first):
opencv_contrib/modules/dnn_modern/CMakeLists.txt:18 (ocv_download)
```

When building with opencv_contrib on branch 3.2.0, this does not occur

**Comment by mlee980** [comment]
I am having the same problem:

-- Downloading ...
CMake Error at cmake/OpenCVUtils.cmake:947 (file):
  file DOWNLOAD cannot open file for write.
Call Stack (most recent call first):
  modules/opencv_contrib/modules/dnn_modern/CMakeLists.txt:18 (ocv_download)

CMake Error at cmake/OpenCVUtils.cmake:951 (message):
  Failed to download .  Status=
Call Stack (most recent call first):
  modules/opencv_contrib/modules/dnn_modern/CMakeLists.txt:18 (ocv_download)

on macOS 10.12, opencv 3.1.0

**Comment by alalek** [comment]
> opencv 3.1.0

You should keep both repositories synchronized (the same code version).
There is nothing to fix in OpenCV, so closing this.
