### ISSUE TITLE
runtime bugs in modules/tracking/samples/tutorial_multitracker.cpp

### ISSUE THREAD

**Issue by klchang** [opencv/opencv_contrib#1368]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => Fedora 21 x64
- Compiler => g++

##### Detailed description

When I run the tutorial code "modules/tracking/samples/tutorial_multitracker.cpp", then the prompt outputs the hint 
"Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!".
I found two runtime bugs. 
One is when I press "ENTER" button, no respond from the program, but pressing SPACE button is OK. For this issue, I give my proposed workaround in [here](https://github.com/opencv/opencv/issues/9641);
The other is that after I finish my selections, the program exits directly.

So I read the codes in the 'tutorial_multitracker.cpp' carefully, and found 2 positions where the variable 'objects' is wrongly used. The positions are line 65 and line 71:
```
  vector<Rect2d> objects;
  //! [roi]

  // set input video
  std::string video = argv[1];
  VideoCapture cap(video);

  Mat frame;

  // get bounding box
  cap >> frame;
  //! [selectmulti]
  vector<Rect> ROIs;
  selectROIs("tracker",frame,ROIs);
  //! [selectmulti]

  //quit when the tracked object(s) is not provided
  if(objects.size()<1)  // line 65
    return 0;

  // initialize the tracker
  //! [init]
  std::vector<Ptr<Tracker> > algorithms;
  for (size_t i = 0; i < objects.size(); i++)  // line 71
```
To fix this issue, it is very easy. i.e. change the variable 'objects' to 'ROIs' in lines 65 and 71:
"tutorial_multitracker.cpp: 65"
` if(ROIs.size()<1) `
"tutorial_multitracker.cpp: 71"
`for (size_t i = 0; i < ROIs.size(); i++)`

Then recompile and run the tutorial code, it is OK now.

**Comment by sovrasov** [comment]
That's right! `objects` should be replaced with `ROIs` in the loop condition. Can you provide a PR with the fix?

**Comment by klchang** [comment]
@sovrasov OK. I have just provided a PR with this fix.

**Comment by sovrasov** [comment]
Actually you don't need to close this issue if fix is provided. If you specify `resolves #xxxx` in the PR description , buildbot will close the issue as PR gets merged.

**Comment by klchang** [comment]
@sovrasov Sorry, this is my first PR, so I don't know the workflow clearly. Thanks for your explanation!
