### ISSUE TITLE
Error when using textdetection.cpp

### ISSUE THREAD

**Issue by csyuab** [opencv/opencv_contrib#1405]
Hi, I am trying to use the textdetection.cpp to do some real time texts detection or from the images. But once I have cloned the cpp to Xcode and run it, it just showed "Default classifier files (trained_classifierNM*.xml) must be in current directory". Can I get any advices from you? Thanks!!

**Comment by chedanix** [comment]
The error message isn't correct. The code has a function called show_help_and_exit(), which displays this error message. The function gets called by mistake when there aren't enough arguments being passed to main().

To fix this, you need to pass the picture path&name to the main() function.
