### ISSUE TITLE
Fix name extraction from path in multicalib

### ISSUE THREAD

**Issue by cdcseacave** [opencv/opencv_contrib#1420]
At https://github.com/opencv/opencv_contrib/blob/master/modules/ccalib/src/multicalib.cpp#L144 instead of:
`std::string filename = file_list[i].substr(0, file_list[i].find('.'));`
should be:
`std::string filename = file_list[i].substr(0, file_list[i].rfind('.'));`
in order to support all types of path, including path names with points or relative paths.

**Comment by sovrasov** [comment]
Could you please provide a PR with the proposed changes?
