### ISSUE TITLE
Loading the module breaks everything

### ISSUE THREAD

**Issue by eshirima** [opencv/opencv_contrib#1422]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => Mac OS Sierra
- Compiler => Apple LLVM 9.0

##### Detailed description

Including the `contrib.hpp` file throws a bunch of semantic errors during build time.

The thrown errors differ by setup

**Setup 1**

```
#include <stdio.h>
#include <vector>
#include <opencv2/opencv.hpp>
#include <opencv2/contrib/contrib.hpp>

using namespace cv;

using std::cout;
using std::vector;
using std::string;
```

Errors: 

> No template named 'vector'; did you mean 'std::vector'?

105 of these are thrown

**Setup 2**

```
#include <stdio.h>
#include <vector>
#include <opencv2/opencv.hpp>
using std::vector;
#include <opencv2/contrib/contrib.hpp>

using namespace cv;

using std::cout;
using std::string;
```

Errors: 

> Unknown type name 'string'; did you mean 'String'?
> Redefinition of enumerator COLORMAP_AUTUMN
> Redefinition of enumerator COLORMAP_BONE
> Redefinition of enumerator COLORMAP_JET
> Redefinition of 'TickMeter'
> Redefinition of 'LDA'

I have always had this issue dating back to OpenCV 3.2.0.

OpenCV was built from source and this is my config info

> General configuration for OpenCV 3.3.0-dev =====================================
>   Version control:               3.3.0-538-g5ed354221
> 
>   Extra modules:
>     Location (extra):            /Users/****/opencv_contrib/modules
>     Version control (extra):     3.3.0-124-ge9cd99d9
> 
>   Platform:
>     Timestamp:                   2017-10-15T02:43:50Z
>     Host:                        Darwin 16.7.0 x86_64
>     CMake:                       3.10.0-rc2
>     CMake generator:             Unix Makefiles
>     CMake build tool:            /usr/bin/make
>     Configuration:               Release
> 
>   CPU/HW features:
>     Baseline:                    SSE SSE2 SSE3
>       requested:                 SSE3
>     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
>       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
>       SSE4_1 (3 files):          + SSSE3 SSE4_1
>       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
>       FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
>       AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
>       AVX2 (8 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
> 
>   C/C++:
>     Built as dynamic libs?:      YES
>     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 9.0.0.9000037)
>     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -O3 -DNDEBUG  -DNDEBUG
>     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -g  -O0 -DDEBUG -D_DEBUG
>     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
>     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -O3 -DNDEBUG  -DNDEBUG
>     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -g  -O0 -DDEBUG -D_DEBUG
>     Linker flags (Release):
>     Linker flags (Debug):
>     ccache:                      NO
>     Precompiled headers:         NO
>     Extra dependencies:
>     3rdparty dependencies:
> 
>   OpenCV modules:
>     To be built:                 core flann imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video xphoto bgsegm dnn face fuzzy img_hash imgcodecs shape videoio xobjdetect highgui superres ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow stitching python2
>     Disabled:                    js world contrib_world matlab
>     Disabled by dependency:      -
>     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python3 viz cnn_3dobj cvv dnn_modern freetype hdf sfm
> 
>   Non-free algorithms are enabled
> 
>   GUI: 
>     QT:                          NO
>     Cocoa:                       YES
>     OpenGL support:              NO
>     VTK support:                 NO
> 
>   Media I/O: 
>     ZLib:                        build (ver 1.2.8)
>     JPEG:                        build (ver 90)
>     WEBP:                        build (ver encoder: 0x020e)
>     PNG:                         build (ver 1.6.24)
>     TIFF:                        build (ver 42 - 4.0.2)
>     JPEG 2000:                   build (ver 1.900.1)
>     OpenEXR:                     build (ver 1.7.1)
>     GDAL:                        NO
>     GDCM:                        NO
> 
>   Video I/O:
>     DC1394 1.x:                  NO
>     DC1394 2.x:                  NO
>     FFMPEG:                      YES
>       avcodec:                   YES (ver 57.89.100)
>       avformat:                  YES (ver 57.71.100)
>       avutil:                    YES (ver 55.58.100)
>       swscale:                   YES (ver 4.6.100)
>       avresample:                YES (ver 3.5.0)
>     GStreamer:                   NO
>     OpenNI:                      NO
>     OpenNI PrimeSensor Modules:  NO
>     OpenNI2:                     NO
>     PvAPI:                       NO
>     GigEVisionSDK:               NO
>     Aravis SDK:                  NO
>     AVFoundation:                YES
>     V4L/V4L2:                    NO/NO
>     XIMEA:                       NO
>     Intel Media SDK:             NO
>     gPhoto2:                     NO
> 
>   Parallel framework:            GCD
> 
>   Trace:                         YES (with Intel ITT)
> 
>   Other third-party libraries:
>     Use Intel IPP:               2017.0.3 [2017.0.3]
>                at:               /Users/****/opencv/build/3rdparty/ippicv/ippicv_mac
>     Use Intel IPP IW:            sources (2017.0.3)
>                   at:            /Users/****/opencv/build/3rdparty/ippicv/ippiw_mac
>     Use VA:                      NO
>     Use Intel VA-API/OpenCL:     NO
>     Use Lapack:                  YES (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framework)
>     Use Eigen:                   YES (ver 3.3.3)
>     Use Cuda:                    NO
>     Use OpenCL:                  YES
>     Use OpenVX:                  NO
>     Use custom HAL:              NO
> 
>   OpenCL:                        <Link with OpenCL library>
>     Link libraries:              -framework OpenCL
>     Use AMDFFT:                  NO
>     Use AMDBLAS:                 NO
> 
>   Python 2:
>     Interpreter:                 /Users/****/anaconda/bin/python2.7 (ver 2.7.10)
>     Libraries:                   /usr/lib/libpython2.7.dylib (ver 2.7.10)
>     numpy:                       /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include (ver 1.8.0rc1)
>     packages path:               /Users/****/anaconda/lib/python2.7/site-packages
> 
>   Python 3:
>     Interpreter:                 NO
> 
>   Python (for build):            /Users/****/anaconda/bin/python2.7
> 
>   Java:
>     ant:                         NO
>     JNI:                         /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/JavaVM.framework/Headers
>     Java wrappers:               NO
>     Java tests:                  NO
> 
>   Matlab:
>     mex:                         /Applications/MATLAB_R2017b.app/bin/mex
>     Compiler/generator:          Not working (bindings will not be generated)
> 
>   Documentation:
>     Doxygen:                     NO
> 
>   Tests and samples:
>     Tests:                       YES
>     Performance tests:           YES
>     C/C++ Examples:              NO
> 
>   Install path:                  /usr/local
> 
>   cvconfig.h is in:              /Users/****/opencv/build
> -----------------------------------------------------------------

**Comment by alalek** [comment]
Use -H option (GCC/Clang) to check path of included files.

> #include <opencv2/contrib/contrib.hpp>

This file doesn't exist in OpenCV 3.x (it is from OpenCV 2.4).


Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
