### ISSUE TITLE
dependency can't be resolved

### ISSUE THREAD

**Issue by sturkmen72** [opencv/opencv_contrib#1436]
Module opencv_text disabled because opencv_dnn dependency can't be resolved!
Module opencv_datasets disabled because opencv_text dependency can't be resolved!

i think some improvements about optional dependency will be better

**Comment by LaurentBerger** [comment]
I haven't got any problem with text module. What's your version?

**Comment by sturkmen72** [comment]
i will give more details later. i got it when compiling with BUILD_SHARED_LIBS = OFF

**Comment by terfendail** [comment]
fixed by #1447
