### ISSUE TITLE
real_illum_568..mat

### ISSUE THREAD

**Issue by yangguang-v** [opencv/opencv_contrib#1445]
Preview

parser.add_argument(
        "-g",
        "--ground_truth",
        metavar="GROUND_TRUTH",
        default="real_illum_568..mat",
        help=("Path to the mat file containing ground truth illuminations. Currently "
              "supports formats supplied by the Gehler-Shi and NUS 8-camera datasets."))

where is real_illum_568..mat from?  And where is colourchecker_gamma1_bit12?
In addition to , I want to know How I use this model to other dataset?

**Comment by mshabunin** [comment]
You can find some information in the documentation: https://docs.opencv.org/3.3.0/dc/dcb/tutorial_xphoto_training_white_balance.html

Gehler-Shi dataset is here: http://www.cs.sfu.ca/~colour/data/shi_gehler/
