### ISSUE TITLE
optflow error in building

### ISSUE THREAD

**Issue by andreluizbarbieri** [opencv/opencv_contrib#1469]
I set Cmake extra-modules to opencv-contrib/modules , and few extra-modules compile with no errors (e.g. _bgsegm_ work very well)  but the _optflow_ can't be build... Did have some tip?

a short view (first line) of building errors...
> `C:\opencv-3.3.0\modules\optflow\src\simpleflow.cpp(134): error C2653: 'traits'`

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
