### ISSUE TITLE
Tracker.KCF Tracker.Init crashes

### ISSUE THREAD

**Issue by WeitesFeld** [opencv/opencv_contrib#1472]
Tracker.Init for the KCF results in crashes when initialising it with a valid Rect2d with double values. e.g. Init works when using something like Rect2d(10,10,10,10) but crashes when using a Rect2d with values like this:
Rect2d is {(x:64,6813250828544 y:41,6813250828544 width:32,6373498342912 height:32,6373498342912)} 

OpenCV 3.3.1, Win7 x64, Compiled in x86 with VS2017

Steps to reproduce: Try to init a KCF tracker with valid doubles with decimals

**Comment by WeitesFeld** [comment]
One additional thing to check:
If youuse a grayscale mat instead of other popular choices, e.g. BGR8UC3, Tracker.KCF will crash on Tracker.Update while other trackers works fine, e.g. MIL.

**Comment by berak** [comment]
thanks for your report !

1. indeed a bug. ([rounding problem here](https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/src/trackerKCF.cpp#L244-L248)

2. it's not at all obvious, but for grayscale image, you should set the correct tracker params, like:

    Params p;
    p.desc_npca = GRAY;
    p.desc_pca = GRAY;

else it tries to use the colornames feature, which obviously needs 3 channel images.

nonetheless, i think, we should look at the provided image in initImpl(), and probably override / correct the params before [creating the TrackerKCFModel](https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/src/trackerKCF.cpp#L258)

**Comment by berak** [comment]
@WeitesFeld , just curious, how did you come up with that boundingbox, and what did you expect to happen ?

**Comment by WeitesFeld** [comment]
Thanks for the fix.

@berak The bounding box is calculated in correlation to real scene values. My thought was, when a method accept those values, it also can deal with them internally. Up to now I didnt check the trackerKCF code

**Comment by jorabold** [comment]
For anyone trying to use the KCF tracker on grayscale images with OpenCV 4.2.0, here are the parameters that worked for me:
```
cv::TrackerKCF::Params p;
p.desc_npca = cv::TrackerKCF::GRAY;
p.desc_pca = cv::TrackerKCF::GRAY;
p.compressed_size = 1;
cv::Ptr<cv::Tracker> tracker = cv::TrackerKCF::create(p);
```
