### ISSUE TITLE
bug in using line_descriptor model

### ISSUE THREAD

**Issue by f1r1o1n1t1** [opencv/opencv_contrib#1481]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

when using line matching, Segmentation fault (core dumped) occurs.
[136,  32,   8,   0,   0,   0,  32, 112,  32,  80,   0, 216, 136,  80, 128,  64, 196,  32,   4, 132,   4, 196,  84, 196,  68, 196, 132,   4, 196,  72,  68, 196]
[191, 191, 191, 187, 191, 255, 255, 191, 187, 191, 255,  19,  19,  59, 255, 255, 255, 187, 191, 255, 255, 255, 191, 255, 255, 255, 255, 255, 255, 255, 255, 119]
two Mat/array above represent descriptors of two lines, when using the match() function, error occurs!
My code:

#include <iostream>
#include <opencv2/line_descriptor.hpp>
//#include "opencv2/core/utility.hpp"
//#include <opencv2/imgproc.hpp>
//#include <opencv2/features2d.hpp>
//#include <opencv2/highgui.hpp>
#define MATCHES_DIST_THRESHOLD 25

using namespace std;
using namespace cv;
using namespace cv::line_descriptor;

int main( int argc, char** argv )
{

  /* create a BinaryDescriptorMatcher object */
  Ptr<BinaryDescriptorMatcher> bdm = BinaryDescriptorMatcher::createBinaryDescriptorMatcher();

  Mat left_lbd,right_lbd;
  left_lbd=Mat::zeros(1,32,CV_8UC1);
  right_lbd=Mat::zeros(1,32,CV_8UC1);
  left_lbd.at<uchar>(0,0)=136;
  left_lbd.at<uchar>(0,1)=32;
  left_lbd.at<uchar>(0,2)=8;
  left_lbd.at<uchar>(0,3)=0;
  left_lbd.at<uchar>(0,4)=0;
  left_lbd.at<uchar>(0,5)=0;
  left_lbd.at<uchar>(0,6)=32;
  left_lbd.at<uchar>(0,7)=112;
  left_lbd.at<uchar>(0,8)=32;
  left_lbd.at<uchar>(0,9)=80;
  left_lbd.at<uchar>(0,10)=0;
  left_lbd.at<uchar>(0,11)=216;
  left_lbd.at<uchar>(0,12)=136;
  left_lbd.at<uchar>(0,13)=80;
  left_lbd.at<uchar>(0,14)=128;
  left_lbd.at<uchar>(0,15)=64;
  left_lbd.at<uchar>(0,16)=196;
  left_lbd.at<uchar>(0,17)=32;
  left_lbd.at<uchar>(0,18)=4;
  left_lbd.at<uchar>(0,19)=132;
  left_lbd.at<uchar>(0,20)=4;
  left_lbd.at<uchar>(0,21)=196;
  left_lbd.at<uchar>(0,22)=84;
  left_lbd.at<uchar>(0,23)=196;
  left_lbd.at<uchar>(0,24)=68;
  left_lbd.at<uchar>(0,25)=196;
  left_lbd.at<uchar>(0,26)=132;
  left_lbd.at<uchar>(0,27)=4;
  left_lbd.at<uchar>(0,28)=196;
  left_lbd.at<uchar>(0,29)=72;
  left_lbd.at<uchar>(0,30)=68;
  left_lbd.at<uchar>(0,31)=196;

  right_lbd.at<uchar>(0,0)=191;
  right_lbd.at<uchar>(0,1)=191;
  right_lbd.at<uchar>(0,2)=191;
  right_lbd.at<uchar>(0,3)=187;
  right_lbd.at<uchar>(0,4)=191;
  right_lbd.at<uchar>(0,5)=255;
  right_lbd.at<uchar>(0,6)=255;
  right_lbd.at<uchar>(0,7)=191;
  right_lbd.at<uchar>(0,8)=187;
  right_lbd.at<uchar>(0,9)=191;
  right_lbd.at<uchar>(0,10)=255;
  right_lbd.at<uchar>(0,11)=19;
  right_lbd.at<uchar>(0,12)=19;
  right_lbd.at<uchar>(0,13)=59;
  right_lbd.at<uchar>(0,14)=255;
  right_lbd.at<uchar>(0,15)=255;
  right_lbd.at<uchar>(0,16)=255;
  right_lbd.at<uchar>(0,17)=187;
  right_lbd.at<uchar>(0,18)=191;
  right_lbd.at<uchar>(0,19)=255;
  right_lbd.at<uchar>(0,20)=255;
  right_lbd.at<uchar>(0,21)=255;
  right_lbd.at<uchar>(0,22)=191;
  right_lbd.at<uchar>(0,23)=255;
  right_lbd.at<uchar>(0,24)=255;
  right_lbd.at<uchar>(0,25)=255;
  right_lbd.at<uchar>(0,26)=255;
  right_lbd.at<uchar>(0,27)=255;
  right_lbd.at<uchar>(0,28)=255;
  right_lbd.at<uchar>(0,29)=255;
  right_lbd.at<uchar>(0,30)=255;
  right_lbd.at<uchar>(0,31)=119;

  std::vector <DMatch> matches;
  cout<<left_lbd<<endl;
  cout<<right_lbd<<endl;
  Mat mask=Mat::ones(1,1, CV_8UC1);
  bdm->match( left_lbd, right_lbd, matches,mask);
  cout<<matches.size()<<endl;

  return 1;
}

the output:
[136,  32,   8,   0,   0,   0,  32, 112,  32,  80,   0, 216, 136,  80, 128,  64, 196,  32,   4, 132,   4, 196,  84, 196,  68, 196, 132,   4, 196,  72,  68, 196]
[191, 191, 191, 187, 191, 255, 255, 191, 187, 191, 255,  19,  19,  59, 255, 255, 255, 187, 191, 255, 255, 255, 191, 255, 255, 255, 255, 255, 255, 255, 255, 119]
Segmentation fault (core dumped)

Someone met this? I am confused...

**Comment by berak** [comment]
[this might be related](https://github.com/opencv/opencv_contrib/issues/1443)

**Comment by f1r1o1n1t1** [comment]
@berak I think that two issues are not the same thing. In his case, mask is for keyline detection, mask is used to decide the region of interest to detect lines; in this case,line detection and descriptor computation are done. Though we also have a mask, this mask is used to force a match for the query line descriptor.
