### ISSUE TITLE
example_datasets_hpe_humaneva is missing from directory opencv/build/bin/

### ISSUE THREAD

**Issue by devmishrs** [opencv/opencv_contrib#1489]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by devmishrs** [comment]
thank you @sturkmen72 for your response. Later I'd just changed my plan and switched to OpenPose dataset. But later I want to extend my project. So I want support of you guys.

**Comment by devmishrs** [comment]
@sturkmen72 You supported me(I am Dev) on answers.opencv.org so thanks a lot!!

**Comment by sturkmen72** [comment]
please close the issue and use Q&A forum for questions.
