### ISSUE TITLE
DPM detection example crashes with exception

### ISSUE THREAD

**Issue by kostik1337** [opencv/opencv_contrib#1490]
##### System information (version)
- OpenCV => 3.4.0-rc
- Operating System / Platform => Linux Mint 18.2 Sonya, kernel 4.8.0-53-generic, x86_64
- Compiler => g++ 5.4.0

##### Detailed description

Module dpm crashes on method detect with exception:
OpenCV Error: Assertion failed (func != 0) in resize, file /home/xxx/opencv/modules/imgproc/src/resize.cpp, line 3722
I found that if I revert changes done in commit 8c394a4f2e02994f21c3cf88706ad62d65b53431 (change resize(imageM, imScaled, imSize * scale, 0, 0, INTER_LINEAR_EXACT) to resize(imageM, imScaled, imSize * scale)), everything is working OK.

##### Steps to reproduce

Simply run any dpm example, cascade_detect_camera or cascade_detect_sequence

**Comment by sturkmen72** [comment]
i already get a problem and forgot to report in line https://github.com/opencv/opencv/blob/master/modules/photo/src/contrast_preserve.hpp#L236

**Comment by alalek** [comment]
related PRs: https://github.com/opencv/opencv/pull/9468 , #1482
/cc @terfendail

**Comment by terfendail** [comment]
INTER_LINEAR_EXACT should be reverted in case CV_32F or CV_64F matrices are processed. Bit-exact resize make sense(and thus was implemented) for integer types only.
Going to check where I've changed resize to bit-exact for floating point type matrices
