### ISSUE TITLE
Compile Opencv 3.3 with contrib module 

### ISSUE THREAD

**Issue by ShaharSarShalom** [opencv/opencv_contrib#1494]
Hey 

I'd like to know what is the compatible version of opencv with opencv contrib module. 

I compiled opencv 3.3 with the latest contrib module and kept on receiving the following error: 
undeclared identifier INTER_LINEAR EXACT

##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

tracking and many more modules failed due to this error. 

##### Steps to reproduce

Compile latest opencv 3.3 with latest contrib module 

Thank you for your help 

S

**Comment by alalek** [comment]
Different versions of opencv / opencv_contrib are not supported. Keep source code synchronized.

**Comment by ShaharSarShalom** [comment]
Ok, what is the current supported opencv version?

**Comment by vpisarev** [comment]
Opencv_contrib has the same tags as opencv. Download the snapshot with the same tag as opencv. In your case that will be 3.3.0
