### ISSUE TITLE
Can we use the new background subtraction algorithms in Java wrapping?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv_contrib#1495]
##### System information (version)

- OpenCV =>3.4.0
- Operating System / Platform =>Windows 64 Bit
- Compiler =>Visual Studio 2017

##### Detailed description

I want to use **new background subtraction algorithms** in Java wrapping, but when I build OpenCV from source with extra modules for Java, but I cannot see any newly added algorithms for background subtraction in Java Jar file. But when I open `opencv_contrib\modules\bgsegm` then opened `CMakeLists.txt` and inside I did not see wrapping for Java. 

> set(the_description "Background Segmentation Algorithms")
> ocv_define_module(bgsegm opencv_core opencv_imgproc opencv_video opencv_calib3d WRAP python)

So I want to ask that, can I manually add Java or not? Something like this:

> set(the_description "Background Segmentation Algorithms")
> ocv_define_module(bgsegm opencv_core opencv_imgproc opencv_video opencv_calib3d WRAP python **java**)

**Comment by mshabunin** [comment]
@Bahramudin , surely you can try. Feel free to provide a pull request if it builds and works well.

**Comment by Bahramudin** [comment]
@mshabunin I have tried, but it failed to build the Jar file and its corresponding DLL. So I think now it does not support Java, hope in next updated we can able to use the new background subtraction algorithms in Java too.

**Comment by berak** [comment]
there is no `import org.opencv.video.BackgroundSubtractor` in the generated BackgroundSubtractorMOG.java, etc, so it tries to inherit from bgsegm.BackgroudExtractor, which does not exist.
