### ISSUE TITLE
yml file not loaded using xphoto::LearningBasedWB function

### ISSUE THREAD

**Issue by davidlavy88** [opencv/opencv_contrib#1504]
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Ubuntu 16.04
- Compiler => Qt

##### Detailed description

xphoto::LearningBasedWB(String) doesn't load the input yml string. The tutorial referenced here https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/tutorials/training_white_balance.markdown when doing the testing part always throws a Segmentation fault (core dumped) error. And it's because it's not loading the yml file. I also used this example https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/include/opencv2/xphoto/white_balance.hpp and used the yml file given by the first tutorial and the same error appeared

##### Steps to reproduce

Running the python tutorial here: https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/tutorials/training_white_balance.markdown
Or the cpp example here: https://github.com/opencv/opencv_contrib/blob/master/modules/xphoto/samples/color_balance.cpp
Both loading the yml file throws a Segmentation fault (core dumped) error.

I'm also uploading the .yml file for easier reproduction of the problem: 
https://drive.google.com/file/d/1_5PUUb_VsSC18nMzsy_DYzWNnO926UI9/view?usp=sharing

**Comment by berak** [comment]
learn_color_balance.py erroneously wrote double values, where integers are expected. so the yml looks like:

```
%YAML:1.0
---
num_trees: 30.
num_tree_nodes: 64.
...

trying to read them back into integers from c++:

```
            num_trees = fs["num_trees"];
            num_tree_nodes = fs["num_tree_nodes"];
```

results in 0x7fffffff for both values
