### ISSUE TITLE
DAISY is not thread-safe

### ISSUE THREAD

**Issue by Sahloul** [opencv/opencv_contrib#1508]
##### System information (version)
- OpenCV => 3.3.1-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I have tested many detectors and descriptors, and it seems DAISY have some threading issue!

##### Steps to reproduce
```.py
import cv2
from multiprocessing.pool import ThreadPool

fast = cv2.FastFeatureDetector_create()
daisy = cv2.xfeatures2d.DAISY_create()
pool = ThreadPool(processes = cv2.getNumberOfCPUs())

def process(idx):
    rgb = cv2.imread('any_image.png', cv2.IMREAD_UNCHANGED)
    kps = fast.detect(rgb)
    kps, descrs = daisy.compute(rgb, kps)
    return idx

#ires = map(process, range(10)) #This iterator does not fail
ires = pool.imap(process, range(10))
print(sum(ires))
```

##### Expected output
```
45
```

##### Actual output
Python CRASH due to some error in the CV2 library!

Any idea what is going on?

**Comment by alalek** [comment]
Create for each thread own detector/desriptor/or any other OpenCV algorithm. You can not share OpenCV algorithms between threads. There is no this thread-safety requirement for OpenCV algorithms by design due performance reasons and coding simplification.

**Comment by alalek** [comment]
@Sahloul I created the issue about this in the main repo: https://github.com/opencv/opencv/issues/10532
Suggestions are welcome.

**Comment by cbalint13** [comment]
@Sahloul ,

*  You can call daisy.compute() with different  rgb/kpt data (copies).
*  Please notice that daisy.compute() internally is already doing lot of parallel stuff (wherever is possible).

* I was able to do computation in different threads but in C++ (same const rgb Mat image, different localy computed keypoints), not sure your python code what is doing exactly, but as @alalek said is important that detector (fast) and descriptor (daisy) to be initialized from scratch as different objects within each separate thread, then all should work.

Described idea should look something like bellow (untested):

```
import cv2
from multiprocessing.pool import ThreadPool

pool = ThreadPool(processes = cv2.getNumberOfCPUs())

# load once as global image (in C++ would be const), and reuse it in each thread
rgb = cv2.imread('any_image.png', cv2.IMREAD_UNCHANGED)

def process(idx):

    // init detector & descriptor objects
    fast = cv2.FastFeatureDetector_create()
    daisy = cv2.xfeatures2d.DAISY_create()

    kps = fast.detect(rgb)
    kps, descrs = daisy.compute(rgb, kps)
    return idx

#ires = map(process, range(10)) #This iterator does not fail
ires = pool.imap(process, range(10))
print(sum(ires))
```

**Comment by Sahloul** [comment]
@cbalint13 Thank you very much for your reply.

I am concern more about how to solve the crash issue, rather than how to detect the keypoints or compute the descriptors. OpenCV currently does not throw an exception, which is workable, but rather it crash the whole application. This behavior needs to be changed, because other users will keep attempting the same. Ultimately, crashing is not a way to report errors!

Anyway, thanks again for your kind efforts.
