### ISSUE TITLE
SFM for Android

### ISSUE THREAD

**Issue by asecc** [opencv/opencv_contrib#1518]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Android
- Compiler => NDK 16b

##### Detailed description

We try to compile sfm for android, but we face some errors. 

Is it possible, Do we compile sfm for android and how it can be?

**Comment by alalek** [comment]
It should be possible, but you should have proper versions of Android tools (Android SDK has breaking changes in the last 1-2 years) and install sfm dependencies (ceres) somehow.

NDK 16+ is not supported [yet](https://github.com/opencv/opencv/pull/10515)
Android SDK build-tools: up to [25.2.5](https://github.com/opencv/opencv/pull/8460) with Ant support

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
