### ISSUE TITLE
Census-penalized (Semi-Global) Block Matching

### ISSUE THREAD

**Issue by InonS** [opencv/opencv_contrib#1520]
Has anyone thought of implementing Census-penalized SGBM as part of `opencv_contrib`?

It could make use of the Census & SGBM codes already existing in `opencv_contrib`.

## Reference
http://answers.opencv.org/question/133079/stereo-matching-census-based/

On 2014-05-08, @llschloesser [wrote](http://answers.opencv.org/question/15560/stereo-vision-related-queries/):
> Here is a link to my video of a census stereo alogrithm in OpenCV: https://www.youtube.com/watch?v=glwB9QI8C9Y I can provide source code if folks are interested. It could be optimized further. I think for a CPU algorithm that you want to run at 30 fps, you will find that SGBM is the best tradeoff in terms of accuracy and speed. > However, I would love for someone to replace the BT cost function in SGBM with the census cost function (hamming distance), and similarly for BM (which is essentially what I tried to do). The OpenCV source code isn't very revealing and so I would need a decent amount of time to understand how to insert the different cost functions, but it would be well worth the effort.

**Comment by mshabunin** [comment]
Did you check the _stereo_ module? 
https://github.com/opencv/opencv_contrib/tree/master/modules/stereo

**Comment by InonS** [comment]
@mshabunin I did. Couldn't find a way to include Census in the BM cost function.

**Comment by mshabunin** [comment]
Isn't it a Census cost function: [stereo/src/stereo_binary_bm.cpp#L365-L404](https://github.com/opencv/opencv_contrib/blob/c14ee71106fb0edd2922ee84c621b7376ed46114/modules/stereo/src/stereo_binary_bm.cpp#L365-L404)?

**Comment by InonS** [comment]
@mshabunin you're right, obviously!
I guess [it](https://github.com/opencv/opencv_contrib/blob/c14ee71106fb0edd2922ee84c621b7376ed46114/modules/stereo/src/stereo_binary_sgbm.cpp#L724) could just be [documented](https://docs.opencv.org/master/d1/d9f/classcv_1_1stereo_1_1StereoBinarySGBM.html#aba6accc59d827028635117452a8e5df0) a bit better...
