### ISSUE TITLE
Ridge detection implementation

### ISSUE THREAD

**Issue by trungpv88** [opencv/opencv_contrib#1537]
##### System information (version)

- OpenCV extra module (ximgproc)

##### Detailed description

I am using the ridge detection filter from opencv contrib. This filter uses the eigen values from the Hessian Matrix of the input image using Sobel Derivative. In the the implementation of the filter, I see:

Mat rootex;
rootex = (sb2xx +  (sb2xy + sb2xy + sb2xy + sb2xy)  - (sbxxyy + sbxxyy) + sb2xy );

##### Steps to reproduce

But as i compute, it should be:

Mat rootex;
rootex = (sb2xx +  (sb2xy + sb2xy + sb2xy + sb2xy)  - (sbxxyy + sbxxyy) + sb2yy );

Please check it.

**Comment by kushalvyas** [comment]
yes, it should be `sb2yy` instead of `sb2xy`

**Comment by kushalvyas** [comment]
I'll submit the patch to opencv_extra . That'll sort out the build issues
