### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MultiTracker_create'

### ISSUE THREAD

**Issue by korabelnikov** [opencv/opencv_contrib#1541]
same issue as in https://github.com/opencv/opencv_contrib/issues/1271 what was closed without right answer

> Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.4.0'
>>> tracker = cv2.MultiTracker_create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'MultiTracker_create'

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Check that your build contains modules from opencv_contrib (see getBuildinformation()).
