### ISSUE TITLE
documentation git-bash script for installing tesseract and leptonica doesn't generate cv::text library

### ISSUE THREAD

**Issue by estekitaly** [opencv/opencv_contrib#1558]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform =>Windows 64 Bit
- Compiler => CMake 3.9.1 - Visual Studio 2015 64 Bit

##### Detailed description

as suggested by @LaurentBerger I created this separate issue to report a problem that I described in https://github.com/opencv/opencv_contrib/issues/1556

the last part of the script suggested in https://docs.opencv.org/3.4.0/db/d4c/tutorial_install_tesseract.html  doesn't actually generate the cv::text library that contains the OCR classes.

I think we should add the BUILD_opencv_text option to the CMAKE_OPTION

##### Steps to reproduce

follow the steps in https://docs.opencv.org/3.4.0/db/d4c/tutorial_install_tesseract.html

the main thing to test is the last part of the script "installTesseract.sh"

**Comment by LaurentBerger** [comment]
No when opencv cmake detects that all condition are available  for a module then BUILD_modulename becomes true
