### ISSUE TITLE
documentation git-bash script for installing tesseract and leptonica doesn't actually use libs generated in the previous steps

### ISSUE THREAD

**Issue by estekitaly** [opencv/opencv_contrib#1560]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => CMake - Visual Studio 2015 64bit

##### Detailed description

the line: cmake -G"$CMAKE_CONFIG_GENERATOR" -DCMAKE_INSTALL_PREFIX="$myRepo"/Install/leptonica "$myRepo/$RepoSource"

should it contain both zlib and libpng references?

##### Steps to reproduce
follow the instructions in https://docs.opencv.org/3.4.0/db/d4c/tutorial_install_tesseract.html until the creation of installTesseract.sh

**Comment by alalek** [comment]
Lets keep these issues with documentation in the single issue #1556 .
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org - this tracker is for issues and bugs that needs fix in OpenCV.
