### ISSUE TITLE
debug - cv::text::OCRTesseractImpl::run crashes on delete [] if no text is detected

### ISSUE THREAD

**Issue by estekitaly** [opencv/opencv_contrib#1561]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015 Win64
- Configuration => Debug
- Method => cv::text::OCRTesseractImpl::run
- File => opencv_contrib\modules\text\src\ocr_tesseract.cpp
##### Detailed description
        char *outText;
        outText = tess.GetUTF8Text();
        output = string(outText);
        delete [] outText;
if outText is blank then my visual studio will throw an access violation

same thing for the following line

        delete[] word;
it will crash

This only happens on the Debug Configuration, If I change to Release then there is no crash.
##### Steps to reproduce
just need to pass an image with no text in it, I will try to provide a better test case later.

**Comment by berak** [comment]
the `delete [] word` case is already handled by the `continue` [here](https://github.com/opencv/opencv_contrib/blob/master/modules/text/src/ocr_tesseract.cpp#L215) , but there's another possible null pointer case wit `ri` [here](https://github.com/opencv/opencv_contrib/blob/master/modules/text/src/ocr_tesseract.cpp#L215)
