### ISSUE TITLE
 make error: While installing OpenCV 3.3.0 on Raspberry pi 3

### ISSUE THREAD

**Issue by PainHup** [opencv/opencv_contrib#1567]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => Raspbian Stretch on Raspberry Pi 3
- Compiler => make

##### Detailed description

- When I finished cmake command and moved to next step which is make I got error.
- I run make VERBOSE=1 and included the result in the attached file

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example
    
 or attach as .txt or .zip file
-->
[error.txt](https://github.com/opencv/opencv_contrib/files/1758620/error.txt)

**Comment by alalek** [comment]
> OpenCV 3.3.0

Fixed in OpenCV master / 3.4.1
