### ISSUE TITLE
Build error: Cannot open opencv_core340d.lib

### ISSUE THREAD

**Issue by zeshaoaaa** [opencv/opencv_contrib#1576]
#### System information (version)
- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

#### Detailed description

I configured and generate CMake configuration succeed. When I trying to build the solution for extra module 'contrib', following errors will occur. I didn't find opencv_core340d.lib on my computer. Is there anyone know how to fix this problem? If my description is not clear enough, please tell me. Thanks in advance!

#### Visual Studio Error Info
Severity	Code	Description	Project	File	Line	Suppression State

Error	MSB6006	"cmd.exe" exited with code 1.	opencv_core	d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_core340d.lib'	opencv_flann	D:\Program Files\opencv\build\modules\flann\LINK	1	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_core340d.lib'	opencv_ml	D:\Program Files\opencv\build\modules\ml\LINK	1	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_flann340d.lib'	opencv_surface_matching	D:\Program Files\opencv\build\modules\surface_matching\LINK	1	

Error	MSB6006	"cmd.exe" exited with code 1.	opencv_cudaarithm	d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_core340d.lib'	opencv_imgproc	D:\Program Files\opencv\build\modules\imgproc\LINK	1	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_imgproc340d.lib'	opencv_objdetect	D:\Program Files\opencv\build\modules\objdetect\LINK	1	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_imgproc340d.lib'	opencv_video	D:\Program Files\opencv\build\modules\video\LINK	1	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_video340d.lib'	opencv_shape	D:\Program Files\opencv\build\modules\shape\LINK	1	

Error	LNK1104	cannot open file '....\lib\Debug\opencv_imgproc340d.lib'	opencv_plot	D:\Program Files\opencv\build\modules\plot\LINK	1	

#### Steps to reproduce

Configure CMake.
Generate CMake files.
build 'ALL_BUILD'.

**Comment by berak** [comment]
since this is not an opencv library bug, and also not specific to opencv_contrib, 

would you be so kind, to close this issue, and ask again on http://answers.opencv.org ? 

(we could help you better from there)
