### ISSUE TITLE
face: face_landmark_model does not get installed

### ISSUE THREAD

**Issue by berak** [opencv/opencv_contrib#1577]
##### System information (version)

- OpenCV => 3.4.1 (master
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw64

##### Detailed description

cmake downloads it, but it ends up in `opencv/build/testdata` .
(probably useful, to have a copy there for local tests, but the build folder is likely to be removed after installing opencv to the final location. shouldn't it go to  `install/etc` , along with the cascade files ?

**Comment by alalek** [comment]
Like DNN models such large "optional" files should not be included in the default binary distribution. Users should download them separately (link to this file should exist in the tutorials).

**Comment by berak** [comment]
ok. right now, cmake *does* download it automatically, 69mb.

**Comment by alalek** [comment]
This is for tests (downloaded into build folder).
It is not "installed" (included into default binary distribution).

**Comment by berak** [comment]
ok, seems i misunderstood the purpose, then.
