### ISSUE TITLE
cv::xphoto::inpaint crashed in KDTreeComparator::operator()(int const&, int const&) const

### ISSUE THREAD

**Issue by hezhk3** [opencv/opencv_contrib#1578]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => iOS 11
![inpaint-crash](https://user-images.githubusercontent.com/18214217/37457868-2efc0f1c-287e-11e8-8aae-54c987554da3.png)

**Comment by berak** [comment]
hello, @hezhk3 , could you add a short code example (and maybe a small image) to reproduce the error ?

(and maybe drop the screenshot ? yes, there's a buffer overrun, but apart from that, no useful information there)

**Comment by hezhk3** [comment]
Sorry for the late reply. Using these two images as src and mask, the xphoto::inpaint is crashing all the time.

[images.zip](https://github.com/opencv/opencv_contrib/files/1854292/images.zip)

my test code: https://pan.baidu.com/s/1Ospqv_atheXd-Svu8bqrTw

**Comment by terfendail** [comment]
I've tried to reproduce the issue but doesn't get the crash at least for the following code
`
Mat src = imread("src.png", IMREAD_GRAYSCALE);
Mat mask = imread("mask.png", IMREAD_GRAYSCALE);
Mat dst;
xphoto::inpaint(src, mask, dst, xphoto::INPAINT_SHIFTMAP);
return 0;
`

**Comment by hezhk3** [comment]
@terfendail I've tested on Windows. It's wired that I can't reproduce on Windows. Maybe it's only crashing on iOS.

```
#include "stdafx.h"

#include <opencv.hpp>
#include <opencv2/xphoto.hpp>

using namespace cv;


int main()
{
	Mat src = imread("src.png");
	Mat mask = imread("mask.png", IMREAD_GRAYSCALE);
	Mat dst;
	xphoto::inpaint(src, mask, dst, xphoto::INPAINT_SHIFTMAP);
	imwrite("dst.png", dst);
	return 0;
}
```

**Comment by puchog** [comment]
I am getting the same issue on iOS, I found that applying the modifications proposed on https://github.com/opencv/opencv_contrib/issues/965#issuecomment-429535041 the issue its fixed, when I get some time I will create the PR with the fix

**Comment by doprea** [comment]
I have a segmentation fault too using the inpaint cv::xphoto::INPAINT_SHIFTMAP and the following images.
If I use smaller images I have no problems.

![test_shiftmap](https://user-images.githubusercontent.com/7062741/150516921-6af0d130-76a1-417d-8e7f-4cdd1ba2c4de.png)
![mask_shiftmap](https://user-images.githubusercontent.com/7062741/150516978-01191955-58cc-41fe-97b8-e20750bf48d1.png)
