### ISSUE TITLE
Syntax error 'constant' in mace.cpp on Windows

### ISSUE THREAD

**Issue by lamantine** [opencv/opencv_contrib#1580]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 32 bit / Windows 64 bit
- Compiler => Visual Studio 2017

##### Detailed description

Compiler fails with error:
98>E:\Dev\OpenCV\opencv_contrib\modules\face\src\mace.cpp(211): error C2059: syntax error: 'constant'
98>E:\Dev\OpenCV\opencv_contrib\modules\face\src\mace.cpp(212): error C2059: syntax error: 'constant'

This happens because constants rad1 and rad2 are defined in Windows Kits:
c:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\dlgs.h

Renaming constants does help.

**Comment by berak** [comment]
oh, cool, you're fixing it yourself ! (i'll close mine !)

**Comment by lamantine** [comment]
Sorry, I didn't notice your change before sending pull request.
Anyway, thanks for taking my first contribution to this repository :)

**Comment by berak** [comment]
nvm, happy to leave the honour to you !
