### ISSUE TITLE
aruco: Inconsistent custom dictionary generation

### ISSUE THREAD

**Issue by duerig** [opencv/opencv_contrib#1586]
When generating a custom dictionary, aruco uses the platform-specific rand() function to start generating a custom dictionary. Because of this, it does not consistently generate the same set of markers.

There is also no way to readily export or import markers (documentation on this point is old and outdated and doesn't appear to actually map to current practice).  This means that when using a custom dictionary, you must rely on the dictionary being generated the same way with the same parameters each time.

And the result is that markers generated on a Linux build will be different than those on a Windows build, etc. A solution would be to (a) use a known algorithm which performs consistently across platforms  like Mersenne Twister and (b) allow the user to pass in a seed.

Alternatively, adding convenience functions for exporting and importing custom generated dictionaries would also be a solution.

As it stands, the custom dictionary generation is a fundamentally broken workflow which will break in unpredictable ways. The tokens you physically construct today might start inexplicably failing tomorrow because the PRNG changed its output.

**Comment by alalek** [comment]
`rand()` should be replaced to `cv::RNG` methods: integers generation is bit-exact across platforms (floating point numbers generation doesn't bit-exact at this moment).
Current generator (and its seed) can be controlled via `cv::theRNG()`.

**Comment by duerig** [comment]
Thanks to both of you!
