### ISSUE TITLE
Unknown CMake command "ocv_append_source_files_cxx_compiler_options"

### ISSUE THREAD

**Issue by chenjeiwen** [opencv/opencv_contrib#1598]
- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => CMake 3.5.1

##### Detailed description

 Error:CMake Error at opencv_contrib/modules/datasets/CMakeLists.txt:5 (ocv_append_source_files_cxx_compiler_options):
  Unknown CMake command "ocv_append_source_files_cxx_compiler_options".

Is there a solution for this ?

thank you.

**Comment by chaitanyasiva8** [comment]
I got the same error. 
Solved it by using  a previous release.

**Comment by Ivers87** [comment]
Yes, I have the same error.
Cmake: 3.11

**Comment by berak** [comment]
@chaitanyasiva8 , @Ivers87 , it will be nessecary to update you main opencv repository to latest master, so you have [the corresponding cmake definitions](https://github.com/opencv/opencv/pull/11093)

**Comment by yasmineLalabouali** [comment]
@chaitanyasiva8 a previous release of opencv ??

**Comment by yasmineLalabouali** [comment]
I have the same error, I'm working on windows 7

**Comment by berak** [comment]
@yasmineLalabouali please see the comment above , again, and update your main opencv repo. you need latest **master** not the last release (changes from a week ago)

**Comment by virapasas** [comment]
Hey guys. I have one of good solutions about this. Please check this out.

1. Go to <opencv_contrib>/modules/datasets

2. Open CMakeLists.txt 

3. Make all lines of that makeup file as comments. (# --> this is the key, making the line as a comment..)

4. Paste lines below
set (the_description "datasets framework") 
ocv_define_module (datasets opencv_core opencv_imgcodecs opencv_ml opencv_flann OPTIONAL opencv_text WRAP python ) 
ocv_warnings_disable (CMAKE_CXX_FLAGS / wd4267) # flann, Win64 

5. Follow the instruction of <opencv_contrib>/README.md


I think some error of CMake-up file creates the error.

**Comment by alalek** [comment]
> good solutions

Good solution is too keep **both** opencv/opencv_contrib up-to-date (or use the same version). Different versions are not tested and doesn't work.

**Comment by 1091390146** [comment]
@virapasas I have used your method, not to report this mistake, thank you very much.

**Comment by virapasas** [comment]
@1091390146 I found some error when making in build folder in the opencv directory. I am looking at the root cause. Do you have any mind?

**Comment by anthonyshibitov** [comment]
@virapasas this worked for me, thank you.

also experiencing this issue on macOS High Sierra 10.13.2

**Comment by 1091390146** [comment]
@virapasas However, after the change, I encountered some other problems. I think it is because the version doesn't match.

**Comment by anthonyshibitov** [comment]
Can confirm, did not have any errors when building this on opencv 4.0.0

**Comment by virapasas** [comment]
@anthonyshibitov , @1091390146, 

This was very simple problem. The solution is 'use the correlated version of opencv_contrib with the opencv version.'. For example, if you guys installed opencv-3.4.0, copencv_contrib-3.4.0 should be installed. Please refer to the url below:

https://github.com/opencv/opencv_contrib/releases

**Comment by maddanio** [comment]
opencv 4? there is not tag for that. i tried with 3.4.1 on both repos and it breaks, so this is definitely a bug that should be fixed for 3.4.2

**Comment by maddanio** [comment]
do you want to re-open, or should i file a new issue?

**Comment by maddanio** [comment]
oh, shit, this seems to actually be a bug in the cmake function i use to clone repos, sorry!
