### ISSUE TITLE
When I use FeatureDetector.create(FeatureDetector.SURF).detect(templateImage, templateKeyPoints), java vm crashed.

### ISSUE THREAD

**Issue by whoooami** [opencv/opencv_contrib#1603]
##### System information (version)

- OpenCV = 3.2
- Operating System / Platform => Mac OS 10.13.2
- Compiler => cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>

###### When I run code like this:  

public void matchImage(Mat templateImage, Mat originalImage) {
        MatOfKeyPoint templateKeyPoints = new MatOfKeyPoint();
        FeatureDetector featureDetector = FeatureDetector.create(FeatureDetector.SURF);
        featureDetector.detect(templateImage, templateKeyPoints);
}

###### The java vm was crashed...  

```
A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x000000012647dd69, pid=6534, tid=0x0000000000001903

JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C  [libopencv_java320.dylib+0x74d69]  Java_org_opencv_features2d_FeatureDetector_detect_11+0xa9

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

An error report file with more information is saved as:
```

Thx for your time.

**Comment by alalek** [comment]
> OpenCV = 3.2

There are 4 releases after OpenCV 3.2. We don't maintain already released versions.
Try OpenCV 3.4.1 and/or the latest master branch at first.

**Comment by berak** [comment]
also, answered [here](http://answers.opencv.org/question/188975/when-i-use-featuredetectorcreatefeaturedetectorsurfdetecttemplateimage-templatekeypoints-java-vm-crashed/)

(imho, we can close this)

**Comment by whoooami** [comment]
Yeah, it works. Thank you all.
