### ISSUE TITLE
Phase Unwrapping Build Errors on OSX

### ISSUE THREAD

**Issue by anthonyshibitov** [opencv/opencv_contrib#1607]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => High Sierra 10.13.2
- Compiler => Apple LLVM version 9.1.0 (clang-902.0.39.1)

##### Detailed description

/modules/phase_unwrapping/src/histogramphaseunwrapping.cpp fails to compile, gives following errors:

/opencv_contrib/modules/phase_unwrapping/src/histogramphaseunwrapping.cpp:54:45: error: 
      expected ';' at end of declaration list
    virtual ~HistogramPhaseUnwrapping_Impl() CV_OVERRIDE {};

/opencv_contrib/modules/phase_unwrapping/src/histogramphaseunwrapping.cpp:58:61: error: 
      expected ';' at end of declaration list
                         InputArray shadowMask = noArray() ) CV_OVERRIDE;

/opencv_contrib/modules/phase_unwrapping/src/histogramphaseunwrapping.cpp:60:64: error: 
      expected ';' at end of declaration list
    void getInverseReliabilityMap( OutputArray reliabilityMap ) CV_OVERRIDE;

##### Steps to reproduce

Uncheck BUILD_SHARED_LIBS
Uncheck BUILD_TESTS
Uncheck BUILD_opencv_hdf
Add an SDK path to CMAKE_OSX_SYSROOT, “/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk”.
Add x86_64 to CMAKE_OSX_ARCHITECTURES, this tells it to compile against the current system
Uncheck WITH_1394
Uncheck WITH_FFMPEG
-->

**Comment by alalek** [comment]
Update both opencv/opencv_contrib repositories.
