### ISSUE TITLE
Failed to build xobjdetect module opencv contrib

### ISSUE THREAD

**Issue by anhdan** [opencv/opencv_contrib#1608]
**Please state the information for your system**

    OpenCV version: 3.3.0
    Host OS: Linux 4.4.38-tegra aarch64
    Compiler & CMake: GCC 5.4.0 & CMake 3.5.1

**In which part of the OpenCV library you got the issue?**

Building the repository with extra opencv_contrib, xobjdetect module

**Expected behaviour**

As the instruction in https://jkjung-avt.github.io/opencv3-on-tx2/

**Actual behaviour**

The make process failed at building **xobjdetect** module.

Here is the log after cmake command

` OpenCV modules:
         To be built:                 cudev core cudaarithm flann hdf imgproc ml objdetect phase_unwrapping plot reg surface_matching video xphoto cudabgsegm cudafilters cudaimgproc cudawarping dnn freetype fuzzy hfs img_hash imgcodecs photo shape videoio xobjdetect cudacodec face highgui bioinspired dnn_objdetect dpm features2d line_descriptor saliency text calib3d ccalib cudafeatures2d cudalegacy cudaobjdetect cudaoptflow cudastereo cvv datasets rgbd stereo structured_light superres tracking videostab xfeatures2d ximgproc aruco bgsegm optflow sfm stitching python2
         Disabled:                    world
         Disabled by dependency:      -
         Unavailable:                 java python3 ts viz cnn_3dobj dnn_modern matlab ovis
     
       GUI: 
         QT 5.x:                      YES (ver 5.5.1)
         QT OpenGL support:           YES (Qt5::OpenGL 5.5.1)
     Pe     OpenGL support:              YES (/usr/lib/aarch64-linux-gnu/libGLU.so /usr/lib/aarch64-linux-gnu/libGL.so)
         VTK support:                 NO
     
       Media I/O: 
         ZLib:                        /usr/lib/aarch64-linux-gnu/libz.so (ver 1.2.8)
         JPEG:                        /usr/lib/aarch64-linux-gnu/libjpeg.so (ver )
         WEBP:                        /usr/lib/aarch64-linux-gnu/libwebp.so (ver encoder: 0x0202)
         PNG:                         /usr/lib/aarch64-linux-gnu/libpng.so (ver 1.2.54)
         TIFF:                        /usr/lib/aarch64-linux-gnu/libtiff.so (ver 42 - 4.0.6)
         JPEG 2000:                   /usr/lib/aarch64-linux-gnu/libjasper.so (ver 1.900.1)
         OpenEXR:                     build (ver 1.7.1)
         GDAL:                        NO
         GDCM:                        NO
     
       Video I/O:
         DC1394 1.x:                  NO
         DC1394 2.x:                  YES (ver 2.2.4)
         FFMPEG:                      YES
           avcodec:                   YES (ver 56.60.100)
           avformat:                  YES (ver 56.40.101)
           avutil:                    YES (ver 54.31.100)
           swscale:                   YES (ver 3.1.101)
           avresample:                NO
         GStreamer:                   
           base:                      YES (ver 1.8.3)
           video:                     YES (ver 1.8.3)
           app:                       YES (ver 1.8.3)
           riff:                      YES (ver 1.8.3)
           pbutils:                   YES (ver 1.8.3)
         OpenNI:                      NO
         OpenNI PrimeSensor Modules:  NO
         OpenNI2:                     NO
         PvAPI:                       NO
         GigEVisionSDK:               NO
         Aravis SDK:                  NO
         UniCap:                      NO
         UniCap ucil:                 NO
         V4L/V4L2:                    Using libv4l1 (ver 1.10.0) / libv4l2 (ver 1.10.0)
         XIMEA:                       NO
         Xine:                        NO
         Intel Media SDK:             NO
         gPhoto2:                     NO
     
       Parallel framework:            pthreads
     
       Trace:                         YES ()
     
       Other third-party libraries:
         Use Intel IPP:               NO
         Use Intel IPP IW:            NO
         Use VA:                      NO
         Use Intel VA-API/OpenCL:     NO
         Use Lapack:                  YES (/usr/lib/libopenblas.so)
         Use Eigen:                   YES (ver 3.2.92)
         Use Cuda:                    YES (ver 8.0)
         Use OpenCL:                  YES
         Use OpenVX:                  NO
         Use custom HAL:              YES (carotene (ver 0.0.1))
     
       NVIDIA CUDA
         Use CUFFT:                   YES
         Use CUBLAS:                  YES
         USE NVCUVID:                 NO
         NVIDIA GPU arch:             62
         NVIDIA PTX archs:
         Use fast math:               YES
     
       OpenCL:                        <Dynamic loading of OpenCL library>
         Include path:                /home/nvidia/Workspace_dando/setups/opencv330_withContrib/3rdparty/include/opencl/1.2
         Use AMDFFT:                  NO
         Use AMDBLAS:                 NO
     
       Python 2:
         Interpreter:                 /usr/bin/python2.7 (ver 2.7.12)
         Libraries:                   /usr/lib/aarch64-linux-gnu/libpython2.7.so (ver 2.7.12)
         numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.0)
         packages path:               lib/python2.7/dist-packages
     
       Python 3:
         Interpreter:                 /usr/bin/python3 (ver 3.5.2)
     
       Python (for build):            /usr/bin/python2.7
     
       Java:
         ant:                         NO
         JNI:                         NO
         Java wrappers:               NO
         Java tests:                  NO
     
       Matlab:                        Matlab not found or implicitly disabled
     
       Documentation:
         Doxygen:                     NO
     
       Tests and samples:
         Tests:                       NO
         Performance tests:           NO
         C/C++ Examples:              NO
     
       Install path:                  /home/nvidia/Workspace_dando/setups/opencv330_withContrib/install
     
       cvconfig.h is in:              /home/nvidia/Workspace_dando/setups/opencv330_withContrib/build`

When I run make,  there is compilation error when building xobjdetect module

`[ 15%] Building CXX object modules/face/CMakeFiles/opencv_face_pch_dephelp.dir/opencv_face_pch_dephelp.cxx.o
In file included from /home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/precomp.hpp:74:0,
                 from /home/nvidia/Workspace_dando/setups/opencv330_withContrib/build/modules/xobjdetect/opencv_xobjdetect_pch_dephelp.cxx:1:
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/feature_evaluator.hpp:114:47: error: expected ‘;’ at end of member declaration
     virtual void write( cv::FileStorage &fs ) const CV_OVERRIDE;
                                               ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/feature_evaluator.hpp:114:53: error: ‘CV_OVERRIDE’ does not name a type
     virtual void write( cv::FileStorage &fs ) const CV_OVERRIDE;
                                                     ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/feature_evaluator.hpp:115:49: error: expected ‘;’ at end of member declaration
     virtual bool read( const cv::FileNode &node ) CV_OVERRIDE;
                                                 ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/feature_evaluator.hpp:115:51: error: ‘CV_OVERRIDE’ does not name a type
     virtual bool read( const cv::FileNode &node ) CV_OVERRIDE;
                                                   ^
In file included from /home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/precomp.hpp:75:0,
                 from /home/nvidia/Workspace_dando/setups/opencv330_withContrib/build/modules/xobjdetect/opencv_xobjdetect_pch_dephelp.cxx:1:
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:67:48: error: expected ‘;’ at end of member declaration
         int _maxSampleCount, cv::Size _winSize ) CV_OVERRIDE;
                                                ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:67:50: error: ‘CV_OVERRIDE’ does not name a type
         int _maxSampleCount, cv::Size _winSize ) CV_OVERRIDE;
                                                  ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:68:107: error: expected ‘;’ at end of member declaration
     virtual void setImage(const cv::Mat& img, uchar clsLabel, int idx, const std::vector<int> &feature_ind) CV_OVERRIDE;
                                                                                                           ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:68:109: error: ‘CV_OVERRIDE’ does not name a type
     virtual void setImage(const cv::Mat& img, uchar clsLabel, int idx, const std::vector<int> &feature_ind) CV_OVERRIDE;
                                                                                                             ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:69:46: error: expected ‘;’ at end of member declaration
     virtual void setWindow(const cv::Point& p) CV_OVERRIDE
                                              ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:69:48: error: ‘CV_OVERRIDE’ does not name a type
     virtual void setWindow(const cv::Point& p) CV_OVERRIDE
                                                ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:71:44: error: expected ‘;’ at end of member declaration
     virtual float operator()(int featureIdx) CV_OVERRIDE
                                            ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:71:46: error: ‘CV_OVERRIDE’ does not name a type
     virtual float operator()(int featureIdx) CV_OVERRIDE
                                              ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:73:82: error: expected ‘;’ at end of member declaration
     virtual void writeFeatures( cv::FileStorage &fs, const cv::Mat& featureMap ) const CV_OVERRIDE;
                                                                                  ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:73:88: error: ‘CV_OVERRIDE’ does not name a type
     virtual void writeFeatures( cv::FileStorage &fs, const cv::Mat& featureMap ) const CV_OVERRIDE;
                                                                                        ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:75:35: error: expected ‘;’ at end of member declaration
     virtual void generateFeatures() CV_OVERRIDE;
                                   ^
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/lbpfeatures.h:75:37: error: ‘CV_OVERRIDE’ does not name a type
     virtual void generateFeatures() CV_OVERRIDE;
                                     ^
In file included from /home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/precomp.hpp:77:0,
                 from /home/nvidia/Workspace_dando/setups/opencv330_withContrib/build/modules/xobjdetect/opencv_xobjdetect_pch_dephelp.cxx:1:
/home/nvidia/Workspace_dando/setups/opencv_contrib/modules/xobjdetect/src/wbdetector.hpp:55:31: error: expected initializer before ‘:’ token
 class WBDetectorImpl CV_FINAL : public WBDetector {
                               ^
modules/xobjdetect/CMakeFiles/opencv_xobjdetect_pch_dephelp.dir/build.make:62: recipe for target 'modules/xobjdetect/CMakeFiles/opencv_xobjdetect_pch_dephelp.dir/opencv_xobjdetect_pch_dephelp.cxx.o' failed
make[2]: *** [modules/xobjdetect/CMakeFiles/opencv_xobjdetect_pch_dephelp.dir/opencv_xobjdetect_pch_dephelp.cxx.o] Error 1
CMakeFiles/Makefile2:5564: recipe for target 'modules/xobjdetect/CMakeFiles/opencv_xobjdetect_pch_dephelp.dir/all' failed
make[1]: *** [modules/xobjdetect/CMakeFiles/opencv_xobjdetect_pch_dephelp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

One more weird thing is that I have tried to disable some module with '-DBUILD_<module>=OFF', but they still appear in to-build list. Could you help me solve this problem, please?

Thank in advance

**Comment by alalek** [comment]
You can't use different versions of `opencv`/`opencv_contrib`.
You should use code from **the same** tag, HEAD of the branch, date for *both* repositories.

**Comment by anhdan** [comment]
Thank you alalek, 

Let me try it

**Comment by anhdan** [comment]
You are right, I mistake is not taking the correct opencv_contrib version for opencv_3.3.0

Thank you, :))
