### ISSUE TITLE
weightedMedianFilter hangs with some input images

### ISSUE THREAD

**Issue by amyznikov** [opencv/opencv_contrib#1610]
##### System information (version)
- OpenCV => 3.4.1-312-g7e5581c
- opencv_contrib => 3.4.1-70-g2aaa67a
- Operating System / Platform => GNU/Linux x86_64 (Linux Mint 18.3 Sylvia)
- Compiler => gcc  5.4.0 20160609

##### Detailed description
The weightedMedianFilter () sometimes hangs with some particular input images.
The hang seems not depend on particular parameters (sigma, radius, weight type or mask image) as well as on joint image, but just on input image content.

It works fine with total majority of input images but fails with some particulars.
   
##### Steps to reproduce
Attached is an example of 16-bit single-channel grayscale png image (uint16_t), which causes weightedMedianFilter() hangup . The image was converted to CV_32FC1 before passing to  weightedMedianFilter().

If I change pixel values in this image in a some way  (for example convert the image to 8 bit, make some brighness/contrast stretch, etc) then no hangups happened.

![ss-2 003](https://user-images.githubusercontent.com/1285263/38772645-ad6218d2-4044-11e8-81fb-19ca63369c42.png)

The outline of code example is below:

    ```.cpp

     // C++ code example
     Mat input_image = cv::imread("ss-2.003.png", IMREAD_UNCHANGED);
     
     input_image.convertTo(input_image, CV_32F);
   
     weightedMedianFilter(Mat::ones(input_image.size(), CV_8U),
        input_image, output_image, raduis, sigma,  WMF_OFF);
    
     // No return: hang up inside of weightedMedianFilter()
 
    ```
Attached is complete code exampe to reproduce.
[weightedMedianFilter-hangup.tar.gz](https://github.com/opencv/opencv_contrib/files/1911165/weightedMedianFilter-hangup.tar.gz)

Just unpack, make and run:
$ ./weightedMedianFilter-hangup ss-2.003.png 

Will see 100% cpu load with no return.

**Comment by berak** [comment]
i could reproduce it, [the problem is here](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/weighted_median_filter.cpp#L79-L100)

with your example image, `(l-r)` reaches a final value of `0.000015` in iteration ~25 , and stops decreasing.

**Comment by amyznikov** [comment]
The example image I attached above is not unique problematic image, I can attach more examples if need.

**Comment by alalek** [comment]
@amyznikov Could you check this patch: #1613 ?

BTW, the most part of OpenCV algorithms expect 32F(64F) images within range 0..1.
So It is better to use something like this:
```
-input_image.convertTo(input_image, CV_32F);
+input_image.convertTo(input_image, CV_32F, 1.0f/65535.0f);  // CV_16U only
```

**Comment by amyznikov** [comment]
Hi @alalek , sorry for delay with responce, 

I tested the patch #1613 on 200 potentially problematic images I have, everything works fine now, no hangups happened.

Thank you a lot!
