### ISSUE TITLE
macOS  brew install but can't use --with -contrib option

### ISSUE THREAD

**Issue by ChicCheung** [opencv/opencv_contrib#1616]
System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => macOS High Sierra 10.13.4
- Compiler => homebrew

Detailed description

I use :
brew reinstall opencv3 --with-contrib --with-python3
but return 2 warnings:
Warning: opencv: this formula has no --with-contrib option so it will be ignored!
Warning: opencv: this formula has no --with-python3 option so it will be ignored!

how to fix them?

**Comment by ChicCheung** [comment]
##### System information (version)
<!-- Example
- OpenCV => 3.4.1
- Operating System / Platform => macOS High Sierra 10.13.4
- Compiler => homebrew

##### Detailed description

I use :
brew reinstall opencv3 --with-contrib --with-python3
but return 2 warnings:
Warning: opencv: this formula has no --with-contrib option so it will be ignored!
Warning: opencv: this formula has no --with-python3 option so it will be ignored!

how to fix them?

**Comment by alalek** [comment]
There are no maintainers of homebrew package. Report this to homebrew repository instead (also check for duplicates and related patches before that).
