### ISSUE TITLE
Compiler Ext Modules with Matlab, CMake Generate Error.

### ISSUE THREAD

**Issue by dbyoung720** [opencv/opencv_contrib#1628]
##### System information (version)

- OpenCV => New
- Operating System / Platform => Windows10 X64
- Compiler =>CMake

##### Detailed description

Compiler Ext Modules with Matlab, CMake Generate Error.
Prompt:
CMake Error at E:/Source/OpenCV/opencv_contrib/modules/matlab/CMakeLists.txt:290 (add_dependencies):
The dependency target "opencv_calib3d" of target "opencv_matlab" does not exist.

CMake Error at E:/Source/OpenCV/opencv_contrib/modules/matlab/CMakeLists.txt:290 (add_dependencies):
The dependency target "opencv_core" of target "opencv_matlab" does not exist.
..................................................
..................................................
..................................................

Opencv_world and MATLAB is not coexistence ?

**Comment by berak** [comment]
> Opencv_world and MATLAB is not coexistence ?

you have to disable opencv_world, when building with the modules from opencv_contrib:

    cmake -DBUILD_opencv_world=OFF

**Comment by dbyoung720** [comment]
OK. THANK!
