### ISSUE TITLE
 ‘create’ is not a member of ‘cv::saliency::StaticSaliency’

### ISSUE THREAD

**Issue by Geta-meko** [opencv/opencv_contrib#1633]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by berak** [comment]
[StaticSaliency](https://github.com/opencv/opencv_contrib/blob/fbc4d82fd36009e02af4f6391312e3a9325051e0/modules/saliency/include/opencv2/saliency/saliencyBaseClasses.hpp#L85) is an interface, it's abstract, you cannot create an instance of it.

you can only create child classes of it, e.g. [StaticSaliencySpectralResidual ](https://github.com/opencv/opencv_contrib/blob/fbc4d82fd36009e02af4f6391312e3a9325051e0/modules/saliency/include/opencv2/saliency/saliencyBaseClasses.hpp#L85) or [StaticSaliencyFineGrained](https://github.com/opencv/opencv_contrib/blob/fbc4d82fd36009e02af4f6391312e3a9325051e0/modules/saliency/include/opencv2/saliency/saliencySpecializedClasses.hpp#L122)
