### ISSUE TITLE
TrackerCSRT::update always returns true

### ISSUE THREAD

**Issue by coder80** [opencv/opencv_contrib#1663]
System information (version)
- OpenCV =>  4.0.0 - pre :grey_question:
- Operating System / Platform =>  Ubuntu 16.04 :grey_question:
- Compiler => GCC :grey_question:

##### Detailed description

TrackerCSRT::update always returns true, but expected behavior update must return true/false depends on situation

##### Steps to reproduce

Part of tracker`s code in trackerCSRT.cpp:
    update_csr_filter(image, filter_mask);
    dsst.update(image, object_center);
    boundingBox = bounding_box;
    **return true**;

**Comment by coder80** [comment]
Could you give me method for calculation tracker confidence?

**Comment by amuhic** [comment]
Hi,
this tracker currently does not have a very reliable way of calculating the confidence. The closest thing to what you probably want is located in Point2f TrackerCSRTImpl::estimate_new_position(const Mat &image). Where new position is based on the max value's location of response matrix. You could probably look at the magnitude of that value to determine the confidence, but I'm unsure of how accurate this will be.

**Comment by berak** [comment]
so, i made some experiment based on @amuhic 's idea.

https://github.com/opencv/opencv_contrib/blob/14be1519fb661babe6a00825d4578da8b056f186/modules/tracking/src/trackerCSRT.cpp#L433

this seems to be the the psr of the localization step in figure 6 [of the paper](https://arxiv.org/abs/1611.08461)

we could threshold the max_val, for the test videos (david,dudek,faceocc) i get a mean value of 0.2, the worst one is 0.059 in the faceocc scene.

trying with a webcam,
a psr threshold of <0.04 seems adequate for detecting "we've lost it !"
