### ISSUE TITLE
ChAruco board topology (nearestMarkerIdx) is sensitive to scale

### ISSUE THREAD

**Issue by gmedan** [opencv/opencv_contrib#1665]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

For certain choices of squareLength in aruco::CharucoBoard::create, the topology of the output board is different from other choices, manifesting in only one option for nearestMarkerIdx where there should be two.
This is due to a magic number 0.0001 in _getNearestMarkerCorners that doesn't take scale into account.
Can cause issues in pose estimation later when charuco corners are filtered out because the only nearest marker is missing, though the correct topology would not filter them out.
I would suggest changing 0.0001 to 
cv::pow(0.01 * _squareLength, 2)

any comments?

##### Steps to reproduce

```.cpp

/**
* @brief Check charuco board creation
*/
class CV_CharucoBoardCreation : public cvtest::BaseTest {
public:
    CV_CharucoBoardCreation();

protected:
    void run(int);
};

CV_CharucoBoardCreation::CV_CharucoBoardCreation() {}

void CV_CharucoBoardCreation::run(int)
{
    Ptr<aruco::Dictionary> dictionary = aruco::getPredefinedDictionary(aruco::DICT_5X5_250);
    int n = 6;
    
    double markerSizeFactor = 0.5;

    for (double squareSize_mm = 5.0; squareSize_mm < 35.0; squareSize_mm += 0.1)
    {
        Ptr<aruco::CharucoBoard> board_meters = aruco::CharucoBoard::create(
            n, n, squareSize_mm*1e-3, squareSize_mm * markerSizeFactor * 1e-3, dictionary);

        Ptr<aruco::CharucoBoard> board_millimeters = aruco::CharucoBoard::create(
            n, n, squareSize_mm, squareSize_mm * markerSizeFactor, dictionary);

        for (int i = 0; i < board_meters->nearestMarkerIdx.size(); i++)
        {
            if (board_meters->nearestMarkerIdx[i].size() != board_millimeters->nearestMarkerIdx[i].size() ||
                board_meters->nearestMarkerIdx[i][0] != board_millimeters->nearestMarkerIdx[i][0])
            {
                ts->printf(cvtest::TS::LOG, 
                    cv::format("Charuco board topology is sensitive to scale with squareSize=%.1f\n",
                        squareSize_mm).c_str());
                ts->set_failed_test_info(cvtest::TS::FAIL_INVALID_OUTPUT);
                break;
            }
        }
    }
}
```

output:
...
Charuco board topology is sensitive to scale with squareSize=6.8
Charuco board topology is sensitive to scale with squareSize=6.9
Charuco board topology is sensitive to scale with squareSize=7.0
Charuco board topology is sensitive to scale with squareSize=9.1
Charuco board topology is sensitive to scale with squareSize=10.6
Charuco board topology is sensitive to scale with squareSize=10.9
...

**Comment by alalek** [comment]
Could you create a Pull Request for "3.4" branch? It will be automatically checked with existed OpenCV tests.
