### ISSUE TITLE
build ios framewrok success but get 'opencv2/xfeatures2d/nonfree.hpp' file not found???

### ISSUE THREAD

**Issue by zhangkai1234** [opencv/opencv_contrib#1666]
the opencv version is :3.4
and the contrib version is 3.4 too.

i build the ios frame success  , just running:
python opencv-3.4.1/platforms/ios/build_framework.py ios --contrib=./opencv_contrib-3.4.1

after 30 minutes , i get the opencv2.framework

all run ok ,but when i : 

#include "opencv2/xfeatures2d/nonfree.hpp"

it gets an error:

'opencv2/xfeatures2d/nonfree.hpp' file not found.

but the most strange was 

i can find the xfeatures2d dir in opencv2framework.

i do not know why?

can any one help me?

thank you very much

**Comment by VladIacobIonut** [comment]
Hi @zhangkai1234 

I'm having the same problem. Did you managed to solve this ??

Thanks.

**Comment by asura1234** [comment]
same problem here

**Comment by siam009** [comment]
Samer problem here

**Comment by riccardoruocco** [comment]
Same problem
