### ISSUE TITLE
Error compiling opencv-3.4.1 with contrib modules (rgbd, aruco, face, etc.)

### ISSUE THREAD

**Issue by ashokpant** [opencv/opencv_contrib#1667]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => cmake

##### Detailed description
Error while compiling opencv with contrib modules
```
modules/rgbd/CMakeFiles/opencv_rgbd.dir/build.make:134: recipe for target 'modules/rgbd/CMakeFiles/opencv_rgbd.dir/src/fast_icp.cpp.o' failed
make[2]: *** [modules/rgbd/CMakeFiles/opencv_rgbd.dir/src/fast_icp.cpp.o] Error 1
CMakeFiles/Makefile2:8251: recipe for target 'modules/rgbd/CMakeFiles/opencv_rgbd.dir/all' failed
make[1]: *** [modules/rgbd/CMakeFiles/opencv_rgbd.dir/all] Error 2
```

##### Steps to reproduce
From opencv-3.4.1 source dir
```bash
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_PYTHON_EXAMPLES=OFF \
      -D INSTALL_C_EXAMPLES=OFF \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.4.1/modules \
      -D PYTHON_EXECUTABLE=~/anaconda3/envs/ml3/bin/python \
      -D BUILD_EXAMPLES=OFF -D WITH_PROTOBUF=OFF -D BUILD_JAVA=OFF ..
make -j8
```

**Comment by daspranab** [comment]
Against WSL shell command ../opencv/build$ cmake -DOPENCV_EXTRA_MODULES_PATH=.../opencv_contrib-master/modules .../opencv/sources got the following output/error logs.
[CMakeError.log](https://github.com/opencv/opencv_contrib/files/2147987/CMakeError.log)
[CMakeOutput.log](https://github.com/opencv/opencv_contrib/files/2147988/CMakeOutput.log)

Any comment?

**Comment by alalek** [comment]
@daspranab Don't add unrelated comments to existed issues.
There is no official support for WSL (`Linux - 4.4.0-43-Microsoft - x86_64`) from OpenCV yet. So custom build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
WSL is declared to be compatible with Linux tools, so looks like it is configuration problem (without acceptable fix in OpenCV).

**Comment by daspranab** [comment]
It's very buggy nevertheless. Shouldn't have wasted time and energy on this.

⁣Sent from BlueMail ​
