### ISSUE TITLE
xfeatures2d module built with SURF and SIFT even when OPENCV_ENABLE_NONFREE is disabled

### ISSUE THREAD

**Issue by SwooshyCueb** [opencv/opencv_contrib#1668]
When setting `OPENCV_ENABLE_NONFREE` to false, the `SURF` and `SIFT` bits of the `xfeatures2d` module are still built. It is my understanding that these bits are patented and require licensing if they are to be used, so they should only be built if `OPENCV_ENABLE_NONFREE` is set to true.

**Comment by SwooshyCueb** [comment]
I agree! I might be able to work on a pull request for this soon-ish.

**Comment by drzraf** [comment]
Isn't #442 a free (or at least authorized) implementation? Wouldn't that be even better?

**Comment by berak** [comment]
@drzraf , it's the algorithm, which is patented, not the implementation. (so, same problem there, imho)
