### ISSUE TITLE
rgbd/src/odometry.cpp:472:30: error: ‘class cv::AutoBuffer<float>’ has no member named ‘data’      float *KRK_inv0_u1 = buf.data();

### ISSUE THREAD

**Issue by s0r2637** [opencv/opencv_contrib#1684]
I am getting aforementioned error in compiling the rgbd module from the Opencv-contrib branch 3.4.

I am running Opencv 3.4.1-dev with Python 2.7.12 on Ubuntu 16.04 64-bit system.

Can someone please help me fix this issue?

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
You should update code from **both** opencv/opencv_contrib repositories.

**Comment by s0r2637** [comment]
I updated both Opencv and Opencv-contrib to master, and I am still getting the same error but in a different context

`error: 'class cv::AutoBuffer <unsigned char>'  has no member data`

This contrib was working fine until 10 days back.  I updated it, and now it is giving all sorts of problems.  Also, I need to use Opencv 3.x for my application.  What is the compatible opencv-contrib for Opencv 3.x?

**Comment by alalek** [comment]
> to master

These changes are not merged into master yet. You need to check 3.4 branch.

Finally, you should get [these lines](https://github.com/opencv/opencv/commit/135ea264ef3ab940feb72ff13bfb944ba1ee4bf8#diff-0602af3c78cf89125b1092e37af6625aR146).

**Comment by s0r2637** [comment]
So the opencv-contrib branch can be anything.  The problem is with the
OpenCV main branch.  I just want to make sure what combination will build
correctly.

**Comment by alalek** [comment]
> So the opencv-contrib branch can be anything

Nope.

We only test code from repositories on the same date from the same branch (3.4 / master) or from the  same tag/version.
You should not mess 3.4/master code.
