### ISSUE TITLE
Aruco Markers white margin 

### ISSUE THREAD

**Issue by vgenten** [opencv/opencv_contrib#1698]
Hello,

I'm currently running different tests to figure out the size of the white margin surrounding an aruco marker. When running the detection on a single marker, the results are best when the size of the white margin is at least as big as the black border of the marker.
But running the detection on a grid of e.g. 4x6 markers the size of the white margin seems to be indifferent, since all detection results are the same. (I run it with white margin sizes 0.1cm, 0.5cm, 1cm with a marker size of 5cm)
Why is that? 
Here is an example of my detection:

![aruco_smaller_size](https://user-images.githubusercontent.com/24294021/43146765-1525e996-8f62-11e8-95db-36a4029ccb30.png)
![aruco grid small margins](https://user-images.githubusercontent.com/24294021/43146775-17b92c86-8f62-11e8-8027-6ccdb0a63eee.png)

Thanks for your answer.

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by MartinStellmacher** [comment]
Is this really a usage question? Detection fails often for single markers if the white border around the black border isn't at least the width of the black border... Of course one can argue: this is a feature and not a bug. But in that case ist should be documented ...
