### ISSUE TITLE
Surface Matching Output Pose is Wrong

### ISSUE THREAD

**Issue by Techtony96** [opencv/opencv_contrib#1701]
##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu 16.04 64 Bit

##### Detailed description
The resulting pose after matching and ICP contains a blob of points and the original model without any changes in pose. The image below is what I am trying to describe. The Dog model is our training input.
![image](https://user-images.githubusercontent.com/1782682/43272920-252da26c-90c9-11e8-9f7c-79019c61e60c.png)
Code used to save .ply file:
```.cpp
cv::Mat pct = cv::ppf_match_3d::transformPCPose(model, result->pose);
cv::ppf_match_3d::writePLY(pct, "pose.ply");
```

##### Steps to reproduce
I am using a .ply dog model exported from blender and almost the exact sample code given. The only special thing I am doing is converting the depth frame I get from the camera (via Intel Realsense) into a Mat with the specified structure and calculating the normals. I got help from the #OpenCV IRC channel for the conversion process and format.

**Comment by Techtony96** [comment]
@alalek I would greatly appreciate any insight you may have into where my process may be wrong or if there is actually a problem in the surface matching module. I can share my some code/my process if that is helpful. I did not include it in the original issue because the code is somewhat scattered through my project.

**Comment by tolgabirdal** [comment]
Well, just by seeing point clouds does not provide us much information. The correct match depends on a couple of things. One of the most important factors is the correctness of the normals of the point cloud. You should make sure the sign ambiguity is correctly resolved: If point clouds are used, the normals are flipped towards the camera and if meshes are used, the triangle indices are correctly ordered.
