### ISSUE TITLE
SelectiveSearchSegmentation crashes with some image

### ISSUE THREAD

**Issue by Rayndell** [opencv/opencv_contrib#1707]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform =>Windows 10 64 bits
- Compiler => Visual Studio 2013

##### Detailed description

cv::ximgproc::segmentation::SelectiveSearchSegmentation crashes with the following error for some images:

OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in cv::Mat::Mat, file F:\OpenCV\opencv-3.2.0\sources\modules\core\src\matrix.cpp, line 522

I attached a particular image for which the crash happens. Strangely, the crash does not happen when I resize the image at a scale of 0.5

![101-2](https://user-images.githubusercontent.com/40670939/43530865-db84cb64-95ae-11e8-9173-34fb21ad8c5f.png)

##### Steps to reproduce

        string filename = "101-2.png";
	Ptr<SelectiveSearchSegmentation> ssSegmentation = createSelectiveSearchSegmentation();

	Mat image = imread(filename, IMREAD_COLOR);
	
	vector<cv::Rect> rectangles;
	//resize(image, image, cv::Size(0, 0), 0.5, 0.5);
	ssSegmentation->setBaseImage(image);
	ssSegmentation->switchToSelectiveSearchFast(100, 100, 0.5);
	ssSegmentation->process(rectangles);

**Comment by alalek** [comment]
Thank you for the reproducer.

Lets track issue in a single place: #705
