### ISSUE TITLE
possible memory leak issue for StereoBinarySGBM

### ISSUE THREAD

**Issue by bill2239** [opencv/opencv_contrib#1710]
I am running disparity computation using StereoBinarySGBM for multiple images, and it crash my program after a while, so my best guess for this to happen is memory leak.
This can be reproduced by running the same images with a infinite loop,
 
while (true) {
image1= imread();
image2=imread();
Ptr<StereoBinarySGBM> sgbm = StereoBinarySGBM::create(0, number_of_disparities, kernel_size);
settings...
sgbm->compute(image1,image2,disp);
}

it looks like to me StereoBinarySGBM is pretty much the same implementation as opencv StereoSGBM, but StereoSGBM run just fine, so I am wondering if someone can shed some light on this issue. thanks.

btw, I use OpenCV 3.3 and Windows 10

**Comment by LaurentBerger** [comment]
Using this source code (windows 10 win 64 opencv -3.4.2-dev) I haven't got any problem : 

#include <windows.h>
#include <psapi.h>
#include <opencv2/opencv.hpp>
#include <opencv2\stereo.hpp>

int main()
{
        MEMORYSTATUSEX memInfo;
        memInfo.dwLength = sizeof(MEMORYSTATUSEX);
        GlobalMemoryStatusEx(&memInfo);
        DWORDLONG totalVirtualMem = memInfo.ullTotalPageFile;
        PROCESS_MEMORY_COUNTERS_EX pmc;
        GetProcessMemoryInfo(GetCurrentProcess(), (PROCESS_MEMORY_COUNTERS*)&pmc, sizeof(pmc));
        SIZE_T virtualMemUsedByMe = pmc.PrivateUsage;
        DWORDLONG totalPhysMem = memInfo.ullTotalPhys; 
        DWORDLONG physMemUsed = memInfo.ullTotalPhys - memInfo.ullAvailPhys;
        Mat image1, image2,disp;
        int i = 0;
        while (true) {
            image1 = imread("g:/lib/opencv/samples/data/aloel.jpg", IMREAD_GRAYSCALE);
            image2 = imread("g:/lib/opencv/samples/data/aloer.jpg", IMREAD_GRAYSCALE);
            Ptr<stereo::StereoBinarySGBM> sgbm = stereo::StereoBinarySGBM::create(0, 64, 5);
            sgbm->compute(image1, image2, disp);

            cout << "Iter : ******************* " << i << " ****************\n";
            cout << "Virtual Memory currently used = " << memInfo.ullTotalPageFile - memInfo.ullAvailPageFile << "\n";
            cout << "Virtual Memory currently used by current process = " << memInfo.ullTotalPageFile - memInfo.ullAvailPageFile << "\n";
            cout << "Total Physical Memory  = " << memInfo.ullTotalPhys << "\n";
            cout << "Physical Memory currently used = " << memInfo.ullTotalPhys - memInfo.ullAvailPhys << "\n";
            cout << "Physical Memory currently used = " << pmc.WorkingSetSize << "\n";
            i++;
        }
    }


Memory comsumption https://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process

**Comment by bill2239** [comment]
okay, thanks. I was using opencv 3.3.1, will try 3.4.2.

**Comment by bill2239** [comment]
it is fixed at 3.4.2!
