### ISSUE TITLE
Erro in fast.cpp

### ISSUE THREAD

**Issue by LiyuCode** [opencv/opencv_contrib#1720]
[https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/src/fast.cpp#L342](Source Code Position)
The line:
```
        buf[0] = _buf.data() ...
```
seems should be :
```
	buf[0] = _buf ...
```
There is no `data` member for `cv::AutoBuffer<uchar,1032>`

**Comment by catree** [comment]
Please keep OpenCV and OpenCV contrib modules synchronized.
Related: [core: align cv::AutoBuffer API with std::vector/std::array #11719](https://github.com/opencv/opencv/pull/11719).
