### ISSUE TITLE
Face tests are failing

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv_contrib#1746]
The build farm is failing due to some broken tests of the face module.
Check the results of the totally unrelated PRs #1730 and #1745 as an example.

**Comment by alalek** [comment]
Confirmed: [nightly build since 1 Sept](http://pullrequest.opencv.org/buildbot/builders/3_4-contrib-lin64/builds/111)

**Comment by alalek** [comment]
`git bisect` points on this commit: https://github.com/opencv/opencv/commit/e1ee744e1552b44b51bc61c393cc947c79506743

**Comment by cv3d** [comment]
Which means `imgproc` is not well tested :/

**Comment by alalek** [comment]
Right, zero C++ tests for `cv::SubDiv2D` =(
