### ISSUE TITLE
failing test_xfeatures2d & test_ximgproc tests

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv_contrib#1754]
The build farm is failing due to some bad commit(s)...
Check the results of the totally unrelated PRs #1730 and #1750 for further details.

@alalek I got you another bisect job ;)
Perhaps nightly builds are not detecting that yet though!

**Comment by alalek** [comment]
Today's nightly builds are failed too.
Problem is caused by this patch: https://github.com/opencv/opencv/pull/12279
