### ISSUE TITLE
Cannot compile opencv_contrib 4.0.0

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1767]
VS 2017 x64 windows 10 64 bits
cmake 3.11.0
opencv (Merge pull request #12467 from alalek:core_use_shared_ptr) and opencv_contrib  (Merge pull request #1765 from alalek:core_use_shared_ptr)

Error in correspondance project 
```
1>g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc(156): error C2088: '==': illegal for struct
1>g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc(183): error C2088: '==': illegal for struct
1>g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc(156): error C2666: 'std::operator ==': 3 overloads have similar conversions
1>g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc(183): error C2666: 'std::operator ==': 3 overloads have similar conversions

```
replaced cv::Ptr with std::shared_ptr [here ](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/src/libmv_light/libmv/correspondence/nRobustViewMatching.h#L130-L132)solves problem

**Comment by alalek** [comment]
> replaced cv::Ptr with std::shared_ptr

Looks good to me. Could you please create PR with proposed changes? (master branch)

**Comment by LaurentBerger** [comment]
Must I change https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/src/libmv_light/libmv/correspondence/nRobustViewMatching.h#L42-L43 too?
Many warnings too : 
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'=': conversion from 'const int' to 'float', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\feature.h	59	
Warning	C4267	'=': conversion from 'size_t' to 'libmv::Matches::ImageID', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\matches.h	120	
Warning	C4267	'=': conversion from 'size_t' to 'libmv::Matches::ImageID', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\matches.h	120	
Warning	C4267	'=': conversion from 'size_t' to 'libmv::Matches::TrackID', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\matches.h	127	
Warning	C4267	'=': conversion from 'size_t' to 'libmv::Matches::TrackID', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\matches.h	127	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc	67	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	97	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	99	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	116	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	263	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	264	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	270	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	271	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	272	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	273	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	239	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	246	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\simple_pipeline.cpp	247	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	97	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	99	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	116	
Warning	C4267	'argument': conversion from 'size_t' to 'unsigned int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	95	
Warning	C4267	'argument': conversion from 'size_t' to 'unsigned int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	106	
Warning	C4267	'argument': conversion from 'size_t' to 'unsigned int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	95	
Warning	C4267	'argument': conversion from 'size_t' to 'unsigned int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	106	
Warning	C4267	'initializing': conversion from 'size_t' to 'const int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc	278	
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc	278	
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\matches.h	231	
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\matches.h	231	
Warning	C4244	'initializing': conversion from '__int64' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc	121	
Warning	C4244	'initializing': conversion from '__int64' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\nrobustviewmatching.cc	123	
Warning	C4267	'return': conversion from 'size_t' to 'int', possible loss of data	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	79	
Warning	C4267	'return': conversion from 'size_t' to 'int', possible loss of data	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\base\vector.h	79	
Warning	C4505	'sincos': unreferenced local function has been removed	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\numeric\numeric.h	39	
Warning	C4505	'sincos': unreferenced local function has been removed	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\numeric\numeric.h	39	
Warning	C4458	declaration of 'descriptor' hides class member	correspondence	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\feature_matching.h	42	
Warning	C4458	declaration of 'descriptor' hides class member	opencv_sfm	g:\lib\opencv_contrib\modules\sfm\src\libmv_light\libmv\correspondence\feature_matching.h	42	
Warning	C4701	potentially uninitialized local variable 'i' used	correspondence	g:\lib\eigen\eigen\src\core\util\memory.h	275	
Warning	C4702	unreachable code	correspondence	g:\lib\eigen\eigen\src\core\util\memory.h	278

**Comment by alalek** [comment]
`libmv` is external library, so it is better do not touch this code. It is enough to just [disable these warnings](https://github.com/opencv/opencv_contrib/blob/3.4.3/modules/sfm/src/libmv_light/CMakeLists.txt#L6).
