### ISSUE TITLE
wrong link in oilpainting tutorial

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1787]
Something is wrong in this [page ](https://docs.opencv.org/trunk/dd/d8c/tutorial_xphoto_oil_painting_effect.html). Images links https://docs.opencv.org/trunk/images/baboon.jpg and https://docs.opencv.org/trunk/images/baboon_oil_painting_effect.jpg are : 
`The requested URL /trunk/images/baboon.jpg was not found on this server.`
In my local build image links are good but wrong in buildbot too (http://pullrequest.opencv.org/buildbot/export/pr_contrib/1779/docs/dd/d8c/tutorial_xphoto_oil_painting_effect.html)

**Comment by berak** [comment]
hi @LaurentBerger , i have some suspicion here: 

your `Images` folder has a capital `I` , while a lowercase one is expected 

(the linux filesystem is case sensitive, i guess your images could not be copied because of this)

**Comment by alalek** [comment]
Please use lowercase for file names / links if possible.
