### ISSUE TITLE
compile error "Duplicated modules NAMES has been found"

### ISSUE THREAD

**Issue by jsjtczh** [opencv/opencv_contrib#1806]
When I compile opencv_contrib using "cmake -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules .."

it returns: 

-- Looking for ccache - not found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.3") 
-- Could NOT find Jasper (missing: JASPER_LIBRARIES JASPER_INCLUDE_DIR) 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-video-1.0'
--   No package 'gstreamer-video-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Checking for module 'gstreamer-base-0.10'
--   No package 'gstreamer-base-0.10' found
-- Checking for module 'gstreamer-video-0.10'
--   No package 'gstreamer-video-0.10' found
-- Checking for module 'gstreamer-app-0.10'
--   No package 'gstreamer-app-0.10' found
-- Checking for module 'gstreamer-riff-0.10'
--   No package 'gstreamer-riff-0.10' found
-- Checking for module 'gstreamer-pbutils-0.10'
--   No package 'gstreamer-pbutils-0.10' found
-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - not found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- Checking for module 'libavresample'
--   No package 'libavresample' found
-- found Intel IPP (ICV version): 2017.0.3 [2017.0.3]
-- at: /home/zonghaochen/Thirdparty/opencv-3.4.3/build/3rdparty/ippicv/ippicv_lnx
-- found Intel IPP IW sources: 2017.0.3
-- at: /home/zonghaochen/Thirdparty/opencv-3.4.3/build/3rdparty/ippicv/ippiw_lnx
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
-- Could NOT find Atlas (missing: Atlas_CBLAS_INCLUDE_DIR Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY Atlas_LAPACK_LIBRARY) 
-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Could NOT find Matlab (missing: MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
-- Found VTK 8.1.1 (/usr/local/lib/cmake/vtk-8.1/UseVTK.cmake)
   calib3d
   core
 > cudaarithm
 > cudabgsegm
 > cudacodec
 > cudafeatures2d
 > cudafilters
 > cudaimgproc
 > cudalegacy
 > cudaobjdetect
 > cudaoptflow
 > cudastereo
 > cudawarping
 > cudev
   dnn
   features2d
   flann
   highgui
   imgcodecs
   imgproc
   java
   js
   ml
   objdetect
   photo
   python
   shape
   stitching
   superres
   ts
   video
   videoio
   videostab
   viz
   world
   aruco
   bgsegm
   bioinspired
   ccalib
   cnn_3dobj
 > cudaarithm
 > cudabgsegm
 > cudacodec
 > cudafeatures2d
 > cudafilters
 > cudaimgproc
 > cudalegacy
 > cudaobjdetect
 > cudaoptflow
 > cudastereo
 > cudawarping
 > cudev
   cvv
   datasets
   dnn_objdetect
   dpm
   face
   freetype
   fuzzy
   hdf
   hfs
   img_hash
   line_descriptor
   matlab
   optflow
   ovis
   phase_unwrapping
   plot
   reg
   rgbd
   saliency
   sfm
   stereo
   structured_light
   surface_matching
   text
   tracking
   xfeatures2d
   ximgproc
   xobjdetect
   xphoto
CMake Error at cmake/OpenCVModule.cmake:352 (message):
  Duplicated modules NAMES has been found
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:370 (_assert_uniqueness)
  modules/CMakeLists.txt:7 (ocv_glob_modules)

-- Configuring incomplete, errors occurred!
See also "/home/zonghaochen/Thirdparty/opencv-3.4.3/build/CMakeFiles/CMakeOutput.log".
See also "/home/zonghaochen/Thirdparty/opencv-3.4.3/build/CMakeFiles/CMakeError.log".

**Comment by aalarcon96** [comment]
Did you find a solution for this? I am also getting the same error
