### ISSUE TITLE
`RGBD_Odometry_Rgbd.algorithmic` test is failing

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv_contrib#1818]
##### Detailed description
Please refer to [this](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/12201), [this](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/12204), or [that](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/12202) builds for more details.

**Comment by savuor** [comment]
I made some changes in tests recently, please check the test again since this works on latest builds.

**Comment by alalek** [comment]
It is still failed on 3.4 branch.

**Comment by savuor** [comment]
Confirm that, the test fails because the PR #1627 which fixes that wasn't merged into 3.4
The fix is going to be provided by me soon

**Comment by alalek** [comment]
[Nightly builds for master contrib](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-master-contrib) are red on rgbd test.
