### ISSUE TITLE
Duplicate Modules NAMES has been found OpenCV & Contrib latest

### ISSUE THREAD

**Issue by awmiller** [opencv/opencv_contrib#1824]
##### System information (version)

- OpenCV =>Latest from github.com/opencv/opencv
- Operating System / Platform =>  Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Using CMAKE gui, after first configure, I set the OPENCV_EXTRA_MODULES_PATH and check OPENCV_ENABLE_NONFREE. 

Short Error:
CMake Error at cmake/OpenCVModule.cmake:352 (message):
  Duplicated modules NAMES has been found
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:370 (_assert_uniqueness)
  modules/CMakeLists.txt:7 (ocv_glob_modules)

see attached files for details
[CMakeError.log](https://github.com/opencv/opencv_contrib/files/2462538/CMakeError.log)
[CMakeOutput.log](https://github.com/opencv/opencv_contrib/files/2462539/CMakeOutput.log)

##### Steps to reproduce

follow OpenCV CMAKE Gui Tutorial, and Contrib Gui Tutorial in README

**Comment by alalek** [comment]
You must use code from **the same branch name**.

**Comment by awmiller** [comment]
is "master" on each not good enough?

**Comment by harounbest** [comment]
i am facing the same problem any suggestion please

**Comment by chenzhi1992** [comment]
I met the same problem, and I solved it. My opencv version is 3.4 
git clone https://github.com/opencv/opencv_contrib.git
cd opencv_contrib
git checkout 3.4

**Comment by Jose-Trevino** [comment]
> I met the same problem, and I solved it. My opencv version is 3.4
> git clone https://github.com/opencv/opencv_contrib.git
> cd opencv_contrib
> git checkout 3.4

It worked for me, thanks a lot !

**Comment by libichong** [comment]
From the build log, it will report the error:
error C2065: 'off64_t': undeclared identifier

but it will be solved by the same action.  It still works on 2019/9/5.

**Comment by zchrissirhcz** [comment]
> You must use code from **the same branch name**.

It would be more precise to say:
We must use code from **the same tag name**.

**Comment by aaron-asl** [comment]
> I met the same problem, and I solved it. My opencv version is 3.4
> git clone https://github.com/opencv/opencv_contrib.git
> cd opencv_contrib
> git checkout 3.4

Worked for me! Thanks!

**Comment by cayman1021** [comment]
I have the same problem, and I resolved it by this article too.
The problem is:
I've used "git checkout 3.4.x" some version in my opencv folder, but forgotten to "git checkout 3.4.x" the same version to the opencv folder.
That's why when I run cmake in opencv folder, it reports the error like OP posted.

**Comment by MouKanga** [comment]
my mistake here was simply i was selecting the normal opencv folder path instead of the contrib path.
Lazy night eyes mistakes in case someone oversee's it one day as well

**Comment by jk3456a** [comment]
> my mistake here was simply i was selecting the normal opencv folder path instead of the contrib path. Lazy night eyes mistakes in case someone oversee's it one day as well
thanks, i made the same mistake
