### ISSUE TITLE
build opencv_contrib successfully, but haarcascade_mcs_leftear.xml doesn't exsit in opencv lib

### ISSUE THREAD

**Issue by utc1205** [opencv/opencv_contrib#1825]
##### System information (version)

my installation :  
git clone https://github.com/opencv/opencv.git
git checkout 3.4.1
git clone https://github.com/opencv/opencv_contrib.git
git checkout 3.4.1
cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ .. 
make -j8
sudo make install

finally install successfully 

but when i try to load "cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_mcs_leftear.xml')"
haarcascade_mcs_leftear.xml is missing the haarcasca folder, 
and i also try to give a absolute path to haarcascade_mcs_leftear.xml (in opencv_contrib folder),
but the ear detection result is always zeros. 
So i am confused...

**Comment by berak** [comment]
this can be closed, the mcs cascades were removed from the face module.
