### ISSUE TITLE
Missing headers from contrib

### ISSUE THREAD

**Issue by pbertoni** [opencv/opencv_contrib#1827]
##### System information (version)

- OpenCV => commit [295b988](https://github.com/opencv/opencv/commit/295b988657c8f313fc9d3be804b357daa9b85b36)
- Operating System / Platform => Ubuntu 16.04 LTS
- Compiler => gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

##### Detailed description

Successful build with contrib modules, yet some expected headers from `3.4` era are missing in the installation directory.

Are them supposed to remain inside `opencv_contrib/modules` ?

##### Steps to reproduce
```.sh
cmakeArgs="-D CMAKE_BUILD_TYPE=RELEASE \
	-D ENABLE_PRECOMPILED_HEADERS=off \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D WITH_TBB=on \
	-D WITH_GTK=on \
	-D PYTHON_EXECUTABLE=/usr/bin/python3 \
	-D ENABLE_FAST_MATH=1 \
	-D CUDA_FAST_MATH=0 \
	-D WITH_CUBLAS=1 \
	-D INSTALL_PYTHON_EXAMPLES=off \
	-D INSTALL_C_EXAMPLES=off \
	-D OPENCV_EXTRA_MODULES_PATH=/usr/local/opencv_contrib/modules \
	-D BUILD_DOCS=off \
	-D BUILD_EXAMPLES=off"
cmake $cmakeArgs .. && make && sudo make install
# everything fine
find /usr/local/include/opencv4 -name cudaimgproc.hpp
#
# no results
find /usr/local/opencv_contrib/ -name cudaimgproc.hpp
# /usr/local/opencv_contrib/modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
# yet it exists inside cloned contrib repo
```

**Comment by pbertoni** [comment]
I forgot that while formatting this MWE, but grant for sure it was in my cmake, hence problem persists

**Comment by alalek** [comment]
[Build](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_custom_linux64/builds/30/steps/compile%20release/logs/stdio):

> --   Install to:                    /build/precommit-contrib_custom_linux64/install

> -- Installing: /build/precommit-contrib_custom_linux64/install/include/opencv4/opencv2/cudaimgproc.hpp

So something is wrong in your configuration.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
