### ISSUE TITLE
face: MACE filter implementation bug

### ISSUE THREAD

**Issue by alalek** [opencv/opencv_contrib#1848]
[Here](https://github.com/opencv/opencv_contrib/blob/3.4.3/modules/face/src/mace.cpp#L138-L139):
```
Mat sq; cv::sqrt(D, sq);
Mat_<Vec2d> DINV = TOTALPIXEL * size / sq;
```

Comments:
```
// FIXIT What is expected here? complex numbers math?
// D(,)[1] is 0 (always)
Mat sq; cv::sqrt(D, sq);  // Per-element sqrt(): sq(,)[1] is 0 (always)
Mat_<Vec2d> DINV = TOTALPIXEL * size / sq;  // "per-element" division which provides "Inf"
```

Exploded by https://github.com/opencv/opencv/pull/12826 patch.

**Comment by berak** [comment]
thanks a ton for the rescue (again !)

i had another look at the paper:

> D is a MxM diagonal matrix containing the average
power spectrum of all the training images along its
diagonal.

so, indeed only a "real" valued Mat is needed here, not a complex one. 
your fix (and the other objections) are all correct.

i'll try to clean it up a bit later, -- thanks again !
