### ISSUE TITLE
Bug in file line_descriptor/src/binary_descriptor.cpp 

### ISSUE THREAD

**Issue by Varvrar** [opencv/opencv_contrib#1859]
In function BinaryDescriptor::computeImpl
Line 628:

    for ( size_t j = 0; j < sl[i].size(); j++ )
    {
      //if( (int) ( sl[i][j] ).octaveCount > params.numOfOctave_ )
      if( (int) ( sl[i][j] ).octaveCount > octaveIndex )
        ( sl[i] ).erase( ( sl[i] ).begin() + j );
    }

After erasing, the size of the vector sl[i] will change and the last element will not be processed.

**Comment by alalek** [comment]
Nice catch!
Feel free to prepare PR into 3.4 branch (we will merge it into master later).
