### ISSUE TITLE
Cannot detect markers in Android Aruco

### ISSUE THREAD

**Issue by syaifulnizamyahya** [opencv/opencv_contrib#1899]
Im trying to create an Android app that can detect Aruco marker.
This is my code to detect and draw detected marker.  The implementation is based on https://docs.opencv.org/3.4.3/d5/dae/tutorial_aruco_detection.html

```
	@Override
	public Mat onCameraFrame(CameraBridgeViewBase.CvCameraViewFrame inputFrame)
	{
		Dictionary dictionary =  Aruco.getPredefinedDictionary(Aruco.DICT_4X4_50);
		Mat image = inputFrame.gray();
		Mat imageCopy = null;
		image.copyTo(imageCopy);
		Mat ids = new Mat();
		List<Mat> corners = new ArrayList<>();

		Aruco.detectMarkers(image, dictionary, corners, ids);

		if (corners.size()>0)
		{
			Aruco.drawDetectedMarkers(imageCopy, corners);
		}

		return imageCopy;
	}
```

Im not sure if detectMarkers is working. When I try to scan images generated from http://chev.me/arucogen/ with the same dictionary, corners.size() is always 0. drawDetectedMarkers was never triggered.

Thanks.

**Comment by syaifulnizamyahya** [comment]
Got it working. My mistake was I use MarkerID 999 for DICT_4X4_50.

**Comment by vivek-shindhe96** [comment]
hey, the  link that you have given in the question, it doesn't exist anymore. Do  you have any other resource that I can use as reference to build the application? It would be of great help.. thanks.

**Comment by Ricodan** [comment]
Have you managed to detect the marker and return a colour image? I've tried unsuccessfully.

**Comment by vivek-shindhe96** [comment]
If you are using opencv camera its the most easiest thing you can do.. 
generate two mats, 
 Mat colorMat = inputMat.rgba()
 Mat greyMat = inputMat.gray()

Use the gray mat to detect markers.
 Get the corners for the detected markers in the corners object. 
Call the drawDetectedMarkers function on the colorMat object and return the same mat in the function.

 Et Voila.. Btw,  I hope this was what you were looking for.. else let me know.

**Comment by Ricodan** [comment]
> If you are using opencv camera its the most easiest thing you can do..
> generate two mats,
> Mat colorMat = inputMat.rgba()
> Mat greyMat = inputMat.gray()
> 
> Use the gray mat to detect markers.
> Get the corners for the detected markers in the corners object.
> Call the drawDetectedMarkers function on the colorMat object and return the same mat in the function.
> 
> Et Voila.. Btw, I hope this was what you were looking for.. else let me know.

That's exactly what I wanted, I will try it out.

**Comment by Ricodan** [comment]
My problem is that when I try to implement this it crashes. I'm doing this on android and using inputFrame.rgba() and inputFrame.gray().

**Comment by vivek-shindhe96** [comment]
Can you show me your code and the crash log? I have recently done this on
android and I got it to work

**Comment by Ricodan** [comment]
`  public Mat onCameraFrame(CameraBridgeViewBase.CvCameraViewFrame inputFrame) {
        mat4= inputFrame.rgba();
        mat1 = inputFrame.gray();

        //rotate the frame by 90 degrees
//        Core.transpose(mat1, mat2);
//        Imgproc.resize(mat2, mat3, mat3.size(), 0, 0, 0);
//        Core.flip(mat3, mat1, 1);
//
//        Core.transpose(mat4, mat2);
//        Imgproc.resize(mat2, mat3, mat3.size(), 0, 0, 0);
//        Core.flip(mat3, mat4, 1);


        //The actual Aruco stuff happening.
        Dictionary dictionary =  Aruco.getPredefinedDictionary(Aruco.DICT_4X4_50);
        Mat ids = new Mat();
        List<Mat> corners = new ArrayList<>();
        //readCameraParameters(cameraMatrix, distCoeffs);

        Aruco.detectMarkers(mat1, dictionary, corners, ids);

        if (corners.size()>0)
        {
            Aruco.drawDetectedMarkers(mat4, corners, ids);
            //Aruco.estimatePoseSingleMarkers(corners, 0.85, cameraMatrix);
        }

        return mat4;

    }`

And the crash log is as follows:

> 2019-04-11 16:04:13.806 18281-18373/com.example.myarapp E/cv::error(): OpenCV(3.4.4) Error: Assertion failed (_image.getMat().total() != 0 && (_image.getMat().channels() == 1 || _image.getMat().channels() == 3)) in void cv::aruco::drawDetectedMarkers(cv::InputOutputArray, cv::InputArrayOfArrays, cv::InputArray, cv::Scalar), file /build/3_4-contrib_pack-contrib-android/opencv_contrib/modules/aruco/src/aruco.cpp, line 1692
2019-04-11 16:04:13.807 18281-18373/com.example.myarapp E/org.opencv.aruco: aruco::drawDetectedMarkers_11() caught cv::Exception: OpenCV(3.4.4) /build/3_4-contrib_pack-contrib-android/opencv_contrib/modules/aruco/src/aruco.cpp:1692: error: (-215:Assertion failed) _image.getMat().total() != 0 && (_image.getMat().channels() == 1 || _image.getMat().channels() == 3) in function 'void cv::aruco::drawDetectedMarkers(cv::InputOutputArray, cv::InputArrayOfArrays, cv::InputArray, cv::Scalar)'
2019-04-11 16:04:13.808 18281-18373/com.example.myarapp E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.example.myarapp, PID: 18281
    CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.4) /build/3_4-contrib_pack-contrib-android/opencv_contrib/modules/aruco/src/aruco.cpp:1692: error: (-215:Assertion failed) _image.getMat().total() != 0 && (_image.getMat().channels() == 1 || _image.getMat().channels() == 3) in function 'void cv::aruco::drawDetectedMarkers(cv::InputOutputArray, cv::InputArrayOfArrays, cv::InputArray, cv::Scalar)'
    ]
        at org.opencv.aruco.Aruco.drawDetectedMarkers_1(Native Method)
        at org.opencv.aruco.Aruco.drawDetectedMarkers(Aruco.java:631)
        at com.example.myarapp.MainActivity.onCameraFrame(MainActivity.java:109)
        at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:392)
        at org.opencv.android.JavaCameraView$CameraWorker.run(JavaCameraView.java:373)
        at java.lang.Thread.run(Thread.java:764)
The type I'm using for Mat is ` mat1 = new Mat(width, height, CvType.CV_8UC3);` So it is 3 channels, that means that the assertion should not fail since it's either 1 or 3 channels. Perhaps it somehow retars false on ´_image.getMat().total() != 0 ´. Don't know what that would imply in any case.

**Comment by alalek** [comment]
> crash

It should be an exception. Consider using `try...catch`.

> (_image.getMat().channels() == 1 || _image.getMat().channels() == 3)

Looks like condition in implementation is too strong and doesn't expect 4 channel RGBA images.
Workaround is to pass RGB image. Use cvtColor to convert `RGBA->RGB/BGR->drawMarkers->RGBA`.

**Comment by Ricodan** [comment]
I don't know how I would implement ´try...catch´ when that code belongs to the library and I don't have access to it. However, I used cvtColor and it worked!! Thank you!

**Comment by nayan826** [comment]
Hi i am new to OpenCV and  trying to to detect aruco marker from https://chev.me/arucogen/ 

but corner.size() always returns 0

This is the code
```
 public Mat onCameraFrame(CameraBridgeViewBase.CvCameraViewFrame inputFrame) {
        Mat rgba = inputFrame.rgba();
        Mat gray = new Mat();
        Imgproc.cvtColor(rgba, gray, Imgproc.COLOR_RGBA2GRAY);
        Dictionary dictionary =  Aruco.getPredefinedDictionary(Aruco.DICT_4X4_50);
        Mat ids = new Mat();
        List<Mat> corners = new ArrayList<>();
        Aruco.detectMarkers(gray, dictionary, corners, ids);

        if (corners.size()>0)
        {
            Aruco.drawDetectedMarkers(gray, corners);
            //Aruco.estimatePoseSingleMarkers(corners, 0.85, cameraMatrix);
        }

        return rgba;
    }
```
