### ISSUE TITLE
python: ppf_match_3d_PPF3DDetector cannot train model

### ISSUE THREAD

**Issue by ljc19800331** [opencv/opencv_contrib#1902]
System: 
- OpenCV = 4.00 pre
- Operating System / Platform => Linux ubuntu 16.04
- Compiler =>Python3

Description:
Hello, I tried to use python package of surface matching with python opencv_contrib package. When I use the surface matching method, it shows the error as "'cv2.ppf_match_3d_PPF3DDetector' object has no attribute 'trainModel'". Thanks.

Code:
import cv2 as cv
import numpy as np
import open3d
modelp = cv.ppf_match_3d.loadPLYSimple('test_1.ply',0)
detector = cv.ppf_match_3d_PPF3DDetector(0.025, 0.05)
detector.trainModel(modelp)

**Comment by berak** [comment]
@ljc19800331 , indeed, the trainModel() or match() functions are not exposed to the python api.

from python, instead of the loadModel() -> trainModel() -> loadModel() -> match() approach, 
you should use the more compact [ICP approach here](https://github.com/opencv/opencv_contrib/blob/master/modules/surface_matching/samples/ppf_icp.py)

**Comment by Microset** [comment]
The same problem. I tried to use python  of surface matching on opencv_contrib and got a message for traininig mode:
Error: 'cv2.ppf_match_3d_PPF3DDetector' object has no attribute 'trainModel'
and for matching scene and model:
Error: 'cv2.ppf_match_3d_PPF3DDetector' object has no attribute 'match'
But another surface matching commands cv2.ppf_match_3d_PPF3DDetector(), cv2.ppf_match_3d.loadPLYSimple(), icp.registerModelToScene() and etc. everything well.

System:
OpenCV = 4.0.0
Operating System  = Ubuntu 16.04
Compiler = Python 3.5.2

Description code:
import cv2 as cv
detector = cv.ppf_match_3d_PPF3DDetector(0.025, 0.05)
PC = cv.ppf_match_3d.loadPLYSimple("1.ply", 0)
detector.trainModel(PC)
PCT = cv.ppf_match_3d.loadPLYSimple("2.ply", 0)1
results = detector.match(PCT, 1.0/40.0, 0.05)

We'll grateful for any help!
