### ISSUE TITLE
尝试测试追踪模块,但是feature.hpp报错

### ISSUE THREAD

**Issue by Dorismz** [opencv/opencv_contrib#1907]
报错提示: 
opencv_contrib/modules/tracking/include/opencv2/tracking/feature.hpp:149:41: error: expected ‘;’ at end of member declaration
   virtual void write( FileStorage &fs ) const CV_OVERRIDE;
                                         ^
compilation terminated due to -Wfatal-errors.

测试代码:
#include "opencv2/opencv.hpp"
#include "opencv2/tracking/tracking.hpp"
#include "opencv2/tracking/tracker.hpp"
 #include "opencv2/highgui.hpp"
 #include "opencv2/video.hpp"
 #include "opencv2/core/utility.hpp"
#include <vector>
 using namespace cv;
 using namespace std; 
int main() {
 Mat frame; VideoCapture cap("1.mp4");//输入待处理的视频 
cap >> frame; 
vector<Rect> rois; 
cv::selectROIs("rois", frame, rois, false);
 if (rois.size()<1)
 return 0; 
MultiTracker trackers; 
vector<Rect2d> obj; 
vector<Ptr<Tracker>> algorithms;
//Ptr<TrackerMIL> tracker= TrackerMIL::create()
 for (auto i = 0; i < rois.size(); i++) {
 
obj.push_back(rois[i]); 
Ptr<TrackerKCF> tracker = TrackerKCF::create();
algorithms.push_back(tracker);
 }
 trackers.add(algorithms, frame, obj); 

while (cap.read(frame)) {

 bool ok = trackers.update(frame);
 if (ok) { 

for (auto j = 0; j < trackers.getObjects().size(); j++) {

 rectangle(frame, trackers.getObjects()[j], Scalar(255, 0, 0), 2, 1);
 }
 imshow("tracker", frame);
 } 
if (waitKey(1) == 27)
break;
} 
return 0;
 }

**Comment by hello-ljs** [comment]
将opencv-contrib/modules/中的相关hpp文件移动到/usr/local/include下即可
