### ISSUE TITLE
Opencv framework for iOS does not work

### ISSUE THREAD

**Issue by VladIacobIonut** [opencv/opencv_contrib#1908]
Hello, 

I am trying to generate an opencv2.framework to use in an iOS project, which contains the nonfree libs as well. The steps I am following are:

- clone both the source from the opencv repository and the opencv_contrib
- go into opencv-master/platforms/ios/ and I run the build_framework.py and set the flag --contrib to the path of the source of opencv_contrib

Everything works fine and after a good 30 min wait I get my framework. I import it in the app and surely I can import nonfree.hpp with no problem. 
However when I try to use the sift detector as follows : 

```
 cv::Ptr<xfeatures2d::SiftFeatureDetector> detector = xfeatures2d::SiftFeatureDetector::create();
detector -> detect(image, keypoints) 
```

my app crashes and I get : 

`-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'`

I searched about this crash and found out that I have to set DOPENCV_ENABLE_NONFREE to ON when I cmake. But I can't see how this might help me as the generated build from cmake does not contain any build_framework.py to generate a framework.

Any idea on this ?
Thank you very much!

**Comment by asura1234** [comment]
I'm having the same problem. I'm trying to use SIFT too.

**Comment by VladIacobIonut** [comment]
@asura1234 as I remember, eventually I ended up using another algorithm as some algorithms including SIFT have been removed from the standard library and are only available on payment. But this is only how I remember it
