### ISSUE TITLE
cannot find contrib module using android studio

### ISSUE THREAD

**Issue by arsalanjk** [opencv/opencv_contrib#1926]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
Contrib modules are built well: http://pullrequest.opencv.org/buildbot/builders/3_4-contrib_pack-contrib-android
Packages with contrib code are not distributed with OpenCV releases by OpenCV team.
