### ISSUE TITLE
opencv2.4.11 installation issue

### ISSUE THREAD

**Issue by dalongmaoxiaotushu** [opencv/opencv_contrib#1951]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

I want to install opencv 2.4.11 on ubuntu18.04 Inorder to install yolov3. cmake is success,but make cannot pass . the error information is 1985,Icouldnot find answer on google and baidu,please help me.

the generic information about error is:

modules/highgui/CMakeFiles/opencv_highgui.dir/build.make:254: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o' failed
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o] Error 1
CMakeFiles/Makefile2:1985: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alalek** [comment]
There is no DNN module before OpenCV 3.2.
To run yolov3 you need OpenCV 3.4.x at least.
