### ISSUE TITLE
error: ‘FILTER_SCHARR’ was not declared in this scope

### ISSUE THREAD

**Issue by Mregussek** [opencv/opencv_contrib#1966]
- OpenCV => 4.0.0
- Operating System  => Ubuntu 64bit
- Compiler => gcc 7.3.0

```
opencv_contrib-4.0.0/modules/cvv/src/qtutil/filter/sobelfilterwidget.cpp:265:15: error: ‘FILTER_SCHARR’ was not declared in this scope
  if (ksize == FILTER_SCHARR)
```

Solution is to add 'cv::' before every FILTER_SHARR in 
opencv_contrib-4.0.0/modules/cvv/src/qtutil/filter/sobelfilterwidget.cpp
With this change (cv::FILTER_SHARR) it compiles correctly.

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.
