### ISSUE TITLE
Mismatch between code and documentation in anisotropicDifussion funciton

### ISSUE THREAD

**Issue by mechatron1991** [opencv/opencv_contrib#1970]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Debian on Windows 10(WSL)
- Compiler => python3 interpreter

##### Detailed description

Hi, 

There appears to be mismatch between the official documentation [here](https://docs.opencv.org/4.0.1/df/d2d/group__ximgproc.html#gaffedd976e0a8efb5938107acab185ec2) and the anisotropicDiffusion function defined [here](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/anisodiff.cpp). The document mentions that source image should be grayscale but the assert statement in line 251 checks if the source image has 3 channels. 

##### Steps to reproduce
import cv2
image = cv2.imread('image.png')
grayscale = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
filtered_image = cv2.ximgprox.anisotropicDiffusion(grascale, 0.25, 10, 1000)

I get the following error:
cv2.error: OpenCV(4.0.0) /io/opencv_contrib/modules/ximgproc/src/anisodiff.cpp:251: error: (-215:Assertion failed) src_.dims() == 2 && type == CV_8UC3 in function 'anisotropicDiffusion'

**Comment by mechatron1991** [comment]
It should be doable from my understanding. I have asked @alalek [here](https://github.com/opencv/opencv_contrib/pull/1974#discussion_r251428630) and he hasn't responded so far.

**Comment by alalek** [comment]
I had already marked this as documentation issue 7 days ago.

**Comment by crackwitz** [comment]
I skimmed this because it came up as a question on IRC. I have no interest either way in this algorithm and code, so you know where I'm coming from.

The code has the beginnings of multi-channel, but the inner loops are hard-coded for three channels (with obvious patterns). To me it looks definitely doable to take this code, copy it, and strip the copy down to single-channel. What I don't know is the preferred way to lay this out in source. Without any guidance, I'd just make it two static functions to do the work (1ch and 3ch) and run assertions and dispatch in the public function.

**Comment by vijaysinghkadam** [comment]
@alalek .  Should I work on this code changes . I have never contributed before to opencv-contrib but it does seems doable.

**Comment by utkarshg6** [comment]
According to me in this issue, we have to make changes in the documentation where it says that the function inputs a grayscale image instead it should be an image of three channels. Am I saying correctly?

**Comment by LaurentBerger** [comment]
I think that : first(pull request 1) documentation must be changed and later (pull reaquest 2) code could be changed and then doucumentation updated with new functionality

**Comment by utkarshg6** [comment]
I am new to open source, can you tell me which files to look in to for making changes in the documentation?

**Comment by crackwitz** [comment]
look at https://github.com/opencv/opencv_contrib/blob/75fcfa609316456a83d0c5878b65e81dcf3a0fcd/modules/ximgproc/include/opencv2/ximgproc.hpp#L173-L193

**Comment by utkarshg6** [comment]
@kyscg Your changes were the same as my previous PR. I would recommend creating a new PR if there are other changes.
