### ISSUE TITLE
can't read 711 of DICT_6X6_1000

### ISSUE THREAD

**Issue by masahiro-kato** [opencv/opencv_contrib#1975]
##### System information (version)
- OpenCV => 4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
Hi
I'm trying DICT_6X6_1000,
but 711 can't read.

##### Steps to reproduce

DICT_6X6_1000
ID:711

**Comment by LaurentBerger** [comment]
No problem with this code : 
```
        Ptr<aruco::Dictionary> dct=cv::aruco::Dictionary::get(aruco::DICT_6X6_1000);
        Mat mm;
        dct->drawMarker(711, 50, mm);

```
Opencv 4.0.1-dev vs2017
