### ISSUE TITLE
Feature Request: BRISQUE NR-IQA Implementation

### ISSUE THREAD

**Issue by krshrimali** [opencv/opencv_contrib#1983]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Ubuntu 18.04

##### Detailed description

I propose a new feature of an NR-IQA method, BRISQUE for OpenCV.  I have the C++ and Python implementation of BRISQUE. May I create a PR on adding this feature?

Blog Link: https://www.learnopencv.com/image-quality-assessment-brisque/

**Comment by clunietp** [comment]
I would love to see this as part of the IQA module here:
https://github.com/opencv/opencv_contrib/pull/1959

Also see this fork
https://github.com/FlyingRhenquest/No-Reference-Image-Quality-Assessment-using-BRISQUE-Model

How can I help?

**Comment by clunietp** [comment]
@krshrimali Sounds great!  Please ping me if I can be of assistance 👍

**Comment by clunietp** [comment]
@krshrimali I had to rebranch and create a new PR, please see https://github.com/opencv/opencv_contrib/pull/1990

**Comment by krshrimali** [comment]
@clunietp - Thanks! I'll check that out.

There are some licensing problems with the trained model, I think. I'll have to train it again and then only can use for BRISQUE. 

Meanwhile, I'm converting my code for OpenCV compatibility and trying to follow the pattern you did, for similarity. If possible, please get in touch at: kushashwaravishrimali@gmail.com for some discussion. Thanks!

**Comment by krshrimali** [comment]
@alalek - I'm planning to contribute BRISQUE NR-IQA to Quality Module. But since the model loading requires LIBSVM (and it can't be loaded using OpenCV-SVM Implementation), do you think it would be fine to add this requirement for using BRISQUE? Or if you have any other solution, thanks!

**Comment by krshrimali** [comment]
This has been merged! Thanks.
