### ISSUE TITLE
wrong ouput of of net.forward() build-from-source

### ISSUE THREAD

**Issue by lunasdejavu** [opencv/opencv_contrib#1995]
##### Detailed description
My environment is windows 7 x64 tensorflow 1.12 GPU:GTX1060 visual studio 2015 and the dataset has only 1 class. I trained a faster_rcnn_inception_v2_coco model by tensorflow-object detection api, then I did the inference by the C++ code like:
```
const size_t inWidth = 1024;
const size_t inHeight = 1024;
//const float WHRatio = inWidth / (float)inHeight;
const char* classNames[] = { "rainbow" };
const float WHRatio = inWidth / (float)inHeight;
int main()
{
	String weights = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\frozen_inference_graph.pb";
	String prototxt = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\graph.pbtxt";
	dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);
	Mat frame = cv::imread("C:\\hsir\\build\\bin\\test\\test-c1-1.bmp");
	Size frame_size = frame.size();
	cv::Mat blob = cv::dnn::blobFromImage(frame, 1, Size(inWidth, inHeight), false, true);/
	net.setInput(blob);
	Mat output = net.forward();
	Mat detectionMat(output.size[2], output.size[3], CV_32F, output.ptr<float>());
	float confidenceThreshold = 0.5;
	for (int i = 0; i < detectionMat.rows; i++)
	{
		float confidence = detectionMat.at<float>(i, 2);
		printf("%f\n", detectionMat.at<float>(i, 2));
		printf("%d\n", i);
		if (confidence > confidenceThreshold)
		{	
			size_t objectClass = (size_t)(detectionMat.at<float>(i, 1));
			int xLeftBottom = static_cast<int>(detectionMat.at<float>(i, 3) * frame.cols);
			int yLeftBottom = static_cast<int>(detectionMat.at<float>(i, 4) * frame.rows);
			int xRightTop = static_cast<int>(detectionMat.at<float>(i, 5) * frame.cols);
			int yRightTop = static_cast<int>(detectionMat.at<float>(i, 6) * frame.rows);

			ostringstream ss;
			ss << confidence;
			String conf(ss.str());

			Rect object((int)xLeftBottom, (int)yLeftBottom,
				(int)(xRightTop - xLeftBottom),
				(int)(yRightTop - yLeftBottom));

			rectangle(frame, object, Scalar(0, 255, 0), 2);
			String label = String(classNames[objectClass]) + ": " + conf;
			int baseLine = 0;
			Size labelSize = getTextSize(label, FONT_HERSHEY_SIMPLEX, 0.5, 1, &baseLine);
			rectangle(frame, Rect(Point(xLeftBottom, yLeftBottom - labelSize.height),
				Size(labelSize.width, labelSize.height + baseLine)),
				Scalar(0, 255, 0), cv::FILLED);
			putText(frame, label, Point(xLeftBottom, yLeftBottom),
				FONT_HERSHEY_SIMPLEX, 0.5, Scalar(0, 0, 0));
		}
	}
	namedWindow("image", cv::WINDOW_NORMAL);
	imshow("image", frame);
	waitKey(0);
	return 0;
}
```
the graph.pbtxt is[ here](https://drive.google.com/file/d/1drLcaGiPh2qx5jbC85ID_FOrQiS0fwS2/view?usp=sharing)
frozen_inference_graph.pb is [here](https://drive.google.com/file/d/1YO4B0x7eEAx2X93f2ljHjSmFDHwMAXSF/view?usp=sharing)
image is [here](https://drive.google.com/file/d/11SQ3tH3cL8u9QizVkUnTDCwgAfoeaEd_/view?usp=sharing)

	
the outputs of net.forward() are different by opencv4.0.0 win-pack and build-from-source  edit
dnn
objectdetection
4.0.0
opencv
asked 24 hours ago

lunasdejavu gravatar image
lunasdejavu 
1 ●1
updated 3 hours ago

My environment is windows 7 x64 tensorflow 1.12 GPU:GTX1060 visual studio 2015 and the dataset has only 1 class. I trained a faster_rcnn_inception_v2_coco model by tensorflow-object detection api, then I did the inference by the C++ code like:

string weights = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\frozen_inference_graph.pb";
string prototxt = "C:\\tf_od_api\\models\\faster_rcnn_inception_v2_coco\\pb\\graph.pbtxt";
cv::dnn::Net net = cv::dnn::readNetFromTensorflow(weights, prototxt);
cv::Mat frame = cv::imread("C:\\hsir\\build\\bin\\test\\test-c1-1.bmp");
cv::Mat blob = cv::dnn::blobFromImage(frame, 1, cv::Size(inWidth, inHeight), false, true);
net.setInput(blob);
cv::Mat outPut = net.forward();
cv::Mat detectionMat = cv::Mat(outPut.size[2], outPut.size[3], CV_32F, outPut.ptr<float>());
it works fine by my code with opencv 4.0.0 and 4.0.1 installed by win-pack, but I tried to put it in a project of my team which seems to use customized opencv from 4.0.0 which was build from source, then the detectionMat is totally wrong. I traced the bug and just copied the same code into a function of the project, but the result was still wrong. There was no error or warning shows up and nothing wrong with reading the model, image and forward(); The correct result should be only one object detected with confidence 1.0 and the others with confidence 0.0. The wrong result has 100 objects detected with 0.5~0.99 confidences but none of them close to the real object.
cv::Mat frame = cv::imread("C:\hsir\build\bin\test\test-c1-1.bmp");
cv::Mat blob = cv::dnn::blobFromImage(frame, 1, cv::Size(inWidth, inHeight), false, true);
net.setInput(blob);
cv::Mat outPut = net.forward();
cv::Mat detectionMat = cv::Mat(outPut.size[2], outPut.size[3], CV_32F, outPut.ptr());

it works fine by my code with opencv 4.0.0 and 4.0.1 installed by win-pack, but I tried to put it in a project of my team which seems to use customized opencv  4.0.0() which was build from source with openmp and opencv_contrib, then the detectionMat is totally wrong. I traced the bug and just copied the same code into a function of the project, but the result was still wrong. There was no error or warning shows up and nothing wrong with reading the model, image and forward(); The correct result should be only one object detected with confidence 1.0 and the others with confidence 0.0. The wrong result has 100 objects detected with 0.5~0.99 confidences but none of them close to the real object.
So is it possible to use the library properly without rebuilding it?
or how to build it with opencv_contrib but without dnn module?

**Comment by alalek** [comment]
No need to duplicate issues.
