### ISSUE TITLE
 add_subdirectory given source "correspondence" which is not an existing directory

### ISSUE THREAD

**Issue by lunasdejavu** [opencv/opencv_contrib#1996]
##### System information (version)

- OpenCV => 4.0.0
- Operating System / Platform => Windows7 64 Bit
- Compiler => Visual Studio 14 2015 x64
-Cmake =>3.13.3

##### Detailed description
I tried to build the opencv 4.0.0 with opencv_contrib (4.0.0) by cmake-gui
then there is an error happened after pushing configure  button and choosing openmp and filling the path of opencv_contrib folder,

then the errors showed up:

> CMake Error at D:/opencv_contrib-4.0.0/modules/sfm/CMakeLists.txt:1 (add_subdirectory):
>   add_subdirectory given source "correspondence" which is not an existing
>   directory.
> 
> 
> CMake Error at D:/opencv_contrib-4.0.0/modules/sfm/CMakeLists.txt:2 (add_subdirectory):
>   add_subdirectory given source "multiview" which is not an existing
>   directory.
> 
> 
> CMake Error at D:/opencv_contrib-4.0.0/modules/sfm/CMakeLists.txt:3 (add_subdirectory):
>   add_subdirectory given source "numeric" which is not an existing directory.
> 
> 
> CMake Error at D:/opencv_contrib-4.0.0/modules/xobjdetect/CMakeLists.txt:1 (add_subdirectory):
>   add_subdirectory given source "waldboost_detector" which is not an existing
>   directory.

I found some  similar issues #1353 
so I added `set(OPENCV_MODULE_IS_PART_OF_WORLD FALSE)`
but the same error kept showing up.

**Comment by lunasdejavu** [comment]
[CMakelists.txt](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/CMakeLists.txt) of sfm from the master is quite different from [4.0.0]:
```
add_subdirectory(correspondence)
add_subdirectory(multiview)
add_subdirectory(numeric)

if ( Ceres_FOUND )
    add_subdirectory(simple_pipeline)
endif ()
```

**Comment by alalek** [comment]
There is [code from 4.0.0](https://github.com/opencv/opencv_contrib/blob/4.0.0/modules/sfm/CMakeLists.txt). Mentioned lines are missing
Check used version.

**Comment by lunasdejavu** [comment]
> There is [code from 4.0.0](https://github.com/opencv/opencv_contrib/blob/4.0.0/modules/sfm/CMakeLists.txt). Mentioned lines are missing
> Check used version.
I downloaded from [here](https://github.com/opencv/opencv_contrib/archive/4.0.0.zip).it is the zipped file.

**Comment by lunasdejavu** [comment]
Btw if I remove dnn_objdetect folder, then it won't be included ,right?
