### ISSUE TITLE
module reg - compilation problem(s)

### ISSUE THREAD

**Issue by LoucIsZbib** [opencv/opencv_contrib#20]
Hello,

First I'd like to thank all of you, developers who shares freely your work to anyone, go on !

I want to compile and use the reg module. I try on windows 7 + MSYS + MinGW with opencv 2.4.8 and on linux/debian with opencv 2.4.9, same issues : 
After some issues with some headers include ( opencv2/core.hpp => opencv2/core/core.hpp ) than I can handle, I got a fatal error during compilation : 

/home/luc/projets/opencv/opencv-2.4.9/modules/contrib/modules/reg/src/mapperpyramid.cpp:93:25: error: ‘class cv::Ptrcv::reg::Map’ has no member named ‘get’

I don't know how to solve this problem. I don't know if I'm doing something wrong or if it is a bug in reg module.

Has anyone an idea to help me ? Thank you in advance ! 

Luc

**Comment by Ali-E** [comment]
Hi, 
I have the same problem. can you explain how did you solve this problem?

**Comment by LoucIsZbib** [comment]
Hi Ali-E,
I solved my problem by downloading the openCV source code from GITHUB, branch master. It is the 3.x version, still in development.
It seems that the cv::Ptr class is not defined in the openCV 2.4.9 you can download from opencv.org

**Comment by Ali-E** [comment]
Thank you, you're right. I installed version 3 and every thing is OK now.
