### ISSUE TITLE
contributor in opencv_contrib

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#2008]
hi,
I know it's a detail but all history and contributors are vanished. 
If my memory is good  I worked on [this sample](https://github.com/opencv/opencv_contrib/blob/master/modules/viz/samples/histo3D.cpp#L150-L156)

I think reason is [here](http://answers.opencv.org/question/202659/move-opencv-module-in-opencv_contrib/) and commits are still in [opencv ](https://github.com/opencv/opencv/commit/421c5dee12e124282300b1eef5ac3b55e386d34e)

https://stackoverflow.com/questions/41811986/git-move-directory-to-another-repository-while-keeping-the-history

**Comment by alalek** [comment]
Commit states that this code has been moved. Due git limitations history are not moved.
Original code is still here with history, you can check "3.4" branch of "opencv" repository:

> https://github.com/opencv/opencv_contrib/blob/master/modules/viz/samples/histo3D.cpp#L150-L156
> https://github.com/opencv/opencv/blame/3.4.4/samples/cpp/tutorial_code/viz/histo3D.cpp#L150-L156
