### ISSUE TITLE
FreeType::putText write to 4 channels Mat (BGRA)

### ISSUE THREAD

**Issue by xamix** [opencv/opencv_contrib#2009]
Hello,

I need some feedback about an Assert used in freetype module of OpenCv:

##### System information (version)
- OpenCV => 3.4.5-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
I have a Mat which is created with BGRA data layout -> CV_8UC(4).
I need to write some special text on it and so I cannot use **cv::putText**.
So I used the function **FreeType2::putText**

However the Assert at line 196 in **freetype.cpp** is triggering because my image has 4 channels 
but the code seem to handle only 3 channels:
https://github.com/opencv/opencv_contrib/blob/3.4/modules/freetype/src/freetype.cpp#L196

I tested to remove the test to check number of channels and all seem good as far as I know (text seem to be drawn correctly):

```.cpp
CV_Assert( ( _img.empty()    == false ) &&
               ( _img.isMat()    == true  ) &&
               ( _img.depth()    == CV_8U ) &&
               ( _img.dims()     == 2     ) /*&&
               ( _img.channels() == 3     )*/ );
```

So my question is:
Is there any reason to limit **FreeType2::putText** function only to RGB image i.e channels = 3 but not channels = 4?, For example the **cv::putText** function works on both RGB and RGBA image.

Regards

**Comment by kalrey** [comment]
em~~ 
I am faced with the same problem. This solution is still work good？did you find any better way to work?

**Comment by kalrey** [comment]
@xamix

**Comment by xamix** [comment]
I have not found another solution to this.
It seem to work as far as I know.

But since I was using this to get fixed size character set, I decided to generate a raster image and skip using FreeType contrib for the moment, I'm still waiting answer for the question....

**Comment by alalek** [comment]
Relaxing check is not enough, need to extend implementation too (search for code with Vec3b):
- [Vec3b access pattern](https://github.com/opencv/opencv_contrib/blob/6d16876ee2b25519618e74346eabff154b5fcbdc/modules/freetype/src/freetype.cpp#L351-L354)

Also there are bad news - no tests for this module.

**Comment by kalrey** [comment]
I have viewed the code about putTextBitmapMono.I think it’s not necessary to extend implementation of 4 channels.
In fact, 'putTextBitmapMono' just draw the text to a bitmap and then copy it to dst mat. The copying operation is a assignment of B,G,R channel one by one.
