### ISSUE TITLE
Unable to install opencv_contrib on Linux Subsystems Ubuntu 18.04

### ISSUE THREAD

**Issue by RiaanZoetmulder** [opencv/opencv_contrib#2012]
Hello,

I have been trying to compile the opencv_contrib modules because i need the SURF algorithm from xfeatures2d. I have succesfully compiled opencv several times, using anaconda as an environment. However, the installation does not seem to detect the opencv_contrib modules that I have linked to.

My opencv  and opencv_contrib are in the same folder called 'installation', which resides in home/rzoetmulder/ . I have made sure that I have the same version for opencv and opencv_contrib by trying it out with 2 different versions: 3.2.0 and 3.4.2

The commands I have run are, from opencv/build.

I run cmake several times with the following commands:
`cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=~/anaconda3/envs/nipype \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=ON \
-D WITH_TBB=ON \
-D WITH_V4L=ON \
-D OPENCV_ENABLE_NONFREE=ON \
-D BUILD_opencv_xfeatures2d=ON\
-D PYTHON_EXECUTABLE=~/anaconda3/envs/nipype/bin/python \
-D OPENCV_EXTRA_MODULES_PATH= ~/installation/opencv_contrib/modules \
-D BUILD_EXAMPLES=ON .. `

`cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=~/anaconda3/envs/nipype \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=ON \
-D WITH_TBB=ON \
-D WITH_V4L=ON \
-D OPENCV_ENABLE_NONFREE=ON \
-D BUILD_opencv_xfeatures2d=ON\
-D PYTHON_EXECUTABLE=~/anaconda3/envs/nipype/bin/python \
-D OPENCV_EXTRA_MODULES_PATH= ~/installation/opencv_contrib/modules \
-D BUILD_EXAMPLES=ON ..`

`cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local\
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=ON \
-D WITH_TBB=ON \
-D WITH_V4L=ON \
-D OPENCV_ENABLE_NONFREE=ON \
-D BUILD_opencv_xfeatures2d=ON\
-D PYTHON_EXECUTABLE=~/anaconda3/envs/nipype/bin/python \
-D OPENCV_EXTRA_MODULES_PATH= ~/installation/opencv_contrib/modules \
-D BUILD_EXAMPLES=ON ..`

Every time I get the following list of to be built modules: core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d stitching videostab

I have also completed the installation several times, (so a full build + install). No success with opencv_contrib modules.

They never contain any of the opencv_contrib modules. What might be going on here?

##### System information (version)

- OpenCV => 3.2.0 and 3.4.2
- Operating System / Platform => Windows 10, with linux subsystems Ubuntu 18.04

**Comment by berak** [comment]
```
-D OPENCV_EXTRA_MODULES_PATH= ~/installation/opencv_contrib/modules \

-----------------------------^  erroneous space here !
```
