### ISSUE TITLE
Some things about colorMatchTemplate

### ISSUE THREAD

**Issue by liuxingbaoyu** [opencv/opencv_contrib#2014]
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

colorMatchTemplate is a very convenient and useful module.
I like it very much.
But I have encountered some problems when I use it.

The length and width of pic3 will be exactly the same as pic, and this happens.
![snipaste_2019-02-27_03-00-53](https://user-images.githubusercontent.com/30521560/53441623-2b497e00-3a42-11e9-87e1-064bdb03bc89.png)
There are some points below and to the right that mean very high similarity.

And request support for the mask, that would be an extremely good thing.

I am sorry for my bad English, thank you for your help.
@LaurentBerger 

##### Steps to reproduce

```
Mat pic,pic2,pic3;
//pic = a picture;
//pic2 = a picture;
ximgproc::colorMatchTemplate(pic, pic2, pic3);
normalize(pic3, pic3, 1, 0, NORM_MINMAX);
pic3.convertTo(pic4, CV_8U, 255);
imshow("result", pic3);
```

**Comment by Pk13055** [comment]
There are two lines in the code (`quaternion.cpp`) 
```.cpp
int rr = max(getOptimalDFTSize(image.rows), getOptimalDFTSize(colorTemplate.rows));
int cc = max(getOptimalDFTSize(image.cols), getOptimalDFTSize(colorTemplate.cols));
```
Have you checked whether your template has a size greater than the input image?  From the documentation of `getOptimalDFTSize`, it is evident that the image preferred size (due to the way DFT works) is usually of the form `2^p * 3^q * 5^r`  for some integer p, q, r.
- Is your image of said form?
- You could _potentially_ see some performance improvement if your image dimensions are already a power of 2.

**Comment by LaurentBerger** [comment]
@Pk13055 thanks for help 
@liuxingbaoyu can you post orignal image pic1  and pic2 ?

**Comment by Pk13055** [comment]
@LaurentBerger Can you check whether having an image with `template.shape > inputImg.shape` leads to a difference in size? I think even before that, just testing whether `inputImg` not having a shape of the given format should lead to a differently sized `outputImg`.

**Comment by liuxingbaoyu** [comment]
> There are two lines in the code (`quaternion.cpp`)
> 
> ```c++
> int rr = max(getOptimalDFTSize(image.rows), getOptimalDFTSize(colorTemplate.rows));
> int cc = max(getOptimalDFTSize(image.cols), getOptimalDFTSize(colorTemplate.cols));
> ```
> 
> Have you checked whether your template has a size greater than the input image? From the documentation of `getOptimalDFTSize`, it is evident that the image preferred size (due to the way DFT works) is usually of the form `2^p * 3^q * 5^r` for some integer p, q, r.
> 
> * Is your image of said form?
> * You could _potentially_ see some performance improvement if your image dimensions are already a power of 2.



> @Pk13055 thanks for help
> @liuxingbaoyu can you post orignal image pic1 and pic2 ?

Oh! I am a stupid, I am sorry! Thanks for the help of both!
