### ISSUE TITLE
license problem in descriptor.hpp

### ISSUE THREAD

**Issue by fcyella** [opencv/opencv_contrib#2016]
- OpenCV => 4.0.1
- Operating System / Platform => Linux, 
- Compiler => gcc

In modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp, a section between lines 625 and 824 that starts with "Compare doubles by relative error" That appears to come from here: http://www.ipol.im/pub/art/2012/gjmr-lsd/,  which has the GNU Afero General Public License.
Seems it's not compatible with opencv_contrib's 3-clause BSD License, Will this be a problem?

**Comment by vpisarev** [comment]
@fcyella, thank you! Yes, this is definitely a problem. We will patches to remove this code from the master and 3.4 branches shortly.

**Comment by chinhdd** [comment]
I am going to release my company commercial production which is using LineSegmentDetector in OpenCV 3.4.3. Will this be a problem if we will not open our source code?
Thank you!

**Comment by alalek** [comment]
You should contact with your lawyer.
Don't expect legal-related answers on Internet.

**Comment by LaurentBerger** [comment]
@alalek There is no license on this code. Original code is [here ](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/)and about license it's [here](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/#comment-1203)

**Comment by JLLeitschuh** [comment]
Is there a license-compatible version of this logic that will be made available?

**Comment by AlexDaniel** [comment]
Seriously. I just stumbled upon this. Can't we ask them to relicense that particular piece of code? I just spent an hour trying to work around this issue just to keep my code working.

**Comment by randomascii** [comment]
I just saw this issue. I apologize for the problematic license on the blog post. I've updated it. I also put a copy of the code with an embedded license in github: https://github.com/randomascii/blogstuff/blob/main/FloatingPoint/CompareAsInt/CompareAsInt.cpp

**Comment by sturkmen72** [comment]
i am happy to annonce that after i send an e-mail to @rafael-grompone-von-gioi he kindly published his [Computation of a NFA related to a binomial distribution code](https://github.com/rafael-grompone-von-gioi/binomial_nfa) with MIT licence. He also states he will be happy to help on restoration of LDS Algorithm in OpenCV.

thank you @rafael-grompone-von-gioi for your great work.
