### ISSUE TITLE
Problems Generating Cmake Configuration CL_VERSION_2_0 Doesn't Exist

### ISSUE THREAD

**Issue by amrosado** [opencv/opencv_contrib#2044]
##### System information (version)

- OpenCV => 4.x
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 2017

##### Detailed description

I'm unable to generate an appropriate configuration with Cmake when attempting to generate a configuration with CUDA.  When I include opencv_contrib github clone in my cmake configuration I get the following Cmakeerror:

Determining if the CL_VERSION_2_0 exist failed with the following output:
Change Dir: C:/lib/opencv/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_e7517.vcxproj" "/p:Configuration=Debug" "/p:Platform=x64" "/p:VisualStudioVersion=15.0"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/15/2019 9:25:12 PM.

Project "C:\lib\opencv\CMakeFiles\CMakeTmp\cmTC_e7517.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_e7517.dir\Debug\".

  Creating directory "C:\lib\opencv\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_e7517.dir\Debug\cmTC_e7517.tlog\".

InitializeBuildStatus:

  Creating "cmTC_e7517.dir\Debug\cmTC_e7517.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" /Zi /W3 /WX- /diagnostics:classic /MP12 /Od /Ob0 /Oi /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /Gy /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e7517.dir\Debug\\" /Fd"cmTC_e7517.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue  /bigobj C:\lib\opencv\CMakeFiles\CMakeTmp\CheckSymbolExists.c

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" /Zi /W3 /WX- /diagnostics:classic /MP12 /Od /Ob0 /Oi /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /Gy /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e7517.dir\Debug\\" /Fd"cmTC_e7517.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue  /bigobj C:\lib\opencv\CMakeFiles\CMakeTmp\CheckSymbolExists.c

  CheckSymbolExists.c

  

C:\lib\opencv\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: 'CL_VERSION_2_0': undeclared identifier [C:\lib\opencv\CMakeFiles\CMakeTmp\cmTC_e7517.vcxproj]

Done Building Project "C:\lib\opencv\CMakeFiles\CMakeTmp\cmTC_e7517.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\lib\opencv\CMakeFiles\CMakeTmp\cmTC_e7517.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\lib\opencv\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: 'CL_VERSION_2_0': undeclared identifier [C:\lib\opencv\CMakeFiles\CMakeTmp\cmTC_e7517.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.31

File C:/lib/opencv/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include/CL/cl.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CL_VERSION_2_0
  return ((int*)(&CL_VERSION_2_0))[argc];
#else
  (void)argc;
  return 0;
#endif
}

##### Steps to reproduce

In Windows 10, pull most recent OpenCV code from github with opencv_contrib.  Use cmake to attempt to generate visual studio solution files for building using with CUDA flag and the opencv_contrib directory specified.

**Comment by MRinel** [comment]
Have you solved the problem? I catch the same error when compile TVM-v0.4 with cmake-3.11 and cuda-9.0,
```
/tvm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘CL_VERSION_2_0’ undeclared (first use in this function); did you mean          ‘CL_VERSION_1_0’?
      return ((int*)(&CL_VERSION_2_0))[argc];
```
```
File /cross_compile/tvm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
  22 /* */
  23 #include </usr/local/cuda-9.0/include/CL/cl.h>
  24
  25 int main(int argc, char** argv)
  26 {
  27   (void)argv;
  28 #ifndef CL_VERSION_2_0
  29   return ((int*)(&CL_VERSION_2_0))[argc];
  30 #else
  31   (void)argc;
  32   return 0;
  33 #endif

```
And the file /usr/local/cuda-9.0/include/CL/cl.h does not have CL_VERSION_2_0 defined.

**Comment by amrosado** [comment]
I believe I fixed this problem by making sure the opencv_extra_modules_path variable in Cmake was set to the modules directory in the opencv_contrib repository and not the base directory.

**Comment by land-pack** [comment]
> I believe I fixed this problem by making sure the opencv_extra_modules_path variable in Cmake was set to the modules directory in the opencv_contrib repository and not the base directory.

You are right, most tutorial said, just include the name of open_cv, but actually, it's should be like this:

  cmake -D CMAKE_BUILD_TYPE=RELEASE \
```
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=/Users/frank/cv/opencv_contrib/modules \
    -D PYTHON3_LIBRARY=`python3 -c 'import subprocess ; import sys ; s = subprocess.check_output("python-config --configdir", shell=True).decode("utf-8").strip() ; (M, m) = sys.version_info[:2] ; print("{}/libpython{}.{}.dylib".format(s, M, m))'` \
    -D PYTHON3_INCLUDE_DIR=`python3 -c 'import distutils.sysconfig as s; print(s.get_python_inc())'` \
    -D PYTHON3_EXECUTABLE=/Users/frank/venv/gopro/bin/python3 \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
		-D CMAKE_CXX_COMPILER=/usr/local/gcc-9.2/bin/g++-9.2 \
		-D ENABLE_CXX11=ON \
    -D BUILD_EXAMPLES=ON .. 
```

**Comment by alalek** [comment]
> Determining if the CL_VERSION_2_0 exist failed with the following output

It is just a build configuration check. They may fail - it is normal. In the most cases these failures can be safely ignored (because they are handled by configuration scripts).

Next steps, like compilation should not be broken (due applying corresponding flags based on the check result).

---

Real problem should be showed in CMake stdout (terminal) log.
