### ISSUE TITLE
compile error  " boostdesc.cpp:714:11: error: expected ‘}’ before ‘ini_params’"

### ISSUE THREAD

**Issue by BenJaminKen** [opencv/opencv_contrib#2047]
- OpenCV => 4.0.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => cmake  version 3.13.0-rc1  gcc version 5.4.0 20160609 

##### Detailed description

error:    opencv-4.0.1/opencv_contrib-4.0.1/modules/xfeatures2d/src/boostdesc.cpp:714:11: error: expected ‘}’ before ‘ini_params’ ini_params( orientQuant, patchSize,
opencv-4.0.1/opencv_contrib-4.0.1/modules/xfeatures2d/src/boostdesc.cpp:714:11: error: expected ‘,’ or ‘;’ before ‘ini_params’

**Comment by alalek** [comment]
Ensure that ".i" files are downloaded properly by CMake.

**Comment by BenJaminKen** [comment]
@alalek  I dowloaded ".i" files by myself,and move those into the directory ==>"/opencv_contrib-4.0.1/modules/xfeatures2d/src/"
