### ISSUE TITLE
cv::ximgproc::EdgeBoxes does not return box scores

### ISSUE THREAD

**Issue by llschloesser** [opencv/opencv_contrib#2060]
##### System information (version)

- OpenCV => 3.4.5
- Operating System / Platform => Ubuntu 16.04
- Compiler => GCC 5.4.0

##### Detailed description

The `cv::ximgproc::EdgeBoxes` implementation computes a score for each box and sorts the returned rectangles by this score. However, the returned objects are of type `cv::Rect` and not 
`cv::ximgproc::Box`. This means that box scores are not accessible to the user. Returning this score would allow the user to  create a better heat map or an alternative box NMS or box merging method, and not force them to create their own way of re-scoring the boxes (aside from the obvious rank).

##### Steps to reproduce
N/A

**Comment by saskatchewancatch** [comment]
Based on the implementation it seems like implementer intended that only `cv::Rect` be returned and for `cv::ximgproc::Box` as a utility for the algorithm's implementation?

So as not to break API compatibility for those who're using the current method to return boxes, what about optional output param that is a vector of `float`s containing scores corresponding to the vector of Rect's to be returned? So you may have scores too for those Rects if you so desire?

**Comment by llschloesser** [comment]
That works for me. Maybe also hide `cv::ximgproc::Box`? In a more perfect world `cv::saliency::ObjectnessBING` and `cv::ximgproc::EdgeBoxes` would have a common interface, something like `cv::RegionProposer`. Interest in such approaches could revive.

**Comment by saskatchewancatch** [comment]
@alalek  @llschloesser I think OutputArray might be suited for this and make implementing the OP's request easy.

What we have now:
`getBoundingBoxes (InputArray edge_map, InputArray orientation_map, std::vector< Rect > &boxes)`

Proposal 1 - change signature of `getRoundingBoxes` to:
`getBoundingBoxes (InputArray edge_map, InputArray orientation_map, std::vector< Rect > &boxes, OutputArray scores = noArray())`

Proposal 2 - just return Boxes in the same manner that Rect vector is returned:
`getBoundingBoxes (InputArray edge_map, InputArray orientation_map, Boxes scores)`

**Comment by jeromerony** [comment]
Is there any update on this ? That would indeed be really useful.

**Comment by saskatchewancatch** [comment]
@llschloesser  @jeromerony Please feel free to try out PR #2152. I attempted Proposal 1 from my recent comment. Testing with the sample edgeboxes_demo.cpp it returns the scores correctly for me. Let's see how the PR goes.

**Comment by saskatchewancatch** [comment]
PR 2152 should satisfy the OP's requirements.

I think this issue can be closed.

**Comment by alalek** [comment]
I will close this after "Merge-3.4" patch (then fix become available on "master" branch).
