### ISSUE TITLE
BRISQUE algorithm behaving oddly 

### ISSUE THREAD

**Issue by DustinPeabody** [opencv/opencv_contrib#2128]
##### System information (version)

- OpenCV => 4.1.0'
- Operating System / Platform => macOS Mojave 10.14.5

##### Detailed description
Using opencv installed with `brew install opencv@4 --with-contrib`, the `cv2.quality.QualityBRISQUE_compute` method always returns the same result. `(-3.022314549036573e+24, 0.0, 0.0, 0.0)` no matter what image I give to the method to evaluate. Based on the documentation the score should be between 0 and 100. 

##### Steps to reproduce
```python
import cv2
img = cv2.imread('<path-to-image>', 1)
score = cv2.quality.QualityBRISQUE_compute(img ,'<path-to-model-yml>','<path-to-range-yml>')
print(score)
```
Here I used this [image.](https://www.learnopencv.com/wp-content/uploads/2018/06/original-rotated-image.jpg) And this was the score `(-3.022314549036573e+24, 0.0, 0.0, 0.0)` I took the model and range yml files from https://github.com/opencv/opencv_contrib/tree/master/modules/quality/samples

**Comment by alalek** [comment]
Did you try `[img]` instead of `img`? (relates #2111)

**Comment by clunietp** [comment]
@DustinPeabody , please try passing a list like @alalek mentioned.  Recently, we changed the interface to accept individual images rather than lists to avoid this exact problem.

Using the latest opencv/quality code, I get a value of `55.194...` under both Win32 and Linux (WSL) for your test image

**Comment by DustinPeabody** [comment]
Yea I tried passing a list just now and it works just as intended. I see now the docs even say `list of images in Python` so this is my bad. Thanks for getting back to me so quickly. I got `53.390...` when I pass the image inside a list.
