### ISSUE TITLE
Build fails, incorrect include path in odometry.cpp

### ISSUE THREAD

**Issue by dnandha** [opencv/opencv_contrib#2144]
##### System information (version)
- OpenCV => 4.1.0-2
- Operating System / Platform => 5.1.3-arch1-1-ARCH / x86_64 GNU/Linux
- Compiler => gcc version 8.3.0 (GCC)

##### Detailed description

When compiling __OpenCV__ with the `OPENCV_EXTRA_MODULES_PATH` the build fails due to an error in the __rgbd__ => __odometry__ component. The error is caused when __Eigen3__ is already installed, in which case the build of the component fails because of an incorrect path.

I have `eigen 3.3.7-2` already installed on my system. There is a symlink in `/usr/include` named `Eigen` which points to `eigen3/Eigen`. The desired `unsupported/Eigen` folder resides within `eigen3`. Usually __OpenCV__ should find the `eigen3` folder with cmake and expose the underlying `unsupported` folder, but that's not happening in my case.

##### Error log
```
[ %] Building CXX object modules/rgbd/CMakeFiles/opencv_rgbd.dir/src/odometry.cpp.o
/home/xxx/opencv/repos/extra-x86_64/src/opencv_contrib-4.1.0/modules/rgbd/src/odometry.cpp:21:12: fatal error: unsupported/Eigen/MatrixFunctions: No such file or directory
 #  include <unsupported/Eigen/MatrixFunctions>
```

**Comment by alalek** [comment]
probably related changes: https://github.com/opencv/opencv/pull/13337

---

> 4.1.0-2

What is this?

Did you try to build clean 4.1.0? OpenCV 4.0.1?

**Comment by dnandha** [comment]
Problem resolved and build successfull after deleting the mentioned `Eigen` symlink from `/usr/include`.

I'm not sure how that symlink got there, but it did mess up the `find_package` of __OpenCV__ cmake.
I could verify that my __Eigen3__ include path was correct after deleting the symlink and checking `CMakeCache.txt` in the __OpenCV__ build directory. It showed, now correctly:
`EIGEN_INCLUDE_PATH:PATH=/usr/include/eigen3`
