### ISSUE TITLE
Documentation Error Aruco CharucoBoard.draw() (Python)

### ISSUE THREAD

**Issue by JeremyKeusters** [opencv/opencv_contrib#2170]
There's an error in the documentation for the CharucoBoard draw():
https://docs.opencv.org/3.4.3/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html#a5f1b7c91bd8bf8271931d6f06292f1bc

It says the following params are required in Python:

`img	=	cv.aruco_CharucoBoard.draw(	outSize[, img[, marginSize[, borderBits]]]	)`

However, when I input these params, I get the following error:

`TypeError: descriptor 'draw' requires a 'cv2.aruco_CharucoBoard' object but received a 'tuple'`

It appears that method expects the earlier created CharucoBoard Object (with `aruco.CharucoBoard_create`) to be inputted:

```
CHARUCO_BOARD = aruco.CharucoBoard_create(...)
markerBoard = cv2.aruco_CharucoBoard.draw(CHARUCO_BOARD, (1000,1000))
```

And the above works fine.

I only tested this on v 3.4.3.18
Thanks.

**Comment by dogod621** [comment]
Python-OpenCV is not official...
maybe you are reporting issue at wrong place.

by the way
```
cv2.aruco_CharucoBoard.draw(CHARUCO_BOARD, (1000,1000))
```
is as same as
```
CHARUCO_BOARD.draw((1000,1000))
```
I prefer second one,

and it is object oriented design ,
if you do not tell aruco what is your board,
how can it figure out what to draw?

so board must one of the parameter,
or drawing function is member function of board class

**Comment by AleksandrPanov** [comment]
> There's an error in the documentation for the CharucoBoard draw(): https://docs.opencv.org/3.4.3/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html#a5f1b7c91bd8bf8271931d6f06292f1bc
> 
> It says the following params are required in Python:
> 
> `img = cv.aruco_CharucoBoard.draw( outSize[, img[, marginSize[, borderBits]]] )`
> 
> However, when I input these params, I get the following error:
> 
> `TypeError: descriptor 'draw' requires a 'cv2.aruco_CharucoBoard' object but received a 'tuple'`
> 
> It appears that method expects the earlier created CharucoBoard Object (with `aruco.CharucoBoard_create`) to be inputted:
> 
> ```
> CHARUCO_BOARD = aruco.CharucoBoard_create(...)
> markerBoard = cv2.aruco_CharucoBoard.draw(CHARUCO_BOARD, (1000,1000))
> ```
> 
> And the above works fine.
> 
> I only tested this on v 3.4.3.18 Thanks.

`draw()` is member function. You need call `draw()` by this way:
```
CHARUCO_BOARD = aruco.CharucoBoard_create(...)
markerBoard = CHARUCO_BOARD.draw((1000,1000))
```
