### ISSUE TITLE
Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "") -- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags-- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags

### ISSUE THREAD

**Issue by minglou1984** [opencv/opencv_contrib#2173]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
