### ISSUE TITLE
cannot build without NVCUVID

### ISSUE THREAD

**Issue by ashok3t** [opencv/opencv_contrib#2184]
As a user of CUDA 9 or later, I would like to be able to build OpenCV without the NVIDIA CODEC SDK, so that I can simplify build and licensing.

Specifically, HAVE_NVCUVID is defined if WITH_CUDA is defined even if building with -DWITH_NVCUVID=OFF.  This issue applies to OpenCV 4.1.0 or the current head revision.

Although the following patch resolves the issue (tested with cmake 3.10.2 and 3.14.5 with CUDA 10.0 on Ubuntu 18.04 and gcc 7.4), it is not consistent with other opencv build options like WITH_CUBLAS.

```
diff --git a/code/cmake/OpenCVDetectCUDA.cmake b/code/cmake/OpenCVDetectCUDA.cmake
index 574873cd..6c8ee1b8 100644
--- a/code/cmake/OpenCVDetectCUDA.cmake
+++ b/code/cmake/OpenCVDetectCUDA.cmake
@@ -37,7 +37,9 @@ if(CUDA_FOUND)
     set(HAVE_CUBLAS 1)
   endif()
 
-  if(WITH_NVCUVID)
+  unset(HAVE_NVCUVID)
+  unset(HAVE_NVCUVENC)
+  if(DEFINED ${WITH_NVCUVID})
     find_cuda_helper_libs(nvcuvid)
     if(WIN32)
       find_cuda_helper_libs(nvcuvenc)
```

**Comment by alalek** [comment]
> HAVE_NVCUVID is defined if WITH_CUDA is defined even if building with -DWITH_NVCUVID=OFF

This is not true. Take a look on [scripts](https://github.com/opencv/opencv/blob/8408587341f6ed67d02873b51c3862961d1b5374/cmake/OpenCVDetectCUDA.cmake#L50-L61).

`cmake -DWITH_NVCUVID=OFF ...` is enough to turn it off completelly.

Probably you have corrupted CMake cache. Try from clean build directory.

---

```
if(DEFINED ${WITH_NVCUVID})
```

Invalid expression (wrong variable expansion, `WITH_NVCUVID` is always defined if `WITH_CUDA=ON`).

**Comment by ashok3t** [comment]
> Probably you have corrupted CMake cache. Try from clean build directory.
I can reproduce after deleting all build and install artifacts.

> WITH_NVCUVID is always defined if WITH_CUDA=ON
Precisely the problem.  The purpose of the option should be to toggle the use of the SDK.

> Invalid expression (wrong variable expansion
Without my patch, the if test succeeds if the variable is defined even if OFF.  With the patch, the value of the variable is tested.

However, my patch is only an example of a way to address the problem.  A correct fix should apply consistently to OpenCV build options.

**Comment by alalek** [comment]
OpenCV's check is:
```
if(WITH_NVCUVID)
```

> the if test succeeds if the variable is defined even if OFF

This is not true for the check above. See [CMake documentation](https://cmake.org/cmake/help/v3.0/command/if.html).

**Comment by ashok3t** [comment]
It's easy to reproduce the issue.  Just ensure that nvcuvid.h is not found and try to build using -DWITH_NVCUVID=OFF.  You can see that HAVE_NVCUVID is still defined after cmake configuration.

Note also that BUILD_opencv_cudacodec is no longer a build option.

**Comment by alalek** [comment]
Works as expected: [opencv_contrib_2184.txt](https://github.com/opencv/opencv_contrib/files/3373224/opencv_contrib_2184.txt)

**Comment by ashok3t** [comment]
Thanks for the build output, that is really helpful.  The primary difference, as you mentioned earlier, is that you removed the build artifacts.  If you do not perform a clean build, there is no cmake script that removes the definition of HAVE_NVCUVID when toggling WITH_NVCUVID.
