### ISSUE TITLE
Data augmentation module

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv_contrib#2191]
@FadyEssam, I'd like to propose this issue to track reviewing status. Please consider the following recommendations for this PR: https://github.com/opencv/opencv_contrib/pull/2187.

Please write in the issue comments about completeness.

#### augment::Transform
- [x] Use `cv::Rect2f` for `rectangle` method instead of `cv::Vec4f`
- [ ] Mark all the base methods as pure virtual: `image`, `point`, `rectangle`, `mask`. They should be implemented in each transformation to avoid bugs with identity transformations.
- [ ] `Transform::rectangles` should work as with `std::vector<cv::Rect2f>` inside the `InputArray` as with `cv::Mat` with number of columns equal 4 (x, y, w, h).
- [ ] Add Python test for `Transform::rectangles` with Nx4 `numpy.array` of type `np.float32`, list of 1D numpy arrays of type `np.float32`, list of lists with 4 float numbers.
- [ ] `Transform::points` should work as with `std::vector<cv::Point2f>` inside the `InputArray` as with `cv::Mat` with number of columns equal 2 (x, y).
- [ ] Add Python test for `Transform::points` with Nx2 `numpy.array` of type `np.float32`, list of 1D numpy arrays of type `np.float32`, list of lists with 2 float numbers.

#### augment::CropToFixedSize
- [x] Uninitialized values: `originX` and `originY` with first constructor.
- [x] Add a constructor with X and Y positions
- [ ] What if user's image less than crop size? We need to manage it by resizing to desired resolution but keeping aspect ratio.
- [ ] Add randomness. In example, by choosing X any Y.

#### augment::Crop
- [ ] Implement `augment::Crop` with random cropping (different size might be used). I think it's better to merge it with `CropToFixedSize` under the name crop `Crop`: user can specify fixed crop sizes or specify min and max ones.
- [ ] Implement `Crop::rectangle`

#### augment::FlipHorizontal
- [ ] Implement `FlipHorizontal::rectangle` (and FlipVertical as well)
- [ ] Landmarks flipping. We need to propose a way to keep swap specific landmarks after horizontal flipping. In example, if you have a face with "right eye", "left eye" and "nose" you need to swap coordinates of left and right eyes after flip but keep nose:

![image](https://user-images.githubusercontent.com/25801568/61410961-015bff80-a8ee-11e9-9b13-cbd26b934370.png)

So that means we need to override `Transform::points` method

#### augment::Resize
- [x] ~~Drop duplication of `interpolations` and `interpolation`~~
- [ ] Implement `Resize::rectangle`

#### augment::Rotate
- [ ] Add interpolation and border variation. See https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#ga0203d9ee5fcd28d40dbc4a1ea4451983
- [ ] Implement `Rotate::rectangle`
- [ ] Test `Rotate::mask` with non-zero values at the edge of image.

#### augment::Shift
- [ ] Implement random shift

#### augment::Noise
- [ ] Implement noising

#### augment::Augmenter
- [ ] Optimize augmentation by using OpenCV's parallel_for.

#### Custom transformation
- [ ] Implement custom transformation support from Python.

#### General
- [ ] Please remove empty lines (there are two empty lines at the beginning of almost all the files and
one empty line before classes' closing bracket).

--- 
# Resolved

#### augment::AverageBlur

- [x] Add variation of `borderType` parameter. Add a constructor with fixed `borderType` value. See https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga8c45db9afe636703801b0b2e440fce37
- [x] Check that `minSize != maxSize` before random sampling.
- [x] `kernelSize` is uninitialized: set it to minSize in constructors.
- [x] Implement `AverageBlur::rectangle` as an identity

**Comment by FadyEssam** [comment]
augment::Transform
1 - done

2 - that can't be done because the transformations that don't change anything of the ground truth data like GaussianBlur for example don't need to reimplement that they don't change every type, they just don't implement any type of ground truth data and rely on the identity transformation of the base.

That's much more convinient for anyone implementing new transformation

3 - stuck on a problem with the python binder here  'vector_Rect2f': undeclared identifier' when I use std::vector<Rect2f>

**Comment by dkurt** [comment]
> 2 - that can't be done because the transformations that don't change anything of the ground truth data like GaussianBlur for example don't need to reimplement that they don't change every type, they just don't implement any type of ground truth data and rely on the identity transformation of the base.

So if `augment::Transform` means Identity transformation please implement them as identity:
```cpp
Rect2f Transform::rectangle(const Rect2f& src)
{
    return src
}
// etc.
```

**Comment by FadyEssam** [comment]
> > 1 - done
> 
> Thanks! Marked as done
> 
> > 2 - that can't be done because the transformations that don't change anything of the ground truth data like GaussianBlur for example don't need to reimplement that they don't change every type, they just don't implement any type of ground truth data and rely on the identity transformation of the base.
> 
> So if `augment::Transform` means Identity transformation please implement them as identity:
> 
> ```c++
> Rect2f Transform::rectangle(const Rect2f& src)
> {
>     return src
> }
> // etc.
> ```

rectangle of the base class can't be implemented as just plain identity because it is used to utilise the point function to avoid re implementing rectangle function for each transformation.

If the transformation doesn't specify a specific function for point() function it will act as identity, otherwise it will do its job

**Comment by FadyEssam** [comment]
**augment::AverageBlur**

All done

**Comment by dkurt** [comment]
> rectangle of the base class can't be implemented as just plain identity because it is used to utilise the point function to avoid re implementing rectangle function for each transformation.

We must do it. In example for flip width and height are invariant. We shouldn't do extra computations.

**Comment by FadyEssam** [comment]
> > rectangle of the base class can't be implemented as just plain identity because it is used to utilise the point function to avoid re implementing rectangle function for each transformation.
> 
> We must do it. In example for flip width and height are invariant. We shouldn't do extra computations.

any transformation that has simpler function can override it to be faster, but not change the base function.

**Comment by FadyEssam** [comment]
**augment::AverageBlur** 
all done

**augment::Resize** 
this is not a duplication as discussed earlier

**Comment by FadyEssam** [comment]
**augment::CropToFixedSize**
1.  done
2. done
4. done
3. resize to a larger size? what does that mean in terms of data augmentation and how is it related to the Crop transformation, we already have a Resize transformation that can be added before the Crop for that

**Comment by dkurt** [comment]
> 

        rectangle of the base class can't be implemented as just plain identity because it is used to utilise the point function to avoid re implementing rectangle function for each transformation.

    We must do it. In example for flip width and height are invariant. We shouldn't do extra computations.

any transformation that has simpler function can override it to be faster, but not change the base function.

So we need to provide these efficient implementations. I'll update an issue with the list of methods which should be overridden.

**Comment by dkurt** [comment]
>  What if user's image less than crop size? We need to manage it by resizing to desired resolution but keeping aspect ratio.

> CV_Assert(width <= srcImageCols && height <= srcImageRows);

We need to remove an assertion anyway. Imagine the situation when training pipeline is failed after hours of iterations because OpenCV couldn't crop image to fixes size because image was less than desired size.

**Comment by FadyEssam** [comment]
> > What if user's image less than crop size? We need to manage it by resizing to desired resolution but keeping aspect ratio.
> 
> > CV_Assert(width <= srcImageCols && height <= srcImageRows);
> 
> We need to remove an assertion anyway. Imagine the situation when training pipeline is failed after hours of iterations because OpenCV couldn't crop image to fixes size because image was less than desired size.

even if we remove the Assertion, the crop in opencv will throw a similar exception, I don't think it is logical to issue a crop to a larger size than the image and the data should be cleaned before training.. don't you think?

**Comment by FadyEssam** [comment]
Added optimized rectangle function for all transformations.

**augment::crop**
imlemented Crop with random sizes and merged it with CropToFixedSize

**Comment by dkurt** [comment]
> even if we remove the Assertion, the crop in opencv will throw a similar exception, I don't think it is logical to issue a crop to a larger size than the image and the data should be cleaned before training.. don't you think?

No dataset fixes, no assertions. We have to provide working solution by default. If we cannot Crop image with specific size - we need to remove this transformation or replace to another one (without specific sizes but central crop)

> Added optimized rectangle function for all transformations.

Added transformations aren't exactly what I meant by optimal transformation. They are still two points 

Should be at least something like this:
```cpp
Rect2f FlipHorizontal::rectangle(const Rect2f& src)
{
    return Rect2f(width - 2 + src.width - src.x, src.y, src.width, src.height);
}
```

**Comment by FadyEssam** [comment]
> Should be at least something like this:
> 
> ```c++
> Rect2f FlipHorizontal::rectangle(const Rect2f& src)
> {
>     return Rect2f(imgWidth - 2 + src.width - src.x, src.y, src.width, src.height);
> }
> ```

fixed that

**Comment by FadyEssam** [comment]
> No dataset fixes, no assertions. We have to provide working solution by default. If we cannot Crop image with specific size - we need to remove this transformation or replace to another one (without specific sizes but central crop)


I handled cropping to larger size..
I resize the image to that size with keeping the original aspect ratio and added specified rectangle() to Crop

**Comment by FadyEssam** [comment]
**augment::Rotate**

Added support for random interpolations and border types

**Comment by FadyEssam** [comment]
**augment::FlipHorizontal**

I think this is very application specific so the user can inherit any transformation and override its points() function.

I think our job here is to provide the ability for custom transformations not to implement app specific features

**Comment by FadyEssam** [comment]
I added  **augment::Shift**

**Comment by FadyEssam** [comment]
I added **augment::GaussianNoise**

**Comment by FadyEssam** [comment]
I added **augment::UniformNoise**

**Comment by FadyEssam** [comment]
I am working on overriding a transformation in python bur there are 2 problems

1. binding any function that uses Rect2f in its argumenta doesn't work

2. the only functions that can be overriden and seen and work proberly in the children are the functions that has parameter InputArray and OutputArray.. they don't work with functions that take Point2f for example

**Comment by FadyEssam** [comment]
**General**

removed unnecessary spaces

**Comment by FadyEssam** [comment]
Now All is finished except regarding **augment::augmenter** and **custom transformation** because of the binder issues
