### ISSUE TITLE
recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/vgg.cpp.o' failed

### ISSUE THREAD

**Issue by George0720** [opencv/opencv_contrib#2201]
I encountered this error while installing opencv3. Has anyone encountered this problem?What should I do?

/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg.cpp: In constructor ‘cv::xfeatures2d::VGG_Impl::VGG_Impl(int, float, bool, bool, float, bool)’:
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg.cpp:513:11: error: expected ‘}’ before ‘ini_params’
           ini_params( PRrows, PRcols, PRidx, sizeof(PRidx)/sizeof(PRidx[0]), PR,
           ^~~~~~~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg.cpp:513:11: error: expected ‘,’ or ‘;’ before ‘ini_params’
In file included from /home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg.cpp:512:0:
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:8:18: warning: unused variable ‘PRrows’ [-Wunused-variable]
 static const int PRrows = 60;
                  ^~~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:11:18: warning: unused variable ‘PRcols’ [-Wunused-variable]
 static const int PRcols = 4096;
                  ^~~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:14:27: warning: unused variable ‘PRidx’ [-Wunused-variable]
 static const unsigned int PRidx[] =
                           ^~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:214:27: warning: unused variable ‘PR’ [-Wunused-variable]
 static const unsigned int PR[] =
                           ^~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:5702:18: warning: unused variable ‘PJrows’ [-Wunused-variable]
 static const int PJrows = 48;
                  ^~~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:5705:18: warning: unused variable ‘PJcols’ [-Wunused-variable]
 static const int PJcols = 480;
                  ^~~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:5708:27: warning: unused variable ‘PJidx’ [-Wunused-variable]
 static const unsigned int PJidx[] =
                           ^~~~~
/home/pi/Downloads/opencv_contrib-3.4.0/modules/xfeatures2d/src/vgg_generated_48.i:5714:27: warning: unused variable ‘PJ’ [-Wunused-variable]
 static const unsigned int PJ[] =
                           ^~
modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/build.make:595: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/vgg.cpp.o' failed
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/vgg.cpp.o] Error 1
CMakeFiles/Makefile2:14012: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all' failed
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by George0720** [comment]
`sudo cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=ON -D OPENCV_EXTRA_MODULES_PATH=/home/pi/Downloads/opencv_contrib-3.4.0/modules -D BUILD_EXAMPLES=ON ..`


Using this cmake config:

**Comment by LDBauswlmq** [comment]
One possibility is that one/some of your vgg_***.i files (like vgg_generated_48.i) is/are incomplete. Please check if they are all ended with "};". 
You can download them according to the urls in CMakeDownloadLog.txt in your build directory (Like here: https://raw.githubusercontent.com/opencv/opencv_3rdparty/fccf7cd6a4b12079f73bbfb21745f9babcd4eb1d/vgg_generated_48.i).
