### ISSUE TITLE
opencv_cudaoptflow 4.1.1 has a strong dependency to nvcuda.dll

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv_contrib#2210]
Starting from OpenCV 4.1.1, the NVidia Optflow sdk is taken into account in cudaoptflow.
However, because of the use of
cuCtxGetCurrent(), cuCtxPopCurrent(), cuCtxPushCurrent(), cuCtxSynchronize(),
then opencv_cudaoptflow411.dll fails to load, and prevents a program from running if nvcuda.dll is not available on the host machine.

A solution under windows+Visual Studio is to "Delay load" opencv_cudaoptflow411.dll, but it is less convenient than unders OpenCV <= 4.1.0, where checking at runtime for "cv::cuda::getCudaEnabledDeviceCount()" was enough to decide if cuda was available.

**Comment by alalek** [comment]
relates #2165

/cc @vchiluka5

**Comment by vchiluka5** [comment]
Nvidia Optical Flow create call requires cuda driver API for creating instance of optical flow on Nvidia hardware accelerator. Hence at least one driver API call cuCtxGetCurrent() is needed in any case for optical flow to work and hence arises dependency for nvcuda.dll. 
There is no way to get cuda context using runtime APIs. 

Any suggestions/alternatives?

**Comment by chacha21** [comment]
What about lazy loading nvcuda.dll to resolve cuCtxPushCurrent() and others at run-time with GetProcAdress() ?

**Comment by vchiluka5** [comment]
Thanks @chacha21  
Can you please give a repro setup scenario (machine, driver, OS installed) where i can reproduce this issue locally? 
Delay loading seems to be a solution but for delay loading cuda.h needs to be there which is supplied via cuda toolkit.

**Comment by chacha21** [comment]
My scenario is Win7 64b, Visual Studio Community 2019, OpenCV 4.1.1 built with CUDA enabled

**Comment by vchiluka5** [comment]
Thanks @chacha21 for information and patch. 
Il send a much simpler version of your patch analyzing what's needed and what not by tomorrow.
I have the patch ready. Its needs to be reviewed within my team.
Hope it works. :-)
