### ISSUE TITLE
Img_hash module fails in C++. Undefined refrence errors

### ISSUE THREAD

**Issue by Mahaaveer** [opencv/opencv_contrib#2212]
**##### System information (version)**

- OpenCV = 3.3.1
- Operating System / Platform => Ubuntu 16.04

**##### Detailed description**

I want to calculate phash for pictures using a cpp program. 
i have compiled opencv 3.3.1 with opencv contrib 3.3.1 successfully
when i try to compile the example code given in https://docs.opencv.org/3.3.1/d4/d93/group__img__hash.html with gcc , it just throws "undefined refrence to" errors

i am in need of calculating phash in cpp. any help is appreciated 

**##### Code**

#include "opencv2/core.hpp"
#include "opencv2/core/ocl.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/img_hash.hpp"
#include <iostream>
using namespace cv;
using namespace cv::img_hash;
using namespace std;
template <typename T>
inline void test_one(const std::string &title, const Mat &a, const Mat &b)
{
    cout << "=== " << title << " ===" << endl;
    TickMeter tick;
    Mat hashA, hashB;
    Ptr<ImgHashBase> func;
    func = T::create();
    tick.reset(); tick.start();
    func->compute(a, hashA);
    tick.stop();
    cout << "compute1: " << tick.getTimeMilli() << " ms" << endl;
    tick.reset(); tick.start();
    func->compute(b, hashB);
    tick.stop();
    cout << "compute2: " << tick.getTimeMilli() << " ms" << endl;
    cout << "compare: " << func->compare(hashA, hashB) << endl << endl;;
}
int main(int argc, char **argv)
{
    if (argc != 3)
    {
        cerr << "must input the path of input image and target image. ex : hash_samples lena.jpg lena2.jpg" << endl;
        return -1;
    }
    ocl::setUseOpenCL(false);
    Mat input = imread(argv[1]);
    Mat target = imread(argv[2]);
    test_one<AverageHash>("AverageHash", input, target);
    test_one<PHash>("PHash", input, target);
    test_one<MarrHildrethHash>("MarrHildrethHash", input, target);
    test_one<RadialVarianceHash>("RadialVarianceHash", input, target);
    test_one<BlockMeanHash>("BlockMeanHash", input, target);
    return 0;
}

**##### result:**

gcc test_success.cpp 
/tmp/ccjlnwUV.o: In function `main':
test_success.cpp:(.text+0x37): undefined reference to `std::cerr'
test_success.cpp:(.text+0x3c): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
test_success.cpp:(.text+0x41): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
test_success.cpp:(.text+0x49): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
test_success.cpp:(.text+0x5d): undefined reference to `cv::ocl::setUseOpenCL(bool)'
test_success.cpp:(.text+0x9b): undefined reference to `cv::imread(cv::String const&, int)'
test_success.cpp:(.text+0xe5): undefined reference to `cv::imread(cv::String const&, int)'
test_success.cpp:(.text+0x103): undefined reference to `std::allocator<char>::allocator()'
test_success.cpp:(.text+0x11e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
test_success.cpp:(.text+0x14a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x159): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x168): undefined reference to `std::allocator<char>::allocator()'
test_success.cpp:(.text+0x183): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
test_success.cpp:(.text+0x1af): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x1be): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x1cd): undefined reference to `std::allocator<char>::allocator()'
test_success.cpp:(.text+0x1e8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
test_success.cpp:(.text+0x214): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x223): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x232): undefined reference to `std::allocator<char>::allocator()'
test_success.cpp:(.text+0x24d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
test_success.cpp:(.text+0x279): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x288): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x297): undefined reference to `std::allocator<char>::allocator()'
test_success.cpp:(.text+0x2b2): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
test_success.cpp:(.text+0x2de): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x2ed): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x39e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x3b2): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x3c9): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x3dd): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x3f1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x405): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x419): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x42d): undefined reference to `std::allocator<char>::~allocator()'
test_success.cpp:(.text+0x441): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_success.cpp:(.text+0x455): undefined reference to `std::allocator<char>::~allocator()'
/tmp/ccjlnwUV.o: In function `__static_initialization_and_destruction_0(int, int)':
test_success.cpp:(.text+0x4b6): undefined reference to `std::ios_base::Init::Init()'
test_success.cpp:(.text+0x4c5): undefined reference to `std::ios_base::Init::~Init()'
/tmp/ccjlnwUV.o: In function `cv::String::String(char const*)':
test_success.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x54): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccjlnwUV.o: In function `cv::String::~String()':
test_success.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
/tmp/ccjlnwUV.o: In function `cv::Mat::~Mat()':
test_success.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to `cv::fastFree(void*)'
/tmp/ccjlnwUV.o: In function `cv::Mat::release()':
test_success.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4b): undefined reference to `cv::Mat::deallocate()'
/tmp/ccjlnwUV.o: In function `cv::TickMeter::start()':
test_success.cpp:(.text._ZN2cv9TickMeter5startEv[_ZN2cv9TickMeter5startEv]+0xd): undefined reference to `cv::getTickCount()'
/tmp/ccjlnwUV.o: In function `cv::TickMeter::stop()':
test_success.cpp:(.text._ZN2cv9TickMeter4stopEv[_ZN2cv9TickMeter4stopEv]+0xd): undefined reference to `cv::getTickCount()'
/tmp/ccjlnwUV.o: In function `cv::TickMeter::getTimeSec() const':
test_success.cpp:(.text._ZNK2cv9TickMeter10getTimeSecEv[_ZNK2cv9TickMeter10getTimeSecEv]+0x27): undefined reference to `cv::getTickFrequency()'
/tmp/ccjlnwUV.o: In function `void test_one<cv::img_hash::AverageHash>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Mat const&, cv::Mat const&)':
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x36): undefined reference to `std::cout'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x3b): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x50): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x5d): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x62): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x6a): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0xb2): undefined reference to `cv::img_hash::AverageHash::create()'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x155): undefined reference to `cv::img_hash::ImgHashBase::compute(cv::_InputArray const&, cv::_OutputArray const&)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash11AverageHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x1a3): undefined reference to `std::cout'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x2c7): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x2cc): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x2d4): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x32e): undefined reference to `cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x340): undefined reference to `std::cout'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x345): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash18RadialVarianceHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x355): undefined reference to `std::ostream::operator<<(double)'
test_success.cpp:(.text._Z8test_oneIN2cv8img_hash13BlockMeanHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash13BlockMeanHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x1cf): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
(.text._Z8test_oneIN2cv8img_hash13BlockMeanHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_[_Z8test_oneIN2cv8img_hash13BlockMeanHashEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_3MatESD_]+0x367): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
/tmp/ccjlnwUV.o:(.eh_frame+0x2eb): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status

**Comment by alalek** [comment]
> undefined reference to std::cerr

Your app can't utilize even C++ standard library. You should check compiler flags at first.
Comment out all OpenCV related code and try again.

**Comment by Mahaaveer** [comment]
Thanks for pointing it out. i was using gcc to compile cpp by mistake.
But even g++ cannot solve the _undefined reference to_ errors

This is what i get now:

In function `main':
test_success.cpp:(.text+0x5d): undefined reference to `cv::ocl::setUseOpenCL(bool)'
test_success.cpp:(.text+0x9b): undefined reference to `cv::imread(cv::String const&, int)'
test_success.cpp:(.text+0xe5): undefined reference to `cv::imread(cv::String const&, int)'
/tmp/ccgPw5W3.o: In function `cv::String::String(char const*)':
test_success.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x54): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccgPw5W3.o: In function `cv::String::~String()':
test_success.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
/tmp/ccgPw5W3.o: In function `cv::Mat::~Mat()':
test_success.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to `cv::fastFree(void*)'
/tmp/ccgPw5W3.o: In function `cv::Mat::release()':
test_success.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4b): undefined reference to `cv::Mat::deallocate()'
/tmp/ccgPw5W3.o: In function `cv::TickMeter::start()':
test_success.cpp:(.text._ZN2cv9TickMeter5startEv[_ZN2cv9TickMeter5startEv]+0xd): undefined reference to `cv::getTickCount()'
/tmp/ccgPw5W3.o: In function `cv::TickMeter::stop()':
test_success.cpp:(.text._ZN2cv9TickMeter4stopEv[_ZN2cv9TickMeter4stopEv]+0xd): undefined reference to `cv::getTickCount()'
/tmp/ccgPw5W3.o: In function `cv::TickMeter::getTimeSec() const':
