### ISSUE TITLE
couldn't open pthread.h: No such file or directory

### ISSUE THREAD

**Issue by mico-yu** [opencv/opencv_contrib#2216]
- OpenCV => 3.4.1
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2019, Cmake

I tryed build OpenCV with extra modules by Cmake tool. But it failed with message:
D:\opencv-3.4.1-build\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): error C1083: could not open including file: “pthread.h”: No such file or directory [D:\opencv-3.4.1-build\build\CMakeFiles\CMakeTmp\cmTC_36a2a.vcxproj]
I tryed every method i searched from BAIDU and offical website, but all of them did not work.
Maybe YOUR one word can help me a lot. 
THANKS.

**Comment by alalek** [comment]
> CheckIncludeFile.c

This is just configuration check.
Your problem is somewhere else.
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

> 3.4.1
> Visual Studio 2019

Not supported.
At least because MSVS 2019 have been released after OpenCV 3.4.1.
Use latest OpenCV version instead.
