### ISSUE TITLE
superres BTVL1 without useOpenCL() call

### ISSUE THREAD

**Issue by Nuzhny007** [opencv/opencv_contrib#2221]
Superresolution BTVL1 with UMat result falls if first do not called function cv::ocl::useOpenCL().

##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Compiler => gcc

##### Detailed description

Superresolution BTVL1 with UMat result falls if first do not called function cv::ocl::useOpenCL().

```
// Don't works if line with cv::ocl::useOpenCL() is commented
std::cout << "OpenCL using: " << cv::ocl::useOpenCL() << std::endl;
superRes = cv::superres::createSuperResolution_BTVL1();
//..
cv::UMat sresFrame;
superRes->nextFrame(sresFrame);
```
Top of the stack trace:
```
bool BTVL1::ocl_readNextFrame(Ptr<FrameSource>& /*frameSource*/)
    {
        ucurFrame_.convertTo(at(storePos_, uframes_), CV_32F); <- Here uframes_ is empty
```

But it correctly works on CPU without OpenCL and on Nvidia GPU with OpenCL otherwise.

**Comment by Nuzhny007** [comment]
The reason is here: https://github.com/opencv/opencv_contrib/blob/master/modules/superres/src/btv_l1.cpp#L945
CV_OCL_RUN checks cv::ocl::isOpenCLActivated() and it return false.
So we have two conflincting conditions: g_isOpenCVActivated == false and isUmat_ == true.
I suggest fix it here:
```
void cv::superres::SuperResolution::nextFrame(OutputArray frame)
{
    CV_INSTRUMENT_REGION();
    isUmat_ = cv::ocl::haveOpenCL() && frame.isUMat();
```

**Comment by alalek** [comment]
> cv::ocl::useOpenCL()
> cv::ocl::isOpenCLActivated()

These two functions has similar meanings. Main difference is that first function makes attempt to initialize OpenCL subsystem.
Second function was introduced to avoid unnecessary loading of OpenCL runtime (if there is no UMat used).

Also any UMat allocation initializes OpenCL subsystem.

> isUmat_ = cv::ocl::haveOpenCL() && frame.isUMat();

I would suggest this fix:

```
isUmat_ = frame.isUMat() && cv::ocl::useOpenCL();
```

**Comment by Nuzhny007** [comment]
Ok, I will create the PL
