### ISSUE TITLE
BRISQUE returns negative score

### ISSUE THREAD

**Issue by xqterry** [opencv/opencv_contrib#2226]
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Python => 3.7

##### Detailed description

Brisque quality module should return score in range 0-100 but when I test with attached .jpg file it returned negative value.

```

img_fn = './1561910551903_128354867.jpg'
model_path = './opencv/opencv-4.1.1/opencv_contrib/modules/quality/samples/brisque_model_live.yml'
range_path = './opencv/opencv-4.1.1/opencv_contrib/modules/quality/samples/brisque_range_live.yml'
obj = cv2.quality.QualityBRISQUE_create(model_path, range_path)

img = cv2.imread(img_fn)
score = obj.compute([img])
print(score[0])
```

result is '-12.396707534790039'

(![1561910551903_128354867](https://user-images.githubusercontent.com/666512/63043806-83484400-beff-11e9-8aa7-d9339c75e0cb.jpg))

**Comment by clunietp** [comment]
@xqterry The algorithm appears to be sensitive to noisy images such as the one you had provided.  I ran your image through the original implementation (both the C++ and MATLAB versions) and received similarly negative scores.  After applying a noise filtering algorithm, the resulting quality score shot up to ~50 as expected.

While I'm not qualified to fix the original algorithm, what I can do is clamp the resulting output from BRISQUE to 0-100.  For now, consider the score less than zero to be a zero.  

If it fits your particular use case, I suppose you could apply a noise reduction algorithm when you do encounter <= zero and rerun BRISQUE.  This may yield misleading results, however, when the image distortion is something other than noise; seems like this approach would require further testing.
