### ISSUE TITLE
CMake issues with opencv build with opencv_contrib

### ISSUE THREAD

**Issue by pleopard777** [opencv/opencv_contrib#2237]
I pulled the latest opencv from github , then pulled the lates opencv_contrib to a folder of the same name under my opencv folder. Using the -DOPENCV_EXTRA_MODULES_PATH option with the opencv_contrib folder doesn't work, complaining that no modules are found (there are no CMake files in that path). Here is my log, can someone advise accordingly?

Detected processor: aarch64
Looking for ccache - not found
Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.3") 
Could NOT find Jasper (missing: JASPER_LIBRARIES JASPER_INCLUDE_DIR) 
Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.11") 
CUDA detected: 10.0
Automatic detection of CUDA generation failed. Going to build for all known architectures.
CUDA NVCC target flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72;-D_FORCE_INLINES
Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
Could NOT find Atlas (missing: Atlas_CLAPACK_INCLUDE_DIR) 
A library with BLAS API found.
A library with LAPACK API found.
Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
**CMake Error at cmake/OpenCVModule.cmake:289 (message):
  No modules has been found:
  /home/_username_/dev/3rdParty/opencv/opencv_contrib**
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:371 (_glob_locations)
  modules/CMakeLists.txt:7 (ocv_glob_modules)

OpenCV Python: during development append to PYTHONPATH: /home/_username_/dev/3rdParty/opencv/release_build/python_loader
Checking for module 'libavresample'
  No package 'libavresample' found
Checking for module 'libdc1394-2'
  No package 'libdc1394-2' found
CMake Error at modules/core/CMakeLists.txt:40 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib

Configuring incomplete, errors occurred!
See also "/home/_username_/dev/3rdParty/opencv/release_build/CMakeFiles/CMakeOutput.log".
See also "/home/_username_/dev/3rdParty/opencv/release_build/CMakeFiles/CMakeError.log".

**Comment by alalek** [comment]
> Using the -DOPENCV_EXTRA_MODULES_PATH option with the opencv_contrib folder doesn't work

Follow the example on this page: https://github.com/opencv/opencv_contrib
You have missing "/modules" subdirectory.

**Comment by pleopard777** [comment]
Yep, I specified the opencv_contib path, not opencv_contrib/modules

**Comment by Unlicensed-driver-ljx** [comment]
看下cmake 的时候opencv_contib的路径对不对，有可能是不小心指定到了上一级目录，比如你是mkdir opencv里面放了你下载的两个安装包在opencv4.6.0下面mkdir build 那你cmake 的时候就是-DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.6.0/modules

**Comment by booomji** [comment]
You have to point explicitly to the modules directory and not just the  opencv_contrib-4.10.0 directory.
So for e.g 
D:/path_to_opencv_contrib_folder/opencv_contrib-4.10.0/modules

Cheers,
b
