### ISSUE TITLE
Build issues with opencv_contrib in Windows x64

### ISSUE THREAD

**Issue by lvora** [opencv/opencv_contrib#2244]
##### System information (version)

- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
Facing compiler errors while building Visual Studio solution generated by CMake including:

\Desktop\OpenCVALL\opencv-master\modules\core\include\opencv2/core/hal/intrin_avx512.hpp(1081): error C3861: '_mm256_min_epu64': identifier not found

and other errors related to similar identifiers:
'_mm256_max_epi64': identifier not found

Searched for this identifier in the repository, but was not to be found. Any clue on what could be going on, or if there is anything missing in the CMake command (steps below)?

##### Steps to reproduce

1. Downloaded latest opencv_master and opencv_contrib from git.
2. Ran these steps on windows command prompt after downloading cmake:
$ cd <opencv_build_directory>
$ cmake DCMAKE_GENERATOR_PLATFORM=x64 -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>
3. Opened up OpenCV.sln and built the cmake targets including: ALL_BUILD and INSTALL (that appear under CMake Targets in Visual Studio).
4. Ran into issues only with a x64 configuration while building the Visual Studio solution. The x86 build seemed to run fine.

**Comment by alalek** [comment]
What is OpenCV version?

What is MSVS 2017 version? (including "update" number)

What is exact compiler version from CMake scripts output? Like this:
> C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe  (ver 19.16.27030.1)

Please attach/dump CMake stdout messages.

**Comment by pstieber** [comment]
I'm having what I believe is a similar problem with the 3.4.7 tag.

My MSVS 2017 version is

C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe  (ver 19.11.25547.0)

I believe that's 15.4.5.

I run cmake with:

```
cmake \
  -Wno-dev \
  -G "Visual Studio 15 2017 Win64" \
  -D BUILD_opencv_python2=OFF \
  -D BUILD_opencv_python3=OFF \
  -D BUILD_DOCS=OFF \
  -D BUILD_EXAMPLES=OFF \
  -D BUILD_PERF_TESTS=OFF \
  -D BUILD_TESTS=OFF \
  -D BUILD_SHARED_LIBS=OFF \
  -D BUILD_WITH_STATIC_CRT=OFF \
  -D BUILD_opencv_matlab=OFF \
  -D BUILD_opencv_cudacodec=OFF \
  -D CUDA_HOST_COMPILER="/c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe" \
  -D CUDA_CUDART_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudart_static.lib" \
  -D CMAKE_INSTALL_PREFIX="/c/ExternalPackages/OpenCV-3.4.7-t1-VC15" \
  -D WITH_OPENGL=ON \
  -D WITH_CUDA=ON \
  -D CUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" \
  -D WITH_CUBLAS=ON \
  -D CUDA_GENERATION=Pascal \
  -D CUDA_NVCC_FLAGS="--default-stream per-thread" \
  -D CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
  ../../opencv
```

Here's the output:

[CmakeOutput.txt](https://github.com/opencv/opencv_contrib/files/3774003/CmakeOutput.txt)

May attempted build was generated using:

```
cmake --build . --config Release --target INSTALL 2>&1 | tee BuildLogRelease.txt
```

Here's a log of the build:

[BuildLogRelease.txt](https://github.com/opencv/opencv_contrib/files/3774042/BuildLogRelease.txt)

**Comment by alalek** [comment]
@pstieber Thank you for build logs!

Looks like mentioned compiler version can't handle AVX512 code properly.

Did you try to build it without CUDA?

Try this workaround with disabling AVX512 `cmake -DCPU_AVX512_SKX_SUPPORTED=OFF ...`

Or try to upgrade MSVS compiler (mentioned version had been released in 2017).

**Comment by pstieber** [comment]
I'm trying your `-DCPU_AVX512_SKX_SUPPORTED=OFF` workaround as I write this.

I work for a company that has a many simultaneous projects that all attempt to use the same code base.  This requires many (over 30) "external projects" like OpenCV.  As you can imagine, building these on Windows (we also have all of our codes working on Linux, CentOS and Ubuntu and a limited set working in an NVIDIA Tegra X2) is a challenge. Upgrading the compiler translates into building all of the external projects using the new compiler and that simply isn't an option for me at the moment due to time constraints.

I'll add a comment to this issue w.r.t. to success or failure of your workaround.

Thanks!

**Comment by pstieber** [comment]
This appears to work.  Here's my modified cmake command:

```
cmake \
  -Wno-dev \
  -G "Visual Studio 15 2017 Win64" \
  -D CPU_AVX512_SKX_SUPPORTED=OFF \
  -D BUILD_opencv_python2=OFF \
  -D BUILD_opencv_python3=OFF \
  -D BUILD_DOCS=OFF \
  -D BUILD_EXAMPLES=OFF \
  -D BUILD_PERF_TESTS=OFF \
  -D BUILD_TESTS=OFF \
  -D BUILD_SHARED_LIBS=OFF \
  -D BUILD_WITH_STATIC_CRT=OFF \
  -D BUILD_opencv_matlab=OFF \
  -D BUILD_opencv_cudacodec=OFF \
  -D CUDA_HOST_COMPILER="/c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe" \
  -D CUDA_CUDART_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudart_static.lib" \
  -D CMAKE_INSTALL_PREFIX="/c/ExternalPackages/OpenCV-3.4.7-t1-VC15" \
  -D WITH_OPENGL=ON \
  -D WITH_CUDA=ON \
  -D CUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" \
  -D WITH_CUBLAS=ON \
  -D CUDA_GENERATION=Pascal \
  -D CUDA_NVCC_FLAGS="--default-stream per-thread" \
  -D CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
  ../../opencv
```

The corresponding output:

[CmakeOutput.txt](https://github.com/opencv/opencv_contrib/files/3775179/CmakeOutput.txt)

And the result of running

```
cmake --build . --config Release --target INSTALL 2>&1 | tee BuildLogRelease.txt
```

Note the many restarts of cmake due to dependency file / file updates:

[BuildLogRelease.txt](https://github.com/opencv/opencv_contrib/files/3775181/BuildLogRelease.txt)

**Comment by pstieber** [comment]
Looks like VS attempted to support AVX-512 in version 15.3

https://devblogs.microsoft.com/cppblog/microsoft-visual-studio-2017-supports-intel-avx-512/

but fouled it up and it isn't properly implemented until version 15.7 and works properly with 15.8 and 15.9 as well.

https://developercommunity.visualstudio.com/content/problem/107204/msvc-fails-to-use-all-32-avx512-registers.html

**Comment by alalek** [comment]
Thank you for investigation!

BTW, to apply "workaround" automatically (disable AVX512 on unsupported configuration) we may add extra simple check into this file: https://github.com/opencv/opencv/blob/3.4/cmake/checks/cpu_avx512.cpp ?

(I don't have MSVS 2017 15.4 installation, so I can't test that)

**Comment by pstieber** [comment]
I could try this for you. Do I just need to attempt a build of the current 3.4 branch with my cmake flags?
