### ISSUE TITLE
A useful app to generate ArucoMarker, Chessboard and ChArUco vector graphic file for print it out

### ISSUE THREAD

**Issue by dogod621** [opencv/opencv_contrib#2249]
Hi, since I am suffering from not able to generate printable marker file,
(Although official doc provide gen_pattern.py tool, but it is not support ArucoMarker and  ChArUco )

so I write a small app to solve the problem.
https://github.com/dogod621/OpenCVMarkerPrinter

if it is valuable to put in doc tool( like gen_pattern.py), just take it. :)

**Comment by alalek** [comment]
Nice tool!

You can contribute helper scripts/tool into `<opencv_contrib>/modules/aruco/misc` directory (under BSD license) and put link somewhere in OpenCV documentation.
