### ISSUE TITLE
The implementation of niBlackThreshold is not consistent with the description of the paper

### ISSUE THREAD

**Issue by Chen-JQ** [opencv/opencv_contrib#2259]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

According to the paper[0], this code is wrong.

opencv_contrib/modules/ximgproc/src/niblack_thresholding.cpp: line 89
 ```.cpp
      case BINARIZATION_NICK:
		sqrt(variance + sqmean, sqrtVarianceMeanSum);
		thresh = mean + static_cast<float>(k) * sqrtVarianceMeanSum;
		break;
```
should be 
 ```.cpp
      case BINARIZATION_NICK:
		sqrt(sqmean, sqrtVarianceMeanSum);
		thresh = mean + static_cast<float>(k) * sqrtVarianceMeanSum;
		break;
```

[0] Khurram Khurshid, Imran Siddiqi, Claudie Faure, and Nicole Vincent. Comparison of niblack inspired binarization methods for ancient documents. In IS&T/SPIE Electronic Imaging, pages 72470U–72470U. International Society for Optics and Photonics, 2009.

**Comment by saskatchewancatch** [comment]
Thank you for reviewing the code.

What is implemented for `BINARIZATION_NICK` is equation 3 from that paper.

Equation 3 is the paper's approximation for the threshold of their technique:
T ≈ mean + k * sqrt(_B_+ mean^2)

The constant B in equation 3 is the variance (square of the standard deviation). _B_ is used in their exposition of the Niblack technique (see equation 1).
T ≈ mean + k * sqrt(variance + mean^2)

Thus `BINARIZATION_NICK` was implemented as such:
   	sqrt(variance + sqmean, sqrtVarianceMeanSum);
   	thresh = mean + static_cast<float>(k) * sqrtVarianceMeanSum;

The approximation is reasonable for "large" images, although it's what's commonly passed as the "Nick binarization" technique

**Comment by Chen-JQ** [comment]
Thank you for explaining the code.
According to Equation 1 and Equation 3：
B = variance = sqmean - mean^2
A = B + mean^2 = sqmean - mean^2 + mean^2 = sqmean
Thus BINARIZATION_NICK should be implemented as such:
sqrt(variance, sqrtVarianceMeanSum);
thresh = mean + static_cast(k) * sqrtVarianceMeanSum;

**Comment by saskatchewancatch** [comment]
@Chen-JQ 

I reviewed the implementation again, and I believe _you are totally correct_.

T **≈** mean + k * sqrt(variance + mean^2) **≈** mean + k * sqrt(sqmean - mean^2 + mean^2) **≈** mean + k * sqrt(sqmean)

```
     case BINARIZATION_NICK:
   	sqrt(sqmean, sqrtVarianceMeanSum);
   	thresh = mean + static_cast<float>(k) * sqrtVarianceMeanSum;
   	break;
```

`sqrtVarianceMeanSum` needs to be a better variable name too.

Thank you for reviewing this and finding it out!

**Comment by saskatchewancatch** [comment]
@Chen-JQ It would be beneficial if the whole binarization module got a review as it hasn't been reviewed. 

If you're interested, reviewing the other binarization method implementations would be a great service to OpenCV's thresholding implementations.

**Comment by Chen-JQ** [comment]
@saskatchewancatch Thank you for your approval. Glad to discuss with you.

**Comment by saskatchewancatch** [comment]
@Chen-JQ Please feel free to correct the implementation via a PR.
