### ISSUE TITLE
Not able to access enum NVIDIA_OF_PERF_PRESET in python

### ISSUE THREAD

**Issue by iamvishal** [opencv/opencv_contrib#2265]
Hi

I am writing a sample app which uses nvidia optical flow algorithm. But here i am not able to access enum NVIDIA_OF_PERF_PRESET in python. 
i see this 
typedef cv::cuda::NvidiaOpticalFlow_1_0::NVIDIA_OF_PERF_LEVEL cuda_NvidiaOpticalFlow_1_0_NVIDIA_OF_PERF_LEVEL;
CV_PY_FROM_ENUM(cuda_NvidiaOpticalFlow_1_0_NVIDIA_OF_PERF_LEVEL);
CV_PY_TO_ENUM(cuda_NvidiaOpticalFlow_1_0_NVIDIA_OF_PERF_LEVEL);
 in  pyopencv_generated_enums.h

but i am not able to access it as cv2.cuda_NvidiaOpticalFlow_1_0_NVIDIA_OF_PERF_LEVEL.

perf = cv2.cuda_NvidiaOpticalFlow_1_0_NVIDIA_OF_PERF_LEVEL.NV_OF_PERF_SLOW
AttributeError: module 'cv2' has no attribute 'cuda_NvidiaOpticalFlow_1_0_NVIDIA_OF_PERF_LEVEL'

**Comment by cudawarped** [comment]
@iamvishal 
It is available under `cv.cuda.` as 
`cv.cuda.NVIDIA_OPTICAL_FLOW_1_0_NV_OF_PERF_LEVEL_SLOW`
