### ISSUE TITLE
detect fail with "singelmarkersoriginal.png" 

### ISSUE THREAD

**Issue by bingyingL** [opencv/opencv_contrib#2266]
#### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu16.04  64Bit
- Compiler => GCC

##### Detailed description

detect ArUco marker fail with image of ["singelmarkersoriginal.png"](https://github.com/opencv/opencv_contrib/blob/4.1.1/modules/aruco/tutorials/aruco_detection/images/singlemarkersoriginal.png) in use case, find nothing using default parameters 

##### Steps to reproduce

 ```.cpp
cv::Mat inputImage = imread("./singlemarkersoriginal.png");
cv::Ptr<cv::aruco::DetectorParameters> parameters=cv::aruco::DetectorParameters::create();
std::vector<int> ids;
std::vector<std::vector<cv::Point2f> > corners, rejectedCandidates;   
 cv::Ptr<cv::aruco::Dictionary> dictionary= cv::aruco::getPredefinedDictionary(cv::aruco::DICT_6X6_250);
cv::aruco::detectMarkers(inputImage, dictionary, corners, ids, parameters, rejectedCandidates);
```

**Comment by AleksandrPanov** [comment]
Now detect ArUco marker for [singlemarkersoriginal.jpg](https://docs.opencv.org/4.x/singlemarkersoriginal.jpg) works correctly, test to check this [was added](https://github.com/opencv/opencv_contrib/blob/56d492cfecb7aadaca79a9494a33ad1c12798e5e/modules/aruco/test/test_arucodetection.cpp#L557).
Use the latest version of OpenCV.
