### ISSUE TITLE
No constructor of RgbdPlane in rgbd/depth.hpp and corresponding create() function

### ISSUE THREAD

**Issue by Takugo** [opencv/opencv_contrib#2277]
Bug report:
There is no any constructor and destructor of a plane-finding method named RgbdPlane in rgbd/depth.hpp and its  create() function...

I think that the constructor should be similar to codes below:
```
    RgbdNormals(int rows, int cols, int depth, InputArray K, int window_size = 5, int method =
        RgbdNormals::RGBD_NORMALS_METHOD_FALS);

    ~RgbdNormals();

    CV_WRAP static Ptr<RgbdNormals> create(int rows, int cols, int depth, InputArray K, int window_size = 5, int method =
        RgbdNormals::RGBD_NORMALS_METHOD_FALS);
```

When I tried using RgbdPlane to find a plane on a depth image(or 3d points), but compiler told me that there was no object of RgbdPlane found.
And I coded like this, but it's not working:
`rgbd_plane = cv.rgbd.RgbdPlane_create()`

So, does this constructor missing in version 4.1.1?

**Comment by czgdp1807** [comment]
It looks like the issue is still unresolved, 
```python
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> rgbd_plane = cv2.rgbd.RgbdPlane_create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2.rgbd' has no attribute 'RgbdPlane_create'
```
@Takugo Can I work on this, if you haven't submitted a PR for it?

**Comment by czgdp1807** [comment]
ping @alalek Can I work on this? AFAICT, the issue is still unresolved. I used `cv2` from inside the `python_loader`, after building, so probably the above code works on latest opencv master.

**Comment by Takugo** [comment]
@czgdp1807 Sure. You could work on it. I haven't submitted a PR into branch.  Thanks to your reply.
