### ISSUE TITLE
libopencv_sfm.so build error

### ISSUE THREAD

**Issue by huyaoyu** [opencv/opencv_contrib#2299]
#### System information (version)

- OpenCV 4.1.2-dev (master cc9b199e), OpenCV-contrib 4.1.2-dev (master 82f3da5e)
- Operating System / Platform Ubuntu 18.04 LTS
- Compiler
$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

$ cmake --version
cmake version 3.15.3

##### Detailed description

Failed to link libopencv_sfm.so.

=== Error message. ===
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
modules/sfm/CMakeFiles/opencv_sfm.dir/build.make:247: recipe for target 'lib/libopencv_sfm.so.4.1.2' failed
make[2]: *** [lib/libopencv_sfm.so.4.1.2] Error 1
CMakeFiles/Makefile2:6611: recipe for target 'modules/sfm/CMakeFiles/opencv_sfm.dir/all' failed
make[1]: *** [modules/sfm/CMakeFiles/opencv_sfm.dir/all] Error 2
=== End of message. ===

##### Steps to reproduce

cmake \
 -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib/modules dir> \
 -DCMAKE_BUILD_TYPE=Release \
 -DEIGEN_INCLUDE_PATH=/usr/local/include/eigen3 \
 -DEigen3_DIR=/usr/local/share/eigen3/cmake \
 -DCUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs/libcuda.so \
 -DCUDA_NVCC_FLAGS=--expt-relaxed-constexpr \
 -DWITH_CUDA=ON \
 -DENABLE_FAST_MATH=1 \
 -DCUDA_FAST_MATH=1 \
 -DWITH_CUBLAS=1 \
 -DINSTALL_PYTHON_EXAMPLES=OFF \
 -DINSTALL_C_EXAMPLES=OFF \
 -DBUILD_EXAMPLES=OFF \
 -DBUILD_TESTS=OFF \
 -DBUILD_opencv_python_tests=OFF \
 -DOPENCV_ENABLE_NONFREE=ON \
 -DWITH_TBB=ON \
 -DCMAKE_INSTALL_PREFIX=/home/yaoyu/Libraries/OpenCV/opencv_install_412 \
 -DOPENCV_PYTHON3_VERSION=3.6 \
 -DPYTHON3_EXECUTABLE=/home/yaoyu/p3pt/bin/python \
 -DPYTHON3_INCLUDE_DIR=/home/yaoyu/p3pt/include/python3.6m \
 -DPYTHON3_LIBRARY=/home/yaoyu/p3pt/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so \
 -DPYTHON3_NUMPY_INCLUDE_DIRS=/home/yaoyu/p3pt/lib/python3.6/site-packages/numpy/core/include \
 -DPYTHON3_PACKAGES_PATH=/home/yaoyu/p3pt/lib/python3.6/site-packages \
 -DBUILD_opencv_python3=ON -DBUILD_opencv_python2=OFF \
 -DENABLE_PIC=ON \
 -DBUILD_SHARED_LIBS=ON \
 <opencv source code dir>

Where /home/yaoyu/p3pt is the root directory of a python virtualenv with python3.6. This cmake configuration gives no error during compile before I install Ceres and the dependencies of Ceres. After Ceres installation, the sfm module also has fulfilled dependencies and becomes ready to be compiled. Then the compilation with sfm failed. I tried to specify modules by -DBUILD_LIST argument when invoking cmake, only ruling out sfm module, however, the opencv_python3 target still reports an error complaining that sfm's header file could not be found.

The cmake output is [CMakeLog.log](https://github.com/opencv/opencv_contrib/files/3732375/CMakeLog.log)

======

After removing one of the dependencies of Ceres, e.g., gflags, from Uubntu18, sfm module will not be compiled. No error is issued during the compilation. opencv_python3 could be installed to the virtualenv properly.

**Comment by Zepyhrus** [comment]
changing gflags from 2.2.2 to 2.2.1 (build from source) solved the same problem for me, hope this helps.

**Comment by Frank-Dz** [comment]
I solve the problem by using cmake 3.9.2.
