### ISSUE TITLE
Error of disparity calculation using StereoBinarySGBM

### ISSUE THREAD

**Issue by hiroyuki0510** [opencv/opencv_contrib#2304]
System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Win 10, 64 bit

Detailed description
I am trying to compute the disparity from our captured images using cv::stereo::SteroBinarySGBM but it is not running fine. Then, I confirmed that our program can run using testdata (imL2.bmp and imL2l.bmp). I suspect that i failed to set parameters.

I set the same parameters referring to the following source code.
opencv_contrib/modules/stereo/samples/sample.cpp

Our images are 1600 x 1200 pixels, 8-bit.

**Comment by alalek** [comment]
Provide complete minimal reproducer (including input data) with actual (received) results.
