### ISSUE TITLE
Wrong definition of cv::viz::Color::navy()

### ISSUE THREAD

**Issue by ColasGael** [opencv/opencv_contrib#2321]
##### Detailed description

cv::viz::Color::navy() should be:
inline cv::viz::Color cv::viz::Color::navy()       { return Color(128,   0,   0); }

https://github.com/opencv/opencv_contrib/blob/4.1.2/modules/viz/include/opencv2/viz/types.hpp#L357

**Comment by alalek** [comment]
Nice catch!

> This class represents color in BGR order.
> inline cv::viz::Color cv::viz::Color::navy()       { return Color(0,     0, 128); }

---

Feel free to propose patch (PR) into Main "opencv" repo onto current maintenance 3.4 branch ([here](https://github.com/opencv/opencv/blob/3.4/modules/viz/include/opencv2/viz/types.hpp#L357)). We will merge these commits into opencv_contrib during regular "Merge 3.4" process.

**Comment by ColasGael** [comment]
Done here: https://github.com/opencv/opencv/pull/15821
