### ISSUE TITLE
Redundancies in the code

### ISSUE THREAD

**Issue by czgdp1807** [opencv/opencv_contrib#2322]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

This issue is associated with the code quality.
I observed some redundancies in [modules/face/src/face_alignmentimpl.hpp](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_alignmentimpl.hpp) and  [modules/face/src/face_utils.hpp](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_utils.hpp). I have described them below,

1. In [this line](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_alignmentimpl.hpp#L16) `using namespace std;` is used but still in the rest of the file, `std::` is written to specify the namespace. Probably, we can remove `using namespace std;`. 

2. Similarly, in [this line](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_utils.hpp#L10)  `using namespace cv;` is written and in the rest of the file, `cv::` is used to specify the namespace. 

Can I create a PR to resolve the above conflicts? Thanks.

**Comment by czgdp1807** [comment]
ping @alalek

**Comment by alalek** [comment]
You can try. CI would check proposed patch.

These lines are not visible to user (not part of public API), so impact should be low.

`using namespace cv;` => `namespace cv {`  (some symbols may be part of global symbols list anyway, like RTTI - so it is better avoid storing/implementing anything in global namespace)

BTW, It is better to avoid large changes in code which doesn't fix anything.

**Comment by czgdp1807** [comment]
Thanks for the response. I will make a PR to this repository, so that the `master` and `3.4` aren't affected due to my changes.
