### ISSUE TITLE
Copy paste error in CUDA PLK

### ISSUE THREAD

**Issue by llschloesser** [opencv/opencv_contrib#2323]
https://github.com/opencv/opencv_contrib/blob/7d7312a99a1508c0a53f4d27953076682c3fc4c5/modules/cudaoptflow/src/pyrlk.cpp#L336

Branch: master

The second condition should be `_nextImg.kind()` instead of `_prevImg.kind()`.

**Comment by alalek** [comment]
Nice catch!
Feel free to fix that in 3.4 branch of main "opencv" repository:
https://github.com/opencv/opencv/blob/3.4.8/modules/cudaoptflow/src/pyrlk.cpp#L336
(we will add commit into opencv_contrib during regular "Merge 3.4" process)

**Comment by asmorkalov** [comment]
Fixed
