### ISSUE TITLE
NvidiaOpticalFlowImpl::upSampler() should be public or free

### ISSUE THREAD

**Issue by llschloesser** [opencv/opencv_contrib#2325]
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Ubuntu 64 bit
- Compiler => GCC

##### Detailed description
The member function `NvidiaOpticalFlowImpl::upSampler()` is not accessible to the user. It simply resizes the flow image and scales the flow vectors. It does not need to be a member function and ought to be a free function that does something a little smarter such as edge-aware up-sampling.

##### Steps to reproduce
N/A

**Comment by czgdp1807** [comment]
Probably this has been fixed.

**Comment by llschloesser** [comment]
I agree, this can be closed.
