### ISSUE TITLE
Cannot open include file: 'opencv2/core/utils/tls.hpp'

### ISSUE THREAD

**Issue by developerNori** [opencv/opencv_contrib#2327]
Cannot open include file: 'opencv2/core/utils/tls.hpp

<a href="https://ibb.co/DkFZhZ8"><img src="https://i.ibb.co/ftWsfsn/Capture.png" alt="Capture" border="0"></a>

i use external modules in cmake and check none_free but i get this error

help me plz
i need xfeatures.lib

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.

**Comment by developerNori** [comment]
OK SURE 

How do I know which version of Opencv synchronized opencv_contrib  with which version?

**Comment by developerNori** [comment]
> You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
> Different versions are not tested for compatibility and may not work.
OK SURE

How do I know which version of Opencv synchronized opencv_contrib with which version?
