### ISSUE TITLE
several target in sfm modules links to target "glog::glog" but the target was not found.

### ISSUE THREAD

**Issue by makeecat** [opencv/opencv_contrib#2328]
#2213 ### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC 7.4

##### Detailed description

Used cmake-gui to generate Makefiles. 
Compiled successfully without BUILD_opencv_sfm. 

However, if I enable BUILD_opencv_sfm, I got the error as below
tryied installing glog using apt and compiling from source, got the same error.

Target "simple_pipeline" links to target "glog::glog" but the target was
not found. Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?

Full log

Detected processor: x86_64iles,  
Looking for ccache - found (/usr/bin/ccache)
libjpeg-turbo: VERSION = 2.0.2, BUILD = opencv-4.1.2-libjpeg-turbo
Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so
found Intel IPP (ICV version): 2019.0.0 [2019.0.0 Gold]
at: /home/yang/repo/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
found Intel IPP Integration Wrappers sources: 2019.0.0
at: /home/yang/repo/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
CUDA detected: 10.1
CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-D_FORCE_INLINES
LAPACK(MKL): LAPACK_LIBRARIES: /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_tbb_thread.so;/usr/lib/x86_64-linux-gnu/libtbb.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_tbb_thread.so;/usr/lib/x86_64-linux-gnu/libtbb.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_tbb_thread.so;/usr/lib/x86_64-linux-gnu/libtbb.so;/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so;-lpthread;-lm;-ldl
LAPACK(MKL): Support is enabled.
The imported target "vtkRenderingPythonTkWidgets" references the file
"/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist. Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
"/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

The imported target "vtk" references the file
"/usr/bin/vtk"
but this file does not exist. Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
"/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

Found VTK 6.3.0 (/usr/lib/cmake/vtk-6.3/UseVTK.cmake)
OpenCV Python: during development append to PYTHONPATH: /home/yang/repo/opencv/build/python_loader
Checking for module 'gstreamer-base-1.0'
No package 'gstreamer-base-1.0' found
Checking for module 'gstreamer-app-1.0'
No package 'gstreamer-app-1.0' found
Checking for module 'gstreamer-riff-1.0'
No package 'gstreamer-riff-1.0' found
Checking for module 'gstreamer-pbutils-1.0'
No package 'gstreamer-pbutils-1.0' found
Caffe: YES
Protobuf: NO
Glog: YES
freetype2: YES (ver 21.0.15)
harfbuzz: YES (ver 1.7.2)
HDF5: Using hdf5 compiler wrapper to determine C configuration
Module opencv_ovis disabled because OGRE3D was not found
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
Detected gflags version: 2.2.1
Found installed version of Eigen: /usr/lib/cmake/eigen3
Found required Ceres dependency: Eigen version 3.3.4 in /usr/include/eigen3
Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
Found required Ceres dependency: glog
Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
Detected gflags version: 2.2.1
Found required Ceres dependency: gflags
Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
Checking SFM deps... TRUE
Checking for module 'tesseract'
No package 'tesseract' found
Tesseract: NO
HDF5: Using hdf5 compiler wrapper to determine C configuration
Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': /home/yang/repo/opencv/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
Caffe: YES
Protobuf: NO
Glog: YES
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
Detected gflags version: 2.2.1
Found installed version of Eigen: /usr/lib/cmake/eigen3
Found required Ceres dependency: Eigen version 3.3.4 in /usr/include/eigen3
Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
Found required Ceres dependency: glog
Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
Detected gflags version: 2.2.1
Found required Ceres dependency: gflags
Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
Checking SFM deps... TRUE
OpenCL samples are skipped: OpenCL SDK is required
Pylint: registered 163 targets. Build 'check_pylint' target to run checks ("cmake --build . --target check_pylint" or "make check_pylint")

General configuration for OpenCV 4.1.2 =====================================
Version control: 4.1.2

Extra modules:
Location (extra): /home/yang/repo/opencv_contrib/modules
Version control (extra): 4.1.2

Platform:
Timestamp: 2019-11-02T20:07:53Z
Host: Linux 5.2.2-050202-generic x86_64
CMake: 3.10.2
CMake generator: Unix Makefiles
CMake build tool: /usr/bin/make
Configuration: Release

CPU/HW features:
Baseline: SSE SSE2 SSE3
requested: SSE3
Dispatched code generation: SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
requested: SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
SSE4_1 (16 files): + SSSE3 SSE4_1
SSE4_2 (2 files): + SSSE3 SSE4_1 POPCNT SSE4_2
FP16 (1 files): + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
AVX (5 files): + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
AVX2 (29 files): + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
AVX512_SKX (6 files): + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

C/C++:
Built as dynamic libs?: YES
C++ Compiler: /usr/bin/c++ (ver 7.4.0)
C++ flags (Release): -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -O3 -DNDEBUG -DNDEBUG
C++ flags (Debug): -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -g -O0 -DDEBUG -D_DEBUG
C Compiler: /usr/bin/cc
C flags (Release): -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -msse -msse2 -msse3 -fvisibility=hidden -fopenmp -O3 -DNDEBUG -DNDEBUG
C flags (Debug): -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -msse -msse2 -msse3 -fvisibility=hidden -fopenmp -g -O0 -DDEBUG -D_DEBUG
Linker flags (Release):
Linker flags (Debug):
ccache: YES
Precompiled headers: NO
Extra dependencies: /usr/lib/x86_64-linux-gnu/libcaffe.so /usr/lib/x86_64-linux-gnu/libglog.so m pthread cudart_static dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu
3rdparty dependencies:

OpenCV modules:
To be built: aruco bgsegm bioinspired calib3d ccalib cnn_3dobj core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python2 python3 quality reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab viz xfeatures2d ximgproc xobjdetect xphoto
Disabled: world
Disabled by dependency: -
Unavailable: cvv java js matlab ovis
Applications: tests perf_tests examples apps
Documentation: doxygen python
Non-free algorithms: NO

GUI:
GTK+: YES (ver 3.22.30)
GThread : YES (ver 2.56.4)
GtkGlExt: NO
OpenGL support: NO
VTK support: YES (ver 6.3.0)

Media I/O:
ZLib: /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
JPEG: build-libjpeg-turbo (ver 2.0.2-62)
WEBP: /usr/lib/x86_64-linux-gnu/libwebp.so (ver encoder: 0x020e)
PNG: build (ver 1.6.37)
TIFF: build (ver 42 - 4.0.10)
JPEG 2000: build (ver 1.900.1)
OpenEXR: /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2.2.0)
HDR: YES
SUNRASTER: YES
PXM: YES
PFM: YES

Video I/O:
DC1394: YES (2.2.5)
FFMPEG: YES
avcodec: YES (57.107.100)
avformat: YES (57.83.100)
avutil: YES (55.78.100)
swscale: YES (4.8.100)
avresample: YES (3.7.0)
GStreamer: NO
OpenNI2: YES (2.2.0)
v4l/v4l2: YES (linux/videodev2.h)

Parallel framework: TBB (ver 2019.0 interface 11008)

Trace: YES (with Intel ITT)

Other third-party libraries:
Intel IPP: 2019.0.0 Gold [2019.0.0]
at: /home/yang/repo/opencv/build/3rdparty/ippicv/ippicv_lnx/icv
Intel IPP IW: sources (2019.0.0)
at: /home/yang/repo/opencv/build/3rdparty/ippicv/ippicv_lnx/iw
Lapack: YES (/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_tbb_thread.so /usr/lib/x86_64-linux-gnu/libtbb.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_tbb_thread.so /usr/lib/x86_64-linux-gnu/libtbb.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_lp64.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_tbb_thread.so /usr/lib/x86_64-linux-gnu/libtbb.so /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so -lpthread -lm -ldl)
Eigen: YES (ver 3.3.4)
Custom HAL: NO
Protobuf: build (3.5.1)

NVIDIA CUDA: YES (ver 10.1, CUFFT CUBLAS)
NVIDIA GPU arch: 30 35 37 50 52 60 61 70 75
NVIDIA PTX archs:

cuDNN: YES (ver 7.6.3)

OpenCL: YES (SVM)
Include path: /home/yang/repo/opencv/3rdparty/include/opencl/1.2
Link libraries: Dynamic load

Python 2:
Interpreter: /usr/bin/python2.7 (ver 2.7.15)
Libraries: /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.15+)
numpy: /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.13.3)
install path: lib/python2.7/dist-packages/cv2/python-2.7

Python 3:
Interpreter: /usr/bin/python3 (ver 3.6.8)
Libraries: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.8)
numpy: /usr/lib/python3/dist-packages/numpy/core/include (ver 1.13.3)
install path: lib/python3.6/dist-packages/cv2/python-3.6

Python (for build): /usr/bin/python2.7
Pylint: /home/yang/.local/bin/pylint (ver: 3.6.8, checks: 163)

Java:
ant: NO
JNI: /usr/lib/jvm/java-8-openjdk-amd64/include /usr/lib/jvm/java-8-openjdk-amd64/include/linux /usr/lib/jvm/java-8-openjdk-amd64/include
Java wrappers: NO
Java tests: NO

Install to: /usr/local
-----------------------------------------------------------------

Configuring done
**CMake Error at /home/yang/repo/opencv/cmake/OpenCVUtils.cmake:1468 (add_library):
Target "opencv_sfm" links to target "glog::glog" but the target was not
found. Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing?**
Call Stack (most recent call first):
/home/yang/repo/opencv/cmake/OpenCVModule.cmake:930 (ocv_add_library)
/home/yang/repo/opencv/cmake/OpenCVModule.cmake:851 (_ocv_create_module)
/home/yang/repo/opencv_contrib/modules/sfm/CMakeLists.txt:118 (ocv_create_module)

**CMake Error at /home/yang/repo/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/CMakeLists.txt:18 (ADD_LIBRARY):
Target "simple_pipeline" links to target "glog::glog" but the target was
not found. Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?**

**CMake Error at /home/yang/repo/opencv/cmake/OpenCVUtils.cmake:1468 (add_library):
Target "opencv_sfm" links to target "glog::glog" but the target was not
found. Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing?**
Call Stack (most recent call first):
/home/yang/repo/opencv/cmake/OpenCVModule.cmake:930 (ocv_add_library)
/home/yang/repo/opencv/cmake/OpenCVModule.cmake:851 (_ocv_create_module)
/home/yang/repo/opencv_contrib/modules/sfm/CMakeLists.txt:118 (ocv_create_module)

**CMake Error at /home/yang/repo/opencv_contrib/modules/sfm/src/libmv_light/libmv/simple_pipeline/CMakeLists.txt:18 (ADD_LIBRARY):
Target "simple_pipeline" links to target "glog::glog" but the target was
not found. Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?**

CMake Warning at /home/yang/repo/opencv/cmake/OpenCVUtils.cmake:1468 (add_library):
Cannot generate a safe runtime search path for target opencv_sfm because
files in some directories may conflict with libraries in implicit
directories:

runtime library [libglog.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/usr/local/lib
runtime library [libtbbmalloc.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/opt/intel/tbb/lib/intel64/gcc4.4
runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/opt/intel/tbb/lib/intel64/gcc4.4

Some of these libraries may not be found correctly.
Call Stack (most recent call first):
/home/yang/repo/opencv/cmake/OpenCVModule.cmake:930 (ocv_add_library)
/home/yang/repo/opencv/cmake/OpenCVModule.cmake:851 (_ocv_create_module)
/home/yang/repo/opencv_contrib/modules/sfm/CMakeLists.txt:118 (ocv_create_module)

Generating done

**Comment by njanirudh** [comment]
Were you able to build the sfm module?

**Comment by makeecat** [comment]
> Were you able to build the sfm module?

No, I gave it up. Can you?

**Comment by alalek** [comment]
> runtime library [libglog.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/usr/local/lib

We really can't fix mess on your machine.

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
