### ISSUE TITLE
Make error about TSLData

### ISSUE THREAD

**Issue by EmiyaEstelle** [opencv/opencv_contrib#2337]
##### Detailed description
Hi. I want to install opencv_contrib in my Ubuntu 18.04. Before I have installed the opencv 3.4.8 successfully.
![Screenshot from 2019-11-08 14-27-18](https://user-images.githubusercontent.com/24841373/68454874-e0207580-0234-11ea-9743-9fcfc0c1a3b0.png)
I download the opencv_contrib 3.4.8 and put them together to make. It meet a problem you can 
see below:
![Screenshot from 2019-11-08 14-35-37](https://user-images.githubusercontent.com/24841373/68454945-1cec6c80-0235-11ea-93f4-f996fabe58b4.png)
I am sure that I downloaded the file from the github there and it is a compressed package which can not loss some thing. The process of cmake has no problem.
Should I change the source code of opencv_contrib? I have no idea about it. Could someone here help me? Thank you!

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.

**Comment by alalek** [comment]
In the future avoid posting text messages as screenshots - it is ridiculous and blocks search engines to find similar problems
