### ISSUE TITLE
Error occurs in the function cv::ppf_match_3d::ICP::registerModelToScene() of SurfaceMatching

### ISSUE THREAD

**Issue by WANGRRUIR** [opencv/opencv_contrib#2338]
- OpenCV => 4.1.1
- Operating System / Platform => ubuntu18.04
- Compiler => clion

##### Detailed description

when using the module of surfaceMatching,the function cv::ppf_match_3d::ICP::registerModelToScene(pc, pcTest, resultsSub) has an error,
the type of parameter pc,pcTest are Mat CV_32F,
the type of parameter resultSub is vector<cv::ppf_match_3d::Pose3DPtr>，

the error is:
          opencv2/flann.hpp:318: error: (-215:Assertion failed) dataset.type() == CvType<ElementType>::type() in function 'GenericIndex'.

CODE:
for example(for easy expression,the code has the same error of above):

try {
        float m2[4][6] = { { 1, 1,0,1,1,1 },{ 2 ,2, 0,1, 1,1 },{ 2, 1, 0 ,1,1 ,1 },{ 1 ,2,0 ,1,1,1 } };
        float m1[4][6] = { { 1,1,0,1,1,1 },{ 2 ,2 ,0,1 , 1, 1 },{ 2, 1,  0 , 1 ,1 ,1 },{ 1 ,2 ,0,1, 1, 1 } };
        Mat M1 = cv::Mat(4, 6, CV_32F, m1);
        Mat M2 = cv::Mat(4, 6, CV_32F, m2);
        double re;
        Matx44d pose1;

        vector<Pose3DPtr> resultsSub;
        cv::ppf_match_3d::ICP calculate(100, 0.005f, 2.5f, 8);
        calculate.registerModelToScene(M1, M2, re, pose1);

        //vector<cv::ppf_match_3d::Pose3DPtr> resultsSub;
        //calculate.registerModelToScene(pc, pcTest, resultsSub)

    }
    catch (cv::Exception ex) {
        std::cout << ex.msg << std::endl;
        std::getchar();
    }

**Comment by alalek** [comment]
Use English in Issues.
Provide complete minimal reproducer (including input data if necessary).
