### ISSUE TITLE
Error occurs in cv::ppf_match_3d::ICP::registerModelToScene() of SurfaceMatching.

### ISSUE THREAD

**Issue by WANGRRUIR** [opencv/opencv_contrib#2339]
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Ubunut 18.04
- Compiler => CLion

##### Detailed description

        when using the module of surfaceMatching,the function                 
    cv::ppf_match_3d::ICP::registerModelToScene(pc, pcTest, resultsSub) has an error,
    the type of parameter pc,pcTest are Mat CV_32F,
    the type of parameter resultSub is vectorcv::ppf_match_3d::Pose3DPtr，

    the error is:
        opencv2/flann.hpp:318: error: (-215:Assertion failed) dataset.type() == CvType::type() in 
    function 'GenericIndex'.

##### Steps to reproduce

    ```.cpp
    // C++ code
    int main(){
        try {
            float m2[4][6] = { { 1, 1,0,1,1,1 },{ 2 ,2, 0,1, 1,1 },{ 2, 1, 0 ,1,1 ,1 },{ 1 ,2,0 ,1,1,1 } };
            float m1[4][6] = { { 1,1,0,1,1,1 },{ 2 ,2 ,0,1 , 1, 1 },{ 2, 1, 0 , 1 ,1 ,1 },{ 1 ,2 ,0,1, 1, 1 } };
            Mat M1 = cv::Mat(4, 6, CV_32F, m1);
            Mat M2 = cv::Mat(4, 6, CV_32F, m2);
            double re;
            Matx44d pose1;
            vector<Pose3DPtr> resultsSub;
            cv::ppf_match_3d::ICP calculate(100, 0.005f, 2.5f, 8);
            calculate.registerModelToScene(M1, M2, re, pose1);
            
            //vector<cv::ppf_match_3d::Pose3DPtr> resultsSub;
            //calculate.registerModelToScene(pc, pcTest, resultsSub)
        }
        catch (cv::Exception ex) {
            std::cout << ex.msg << std::endl;
            std::getchar();
        }
        return 0;
    }
    ```

**Comment by czgdp1807** [comment]
@WANGRRUIR Can I work on this issue?

**Comment by czgdp1807** [comment]
In the latest `3.4` its reproducing the problem. I will try to investigate the cause. Thanks.

**Comment by czgdp1807** [comment]
I invested some time on it and observed that the issue is concerned with the creation of `Mat` objects. I fixed this issue and it started a chain reaction of bugs(all related to `Mat(pc.rows, 4, pc.type())`. Will try to fix the issue by day after tomorrow.
