### ISSUE TITLE
Missed TLSData::gather in sift.cpp

### ISSUE THREAD

**Issue by Nuzhny007** [opencv/opencv_contrib#2352]
### System information (version)
- OpenCV => 4.1.2-dev
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Compiler => g++ 7
-->

##### Detailed description

In sift.cpp used TLSData class. But missed:
1. #include <opencv2/core/utils/tls.hpp>
2. Missed TLSData::gather: tls_kpts_struct.gather(kpt_vecs); <--- error: ‘class cv::TLSData<std::vector<cv::KeyPoint> >’ has no member named ‘gather’; did you mean ‘getRef’?

##### Steps to reproduce

Compile opencv_contrib xfeatures2d with OPENCV_ENABLE_NONFREE=ON

What I can use instead TLSData::gather?

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.
