### ISSUE TITLE
l0smooth has an invalid argument name in Python

### ISSUE THREAD

**Issue by developedby** [opencv/opencv_contrib#2370]
##### System information (version)
- OpenCV => opencv-contrib-python 4.1.2
- Operating System / Platform => Windows 64 Bit

##### Detailed description

l0smooth has an argument called `lambda`. This should be avoided.  
Trying to call this function specifiying the `lambda` kwarg results in `SyntaxError: invalid syntax` because it already is a keyword in the Python language.  
In fact, I'm not even sure how this managed to exist in the first place, since trying to define a function with `lambda` as one of it's arguments also results in a Syntax Error.

Because I'm not sure what the proper fix to this problem should be (change the c++ function or maybe only the Python bindings), I'm not proposing a Pull Request to close this.

##### Steps to reproduce

    import cv2
    cv2.ximgproc.l0smooth(lambda=2.0)

**Comment by alalek** [comment]
Perhaps, bindings generator should rename parameters which have conflicts with reserved keywords:
- `lambda` => `lambda_`

**Comment by VadimLevin** [comment]
Fixed in [PR #20485](https://github.com/opencv/opencv/pull/20485)
