### ISSUE TITLE
detectorCNN.cpp——expected: 'x_min < x_max'

### ISSUE THREAD

**Issue by 1996leo** [opencv/opencv_contrib#2371]
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.1.1) Error: Unspecified error (>  (expected: 'x_min < x_max'), where
>     'x_min' is 0
> must be less than
>     'x_max' is 0
) in void __cdecl cv::text::TextDetectorCNNImpl::getOutputs(const float *,int,int,class std::vector<class cv::Rect_<int>,class std::allocator<class cv::Rect_<int> > > &,class std::vector<float,class std::allocator<float> > &,class cv::Size_<int>), file D:\opencv\opencv_contrib-4.1.1\opencv_contrib-4.1.1\modules\text\src\text_detectorCNN.cpp, line 38

**Comment by alalek** [comment]
Do not create new issues about the same problems: https://github.com/opencv/opencv_contrib/issues/2279#issuecomment-561007803

> 4.1.1

You are using outdated release.
Anyway, there is no release with fix yet (check timestamps of the fix and latest release tag).
