### ISSUE TITLE
Pose Estimation from fingertips to enable markerless AR interaction.

### ISSUE THREAD

**Issue by themechanicalcoder** [opencv/opencv_contrib#2391]
##### Detailed description
This is in reference to the issue  [1530](https://github.com/opencv/opencv_contrib/issues/1530) I am interested in working on this issue and implement pose estimation from fingertips to enable markerless AR interaction can I take this issue as no one is working on it.

**Comment by alalek** [comment]
Don't open duplicate issues about the same things.

Check license of the external code first. OpenCV is BSD licensed, so GPL-like code can't be accepted.
