### ISSUE TITLE
Customizing the CN Tracker example throws exception

### ISSUE THREAD

**Issue by nuwar** [opencv/opencv_contrib#2395]
##### System information (version)
- OpenCV => 3.4.4
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

##### Detailed description
On a new install of ubuntu 18.04 I attempted to run the tutorial
Customizing the CN Tracker
After compiling the code failed when run
Error message

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.4) /home/opencv/modules/core/src/arithm.cpp:685: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'arithm_op'

##### Steps to reproduce
copy code from 
https://docs.opencv.org/3.4.4/dc/db8/tutorial_customizing_cn_tracker.html
compile and run
g++ -ggdb my_tracker.cpp -o tracker `pkg-config --cflags --libs opencv`

./tracker /path_to_file

**Comment by berak** [comment]
the internal format of the hanning windows was [changed from CV_64F to CV_32F here](https://github.com/opencv/opencv_contrib/pull/1374) 
but the sample code was not adapted.
