### ISSUE TITLE
A bug of opencv4>=opencv4.1

### ISSUE THREAD

**Issue by WalkerGraceSep** [opencv/opencv_contrib#2402]
##### opencv4.1 with CUDA and NVCUVID,perhaps has  been deprecated,but it's still appear .
which in file:opencv_contrib-4.1.2/modules/cudacodec/src/precomp.hpp line84
 #include "../src/cap_ffmpeg_api.hpp"
but only older than opencv4.0.1 has this file
i copy this file from 4.0.1 but another error
home/xiaose/data/my/test/opencv_contrib-4.1.2/modules/cudacodec/src/ffmpeg_video_source.cpp:54:5: error: ‘Create_InputMediaStream_FFMPEG_Plugin’ does not name a type; did you mean ‘InputMediaStream_FFMPEG’?
     Create_InputMediaStream_FFMPEG_Plugin create_InputMediaStream_FFMPEG_p = 0;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     InputMediaStream_FFMPEG
/home/xiaose/data/my/test/opencv_contrib-4.1.2/modules/cudacodec/src/ffmpeg_video_source.cpp:55:5: error: ‘Release_InputMediaStream_FFMPEG_Plugin’ does not name a type; did you mean ‘InputMediaStream_FFMPEG’?
     Release_InputMediaStream_FFMPEG_Plugin release_InputMediaStream_FFMPEG_p = 0;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     InputMediaStream_FFMPEG
/home/xiaose/data/my/test/opencv_contrib-4.1.2/modules/cudacodec/src/ffmpeg_video_source.cpp:56:5: error: ‘Read_InputMediaStream_FFMPEG_Plugin’ does not name a type; did you mean ‘InputMediaStream_FFMPEG’?
     Read_InputMediaStream_FFMPEG_Plugin read_InputMediaStream_FFMPEG_p = 0;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     InputMediaStream_FFMPEG

**Comment by alalek** [comment]
Consider upgrading on OpenCV 4.2

**Comment by WalkerGraceSep** [comment]
thanks,i use opencv4.2 and build without threads,it works(i didn't test threads)
