### ISSUE TITLE
Kinect Fusion crash when cover sensor

### ISSUE THREAD

**Issue by timhutton** [opencv/opencv_contrib#2404]
##### System information (version)
- OpenCV => 4.1.2
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 2019
- Depth sensor => Azure Kinect

##### Detailed description
If you cover the sensor (to trigger a reset of the tracking) the rgbd/kinfu sample crashes.

This is unexpected behavior. Covering the sensor to reset the tracking is an established action, as seen in demos of KinectFusion elsewhere.

##### Steps to reproduce
- start the kinfu sample
- cover the sensor

The sample stops and prints the error:
```
[ERROR:0] global H:\OpenCV-4.1.2\sources\modules\core\src\ocl.cpp (3039)
cv::ocl::Kernel::set OpenCL: Kernel(fillPtsNrm)::set(arg_index=14, flags=260):
can't create cl_mem handle for passed UMat buffer (addr=0000004D17DAE480)
```

**Comment by savuor** [comment]
Reproduced and is going to be fixed soon.
It turned out that `getCloud()` lacks a check for empty data.
