### ISSUE TITLE
cv::cudacodec Enums give warning C26812

### ISSUE THREAD

**Issue by 06needhamt** [opencv/opencv_contrib#2411]
##### System information (version)

- OpenCV => 3.4.7
- Operating System / Platform => Windows 10 1909 (x64) Visual Studio 16.4.3
- Compiler => MSVCC & Cuda 10.1

##### Detailed description

Both the `cv::cudacodec::Codec` and `cv::cudacodec::ChromaFormat` Enums give warning C26812 

> Warning C26812 Prefer 'enum class' over 'enum' (Enum.3)

Which can lead to unintended implicit casting.

##### Steps to reproduce

    ```.cpp
      cv::Ptr<cv::cudacodec::VideoReader> decoder = 
      cv::cudacodec::createVideoReader(cv::String(inputFile));
    	cv::Ptr<cv::cudacodec::FormatInfo> formatInfo = &decoder->format();

		int inputWidth = formatInfo->width;
		int inputHeight = formatInfo->height;

		cv::cudacodec::Codec codec = formatInfo->codec; // WARNING C26812
		cv::cudacodec::ChromaFormat chroma = formatInfo->chromaFormat; // WARNING C26812
    ```

**Comment by alalek** [comment]
Add direct GitHub link on mentioned code.

> OpenCV => 3.4.7

You are using outdated version. Try fresh releases and/ot code from master/3.4 branches.
