### ISSUE TITLE
I think there is a bug in python binding cv::reg::Mappper

### ISSUE THREAD

**Issue by mastersg7** [opencv/opencv_contrib#2418]
##### System information (version)

- OpenCV => :4.1.2:
- Operating System / Platform => :Windows 64 Bit:
- Compiler => :Python:

##### Detailed description

The python code below should register an image. The code is based on the example code map_test.cpp found [here](https://github.com/opencv/opencv_contrib/blob/master/modules/reg/samples/map_test.cpp) and also seen below. However I cannot seem to find the equivalent for casting map_ptr (which is a reg_Map object) to a map projection. The cpp code uses a .get() function. Performing this step is relevant as the normalize function is a class member of cv2.reg_MapProjec. In the code below, when I try to cast mat_ptr to map_proj without using the get function, I get the error TypeError: Expected Ptr cv::UMat for argument '%s'. 

##### Steps to reproduce
Python code:

```
def calc_homography_pixel(img1, img2):

    mapper = cv2.reg_MapperGradProj()
    mapp_pyr = cv2.reg_MapperPyramid(mapper)
    map_ptr = mapp_pyr.calculate(img1, img2)

    map_proj = cv2.reg_MapProjec(map_ptr) # the issue is how to the map from the pyramid cal.
    map_proj = map_proj.normalize()

    dest = map_proj.inverseWarp(img2)
```
C++ code:
```
static void calcHomographyPixel(const Mat& img1, const Mat& img2)
{
    static const char* diffpixel = "Difference pixel registered";

    Ptr<MapperGradProj> mapper = makePtr<MapperGradProj>();
    MapperPyramid mappPyr(mapper);
    Ptr<Map> mapPtr = mappPyr.calculate(img1, img2);

    MapProjec* mapProj = dynamic_cast<MapProjec*>(mapPtr.get());
    mapProj->normalize();
    cout << "--- Pixel-based method\n" << Mat(mapProj->getProjTr()) << endl;

    Mat dest;
    mapProj->inverseWarp(img2, dest);
    showDifference(img1, dest, diffpixel);
}
```

**Comment by LaurentBerger** [comment]
I found in doc : 
`map_proj = cv.reg.MapTypeCaster_toProjec(map_ptr)`

**Comment by mastersg7** [comment]
Hi @LaurentBerger , nice find. Unfortunately, I dont really know what is going on there, because using the .normalize() after casting the map with MapTypeCaster_toProjec, I get a None.

**Comment by LaurentBerger** [comment]
there is no value return by normalize. normalise do work in place : 
```
import cv2 as cv

img1 = cv.imread("g:/lib/opencv/samples/data/lena.jpg")
img2 = cv.imread("g:/lib/opencv/samples/data/lena.jpg")
mapper = cv.reg_MapperGradProj()
mapp_pyr = cv.reg_MapperPyramid(mapper)
map_ptr = mapp_pyr.calculate(img, img)
map_proj = cv.reg.MapTypeCaster_toProjec(map_ptr)
map_proj.normalize()

dest = map_proj.inverseWarp(img2)
```

**Comment by mastersg7** [comment]
Yes, it works! Thanks!
