### ISSUE TITLE
Kinect Fusion and OpenCL fails on NVIDIA RTX 2060- clEnqueueNDRangeKernel (-5)

### ISSUE THREAD

**Issue by carlos-martinez** [opencv/opencv_contrib#2422]
Hi,

This is a follow-up of issue: https://github.com/opencv/opencv_contrib/issues/2029

I just wondering if this has been solved for NVIDIA cards. I am still having the same error mentioned before:

_OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clEnqueueNDRangeKernel('fillPtsNrm', dims=3, globalsize=512x512x512, localsize=8x8x16) sync=true_

I have:

- OpenCV 4.2 (debug)

- geForce RTX 2060 SUPER on a desktop. I update to the latest driver (44.219 - Studio Driver). The system had before Radeon Graphics card before

I used the code provided in thread. I tested the code "reproduce_kinfu_failures_V2.cpp", which I just modified to print the extra information about the GPU device. I am attaching the source and output logs.

Is there a solution besides disabling the optimization?

Thanks

PS ... I used tools (e.g. https://www.geeks3d.com/20200117/gpu-caps-viewer-1-44-0-released/) to verify that OpenCL was working in the GPU.

[reproduce_kinfu_failures_v2.zip](https://github.com/opencv/opencv_contrib/files/4168096/reproduce_kinfu_failures_v2.zip)

**Comment by carlos-martinez** [comment]
Hi,

Just to give more information, hoping this can help to figure it out what the issue is.

We got a brand new notebook with GeForce RTX2060. The error is the same as the desktop with the GeForce RTX206 SUPER. In this computer, we mainly installed:
o	PCL 10.0 (binary installation)
o	Build OpenCV 2.0 (release and contrib)
o	CMake 
o	VS 2019

The curious issue is that we have an “older” laptop with GeForce MX250 card. This computer does not present the problem.

Let me know if there is more information I can provide.

Thanks

**Comment by wanghuan10** [comment]
I find the same problem.

Kinect DK
OpenCV 4.1.2
RTX2070

OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clEnqueueNDRangeKernel('fillPtsNrm', dims=3, globalsize=512x512x512, localsize=8x8x16) sync=true

Thanks!!

**Comment by carlos-martinez** [comment]
Hi,

 I don’t know how generic my findings are,  but it seems that Kinfu algorithm does not work with the Nvidia architecture 7.5 (i.e. rtx 2060 and 2070). We have successfully run it on the Nvidia architecture 6.x (i.e. rtx 1060 and 1070).

I don’t have the background to evaluate if this is a easy fix or not, and even if the change is needed at the Kinfu algorithm  or OpenGL driver.

At least for now, we’ll just avoid that configuration.


Thanks

**Comment by wanghuan10** [comment]
Thanks for your information!!

**Comment by kyndred** [comment]
Can confirm same issue with Nvidia rtx 2080ti.

**Comment by yoyiji** [comment]
the same here.


Kinect DK
OpenCV 4.1.0(opencv_contrib-4.1.0)
VTK-8.2.0

win 10 pro
RTX 2080ti
intel xeon scalable 

OpenCL error CL_OUT_OF_RESOURCES (-5) during call: clEnqueueNDRangeKernel('fillPtsNrm', dims=3, globalsize=512x512x512, localsize=8x8x16) sync=true

any update?

**Comment by tkircher** [comment]
Is kinfu not supported anymore?

**Comment by savuor** [comment]
@tkircher it's supported but I have no mentioned hardware to reproduce and fix the issue

**Comment by kyndred** [comment]
If possible, I could run any test code on my end if you had some ideas.

**Comment by tkircher** [comment]
@savuor I'll see if I can narrow down the issue. Like several people above I'm using an RTX 2080 and getting the same error. I have access to an older workstation with a 1060 that may not have the error.

**Comment by carlos-martinez** [comment]
Hi all,

We have engaged the nVidia debugging team, and they found that this might be an app architecture limitation. They are asking if we can try a smaller work-group size of 512 or 256 to see if issue can be reproduce or not?

I do not have this hardware anymore, and I do not know of this test is just as easy as just changing the work-group size. 

Can someone test or share if this is something that can be changed?

Thanks

Carlos

**Comment by savuor** [comment]
@carlos-martinez Checking this can be as easy as to change work group size. This is also possible that some unnecessary optimizations are enabled or some checks missed (as it was in previous KinFu bugs).

**Comment by tkircher** [comment]
That fixed it! Setting the environment variable OPENCV_OPENCL_DEVICE_MAX_WORK_GROUP_SIZE to 512 gave good results on my RTX 2080.

**Comment by kyndred** [comment]
I changed line 1260 in ocl.cpp to be:

const size_t CV_OPENCL_DEVICE_MAX_WORK_GROUP_SIZE = 512;

and got it working as well.

Thank you!

**Comment by savuor** [comment]
Since the solution is so simple I think we need to fix the KinFu code the same way: limit `wgSize` to 512 no matter what `maxWorkGroupSize()` returns.
This can be reverted later in the future when we can rely on OpenCL's HW info.

**Comment by Craniumzzz** [comment]
Hi,
I just got a Kinect for Windows adapter to use my Xbox One Kinect with animation software, and I get "update configuration settings" error when I click "Run" on the Kinect Configuration Verifier in SDK Browser.
 I have an nvidia 2080ti on Windows 10. Could somebody please tell me how to do the above fix? I don't know anything about coding or where to find the file that needs to be changed.
Thanks

**Comment by rzofchak8** [comment]
> 
> 
> I changed line 1260 in ocl.cpp to be:
> 
> const size_t CV_OPENCL_DEVICE_MAX_WORK_GROUP_SIZE = 512;
> 
> and got it working as well.
> 
> Thank you!

Hi, I am also trying to get this to work...

Kinect DK
OpenCV 4.1.0 (with opencv_contrib-4.1.0)
VTK-8.2.0
GTX 1660S

Same error as above. Changing this line before building has not changed anything for me. Does anyone have any ideas of what direction I can go?

Thanks in advance

**Comment by katsh** [comment]
> @savuor I'll see if I can narrow down the issue. Like several people above I'm using an RTX 2080 and getting the same error. I have access to an older workstation with a 1060 that may not have the error.

Thanks! this workaround solved my same problem too.
