### ISSUE TITLE
Building project "opencv_rgbd" FAILED

### ISSUE THREAD

**Issue by excellentcx** [opencv/opencv_contrib#2423]
##### System information (version)

- OpenCV => 4.20
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- CUDA => 10.2
##### Detailed description

All other models except the rgbd model have been compiled.
following is the error message:
![image](https://user-images.githubusercontent.com/17928108/73993192-6d867980-498c-11ea-9b6e-603d22880278.png)

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
2>------ Build started: Project: opencv_rgbd, Configuration: Debug x64 ------
2>dynafu.cpp
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(242,28): warning C4244: '=': conversion from 'double' to '_Tp', possible loss of data
2>        with
2>        [
2>            _Tp=float
2>        ]
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(206): message : while compiling class template member function 'void cv::dynafu::DynaFuImpl<cv::Mat>::drawScene(cv::OutputArray,cv::OutputArray)'
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(524): message : see reference to function template instantiation 'void cv::dynafu::DynaFuImpl<cv::Mat>::drawScene(cv::OutputArray,cv::OutputArray)' being compiled
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(273): message : while compiling class template member function 'cv::dynafu::DynaFuImpl<cv::Mat>::~DynaFuImpl(void)'
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(289): message : see reference to class template instantiation 'cv::dynafu::DynaFuImpl<cv::Mat>' being compiled
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(181,5): error C3861: 'glGenRenderbuffersEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(169): message : while compiling class template member function 'cv::dynafu::DynaFuImpl<cv::Mat>::DynaFuImpl(const cv::dynafu::Params &)'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xmemory(204): message : see reference to function template instantiation 'cv::dynafu::DynaFuImpl<cv::Mat>::DynaFuImpl(const cv::dynafu::Params &)' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\memory(1491): message : see reference to function template instantiation 'void std::_Construct_in_place<_Ty,const cv::dynafu::Params&>(_Ty &,const cv::dynafu::Params &) noexcept(false)' being compiled
2>        with
2>        [
2>            _Ty=cv::dynafu::DynaFuImpl<cv::Mat>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\memory(1591): message : see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<const cv::dynafu::Params&>(const cv::dynafu::Params &)' being compiled
2>        with
2>        [
2>            _Ty=cv::dynafu::DynaFuImpl<cv::Mat>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\memory(1591): message : see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<const cv::dynafu::Params&>(const cv::dynafu::Params &)' being compiled
2>        with
2>        [
2>            _Ty=cv::dynafu::DynaFuImpl<cv::Mat>
2>        ]
2>E:\OpenCV4.2\SourceCode\opencv-4.2.0\modules\core\include\opencv2\core\cvstd_wrapper.hpp(146): message : see reference to function template instantiation 'std::shared_ptr<T> std::make_shared<_Tp,const _Ty&>(const _Ty &)' being compiled
2>        with
2>        [
2>            T=cv::dynafu::DynaFuImpl<cv::Mat>,
2>            _Tp=cv::dynafu::DynaFuImpl<cv::Mat>,
2>            _Ty=cv::dynafu::Params
2>        ]
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(544): message : see reference to function template instantiation 'cv::Ptr<cv::dynafu::DynaFuImpl<cv::Mat>> cv::makePtr<cv::dynafu::DynaFuImpl<cv::Mat>,_Ty>(const _Ty &)' being compiled
2>        with
2>        [
2>            _Ty=cv::dynafu::Params
2>        ]
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(182,27): error C2065: 'GL_RENDERBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(182,5): error C3861: 'glBindRenderbufferEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(183,30): error C2065: 'GL_RENDERBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(183,5): error C3861: 'glRenderbufferStorageEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(186,5): error C3861: 'glGenFramebuffersEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(187,26): error C2065: 'GL_FRAMEBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(187,5): error C3861: 'glBindFramebufferEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(189,34): error C2065: 'GL_FRAMEBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(189,54): error C2065: 'GL_DEPTH_ATTACHMENT_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(189,79): error C2065: 'GL_RENDERBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(189,5): error C3861: 'glFramebufferRenderbufferEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(193,5): error C3861: 'glGenRenderbuffersEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(194,27): error C2065: 'GL_RENDERBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(194,5): error C3861: 'glBindRenderbufferEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(195,30): error C2065: 'GL_RENDERBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(195,5): error C3861: 'glRenderbufferStorageEXT': identifier not found
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(197,34): error C2065: 'GL_FRAMEBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(197,54): error C2065: 'GL_COLOR_ATTACHMENT0_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(197,80): error C2065: 'GL_RENDERBUFFER_EXT': undeclared identifier
2>E:\OpenCV4.2\SourceCode\opencv_contrib-4.2.0\modules\rgbd\src\dynafu.cpp(197,5): error C3861: 'glFramebufferRenderbufferEXT': identifier not found
2>Done building project "opencv_rgbd.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 20 up-to-date, 0 skipped ==========

**Comment by LaurentBerger** [comment]
duplicate https://github.com/opencv/opencv_contrib/issues/2307

**Comment by ravikantbansal** [comment]
While trying to build openCV, faced below error in rgbd

PLease suggest might have went wrong

CMAKE Configuration
General configuration for OpenCV 4.5.1 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            C:/OpenCV/opencv_contrib-4.x/opencv_contrib-4.x/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2022-07-16T09:13:09Z
    Host:                        Windows 10.0.19043 AMD64
    CMake:                       3.19.3
    CMake generator:             Visual Studio 16 2019
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe
    MSVC:                        1929

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (17 files):         + SSSE3 SSE4_1
      SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (31 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (7 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe  (ver 19.29.30146.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:fast     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MD /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:fast     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:fast     /MP   /MD /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:fast     /MP /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          cudart_static.lib nppc.lib nppial.lib nppicc.lib nppicom.lib nppidei.lib nppif.lib nppig.lib nppim.lib nppist.lib nppisu.lib nppitc.lib npps.lib cublas.lib cudnn.lib cufft.lib -LIBPATH:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco barcode bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab wechat_qrcode world xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 alphamat cvv freetype hdf java julia matlab ovis python2 python2 sfm viz
    Applications:                tests perf_tests apps
    Documentation:               NO
    Non-free algorithms:         YES

  Windows RT support:            NO

  GUI: 
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.0.6-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.0.10)
    JPEG 2000:                   build (ver 2.3.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.91.100)
      avformat:                  YES (58.45.100)
      avutil:                    YES (56.51.100)
      swscale:                   YES (5.7.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   C:/OpenCV/Build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                C:/OpenCV/Build/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   YES (ver 10.1, CUFFT CUBLAS FAST_MATH)
    NVIDIA GPU arch:             75
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 7.6.5)

  OpenCL:                        YES (NVD3D11)
    Include path:                C:/OpenCV/opencv-4.5.1/opencv-4.5.1/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 C:/Users/SRI/anaconda3/python.exe (ver 3.9.12)
    Libraries:                   C:/Users/SRI/anaconda3/libs/python39.lib (ver 3.9.12)
    numpy:                       C:/Users/SRI/anaconda3/lib/site-packages/numpy/core/include (ver 1.23.1)
    install path:                C:/Users/SRI/anaconda3/Lib/site-packages/cv2/python-3.9

  Python (for build):            C:/Users/SRI/anaconda3/python.exe

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    C:/OpenCV/install
-----------------------------------------------------------------

Configuring done
Generating done


Error LOgs
-------------
nonrigid_icp.cpp
  normal.cpp
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(229,1): error C2296: '<<': illegal, le
ft operand has type 'const char [18]' [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(215): message : while compiling class
template member function 'bool cv::large_kinfu::LargeKinfuImpl<cv::Mat>::updateT(const MatType &)' [C:\OpenCV\Build\mod
ules\world\opencv_world.vcxproj]
          with
          [
              MatType=cv::Mat
          ]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(187): message : see reference to funct
ion template instantiation 'bool cv::large_kinfu::LargeKinfuImpl<cv::Mat>::updateT(const MatType &)' being compiled [C:
\OpenCV\Build\modules\world\opencv_world.vcxproj]
          with
          [
              MatType=cv::Mat
          ]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(179): message : see reference to class
 template instantiation 'cv::large_kinfu::LargeKinfuImpl<cv::Mat>' being compiled [C:\OpenCV\Build\modules\world\opencv
_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(229,5): error C3861: 'CV_LOG_INFO': id
entifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(236,1): error C2296: '<<': illegal, le
ft operand has type 'const char [22]' [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(236,9): error C3861: 'CV_LOG_INFO': id
entifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(253,13): error C3861: 'CV_LOG_INFO': i
dentifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(272,1): error C2296: '<<': illegal, le
ft operand has type 'const char [9]' [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(272,9): error C3861: 'CV_LOG_INFO': id
entifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(273,1): error C2296: '<<': illegal, le
ft operand has type 'const char [9]' [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(273,9): error C3861: 'CV_LOG_INFO': id
entifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(283,9): error C3861: 'CV_LOG_INFO': id
entifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(287,13): error C3861: 'CV_LOG_INFO': i
dentifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(294,1): error C2296: '<<': illegal, le
ft operand has type 'const char [20]' [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
C:\OpenCV\opencv_contrib-4.x\opencv_contrib-4.x\modules\rgbd\src\large_kinfu.cpp(294,5): error C3861: 'CV_LOG_INFO': id
entifier not found [C:\OpenCV\Build\modules\world\opencv_world.vcxproj]
  odometry.cpp
