### ISSUE TITLE
GMSMatcher Crashes in debug Mode (vector subscript out of range)

### ISSUE THREAD

**Issue by 0x23** [opencv/opencv_contrib#2437]
**Description:**
In '_modules/xfeatures2d/src/gms.cpp_' method `GMSMatcher::run` crashes in Line 373 in debug mode:

```
373: if (mCellPairs[mvMatchPairs[i].first] == mvMatchPairs[i].second)
374:                mvbInlierMask[i] = true;
```

This is because array `mCellPairs` is indexed with `mvMatchPairs[i].first` which sometimes has value -1. The Value -1 is written to `mCellPairs` in method `assignMatchPairs` line 170:

`int lgidx = mvMatchPairs[i].first = getGridIndexLeft(lp, gridType);`

were `getGridIndexLeft()` returns -1 if the feature point coordinates are close to the border. See Line 222:

```
222:    if (x >= mGridSizeLeft.width || y >= mGridSizeLeft.height)
223:        return -1;
```

**Suggested Fix:**

Add additional check for mvMatchPairs[i].first in Line 373:

```
373: if (mvMatchPairs[i].first>=0 && mCellPairs[mvMatchPairs[i].first] == mvMatchPairs[i].second)
374:                mvbInlierMask[i] = true;
```

**Comment by catree** [comment]
Can you add some reproducible code and data (e.g. two images saved in a lossless format as `png`)?

Also, you may want to report the bug in the [upstream repository](https://github.com/JiawangBian/GMS-Feature-Matcher).

**Comment by 0x23** [comment]
I dont have a stand alone exampe for bug reproduction at hand but I think this one can be checked by looking at the code only. I tried to explain the problem above

**Comment by alalek** [comment]
If this line is under test [coverage](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4-contrib_coverage-lin64-debug/20200222-075921_83/coverage_html/index.html), they you can try to create Pull Request with patch. CI run automatic tests on it.

**Comment by catree** [comment]
This has been fixed in the upstream repository, see [this comment](https://github.com/JiawangBian/GMS-Feature-Matcher/issues/34#issuecomment-592337470).

The code in the upstream repository: https://github.com/JiawangBian/GMS-Feature-Matcher/blob/d7e63bb3b1530a6cb183444a5eb27fb0894d0748/include/gms_matcher.h#L411

---

@0x23 

Can you open a pull request with the according change?
