### ISSUE TITLE
files boostdesc_binboost_064.i cannot be downloaded and MD5 not matched

### ISSUE THREAD

**Issue by Maverick-Y** [opencv/opencv_contrib#2450]
##### System information (version)
- OpenCV => 3.4.0
-OpenCV_contrib => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
-Cmake => 3.17.0

##### Detailed description

I'm using CMake to build opencv_contrib but I enconter a problem. I cannot download these files
boostdesc_binboost_064.i
boostdesc_binboost_128.i
boostdesc_binboost_256.i
boostdesc_lbgm.i

I tried to download them using Chrome and put them in the ..\modules\xfeatures2d\src, but when buding, CMake says the md5 mismatch and deleted that file and redownloads, and then timeout.

I've tried this download sourse 
https://answers.opencv.org/question/221324/a-problem-about-building-opencv4solved/
but the md5 still not matched and the file was deleted and redownloaded.

What should I do?

Here is part of the description of CMakeDownloadLog.txt 

do_copy "boostdesc_lbgm.i" "0ae0675534aa318d9668f2a179c2a052" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_lbgm.i" "E:/Open CV/3.4.0/my_opencv/downloads/xfeatures2d"
#missing "E:/Open CV/3.4.0/my_opencv/downloads/xfeatures2d/boostdesc_lbgm.i"
#check_md5 "E:/Open CV/3.4.0/opencv/sources/.cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i"
#mismatch_md5 "E:/Open CV/3.4.0/opencv/sources/.cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i" "d41d8cd98f00b204e9800998ecf8427e"
#delete "E:/Open CV/3.4.0/opencv/sources/.cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i"
#cmake_download "E:/Open CV/3.4.0/opencv/sources/.cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_lbgm.i"
# timeout on name lookup is not supported
#   Trying 151.101.228.133:443...
# TCP_NODELAY set
# connect to 151.101.228.133 port 443 failed: Connection refused
# Failed to connect to raw.githubusercontent.com port 443: Connection refused
# Closing connection 0

**Comment by alalek** [comment]
At first, we can't fix internet connection problem on your side.
You should properly configure proxy settings.

---

> 3.4.0

Outdated version (> 2 years).
Modern versions provides more reliable downloading process (with hijacking it) and more useful information.

**Comment by Maverick-Y** [comment]
> At first, we can't fix internet connection problem on your side.
> You should properly configure proxy settings.
> 
> > 3.4.0
> 
> Outdated version (> 2 years).
> Modern versions provides more reliable downloading process (with hijacking it) and more useful information.

I think you didn't understand me. Even I have copied the correct file (the MD5 code is exactly correct) the CMake still mismatch the file and redownload

**Comment by Maverick-Y** [comment]
I solved this problem by using the old version of CMake 3.14.0 
Maybe the lastest CMake is not competible with opencv 3.4.0
