### ISSUE TITLE
Adding colorchecker chart detector

### ISSUE THREAD

**Issue by AjitPant** [opencv/opencv_contrib#2455]
There are currently no color chart detector as mentioned in https://github.com/opencv/opencv/wiki/OE-30.-Color-Calibration. 

I would like to add a color chart detector (Not the calibration part, just the detector).
For this I would be implementing this paper: http://www.pe.org.pl/articles/2014/9/49.pdf 
The algorithm is not patented. Also I have taken authors permissions for this.

I am thinking of adding it to xobjdetect, is that the right place? 

To avoid any issues later on, I am looking for a maintainers approval before I start the work. Can I start?

**Comment by saskatchewancatch** [comment]
@AjitPant What about `xphoto` module? Possibly the API for the complete flow of finding a color chart down to doing colour correction could reside in a single module, in the same way that chessboard finding and camera calibration using chessboard images reside in the calib3d module. 

Just a thought. I don't work with color correction, but it imagine it falls within the domain of computational photography, for which the photo/xphoto modules exist.

**Comment by AjitPant** [comment]
@saskatchewancatch I don't think that an object detection algorithm would be a good fit for xphoto. On the other hand, adding the detector to a module where the calibrator will be added seems like a good idea. So I will try to add it to ccalib.
