### ISSUE TITLE
Using two seperate GSOC instances causes unexpected crash

### ISSUE THREAD

**Issue by aliufukyaman** [opencv/opencv_contrib#2472]
While experimenting with GSOC algorithm, I encountered a strange issue. As seen on code snipped below, application crashes with no error message if I use two GSOC instances and feed them consequtively. Windows pops and says "Python has stopped working" after the "apply()" method is called for second instance. I tried it with other BG algorithms like MOG, MOG2, KNN ect, they work well. 

Platform: Windows 10
IDE: Visual Studio Code
Language: Python 3.8.1
OpenCV version: 4.2.0

```
import cv2

cap = cv2.VideoCapture("E:/workplace/data/video/abandonedObject/video12.avi")
ret, orgFrame = cap.read()

bgModelShort = cv2.bgsegm.createBackgroundSubtractorGSOC(nSamples=5)
bgModelLong = cv2.bgsegm.createBackgroundSubtractorGSOC(nSamples=100)

while (1):
    retVal, frame = cap.read()
    if(not retVal):
        break

    cv2.imshow("frame", frame)

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    fgFrameShort = bgModelShort.apply(gray)
    fgFrameLong = bgModelLong.apply(gray)

    cv2.imshow("fgFrameShort", fgFrameShort)
    cv2.imshow("fgFrameLong", fgFrameLong)

    bgFrameShort = bgModelShort.getBackgroundImage()
    bgFrameLong = bgModelLong.getBackgroundImage()

    cv2.imshow("bgFrameShort", bgFrameShort)
    cv2.imshow("bgFrameLong", bgFrameLong)

    key = cv2.waitKey(1) & 0xff
    if key == 27:
        break
```

**Comment by berak** [comment]
i tried from c++, and got a few sporadic `bad alloc` exceptions (depending on what else is running).
it's quite a memory hog, i'd say.
