### ISSUE TITLE
How to build x64

### ISSUE THREAD

**Issue by aneira92** [opencv/opencv_contrib#2500]
following the instructions I can compile opencv_java430.dll only x32 and i need x64... how build to x64?

**Comment by alalek** [comment]
Please check CMake's manuals:
- `-G "Visual Studio 14"` - 32-bit
- `-G "Visual Studio 14 Win64"` - 64-bit
- or `-G "Visual Studio 16 2019" -A x64`

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
