### ISSUE TITLE
Error when i try to run mingw32-make on the build folder from cmake 

### ISSUE THREAD

**Issue by charlescookey** [opencv/opencv_contrib#2519]
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler =>CodeBlocks

##### Detailed description

has no member "mutex"

##### Steps to reproduce
After running cmake from opencv/source into my build folder
i went to the build folder in cmd then ran mingw32-make

`mingw32-make
[  2%] Built target zlib
[  6%] Built target libjpeg-turbo
[  8%] Built target libtiff
[ 16%] Built target libwebp
[ 18%] Built target libjasper
[ 19%] Built target libpng
[ 19%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfAttribute.cpp.obj
In file included from C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:44:0:
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:131:20: error: 'mutex' in namespace 'std' does not name a type
 using Mutex = std::mutex;
                    ^~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:138:17: error: 'Mutex' does not name a type
     Lock (const Mutex& m, bool autoLock = true):
                 ^~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:173:5: error: 'Mutex' does not name a type
     Mutex & _mutex;
     ^~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h: In constructor 'IlmThread_opencv::Lock::Lock(const int&, bool)':
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:139:9: error: class 'IlmThread_opencv::Lock' does not have any field named '_mutex'
         _mutex (const_cast<Mutex &>(m)), _locked (false)
         ^~~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:139:28: error: 'Mutex' does not name a type
         _mutex (const_cast<Mutex &>(m)), _locked (false)
                            ^~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:139:34: error: expected '>' before '&' token
         _mutex (const_cast<Mutex &>(m)), _locked (false)
                                  ^
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:139:34: error: expected '(' before '&' token
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:139:35: error: expected primary-expression before '>' token
         _mutex (const_cast<Mutex &>(m)), _locked (false)
                                   ^
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:139:56: error: expression cannot be used as a function
         _mutex (const_cast<Mutex &>(m)), _locked (false)
                                                        ^
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:146:5: error: expected '{' at end of input
     }
     ^
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h: In destructor 'IlmThread_opencv::Lock::~Lock()':
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:151:13: error: '_mutex' was not declared in this scope
             _mutex.unlock();
             ^~~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h: In member function 'void IlmThread_opencv::Lock::acquire()':
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:156:9: error: '_mutex' was not declared in this scope
         _mutex.lock();
         ^~~~~~
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h: In member function 'void IlmThread_opencv::Lock::release()':
C:/opencv/sources/3rdparty/openexr/IlmThread/IlmThreadMutex.h:162:9: error: '_mutex' was not declared in this scope
         _mutex.unlock();
         ^~~~~~
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp: At global scope:
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:54:28: error: 'IlmThread::Mutex' has not been declared
 using ILMTHREAD_NAMESPACE::Mutex;
                            ^~~~~
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:84:5: error: 'Mutex' does not name a type
     Mutex mutex;
     ^~~~~
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp: In static member function 'static bool Imf_opencv::Attribute::knownType(const char*)':
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:116:21: error: 'class Imf_opencv::{anonymous}::LockedTypeMap' has no member named 'mutex'
     Lock lock (tMap.mutex);
                     ^~~~~
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp: In static member function 'static void Imf_opencv::Attribute::registerAttributeType(const char*, Imf_opencv::Attribute* (*)())':
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:127:21: error: 'class Imf_opencv::{anonymous}::LockedTypeMap' has no member named 'mutex'
     Lock lock (tMap.mutex);
                     ^~~~~
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp: In static member function 'static void Imf_opencv::Attribute::unRegisterAttributeType(const char*)':
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:142:21: error: 'class Imf_opencv::{anonymous}::LockedTypeMap' has no member named 'mutex'
     Lock lock (tMap.mutex);
                     ^~~~~
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp: In static member function 'static Imf_opencv::Attribute* Imf_opencv::Attribute::newAttribute(const char*)':
C:\opencv\sources\3rdparty\openexr\IlmImf\ImfAttribute.cpp:152:21: error: 'class Imf_opencv::{anonymous}::LockedTypeMap' has no member named 'mutex'
     Lock lock (tMap.mutex);
                     ^~~~~
3rdparty\openexr\CMakeFiles\IlmImf.dir\build.make:138: recipe for target '3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfAttribute.cpp.obj' failed
mingw32-make[2]: *** [3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfAttribute.cpp.obj] Error 1
CMakeFiles\Makefile2:2209: recipe for target '3rdparty/openexr/CMakeFiles/IlmImf.dir/all' failed
mingw32-make[1]: *** [3rdparty/openexr/CMakeFiles/IlmImf.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
mingw32-make: *** [all] Error 2`

**Comment by SetUpSim** [comment]
Hey, how did solve that issue?
