### ISSUE TITLE
Error Building OpenCV js with Contrib modules

### ISSUE THREAD

**Issue by Petroochio** [opencv/opencv_contrib#2526]
Hello,

I'm trying to build OpenCV.js with the contrib modules, and it keeps erroring out when trying to import Aruco (which happens to be the module I need :cry: ).

#### System Information
- Operating System / Platform => Ubuntu 18.04.4 / 64 bit
- OpenCV Version => Freshly cloned 4.2

#### What I've done
I have followed the instructions [here](https://docs.opencv.org/3.4/d4/da1/tutorial_js_setup.html). Building without the contrib modules works fine. Then I cloned the opencv_contrib repo right next to the opencv core repo.

To get the modules added I've added `"-DOPENCV_EXTRA_MODULES_PATH=/home/peter/Documents/research/opencv_contrib/modules"` to the get_cmake_command array in `/opencv/platforms/js/build_js.py`. This gets most of the way then has an issue resolving the aruco namespace, here is a snippit of the console output

<pre>[100%] Built target opencv_objdetect
[100%] <font color="#8AE234"><b>Linking CXX static library ../../lib/libopencv_video.a</b></font>
cd /home/peter/Documents/research/opencv/build_js/modules/video &amp;&amp; /usr/bin/cmake -P CMakeFiles/opencv_video.dir/cmake_clean_target.cmake
cd /home/peter/Documents/research/opencv/build_js/modules/video &amp;&amp; /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_video.dir/link.txt --verbose=1
/home/peter/Documents/research/emsdk/upstream/emscripten/emar rc ../../lib/libopencv_video.a  @CMakeFiles/opencv_video.dir/objects1.rsp
make[3]: Leaving directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
[100%] Built target opencv_video
make -f modules/js/CMakeFiles/opencv_js.dir/build.make modules/js/CMakeFiles/opencv_js.dir/depend
make[3]: Entering directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
[100%] <font color="#729FCF"><b>Generating bindings.cpp</b></font>
cd /home/peter/Documents/research/opencv/build_js/modules/js &amp;&amp; /usr/bin/python2.7 /home/peter/Documents/research/opencv/modules/js/src/embindgen.py /home/peter/Documents/research/opencv/modules/js/../python/src2/hdr_parser.py /home/peter/Documents/research/opencv/build_js/modules/js/bindings.cpp /home/peter/Documents/research/opencv/build_js/modules/js/headers.txt /home/peter/Documents/research/opencv/modules/js/src/core_bindings.cpp
cd /home/peter/Documents/research/opencv/build_js &amp;&amp; /usr/bin/cmake -E cmake_depends &quot;Unix Makefiles&quot; /home/peter/Documents/research/opencv /home/peter/Documents/research/opencv/modules/js /home/peter/Documents/research/opencv/build_js /home/peter/Documents/research/opencv/build_js/modules/js /home/peter/Documents/research/opencv/build_js/modules/js/CMakeFiles/opencv_js.dir/DependInfo.cmake --color=
Dependee &quot;/home/peter/Documents/research/opencv/build_js/modules/js/CMakeFiles/opencv_js.dir/DependInfo.cmake&quot; is newer than depender &quot;/home/peter/Documents/research/opencv/build_js/modules/js/CMakeFiles/opencv_js.dir/depend.internal&quot;.
Dependee &quot;/home/peter/Documents/research/opencv/build_js/modules/js/CMakeFiles/CMakeDirectoryInformation.cmake&quot; is newer than depender &quot;/home/peter/Documents/research/opencv/build_js/modules/js/CMakeFiles/opencv_js.dir/depend.internal&quot;.
<font color="#AD7FA8"><b>Scanning dependencies of target opencv_js</b></font>
make[3]: Leaving directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
make -f modules/js/CMakeFiles/opencv_js.dir/build.make modules/js/CMakeFiles/opencv_js.dir/build
make[3]: Entering directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
[100%] <font color="#4E9A06">Building CXX object modules/js/CMakeFiles/opencv_js.dir/bindings.cpp.o</font>
cd /home/peter/Documents/research/opencv/build_js/modules/js &amp;&amp; /home/peter/Documents/research/emsdk/upstream/emscripten/em++  -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS @CMakeFiles/opencv_js.dir/includes_CXX.rsp -s USE_PTHREADS=0    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -O2  -DNDEBUG   -std=c++11  -Wno-missing-prototypes -std=c++11 -o CMakeFiles/opencv_js.dir/bindings.cpp.o -c /home/peter/Documents/research/opencv/build_js/modules/js/bindings.cpp
<b>/home/peter/Documents/research/opencv/build_js/modules/js/bindings.cpp:115:17: </b><font color="#EF2929"><b>error: </b></font><b>expected namespace name</b>
using namespace aruco;
<font color="#8AE234"><b>                ^</b></font>
1 error generated.
em++: <font color="#CC0000">error: </font>&apos;/home/peter/Documents/research/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=12 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/lib/libunwind/include -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/peter/.emscripten_cache/wasm/include -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/peter/Documents/research/opencv/build_js -I/home/peter/Documents/research/opencv/modules/js/include -I/home/peter/Documents/research/opencv/build_js/modules/js -I/home/peter/Documents/research/opencv/modules/core/include -I/home/peter/Documents/research/opencv/modules/flann/include -I/home/peter/Documents/research/opencv/modules/imgproc/include -I/home/peter/Documents/research/opencv/modules/photo/include -I/home/peter/Documents/research/opencv/modules/dnn/include -I/home/peter/Documents/research/opencv/modules/features2d/include -I/home/peter/Documents/research/opencv/modules/calib3d/include -I/home/peter/Documents/research/opencv/modules/objdetect/include -I/home/peter/Documents/research/opencv/modules/video/include -I/home/peter/Documents/research/emsdk/upstream/emscripten/system/include -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -Qunused-arguments -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -O2 -DNDEBUG -std=c++11 -Wno-missing-prototypes -std=c++11 -c -DEMSCRIPTEN -fignore-exceptions /home/peter/Documents/research/opencv/build_js/modules/js/bindings.cpp -Xclang -isystem/home/peter/Documents/research/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/opencv_js.dir/bindings.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr&apos; failed (1)
modules/js/CMakeFiles/opencv_js.dir/build.make:135: recipe for target &apos;modules/js/CMakeFiles/opencv_js.dir/bindings.cpp.o&apos; failed
make[3]: *** [modules/js/CMakeFiles/opencv_js.dir/bindings.cpp.o] Error 1
make[3]: Leaving directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
CMakeFiles/Makefile2:4021: recipe for target &apos;modules/js/CMakeFiles/opencv_js.dir/all&apos; failed
make[2]: *** [modules/js/CMakeFiles/opencv_js.dir/all] Error 2
make[2]: Leaving directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
CMakeFiles/Makefile2:3986: recipe for target &apos;modules/js/CMakeFiles/opencv.js.dir/rule&apos; failed
make[1]: *** [modules/js/CMakeFiles/opencv.js.dir/rule] Error 2
make[1]: Leaving directory &apos;/home/peter/Documents/research/opencv/build_js&apos;
Makefile:665: recipe for target &apos;opencv.js&apos; failed
make: *** [opencv.js] Error 2
Traceback (most recent call last):
  File &quot;./platforms/js/build_js.py&quot;, line 278, in &lt;module&gt;
    builder.build_opencvjs()
  File &quot;./platforms/js/build_js.py&quot;, line 196, in build_opencvjs
    execute([&quot;make&quot;, &quot;-j&quot;, str(multiprocessing.cpu_count()), &quot;opencv.js&quot;])
  File &quot;./platforms/js/build_js.py&quot;, line 23, in execute
    raise Fail(&quot;Child returned: %s&quot; % retcode)
__main__.Fail: Child returned: 2</pre>

I've attached my build_js.py file and the logs. Any thoughts on what's going wrong? I've been digging through issues and forum posts for a couple days and I can't seem to uncover a solution. Any help would be amazing!

[build_js.py.txt](https://github.com/opencv/opencv_contrib/files/4612701/build_js.py.txt)
[CMakeError.log.txt](https://github.com/opencv/opencv_contrib/files/4612706/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/opencv/opencv_contrib/files/4612707/CMakeOutput.log.txt)

**Comment by cnvx** [comment]
I'm running into this issue too.

**System information**

Operating System / Platform => Linux Mint 20 (Ubuntu 20.04) / 64 bit
OpenCV Version => Freshly cloned 4.3.0

**Steps to reproduce**

1. Download the source code:
   ```bash
   git clone --depth 1 --branch 4.3.0 https://github.com/opencv/opencv
   git clone --depth 1 --branch 4.3.0 https://github.com/opencv/opencv_contrib
   ```
2. Edit `opencv/platforms/js/build_js.py`, find `def clean_build_dir(self):` and add the contrib modules:
   ```python
   def get_cmake_cmd(self):
       cmd = ["cmake",
              "-DOPENCV_EXTRA_MODULES_PATH=/contrib/modules", # Add this line
   ```
3. Build OpenCV.js with Docker:
   ```bash
   cd opencv/
   sudo docker run --rm --workdir /code -v "$PWD":/code -v "$PWD/../opencv_contrib":/contrib "trzeci/emscripten:sdk-tag-1.38.32-64bit" python ./platforms/js/build_js.py build
    ```

**Error output**

(only the last few lines)

```
make -f modules/js/CMakeFiles/opencv_js.dir/build.make modules/js/CMakeFiles/opencv_js.dir/build
make[3]: Entering directory '/code/build'
[100%] Building CXX object modules/js/CMakeFiles/opencv_js.dir/bindings.cpp.o
cd /code/build/modules/js && /emsdk_portable/sdk/em++  -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS @CMakeFiles/opencv_js.dir/includes_CXX.rsp -s USE_PTHREADS=0    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -pthread -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -O2  -DNDEBUG   -std=c++11  -Wno-missing-prototypes -std=c++11 -o CMakeFiles/opencv_js.dir/bindings.cpp.o -c /code/build/modules/js/bindings.cpp
/code/build/modules/js/bindings.cpp:115:17: error: expected namespace name
using namespace aruco;
                ^
1 error generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
make[3]: *** [modules/js/CMakeFiles/opencv_js.dir/bindings.cpp.o] Error 1
modules/js/CMakeFiles/opencv_js.dir/build.make:135: recipe for target 'modules/js/CMakeFiles/opencv_js.dir/bindings.cpp.o' failed
make[3]: Leaving directory '/code/build'
CMakeFiles/Makefile2:4025: recipe for target 'modules/js/CMakeFiles/opencv_js.dir/all' failed
make[2]: *** [modules/js/CMakeFiles/opencv_js.dir/all] Error 2
make[2]: Leaving directory '/code/build'
CMakeFiles/Makefile2:3990: recipe for target 'modules/js/CMakeFiles/opencv.js.dir/rule' failed
make[1]: *** [modules/js/CMakeFiles/opencv.js.dir/rule] Error 2
make[1]: Leaving directory '/code/build'
Makefile:665: recipe for target 'opencv.js' failed
make: *** [opencv.js] Error 2
Traceback (most recent call last):
  File "./platforms/js/build_js.py", line 278, in <module>
    builder.build_opencvjs()
  File "./platforms/js/build_js.py", line 196, in build_opencvjs
    execute(["make", "-j", str(multiprocessing.cpu_count()), "opencv.js"])
  File "./platforms/js/build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 2
```

**Comment by SujeathPareddy** [comment]
I too have this problem. 

System Information
Operating System / Platform => Mac OS 10.15.6 (building with docker)
OpenCV Version => Freshly cloned 4.2

```
/code/build/modules/js/bindings.cpp:115:17: error: expected namespace name
using namespace aruco;
                ^
1 error generated.
```

The build command was:
```
docker run --rm --workdir /code -v "$PWD":/code "trzeci/emscripten:latest" python ./opencv/platforms/js/build_js.py build
```

**Comment by urbste** [comment]
Might be solved with this fix: https://github.com/opencv/opencv/pull/18985
