### ISSUE TITLE
Compiler  opencv4.3.0 in ubuntu 16.04 with cmake 3.5.1

### ISSUE THREAD

**Issue by zr526799544** [opencv/opencv_contrib#2545]
##### System information (version)

 cmake -DCMAKE_BUILD_TYPE=RELEASE -DINSTALL_PYTHON_EXAMPLES=ON -DINSTALL_C_EXAMPLES=ON -DOPENCV_EXTRA_MODULES_PATH=/home/toor/opencv/opencv_contrib/modules -DBUILD_EXAMPLES=ON -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_TIFF=ON -DENABLE_PRECOMPILED_HEADERS=OFF ..

get error:
Building CXX object modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/test/test_rotation_and_scale_invariance.cpp.o
In file included from /home/toor/opencv/opencv/modules/ts/include/opencv2/ts.hpp:125:0,
                 from /home/toor/opencv/opencv_contrib/modules/xfeatures2d/test/test_precomp.hpp:7,
                 from /home/toor/opencv/opencv_contrib/modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp:5:
/home/toor/opencv/opencv_contrib/modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp: In function ‘testing::internal::ParamGenerator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cv::Ptr<cv::Feature2D>, cv::Ptr<cv::Feature2D>, float> > opencv_test::{anonymous}::gtest_LATCHDescriptorRotationInvariance_EvalGenerator_()’:
/home/toor/opencv/opencv_contrib/modules/xfeatures2d/test/test_rotation_and_scale_invariance.cpp:33:31: error: ‘SIFT’ has not been declared
     make_tuple(IMAGE_TSUKUBA, SIFT::create(), LATCH::create(), 0.98f)
                               ^
/home/toor/opencv/opencv/modules/ts/include/opencv2/ts/ts_gtest.h:19023:66: note: in definition of macro ‘INSTANTIATE_TEST_CASE_P’
       gtest_##prefix##test_case_name##_EvalGenerator_() { return generator; } \
                                                                  ^
modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/build.make:62: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/test/test_rotation_and_scale_invariance.cpp.o' failed
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/test/test_rotation_and_scale_invariance.cpp.o] Error 1
CMakeFiles/Makefile2:12434: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/all' failed
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alalek** [comment]
You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.
