### ISSUE TITLE
Angle to Radian Conversion

### ISSUE THREAD

**Issue by SoapJN** [opencv/opencv_contrib#2552]
https://github.com/opencv/opencv_contrib/blob/8fc6067b5987316d0586bc5db45c10aadad8c97f/modules/surface_matching/src/ppf_match_3d.cpp#L125

In the code, radian = (360.0 / angle) * PI / 180.0.
I think the Correct results is radian = (angle) * PI / 180.0,.

**Comment by alalek** [comment]
Check line 139 from the link above:

> angle_step_relative = NumAngles;

`angle_step_relative` is not an angle.
`360 / angle_step_relative` is angle.

**Comment by SoapJN** [comment]
> Check line 139 from the link above:
> 
> > angle_step_relative = NumAngles;
> 
> `angle_step_relative` is not an angle.
> `360 / angle_step_relative` is angle.

`  if (rotationThreshold<0)
    rotation_threshold = ((360/angle_step) / 180.0 * M_PI);`

rotation_threshold = NumAngles.

Think you for your reply,  your reference is correct. But in the line 159, the NumAngles cannot be rotation_threshold, should change **angle_step** to **angle_step_relative**

**Comment by SoapJN** [comment]
Think you for your reply, your reference is correct. But in the line 159:
###  rotation_threshold = ((360/angle_step) / 180.0 * M_PI);
'rotation_threshold' = 'NumAngles'.
 the 'NumAngles' cannot be 'rotation_threshold', should change 'angle_step' to 'angle_step_relative'.
