### ISSUE TITLE
Invalid conversion when runing cmake on modules/xfeatures2d/ 

### ISSUE THREAD

**Issue by vladLozkin** [opencv/opencv_contrib#2557]
##### System information (version)

- OpenCV => 3.4.10
- Operating System / Platform => ubuntu 16.04 64 Bit
- Compiler => g++

##### Detailed description

Hello,
When I compile opencv 3.4.10 with contrib 3.4.10 using cmake
I've tried to compile the module directly by itself and I get the same error.

Error details:

/home/vlad/opencv_contrib/modules/xfeatures2d/src/fast.cpp: In function ‘void cv::xfeatures2d::FASTForPointSet(cv::InputArray, std::vector<cv::KeyPoint>&, int, bool, int)’:
/home/vlad/opencv_contrib/modules/xfeatures2d/src/fast.cpp:462:74: error: invalid conversion from ‘int’ to ‘cv::FastFeatureDetector::DetectorType’ [-fpermissive]
                 FAST(_img, keypoints, threshold, nonmax_suppression, type);
                                                                          ^
In file included from /home/vlad/opencv_contrib/modules/xfeatures2d/include/opencv2/xfeatures2d.hpp:42:0,
                 from /home/vlad/opencv_contrib/modules/xfeatures2d/src/fast.cpp:5:
/home/vlad/opencv/modules/features2d/include/opencv2/features2d.hpp:532:17: note:   initializing argument 5 of ‘void cv::FAST(cv::InputArray, std::vector<cv::KeyPoint>&, int, bool, cv::FastFeatureDetector::DetectorType)’
 CV_EXPORTS void FAST( InputArray image, CV_OUT std::vector<KeyPoint>& keypoints,
                 ^
modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/build.make:595: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/fast.cpp.o' failed
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/fast.cpp.o] Error 1
CMakeFiles/Makefile2:5874: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all' failed
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas?

**Comment by vladLozkin** [comment]
added -fpremmisve flag to cmake

**Comment by alalek** [comment]
> cv::FastFeatureDetector::DetectorType

There is no `DetectorType` on 3.4 branch.

> When I compile opencv 3.4.10 with contrib 3.4.10 using cmake

OpenCV is from master (4.x) branch.
OpenCV contrib code is from 3.4 branch.

You should verify included headers (`-H` GCC's option) and revise installed versions of OpenCV.
