### ISSUE TITLE
(Python3.6)About CalcOpticalFlowBM in opencv4.2

### ISSUE THREAD

**Issue by Aktcob** [opencv/opencv_contrib#2585]
Is there no python CalcOpticalFlowBM api in opencv4.2

**Comment by sjson** [comment]
https://docs.opencv.org/4.6.0/d5/dc3/group__cudalegacy.html#ga6b4b2e196ebed9c3a4b6c6330e6e4306

It seems to have been moved to legacy using with CUDA. You need to compile opencv to use it.
