### ISSUE TITLE
android Aruco. Cannot draw deteced markers over the image?

### ISSUE THREAD

**Issue by nayan826** [opencv/opencv_contrib#2661]
i am new to openCV and trying to create a project to detect ArUCO markers generated from here https://chev.me/arucogen/.

I am able to getting the value of the corners

D/corner: `[Mat [ 1*4*CV_32FC2, isCont=true, isSubmat=false, nativeObj=0x738f9d4c40, dataAddr=0x73ab9ba540 ]]`

But when i call Aruco.drawDetectedMarkers(rgb, corners) method nothing happens. Below is the logic i am using

```
public Mat onCameraFrame(CameraBridgeViewBase.CvCameraViewFrame inputFrame) {
        Mat rgba = inputFrame.rgba();
        Mat gray = inputFrame.gray();
        Mat rgb = new Mat();
        Dictionary dictionary = Aruco.getPredefinedDictionary(Aruco.DICT_4X4_50);
        Mat ids = new Mat();
        List<Mat> corners = new ArrayList<>();
        Imgproc.cvtColor(rgba, rgb, Imgproc.COLOR_RGBA2RGB);

        Aruco.detectMarkers(gray, dictionary, corners, ids);
        Log.d("corner list", corners.toString());

        if (!corners.isEmpty()) {
            Log.d("corners_entered", ids.toString());
            Aruco.drawDetectedMarkers(rgb, corners);
        } else {
            Log.d("corners_entered", "false");
        }
        return rgba;
    }
```

I am using OpenCV 3.3.1 Android SDK with contrib modules

**Comment by sturkmen72** [comment]
please use [Q&A forum](https://answers.opencv.org/) next time.

you need to update rgba
```
Imgproc.cvtColor(rgb, rgba, Imgproc.COLOR_RGB2RGBA);
return rgba;
```

**Comment by nayan826** [comment]
Thanks,
Now i can see green border around aruco code so i guess image is correctly detected but it doesn't draw the aruco id over it.
![image](https://user-images.githubusercontent.com/11948488/92435626-6f354b80-f1c0-11ea-9dee-1dab1215d5b0.png)
