### ISSUE TITLE
The Fast Line Detector should be able to input an edge image

### ISSUE THREAD

**Issue by tsukada-cs** [opencv/opencv_contrib#2667]
Hi,

I want to input the edge image directly into FastLineDetector, but the current implementation has to use the Canny method internally.

The important function of FastLineDetector is to extract line segments from the edge image, not the creation of the edge image, which is not the essence of the FastLineDetector.

It would be easy to just not use the Canny method when an edge image is input, but I'm not confident I can write that in c++.

If this feature is added, I'd appreciate it.

**Comment by sturkmen72** [comment]
Please close down.
