### ISSUE TITLE
bgsegm module description in README.md is misleading

### ISSUE THREAD

**Issue by kiranpradeep** [opencv/opencv_contrib#267]
In `README.md` file present in modules folder, the description of opencv_bgsegm module is provided as "opencv_bgsegm: Improved Adaptive Background Mixture Model for Real-time Tracking / Visual Tracking of Human Visitors under Variable-Lighting Conditions."

But, that is just the title of paper at http://goldberg.berkeley.edu/pubs/acc-2012-visual-tracking-final.pdf. The OpenCV implementation does only background/foreground segmentation and no tracking as such. For real time tracking the paper mentions use of `bank of kalman filters` which is not provided in the watered down version at `bgfg_gmg.cpp`. Only a part of the paper is implemented in OpenCV.

So could the description of bgsegm in README.md and inside modules/bgsegm be updated to "Statistical background image estimation and per-pixel Bayesian segmentation" ?. I could submit a pull request if required.

**Comment by StevenPuttemans** [comment]
@kiranpradeep please create this PR so that this gets adapted. You are indeed correct :)
