### ISSUE TITLE
compile opencv and opencv_contrib3.4.10 failed

### ISSUE THREAD

**Issue by starskabi** [opencv/opencv_contrib#2702]
- OpenCV => 3.4.10
- Operating System / Platform => ubuntu 18.04

##### Detailed description
my opencv_contrib and opencv version are 3.4.10 

When i try to compile opencv and opencv+contrib , but it broken 

Scanning dependencies of target opencv_xfeatures2d
[ 70%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/fast.cpp.o
/home/starskabi/opencv/opencv_contrib-3.4.10/modules/xfeatures2d/src/fast.cpp: In function ‘void cv::xfeatures2d::FASTForPointSet(cv::InputArray, std::vector<cv::KeyPoint>&, int, bool, int)’:
/home/starskabi/opencv/opencv_contrib-3.4.10/modules/xfeatures2d/src/fast.cpp:462:74: error: invalid conversion from ‘int’ to ‘cv::FastFeatureDetector::DetectorType’ [-fpermissive]
                 FAST(_img, keypoints, threshold, nonmax_suppression, type);
                                                                          ^
In file included from /home/starskabi/opencv/opencv_contrib-3.4.10/modules/xfeatures2d/include/opencv2/xfeatures2d.hpp:42:0,
                 from /home/starskabi/opencv/opencv_contrib-3.4.10/modules/xfeatures2d/src/fast.cpp:5:
/home/starskabi/opencv/opencv/modules/features2d/include/opencv2/features2d.hpp:532:17: note:   initializing argument 5 of ‘void cv::FAST(cv::InputArray, std::vector<cv::KeyPoint>&, int, bool, cv::FastFeatureDetector::DetectorType)’
 CV_EXPORTS void FAST( InputArray image, CV_OUT std::vector<KeyPoint>& keypoints,
                 ^~~~
modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/build.make:187: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/fast.cpp.o' failed
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/fast.cpp.o] Error 1
CMakeFiles/Makefile2:5600: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all' failed
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

i have checked  compile process for times,how could it happen?
thanks

**Comment by alalek** [comment]
> cv::FastFeatureDetector::DetectorType

This code is from the "master" branch instead of 3.4.10

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
