### ISSUE TITLE
Expanding the predefined dictionaries

### ISSUE THREAD

**Issue by EceChaik** [opencv/opencv_contrib#2704]
Hi everybody,

I was wondering if the MIP_36h12 dictionary can be added to opencv_contrib/aruco

**Comment by bign8** [comment]
Is this still wanted or in the works?

Looks like the ArUco authors highly recommend the use of the use of the MIP_36h12 library.  

> We ... recommend using ARUCO_MIP_36h12 because it is more robust to errors.
> [Source](https://github.com/clearpathrobotics/aruco)

After some poking around over there, I found the dictionary in [src/dictionary.cpp#L159](https://github.com/clearpathrobotics/aruco/blob/c47066e/src/dictionary.cpp#L159).

If this is still wanted or open to be contributed, the data has to be converted into a format that the predefined dictionaries expect:

> Dictionaries are stored as a list of bytes in its four rotations
> On each rotation, the marker is divided in bytes assuming a row-major order
> This format allows a faster marker identification.
> For a dictionary composed by M markers of NxN bits, the structure dimensions should be:
> const char name[nMarkers][4rotations][nBytes], or more specifically:
> const char name[M][4][ceil(NxN/8)]
> The element [i][j][k] represents the k-th byte of the i-th marker in the dictionary
> in its j-th rotation.
> Each rotation implies a 90 degree rotation of the marker in anticlockwise direction.
> [Source: modules/aruco/src/predefined_dictionaries.cpp](https://github.com/opencv/opencv_contrib/blob/0ee3192/modules/aruco/src/predefined_dictionaries.hpp#L43-L53)

Any details around why this issue was closed? Is there a simple fix that I'm not seeing?

Thanks,
- an OpenCV (and ArUco) newbie

**Comment by asmorkalov** [comment]
related: https://github.com/opencv/opencv_contrib/pull/3200

**Comment by Em607867** [comment]
> Is this still wanted or in the works?
> 
> Looks like the ArUco authors highly recommend the use of the use of the MIP_36h12 library.
> 
> > We ... recommend using ARUCO_MIP_36h12 because it is more robust to errors.
> > [Source](https://github.com/clearpathrobotics/aruco)
> 
> After some poking around over there, I found the dictionary in [src/dictionary.cpp#L159](https://github.com/clearpathrobotics/aruco/blob/c47066e/src/dictionary.cpp#L159).
> 
> If this is still wanted or open to be contributed, the data has to be converted into a format that the predefined dictionaries expect:
> 
> > Dictionaries are stored as a list of bytes in its four rotations
> > On each rotation, the marker is divided in bytes assuming a row-major order
> > This format allows a faster marker identification.
> > For a dictionary composed by M markers of NxN bits, the structure dimensions should be:
> > const char name[nMarkers][4rotations][nBytes], or more specifically:
> > const char name[M][4][ceil(NxN/8)]
> > The element [i][j][k] represents the k-th byte of the i-th marker in the dictionary
> > in its j-th rotation.
> > Each rotation implies a 90 degree rotation of the marker in anticlockwise direction.
> > [Source: modules/aruco/src/predefined_dictionaries.cpp](https://github.com/opencv/opencv_contrib/blob/0ee3192/modules/aruco/src/predefined_dictionaries.hpp#L43-L53)
> 
> Any details around why this issue was closed? Is there a simple fix that I'm not seeing?
> 
> Thanks,
> 
> * an OpenCV (and ArUco) newbie

Hi, 

Were you able to resolve this issue? I am trying to detect markers in the same dictionary

**Comment by asmorkalov** [comment]
Python bindings for dicts: https://github.com/opencv/opencv_contrib/pull/3229

**Comment by AleksandrPanov** [comment]
Add dictionary bindings #3229 was merged
