### ISSUE TITLE
Exception in constructor of cv::cuda::Stream

### ISSUE THREAD

**Issue by rrrand** [opencv/opencv_contrib#2705]
##### System information (version)
- OpenCV => 4.2, 4.5-pre (c8ebe0e)
- Operating System / Platform => Ubuntu 20.04
- Compiler => g++-8.4.0

##### Detailed description

Exception occured in constructor of cv::cuda::Stream after caught exception from cv::cuda::warpPerspective (see issue https://github.com/opencv/opencv_contrib/issues/2361).

```
Exception in cv::cuda::warpPerspective was processed.
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0-pre) /home/user/projects/opencv-4.5-builddir/opencv-master/modules/core/src/cuda_stream.cpp:303: error: (-217:Gpu API call) an illegal memory access was encountered in function 'Impl'

```

##### Steps to reproduce

Code based on example from issue https://github.com/opencv/opencv_contrib/issues/2361

```
// main.cpp

#include <cstdlib>
#include <opencv2/cudawarping.hpp>
#include <vector>
#include <iostream>

int main() {
  cv::Size inputSize{1000, 1000}; // can be different

  cv::Size outSize{670, 893};
  std::vector<double> values{
      0.3154414342519155,    0.2158186507123098,    133.1013012869572,
      -0.01298153793321658,  0.5681477441984867,    297.7284881948252,
      1.839213382549264e-05, 0.0006366310508410327, 1};

  cv::Mat matrix{cv::Size{3, 3}, CV_64FC1, values.data()};

  try {
    cv::cuda::GpuMat image{inputSize, CV_8UC4};

    cv::cuda::Stream stream;
    cv::cuda::warpPerspective(image, image, matrix, outSize, cv::INTER_LINEAR,
                              cv::BORDER_CONSTANT, cv::Scalar{0, 0, 0, 0},
                              stream);
    stream.waitForCompletion();
  }
  catch (const cv::Exception&) {
    std::cerr << "Exception in cv::cuda::warpPerspective was processed." << std::endl;
  }

  cv::cuda::Stream newStream;    // Exception!

  return EXIT_SUCCESS;
}
```

```
# cmake

cmake_minimum_required(VERSION 3.5)

project(min_ex)

# path to built from sources OpenCV
if (EXISTS /opt/opencv-4.2.0/lib/cmake/opencv4)
  set (OpenCV_DIR /opt/opencv-4.2.0/lib/cmake/opencv4)
endif()

find_package(OpenCV COMPONENTS core cudawarping REQUIRED)

add_executable(${PROJECT_NAME} src/main.cpp)
target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_11)
target_link_libraries(${PROJECT_NAME} PRIVATE ${OpenCV_LIBS})
target_include_directories(${PROJECT_NAME} PRIVATE ${OpenCV_INCLUDE_DIRS})
```

**Comment by alalek** [comment]
> 4.2

We don't support outdated versions.
Try latest code from the master branch first.

**Comment by rrrand** [comment]
@alalek
I've tested on current master (4.5-pre, c8ebe0e). The problem still remains. And the problem https://github.com/opencv/opencv_contrib/issues/2361 also remains.

**Comment by alalek** [comment]
Thank you for update!

Looks like this problem is the same and related to `warpPerspective()` CUDA implementation bug.

Closing as "duplicate".

**Comment by rrrand** [comment]
@alalek 
I absolutely agree that these two issues are related. But they are not the same. Exception in constructor is awful! And it should not just be closed!
At least it must be mentioned in original issue. Do you think I should do it?

**Comment by alalek** [comment]
> mentioned

There is automatic cross-reference link in original issue.

**Comment by alalek** [comment]
Please try to build and run OpenCV CUDA tests (to ensure that CUDA runtime works).

**Comment by rrrand** [comment]
> There is automatic cross-reference link in original issue.

Thank you! Now I see.

> There is automatic cross-reference link in original issue.

Could you please explain what exactly should be tested? I need to check that CUDA rutime works before or after exception? Or I should launch separate test application?

**Comment by alalek** [comment]
Build and run `opencv_test_cudaimgproc` test application.
