### ISSUE TITLE
How to specify to terminal to install opencv 3.4.12 

### ISSUE THREAD

**Issue by Ryan177-del** [opencv/opencv_contrib#2773]
##### System information (version)
 OpenCV => 3.4.12 (i want to install this)
--> Operating System / Platform =>ubuntu 18.04 LTS 
--> Compiler => GCC 7.5.0
--> Cuda:10.0.130
>

##### Detailed description

< Good afternoon, i was seeing that opencv 3.4.12 was available, and i want to install it. However the commands
`git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git`

will install the latest opencv version, which is 4.5. How can i specify to the terminal that i would like to install the 3.4.12 version? 
>
##### Steps to reproduce

Also, i intend to follow this website for instructions on installing the opencv properly. The link is: 
https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/

Please give me some suggestions on this, thank you for taking the time to read my issue.

**Comment by Ryan177-del** [comment]
@alalek  sorry, what does the invalid mean

**Comment by catree** [comment]
@Ryan177-del 

Your question is not related to OpenCV.

You have to learn how to use Git, see the [Git book](https://git-scm.com/book/en/v2) and the [Git tutorial](https://git-scm.com/docs/gittutorial). See tagging in Git.
