### ISSUE TITLE
Inpainting Feature Addition

### ISSUE THREAD

**Issue by RogerPlanck** [opencv/opencv_contrib#2777]
Hi,

I spotted this on GitHub yesterday (https://github.com/Severian-desu-ga/Inpainting). It really seems to be a great inpainting feature that employs the use of opencv-python. It was quite simple to use and resembled the other two inpainting features available on opencv-python, but the results were in my opinion superior. I would love to try do a pull request since I believe this would be an excellent addition to opencv-python but honestly I am still new to all this and really can't decipher how to do this from the "contribute to OpenCV page". Would someone please be able to assist? I am more that happy to ask the author for consent to provide the code and agree to the contribution terms (though their choice is obviously theirs). I'm enthusiastic to see this under OpenCV's umbrella.

**Comment by alalek** [comment]
OpenCV is C++ library.
OpenCV Python is just a binding over effective C++ code.

**Comment by RogerPlanck** [comment]
Ah that is a shame. Thank you for your speedy reply though.
