### ISSUE TITLE
possible unnecessary copy in aruco · charuco.cpp · detectCharucoDiamond

### ISSUE THREAD

**Issue by esopalumpa** [opencv/opencv_contrib#2781]
in charuco.cpp in the aruco module there seems to be an unnecessary explicit copy of an image.

```void detectCharucoDiamond(InputArray _image, InputArrayOfArrays _markerCorners,…```
…
```
    // convert input image to grey
    Mat grey;
    if(_image.type() == CV_8UC3)
        cvtColor(_image, grey, COLOR_BGR2GRAY);
    else
	    _image.copyTo(grey);
```
If the image already is a grayscale-image it is explicitly copied.  `grey = _image.getMat();` should do.

**EDIT**:
same in `_selectAndRefineChessboardCorners()`

**Comment by alalek** [comment]
> grey = _image.getMat()

doesn't copy buffer contents.

**Comment by esopalumpa** [comment]
> > grey = _image.getMat()
> 
> doesn't copy buffer contents.

Yes. The image is an InputArray and it is not necessary to copy the data here.

**Comment by alalek** [comment]
Agreed.
Implementation doesn't modify data from `gray` Mat.

Feel free to propose PR (preferable to 3.4 branch).

**Comment by esopalumpa** [comment]
PR #2785  against 3.4
