### ISSUE TITLE
cv::omnidir::stereoRectify returns wrong R2.

### ISSUE THREAD

**Issue by dzywater** [opencv/opencv_contrib#2787]
Recently, I used cv::stereoRectify, cv::fisheye::stereoRectify and cv::omnidir::stereoRectify.

I found that cv::omnidir::stereoRectify returned R2 which could not get stereo images with epipolar constraint.

So I checked theirs sources.

I think that cv::omnidir::stereoRectify has a mistake.

That is omnidir.cpp, line 2225: _R2 = R21 * _R1;

Based on cv::stereoRectify and cv::fisheye::stereoRectify, this line should be:  _R2 = _R1 * R21;

Besides, R2 is theoretically the rotation matrix from the coordinate system of the world to the second camera.

**Comment by alalek** [comment]
Thank you for the report!

Feel free to prepare PR with fix.

If you have some simple test case please add it into PR description (unfortunately there are no any tests for this module)

**Comment by dzywater** [comment]
For same test data, cv::stereoRectify, fisheye::stereoRectify and stereoRectExx(copy from cv::omnidir::stereoRectify and only the last line is modified) return negligible error. But omnidir::stereoRectify does not.
`#include <opencv2/opencv.hpp>
#include <opencv2/ccalib/omnidir.hpp>
using namespace std;
using namespace cv;

//copy from cv::omnidir::stereoRectify and only the last line is modified
void stereoRectExx(InputArray R, InputArray T, OutputArray R1, OutputArray R2);
void main(int argc = 0, char** argv = 0)
{
	int N = 999;
	for (int k = 0; k < N; ++k)
	{
		//0.GenerateData
		auto randomv = [](int min, int max)->int {return rand() % ((max)-(min)+1) + (min); };
		Mat_<double> r({ 3, 1 }, { 1, 1, 1 }); r = r / cv::norm(r, NORM_L2) * 3.14 / 180 * randomv(15, 45);
		Mat_<double> t({ 3, 1 }, { -double(randomv(10, 20)), double(randomv(2, 5)) , double(randomv(6, 9)) });//left camera x must be negative in right camera system which echoes opencv
		Mat_<double> R(3, 3); cv::Rodrigues(r, R);
		Matx31d P = P.randu(99, 999);

		//1.CalcByOpenCVPin
		Matx33d R11, R12;
		cv::stereoRectify(Matx33d::eye(), Mat(), Matx33d::eye(), Mat(), Size(480, 640), R, t, R11, R12, Matx34d(), Matx34d(), noArray());
		double infP11P12 = cv::norm(R11 * P, R12 * R * P, NORM_INF);

		//2.CalcByOpenCVKB(same as implementation as OpenCVPin)
		Matx33d R21, R22;
		fisheye::stereoRectify(Matx33d::eye(), Matx41d::zeros(), Matx33d::eye(), Matx41d::zeros(), Size(480, 640), R, t, R21, R22, Matx34d(), Matx34d(), noArray(), 0);
		double infP21P22 = cv::norm(R21 * P, R22 * R * P, NORM_INF);

		//3.CalcByDIYPin
		Matx33d R31, R32;
		//Matx31d t3 = stereoRectEx(R31, R32, R, t);
		double infP31P32 = 0;// cv::norm(R31 * P, R32 * R * P, NORM_INF);

		//4.CalcByDIYUCM
		Matx33d R41, R42;
		stereoRectExx(R, t, R41, R42);
		double infP41P42 = cv::norm(R41 * P, R42 * R * P, NORM_INF);

		//5.CalcByOpenCVUCM
		Matx33d R51, R52;
		omnidir::stereoRectify(R, t, R51, R52);
		double infP51P52 = cv::norm(R51 * P, R52 * R * P, NORM_INF);

		//6.PrintError
		cout << endl << "LoopCount: " << k << endl;
		if (infP11P12 > 1E-12 || infP21P22 > 1E-12 || infP31P32 > 1E-12 || infP41P42 > 1E-12 || infP51P52 > 1E-12)
		{
			cout << endl << "5.1PrintError" << endl;
			cout << endl << "infP11P12: " << infP11P12 << endl;
			cout << endl << "infP21P22: " << infP21P22 << endl;
			cout << endl << "infP31P32: " << infP31P32 << endl;
			cout << endl << "infP41P42: " << infP41P42 << endl;
			cout << endl << "infP51P52: " << infP51P52 << endl;
			cout << endl << "Press any key to continue" << endl; 
			std::getchar();
		}
	}
}

void stereoRectExx(InputArray R, InputArray T, OutputArray R1, OutputArray R2)
{
	CV_Assert((R.size() == Size(3, 3) || R.total() == 3) && (R.depth() == CV_32F || R.depth() == CV_64F));
	CV_Assert(T.total() == 3 && (T.depth() == CV_32F || T.depth() == CV_64F));

	Mat _R, _T;
	if (R.size() == Size(3, 3))
	{
		R.getMat().convertTo(_R, CV_64F);
	}
	else if (R.total() == 3)
	{
		Rodrigues(R.getMat(), _R);
		_R.convertTo(_R, CV_64F);
	}

	T.getMat().reshape(1, 3).convertTo(_T, CV_64F);

	R1.create(3, 3, CV_64F);
	Mat _R1 = R1.getMat();
	R2.create(3, 3, CV_64F);
	Mat _R2 = R2.getMat();

	Mat R21 = _R.t();
	Mat T21 = -_R.t() * _T;

	Mat e1, e2, e3;
	e1 = T21.t() / norm(T21);
	e2 = Mat(Matx13d(T21.at<double>(1) * -1, T21.at<double>(0), 0.0));
	e2 = e2 / norm(e2);
	e3 = e1.cross(e2);
	e3 = e3 / norm(e3);
	e1.copyTo(_R1.row(0));
	e2.copyTo(_R1.row(1));
	e3.copyTo(_R1.row(2));
	//_R2 = R21 * _R1;
	_R2 = _R1 * R21;
}
`

**Comment by dzywater** [comment]
For same test data, cv::stereoRectify, fisheye::stereoRectify and stereoRectExx(copy from cv::omnidir::stereoRectify and only the last line is modified) return negligible error. But omnidir::stereoRectify does not. Following are test.

#include <opencv2/opencv.hpp>
#include <opencv2/ccalib/omnidir.hpp>
using namespace std;
using namespace cv;

//copy from cv::omnidir::stereoRectify and only the last line is modified
void stereoRectExx(InputArray R, InputArray T, OutputArray R1, OutputArray R2);
void main(int argc = 0, char** argv = 0)
{
	int N = 999;
	for (int k = 0; k < N; ++k)
	{
		//0.GenerateData
		auto randomv = [](int min, int max)->int {return rand() % ((max)-(min)+1) + (min); };
		Mat_<double> r({ 3, 1 }, { 1, 1, 1 }); r = r / cv::norm(r, NORM_L2) * 3.14 / 180 * randomv(15, 45);
		Mat_<double> t({ 3, 1 }, { -double(randomv(10, 20)), double(randomv(2, 5)) , double(randomv(6, 9)) });//left camera x must be negative in right camera system which echoes opencv
		Mat_<double> R(3, 3); cv::Rodrigues(r, R);
		Matx31d P = P.randu(99, 999);

		//1.CalcByOpenCVPin
		Matx33d R11, R12;
		cv::stereoRectify(Matx33d::eye(), Mat(), Matx33d::eye(), Mat(), Size(480, 640), R, t, R11, R12, Matx34d(), Matx34d(), noArray());
		double infP11P12 = cv::norm(R11 * P, R12 * R * P, NORM_INF);

		//2.CalcByOpenCVKB(same as implementation as OpenCVPin)
		Matx33d R21, R22;
		fisheye::stereoRectify(Matx33d::eye(), Matx41d::zeros(), Matx33d::eye(), Matx41d::zeros(), Size(480, 640), R, t, R21, R22, Matx34d(), Matx34d(), noArray(), 0);
		double infP21P22 = cv::norm(R21 * P, R22 * R * P, NORM_INF);

		//3.CalcByDIYPin
		Matx33d R31, R32;
		//Matx31d t3 = stereoRectEx(R31, R32, R, t);
		double infP31P32 = 0;// cv::norm(R31 * P, R32 * R * P, NORM_INF);

		//4.CalcByDIYUCM
		Matx33d R41, R42;
		stereoRectExx(R, t, R41, R42);
		double infP41P42 = cv::norm(R41 * P, R42 * R * P, NORM_INF);

		//5.CalcByOpenCVUCM
		Matx33d R51, R52;
		omnidir::stereoRectify(R, t, R51, R52);
		double infP51P52 = cv::norm(R51 * P, R52 * R * P, NORM_INF);

		//6.PrintError
		cout << endl << "LoopCount: " << k << endl;
		if (infP11P12 > 1E-12 || infP21P22 > 1E-12 || infP31P32 > 1E-12 || infP41P42 > 1E-12 || infP51P52 > 1E-12)
		{
			cout << endl << "5.1PrintError" << endl;
			cout << endl << "infP11P12: " << infP11P12 << endl;
			cout << endl << "infP21P22: " << infP21P22 << endl;
			cout << endl << "infP31P32: " << infP31P32 << endl;
			cout << endl << "infP41P42: " << infP41P42 << endl;
			cout << endl << "infP51P52: " << infP51P52 << endl;
			cout << endl << "Press any key to continue" << endl; 
			std::getchar();
		}
	}
}

void stereoRectExx(InputArray R, InputArray T, OutputArray R1, OutputArray R2)
{
	CV_Assert((R.size() == Size(3, 3) || R.total() == 3) && (R.depth() == CV_32F || R.depth() == CV_64F));
	CV_Assert(T.total() == 3 && (T.depth() == CV_32F || T.depth() == CV_64F));

	Mat _R, _T;
	if (R.size() == Size(3, 3))
	{
		R.getMat().convertTo(_R, CV_64F);
	}
	else if (R.total() == 3)
	{
		Rodrigues(R.getMat(), _R);
		_R.convertTo(_R, CV_64F);
	}

	T.getMat().reshape(1, 3).convertTo(_T, CV_64F);

	R1.create(3, 3, CV_64F);
	Mat _R1 = R1.getMat();
	R2.create(3, 3, CV_64F);
	Mat _R2 = R2.getMat();

	Mat R21 = _R.t();
	Mat T21 = -_R.t() * _T;

	Mat e1, e2, e3;
	e1 = T21.t() / norm(T21);
	e2 = Mat(Matx13d(T21.at<double>(1) * -1, T21.at<double>(0), 0.0));
	e2 = e2 / norm(e2);
	e3 = e1.cross(e2);
	e3 = e3 / norm(e3);
	e1.copyTo(_R1.row(0));
	e2.copyTo(_R1.row(1));
	e3.copyTo(_R1.row(2));
	//_R2 = R21 * _R1;
	_R2 = _R1 * R21;
}

**Comment by dzywater** [comment]
#include <opencv2/opencv.hpp>
#include <opencv2/ccalib/omnidir.hpp>
using namespace std;
using namespace cv;

//copy from cv::omnidir::stereoRectify and only the last line is modified
void stereoRectExx(InputArray R, InputArray T, OutputArray R1, OutputArray R2);
void main(int argc = 0, char** argv = 0)
{
	int N = 999;
	for (int k = 0; k < N; ++k)
	{
		//0.GenerateData
		auto randomv = [](int min, int max)->int {return rand() % ((max)-(min)+1) + (min); };
		Mat_<double> r({ 3, 1 }, { 1, 1, 1 }); r = r / cv::norm(r, NORM_L2) * 3.14 / 180 * randomv(15, 45);
		Mat_<double> t({ 3, 1 }, { -double(randomv(10, 20)), double(randomv(2, 5)) , double(randomv(6, 9)) });//left camera x must be negative in right camera system which echoes opencv
		Mat_<double> R(3, 3); cv::Rodrigues(r, R);
		Matx31d P = P.randu(99, 999);

		//1.CalcByOpenCVPin
		Matx33d R11, R12;
		cv::stereoRectify(Matx33d::eye(), Mat(), Matx33d::eye(), Mat(), Size(480, 640), R, t, R11, R12, Matx34d(), Matx34d(), noArray());
		double infP11P12 = cv::norm(R11 * P, R12 * R * P, NORM_INF);

		//2.CalcByOpenCVKB(same as implementation as OpenCVPin)
		Matx33d R21, R22;
		fisheye::stereoRectify(Matx33d::eye(), Matx41d::zeros(), Matx33d::eye(), Matx41d::zeros(), Size(480, 640), R, t, R21, R22, Matx34d(), Matx34d(), noArray(), 0);
		double infP21P22 = cv::norm(R21 * P, R22 * R * P, NORM_INF);

		//3.CalcByDIYPin
		Matx33d R31, R32;
		//Matx31d t3 = stereoRectEx(R31, R32, R, t);
		double infP31P32 = 0;// cv::norm(R31 * P, R32 * R * P, NORM_INF);

		//4.CalcByDIYUCM
		Matx33d R41, R42;
		stereoRectExx(R, t, R41, R42);
		double infP41P42 = cv::norm(R41 * P, R42 * R * P, NORM_INF);

		//5.CalcByOpenCVUCM
		Matx33d R51, R52;
		omnidir::stereoRectify(R, t, R51, R52);
		double infP51P52 = cv::norm(R51 * P, R52 * R * P, NORM_INF);

		//6.PrintError
		cout << endl << "LoopCount: " << k << endl;
		if (infP11P12 > 1E-12 || infP21P22 > 1E-12 || infP31P32 > 1E-12 || infP41P42 > 1E-12 || infP51P52 > 1E-12)
		{
			cout << endl << "5.1PrintError" << endl;
			cout << endl << "infP11P12: " << infP11P12 << endl;
			cout << endl << "infP21P22: " << infP21P22 << endl;
			cout << endl << "infP31P32: " << infP31P32 << endl;
			cout << endl << "infP41P42: " << infP41P42 << endl;
			cout << endl << "infP51P52: " << infP51P52 << endl;
			cout << endl << "Press any key to continue" << endl; 
			std::getchar();
		}
	}
}

void stereoRectExx(InputArray R, InputArray T, OutputArray R1, OutputArray R2)
{
	CV_Assert((R.size() == Size(3, 3) || R.total() == 3) && (R.depth() == CV_32F || R.depth() == CV_64F));
	CV_Assert(T.total() == 3 && (T.depth() == CV_32F || T.depth() == CV_64F));

	Mat _R, _T;
	if (R.size() == Size(3, 3))
	{
		R.getMat().convertTo(_R, CV_64F);
	}
	else if (R.total() == 3)
	{
		Rodrigues(R.getMat(), _R);
		_R.convertTo(_R, CV_64F);
	}

	T.getMat().reshape(1, 3).convertTo(_T, CV_64F);

	R1.create(3, 3, CV_64F);
	Mat _R1 = R1.getMat();
	R2.create(3, 3, CV_64F);
	Mat _R2 = R2.getMat();

	Mat R21 = _R.t();
	Mat T21 = -_R.t() * _T;

	Mat e1, e2, e3;
	e1 = T21.t() / norm(T21);
	e2 = Mat(Matx13d(T21.at<double>(1) * -1, T21.at<double>(0), 0.0));
	e2 = e2 / norm(e2);
	e3 = e1.cross(e2);
	e3 = e3 / norm(e3);
	e1.copyTo(_R1.row(0));
	e2.copyTo(_R1.row(1));
	e3.copyTo(_R1.row(2));
	//_R2 = R21 * _R1;
	_R2 = _R1 * R21;
}
