### ISSUE TITLE
Incorrect ARUCO detection with bigger markers

### ISSUE THREAD

**Issue by Chris-Bee** [opencv/opencv_contrib#2811]
##### System information (version)
- OpenCV 4.2.* and 4.5.1
- Operating System: Linux Ubuntu 64 Bit

- Tag family is: DICT_7X7_250
- Image resolution: 2056x2542
- Images are grayscale

##### Detailed description

This issue concerns the implementation of the ARUCO marker detection. I observed, that the corner-detection / detection of squares in the image shows incorrect results. This issue is especially visible with bigger tag sizes (e.g. 0.3-0.5 meters). It appears that the corners or the squares are detected 2/3 into the outer border of the marker which results in incorrect height information. This issue does not occur in all conditions and seems especially related to the orientation of the tags. If the sides of the tag are aligned with the image frame (which basically means that the yaw rotation of the tag is a multiple of 90°) then this issue does not occur (compare attached image zero_yaw_rot.png). However, if the orientation is ~30-60°, then the size of the tag is incorrect (see image non_zero_yaw_rot.png below).

The sizes of the tags in image are [id, size in meter]:
"97: 0.15, 98: 0.15, 99: 0.3, 100: 0.1, 101: 0.15, 102: 0.5, 103: 0.15, 104: 0.1, 105: 0.3, 106: 0.15, 107: 0.15"

I verified that this is not only a problem in visualization, the height information does actually change if the issue occurs. A quick workaround was to transform the grayscale images into black and white images which results in correct detections.

I'm using a ROS package (https://github.com/UbiquityRobotics/fiducials) which implements the aruco detection with OpenCV. However, the attached python script will produce similar results. 

[tag_issue_images.zip](https://github.com/opencv/opencv/files/5803022/tag_issue.zip)
[tag_detect_issue.py.zip](https://github.com/opencv/opencv/files/5803141/tag_detect_issue.py.zip)

**ID 102, the middle tag is detected incorrect:**
![non_zero_yaw_rot](https://user-images.githubusercontent.com/12284463/104329606-609fcd80-54ed-11eb-91bd-0658a1ebec92.png)
**ID105, the tag to the right, is detected incorrect:**
![zero_yaw_rot](https://user-images.githubusercontent.com/12284463/104337290-9c3e9580-54f5-11eb-9e88-3d1c2e39816d.png)

**Comment by paroj** [comment]
#2900 maybe?

**Comment by Chris-Bee** [comment]
@paroj Thank you for your reply! I found the issue on my side and it might actually be the underlining issue for #2900.

I'm using a 3 Megapixel Camera/Image, I assume the default values for the aruco settings are done for ~VGA resolution. Most parameters are relative to the image resolution, however, the threshold window sizes are not. Thus, the default values are too low and because of this, the thresholding was incorrect.
I visualized the threshold with the default parameter, and my adapted threshold window size parameter (see images below). With that, the detection works reliably. #2900 seems to have the same issue by locking at the inner contours.

Adapted parameter:
```python
# Parameter for 3MegaPixel Images
aruco_params.adaptiveThreshWinSizeMin = 141  # default 3
aruco_params.adaptiveThreshWinSizeMax = 251  # default 23
aruco_params.adaptiveThreshWinSizeStep = 20  # default 10
aruco_params.adaptiveThreshConstant = 4      # default 7
```

Default parameter, incorrect threshold:
![default_param_thr_wrong](https://user-images.githubusercontent.com/12284463/112612941-d2669280-8e1f-11eb-874a-cfeaeaee8f85.png)
Default parameter, incorrect detection:
![default_param_wrong_detect](https://user-images.githubusercontent.com/12284463/112612948-d5fa1980-8e1f-11eb-8c7e-5ae493f05fd5.png)
Adapted parameter, correct threshold:
![adapt_param_thr_correct](https://user-images.githubusercontent.com/12284463/112612958-d98da080-8e1f-11eb-9d91-3355f13d7ab9.png)
Adapted parameter, correct detection:
![adapt_param_correct_detect](https://user-images.githubusercontent.com/12284463/112612967-dc889100-8e1f-11eb-82bc-7a3f6d6bde43.png)

Eventually, this can be mentioned in the [tutorial](https://docs.opencv.org/master/d5/dae/tutorial_aruco_detection.html), or the parameter could be rendered as relative values, but the pixel to threshold relation is probably not linear.

This issue can be closed in my opinion.

**Comment by AleksandrPanov** [comment]
add info to FAQ in https://github.com/opencv/opencv_contrib/pull/3200
