### ISSUE TITLE
Python randomly crashes and shows segmentation error

### ISSUE THREAD

**Issue by akshayacharya97** [opencv/opencv_contrib#2825]
Can someone tell me why this error is occuring? I have attached my screen snap for reference. I am trying to create a panorama from a bunch of images. After the images are read, before processing, it is crashing.

![Screen Shot 2021-01-19 at 15 35 09](https://user-images.githubusercontent.com/61483737/105002405-96f0c600-5a74-11eb-89ed-fade12ab0010.png)

**Comment by Mourad-Tlili** [comment]
After exactly 1 year, I'm having the same problem as you using Python 3.7.2 with Big Sur.
Did you find any solution ?
