### ISSUE TITLE
example_sfm_scene_reconstruction sample is broken 

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#2837]
- OpenCV => 4.5.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

sfm sample is not working. I run sample using tutorials result is

example_sfm_scene_reconstruction.exe dataset_files.txt 350 240 360
Initialize nViewMatcher ... OK
Performing Cross Matching ... OK

----------------------------

Reconstruction:
============================
Estimated 3D points: 3809
Estimated cameras: 4
Refined intrinsics:
[469.3013824582011, 0, 312.6849017589538;
 0, 469.3013824582011, 270.4752110859269;
 0, 0, 1]

3D Visualization:
============================
Recovering points  ... [DONE]
Recovering cameras ... [DONE]
Rendering points   ... [DONE]
Rendering Cameras  ... [DONE]

Press 'q' to close each windows ...
![image](https://user-images.githubusercontent.com/3591626/105827774-b16df680-5fc2-11eb-9420-e7611a47c794.png)

now
If i change this 
https://github.com/opencv/opencv_contrib/blob/4f8a400d5d17bf80dc4f25d6f2699a9a93829cc1/modules/sfm/src/reconstruct.cpp#L170-L176

in 

```
 if ( is_projective )
    {
      reconstruct_(images, Rs, Ts, K, points3d,false);
    }

```
I ran example : 
```
example_sfm_scene_reconstruction.exe dataset_files.txt 350 240 360
Initialize nViewMatcher ... OK
Performing Cross Matching ... OK

----------------------------

Reconstruction:
============================
Estimated 3D points: 3809
Estimated cameras: 4
Refined intrinsics:
[350, 0, 240;
 0, 350, 360;
 0, 0, 1]

3D Visualization:
============================
Recovering points  ... [DONE]
Recovering cameras ... [DONE]
Rendering points   ... [DONE]
Rendering Cameras  ... [DONE]

Press 'q' to close each windows ...

```
I can get previous [result](https://github.com/opencv/opencv_contrib/tree/4f8a400d5d17bf80dc4f25d6f2699a9a93829cc1/modules/sfm)
![image](https://user-images.githubusercontent.com/3591626/105826970-ab2b4a80-5fc1-11eb-9c9d-7c86041baad8.png)

Reason is parameters cannot be all refined in first step
@PhilLab q

**Comment by FabianSchuetze** [comment]
Hi! 

I have had the same problem as described above, but  even with the proposed fix the reconstruction does not look good for me. I tried both the "temple" and "templeRing" [dataset](https://vision.middlebury.edu/mview/data/). During the reconstruction, the intrinsics are also refined to:
```Shell
Refined intrinsics: 
[350, 0, 360;
 0, 350, 0;
 0, 0, 1]
```
which is different from the `350 240 360` intrinsics provided as command line argument. 

Is there anything I could do to test the reconstruction code?
