### ISSUE TITLE
aruco feature request: custom images

### ISSUE THREAD

**Issue by marcusx2** [opencv/opencv_contrib#2861]
Can you make the aruco module work with custom images in addition to aruco markers? Real client projects don't use aruco markers, they are based on custom images for the augmented reality experience.

**Comment by urbste** [comment]
I don't think this is possible. The algorithm to extract the markers is specifically tailored to extract quadratic boxes with sharp black/white edges. Subsequently it extracts the code from the marker interior to give each marker a unique ID. 

For your case, you could for example extract natural features using (SIFT,SURF,...) on your custom image offline, save them and then match each live incoming camera image to your custom image features.

**Comment by urbste** [comment]
You could add this feature by yourself without changing the Aruco module. Use the Aruco module to extract Aruco markers if you need to. 

In addition, to use custom image along Aruco markers you can extract natural features (ORB,SURF...) from your custom image offline. Subsequently you can then match the incoming video images against your "feature database".

**Comment by marcusx2** [comment]
I want to do this [](https://www.youtube.com/watch?v=DF9JPv35XzE) but with custom images. There is no video or anything. Is there a module like aruco or something that I can use to easily make an Augmented Reality experience like on the video using custom images, and not aruco markers?

**Comment by paroj** [comment]
see https://www.youtube.com/watch?v=_px3mmg_PqI&t=47s

**Comment by marcusx2** [comment]
I'm not about to watch a 1-hour video to figure out how to do this. Image tracking is a common feature used in augmented reality experiences. I never used, and never seen a real project using aruco though. Aruco is cool and all, but real projects use custom images. Can we just have a ready to use, easy module for image tracking? Something like this [https://www.youtube.com/watch?v=R0kSJ7rDMEI](https://www.youtube.com/watch?v=R0kSJ7rDMEI)
