### ISSUE TITLE
How to install opencv-python 4.5.1-dev?

### ISSUE THREAD

**Issue by jamesjianwang** [opencv/opencv_contrib#2874]
I want to use WechatQRcode function and it seems that it's in 4.5.1-dev.

I used the command "pip install opencv-contrib-python" today, but it installs 4.5.1 and cannot find "wechat_qrcode_WeChatQRCode". See details below.

The code:
import cv2
detector = cv2.wechat_qrcode_WeChatQRCode("detect.prototxt", "detect.caffemodel", "sr.prototxt", "sr.caffemodel")

The error: 
AttributeError: module 'cv2.cv2' has no attribute 'wechat_qrcode_WeChatQRCode'

My question is: how to install opencv-python 4.5.1-dev which contains both the newest main modules and contrib/extra modules? Not 4.5.1.
Thanks!

**Comment by ZhangXinNan** [comment]
The same question !

**Comment by Hupengyu** [comment]
> I want to use WechatQRcode function and it seems that it's in 4.5.1-dev.
> 
> I used the command "pip install opencv-contrib-python" today, but it installs 4.5.1 and cannot find "wechat_qrcode_WeChatQRCode". See details below.
> 
> The code:
> import cv2
> detector = cv2.wechat_qrcode_WeChatQRCode("detect.prototxt", "detect.caffemodel", "sr.prototxt", "sr.caffemodel")
> 
> The error:
> AttributeError: module 'cv2.cv2' has no attribute 'wechat_qrcode_WeChatQRCode'
> 
> My question is: how to install opencv-python 4.5.1-dev which contains both the newest main modules and contrib/extra modules? Not 4.5.1.
> Thanks!

这个只是pip install 能用吗？不需要CMAKE吗？

**Comment by JacquelineXu** [comment]
Install open-python & opencv-contrib-python.
pip install opencv-python
pip install opencv-contrib-python
