### ISSUE TITLE
Sizes of input arguments do not match exception in ximgproc::thinning 

### ISSUE THREAD

**Issue by pauljurczak** [opencv/opencv_contrib#2887]
I'm using OpenCV v4.5.1-dev and v4.2 on Ubuntu 18.04 and 20.04 with gcc-10.1 and clang-10.0. 

This code snippet:
```
  Mat img = cv::imread("6.png");
  ximgproc::thinning(img, img, ximgproc::THINNING_ZHANGSUEN);
```
crashes with this message:
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1-dev) /home/paul/opencv/opencv/modules/core/src/arithm.cpp:232: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'binary_op'
```
Specifically `Sizes of input arguments do not match` doesn't make any sense to me in this context. Both input arguments are identical and in-place thinning is supported according to documentation at https://docs.opencv.org/master/df/d2d/group__ximgproc.html. Behavior is the same with `THINNING_GUOHALL` argument.

Is this a problem of wrong image type? Running `print("{} {}\n", img.depth(), img.type());` produces `0 16`. I can't find image type `16` in the documentation.

 Attached is `6.png` file.

![6](https://user-images.githubusercontent.com/4933032/110532183-c2d61280-80d9-11eb-81f8-d9c351ad64ea.png)

**Comment by berak** [comment]
from [docs](https://docs.opencv.org/master/df/d2d/group__ximgproc.html#ga37002c6ca80c978edb6ead5d6b39740c)


    src | Source 8-bit single-channel image, containing binary blobs, with blobs having 255 pixel values.

but 

    Mat img = cv::imread("6.png");

will read a 3 channel img, and it will throw above exception from here:

https://github.com/opencv/opencv_contrib/blob/d882e6c87362206cf1bf3df9a5fec547d2eb582e/modules/ximgproc/src/thinning.cpp#L81

so, there should be a check for CV_8UC1 [here](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/thinning.cpp#L71) , and also in your code you have to use

    Mat img = cv::imread("6.png", cv::IMREAD_GRAYSCALE); // force single channel

**Comment by pauljurczak** [comment]
Thank you, it works. The problem is that searching the documentation, I didn't see a way to find what is the image type `16`. Adding image type check inside `thinning` function would be most helpful.
