### ISSUE TITLE
use wechat qrcode get SystemError <class 'cv2.wechat_qrcode_WeChatQRCode'> returned a result with an error set

### ISSUE THREAD

**Issue by Nr-rN** [opencv/opencv_contrib#2888]
I use cmake `OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules/` and got cv2.cpython-36m-x86_64-linux-gnu.so*。

Env:
python: 3.6
Ubuntu: 18.04

but if i code ：
import cv2
detector =cv2.wechat_qrcode_WeChatQRCode("detect.prototxt", "detect.caffemodel", "sr.prototxt", "sr.caffemodel")

And I got information below:
```
cv2.error: OpenCV(4.5.1-dev) /XX/XXX/opencv_contrib/modules/wechat_qrcode/src/wechat_qrcode.cpp:56: error: (-215:Assertion failed) utils::fs::exists(detector_prototxt_path) in function 'WeChatQRCode'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'cv2.wechat_qrcode_WeChatQRCode'> returned a result with an error set
```

**Comment by jaffe-fly** [comment]
do you have solve it?

**Comment by Nr-rN** [comment]
> do you have solve it?

of course, 
First you need install the latest opencv package(official website)
Then you need set your  file path to use cv2.wechat_qrcode_WeChatQRCode，like "../../detect.prototxt", "/root/model/detect.caffemodel" , ............

**Comment by JoeXu96** [comment]
hello, I have the same error ,
But my cmake command is 
`cmake -DOPENCV_EXTRA_MODULES_PATH=/root/soft/opencv_contrib-master/modules /root/soft/opencv-4.5.1`

**Comment by JoeXu96** [comment]
> hello, I have the same error ,
> But my cmake command is
> `cmake -DOPENCV_EXTRA_MODULES_PATH=/root/soft/opencv_contrib-master/modules /root/soft/opencv-4.5.1`

ok...I know....
`cv2.wechat_qrcode_WeChatQRCode("detect.prototxt", "detect.caffemodel", "sr.prototxt", "sr.caffemodel")`
This command is loading some model or configure file which I can't find , 
I fix it with change it as `cv2.wechat_qrcode_WeChatQRCode()`
But I still want to use this model, maybe u know which path or download link can get these model file  ?

**Comment by berak** [comment]
@JoeXu96 just read here:

https://github.com/opencv/opencv_contrib/blob/fc0cec623add0775ce855bbe1841027dbad96f5d/modules/wechat_qrcode/samples/qrcode.py#L18

also, if you build from src, cmake will download them to `build/downloads/wechat_qrcode`

**Comment by NiloofarSabouri** [comment]
Hi, I got the same problem. Can you explain more ... how I can solve it.
