### ISSUE TITLE
Bug in function cv::cuda::flip

### ISSUE THREAD

**Issue by numetrix** [opencv/opencv_contrib#2895]
@tomoaki0705 The flip operation will be done inplace when source and destination images have same refcount:

https://github.com/opencv/opencv_contrib/blob/d882e6c87362206cf1bf3df9a5fec547d2eb582e/modules/cudaarithm/src/core.cpp#L166

This line of code should be:
`bool isInplace = (src.data == dst.data) && (src.refcount == dst.refcount); `

We tested this fix and it works.

Thanks.

**Comment by tomoaki0705** [comment]
Relates #18348
Actually, it's not that simple.

https://github.com/opencv/opencv/pull/18348#discussion_r490241178

Could you share an explicit reproducer that bothers you? I.e. did you face an actual bug, or do you think it's a bug?

/cc @alalek

**Comment by numetrix** [comment]
Yes, it's an actual bug. See in opencv2\core\cuda.hpp:333
`//! pointer to the reference counter;`
`//! when GpuMat points to user-allocated data, the pointer is NULL`
`int* refcount;`
If source and destination GpuMat points to user-allocated data, the pointer is NULL.
That's exactly what happen in our case. 
`bool isInplace = (src.data == dst.data) || (src.refcount == dst.refcount); `
will always return true if both source and destination have user-allocated data.
I'm not sure what is the correct solution, but I'm sure there is a bug.

**Comment by alalek** [comment]
Implementation code through NPPI is not able to handle shifted data from the same buffer. It accepts one pointer only through arguments:

https://github.com/opencv/opencv_contrib/blob/d882e6c87362206cf1bf3df9a5fec547d2eb582e/modules/cudaarithm/src/core.cpp#L125

So my comment ( https://github.com/opencv/opencv/pull/18348#discussion_r490241178 ) was not correct for this case and `(src.refcount == dst.refcount)` part should be removed.

---

Please target patch to "3.4" branch of the main "opencv" repository.

**Comment by tomoaki0705** [comment]
Thank you for sharing the situation.
Let's follow what alalek said.
