### ISSUE TITLE
-209:Sizes of input arguments do not match

### ISSUE THREAD

**Issue by WAEL-ABDULAL** [opencv/opencv_contrib#2901]
# System information (version)

- OpenCV => 4.5.1
- Operating System / Platform => Windows 64 Bit
- Compiler => PyCharm 2020.3

# Detailed description

I try OpenCV issue namely Color Correction Model and I got the following error: 

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/pythonProject/main.py", line 35, in <module>
    ccm_object.run()
 cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-i1s8y2i1\opencv\modules\core\src\arithm.cpp:234: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'cv::binary_op'

The code I try is:   // Python code

import cv2
import imutils
import numpy as np
from cv2.ccm import COLORCHECKER_Macbeth

image = cv2.imread("C://Users/User/Downloads/en.jpg")

image = imutils.resize(image, 1200)
original_img = image.copy()
openc_ccm = cv2.mcc_CCheckerDetector.create()

cv2.mcc_CCheckerDetector.process(openc_ccm, image=image, chartType=0)

checkers = cv2.mcc_CCheckerDetector.getListColorChecker(openc_ccm)

color_draw = cv2.mcc_CCheckerDraw.create(checkers[0])
cv2.mcc_CCheckerDraw.draw(color_draw, image)

checkerRect = cv2.mcc_CChecker.getBox(checkers[0])

pt1 = (int(checkerRect[0][0]), int(checkerRect[0][1]))
pt2 = (int(checkerRect[2][0]), int(checkerRect[2][1]))
cv2.rectangle(img=image, pt1=pt1, pt2=pt2, color=(255, 0, 0), thickness=3, lineType=0)

chartsColor = cv2.mcc_CChecker.getChartsRGB(checkers[0])
print(chartsColor.shape)
ChartsRGB = chartsColor[:, 1]

print("=========>>", ChartsRGB.shape[0])
src2 = ChartsRGB.copy().reshape(int(ChartsRGB.shape[0]/3), 3)/255.0
print(src2.shape)
const_color = COLORCHECKER_Macbeth

ccm_object = cv2.ccm_ColorCorrectionModel(src2, const_color)
ccm_object.run()

color_correction_matrix = ccm_object.getCCM()
print(color_correction_matrix)

weights = ccm_object.getWeights()
print(weights)

loss = ccm_object.getLoss()
print(loss)
    ```
 Do you have any suggestion of what the problem might be? I've been stuck on this for a long time...

Thank you.

**Comment by deblauwetom** [comment]
Hello, I have ported the C++ example in the same way as here, except I used (3,24) as the final shape, and I get exactly the same error. 
The detection of the color checker locations is perfect, by the way!

There is a need of a python example that works. On stackoverflow, another person had the exact same crash trying this module in python. So already 3 people can't get it to work.

**Comment by lsorgi** [comment]
I managed to make it work, results are ok, the only issue is that white color becomes slightly yellow-ish.
Below the code I used. 


        img = cv2.imread(filename, cv2.IMREAD_UNCHANGED)
        
        # detect color checker
        detector = cv2.mcc_CCheckerDetector.create()
        if not detector.process(img, ccm_chart_type, 1):
            continue

        checkers = detector.getListColorChecker()
        assert len(checkers) == 1, f'Unexpected checker count, detected ({len(checkers)}), expected (1)'
        checker = checkers[0]

        # extract the checker normalized patches
        chart_sRGB = checker.getChartsRGB()
        src = chart_sRGB[:, 1].copy().reshape(24, 1, 3)
        src /= 255.0

        # color model fitting
        ccm_mdl = cv2.ccm_ColorCorrectionModel(src, ccm_chart_type)
        ccm_mdl.setColorSpace(cv2.ccm.COLOR_SPACE_sRGB)
        ccm_mdl.setCCM_TYPE(cv2.ccm.CCM_3x3)
        ccm_mdl.setDistance(cv2.ccm.DISTANCE_CIE2000)
        ccm_mdl.setLinear(cv2.ccm.LINEARIZATION_COLORPOLYFIT)
        ccm_mdl.setLinearDegree(3)
        ccm_mdl.setSaturatedThreshold(0, 0.98)
        ccm_mdl.run()
        logging.info(f'Complete fitting of color calibration model, loss({ccm_mdl.getLoss()})')
        logging.info(f'CCM: \n {ccm_mdl.getCCM()})')

        # normalize color and save image
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_f = img.astype(np.float64) / 255.0
        img_f = ccm_mdl.infer(img_f) * 255.0
        img_f[img_f < 0] = 0
        img_f[img_f > 255] = 255
        img = img_f.astype(np.uint8)
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

        filename = os.path.join(output_folder, filename_base)
        cv2.imwrite(filename, img)

**Comment by lsorgi** [comment]
notice that the bgr2rgb conversion is applied only for ccm_ColorCorrectionModel.infer but not for ccm_ColorCorrectionModel.run  ..... this is the only combination that produced reasonable results and is not clear to me why....

**Comment by crackwitz** [comment]
`src.shape = (-1, 1, 3)` or (24, 1, 3) if you have 24 rows

that's due to cv::Mat / np.array conversion logic, `(height, width, channels)`

**Comment by WAEL-ABDULAL** [comment]
Thanks you for helping me.

**Comment by llavkush** [comment]
[if not detector.process(img, ccm_chart_type, 1):
        continue](url)

This part seems not to be working, please help me if there is some wok around, collab is crashing if color checker card is not found, I am using opencv-contrib-python==4.5.3.56 for my project
