### ISSUE TITLE
对于微信二维码识别插件有一个疑问

### ISSUE THREAD

**Issue by MichaelHuyp** [opencv/opencv_contrib#2942]
@dddzg 大佬 对于微信二维码识别插件有一个疑问 
最近在做二维码扫描功能 我发现微信的二维码识别在屏幕中出现"可能是二维码的图形"时屏幕会放大 
请问这个"可能是二维码的图形"这个判断是wechat_qrcode.cpp里面那个方法拿到的
难道微信二维码识别插件提供预识别功能么 不知道我表达的是否清楚

**Comment by dddzg** [comment]
嗯，你理解的没错
但小码放大的功能 牵扯到不同客户端的底层逻辑，所以就不在开源代码里涉及
你可以通过检测到的二维码位置封装一个小码放大的方法

**Comment by MichaelHuyp** [comment]
当我扫描一个空白区域没有二维码时,屏幕不会放大
但是当我扫描一个二维码(小码)的区域时,我发现微信这边可以识别出可能是二维码并且将镜头放大.
我理解的"可能是二维码"指的是(当前还没有识别出二维码的内容,但是知道这个黑色的模糊图案可能是二维码),目前这个识别逻辑并没有开源出来是么

**Comment by MichaelHuyp** [comment]
"你可以通过检测到的二维码位置封装一个小码放大的方法" 目前这个插件能够检测出二维码位置,当前二维码的内容其实就已经识别出来了.. 感觉没必要再做一个放大的假象给用户了. 对比了一下微信 感觉微信预识别的距离比demo要远 也就是说目前开源的能力(没有预识别)只能做一个假象是吗 @-@

**Comment by dddzg** [comment]
是这样的，开源代码为了保持API简洁
我们只暴露出来了detectAndDecode 这一个API，返回解出的二维码信息
但实际上它会分为detect  和 decode两步构成  也就意味着确实是存在模型detect到二维码 但decode解不出的情况
考虑到这样会增加一些理解上的困难，我们把能detect但解不出来的二维码都在detectAndDecode过滤掉了
所以，你如果想要利用模型detect的原始结果，具体你可以看这边： https://github.com/opencv/opencv_contrib/blob/fc0cec623add0775ce855bbe1841027dbad96f5d/modules/wechat_qrcode/src/wechat_qrcode.cpp#L97
这里会有初始的candidate_points的坐标

开源代码更多还是学习交流为主，涉及更多微信客户端的细节，我们这边就不讨论了哈

**Comment by MichaelHuyp** [comment]
@dddzg 感谢大佬 学习了
