### ISSUE TITLE
Compiling tutorial_charuco_create_detect.cpp using opencv_contrib in Anaconda

### ISSUE THREAD

**Issue by drf5n** [opencv/opencv_contrib#2948]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Mac w/ Anaconda distribution
- Compiler => g++

##### Detailed description

Documenting using pkg-config to enable packaged opencv/opencv_contrib compilations and execution

I was trying to use an example from a tutorial with a packaged opencv distribution and found that the `pkg-config` tool made it relatively easy.

I was using an Anaconda distribution of opencv:

    conda create -n opencv opencv pkg-config
    conda activate opencv

I then compiled and ran the code from https://docs.opencv.org/master/df/d4a/tutorial_charuco_detection.html  using:

     g++ -o tutorial_charuco_create_detect `pkg-config --cflags --libs opencv` tutorial_charuco_create_detect.cpp
     LD_LIBRARY_PATH=`pkg-config --variable=libdir opencv` ./tutorial_charuco_create_detect -c=1  # create a charuco pattern in BoardImg.jpg

This is not an issue with the code, it might be an issue with the documentation, either on how to use https://github.com/opencv/opencv_contrib/blob/master/modules/aruco/samples/tutorial_charuco_create_detect.cpp  or the tutorial posted at https://docs.opencv.org/3.4/df/d4a/tutorial_charuco_detection.html or how to make it easier to learn about opencv before actually committing to building and installing the full OpenCV from source.  For instance, the https://docs.opencv.org/master/d0/d3d/tutorial_general_install.html page recommends several pre-built versions, but depending on the quality of the pre-built system, it can be difficult to actually make use of the pre-built install.

**Comment by alalek** [comment]
There is an example how to use CMake with sample code: https://github.com/opencv/opencv/tree/master/samples/cpp/example_cmake

Others approaches are possible, but they are not recommended and not tested.
There are no plans to add them into OpenCV API "tutorials".

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
