### ISSUE TITLE
wechat_qrcode  has any plan provide in java language?

### ISSUE THREAD

**Issue by epwtrq** [opencv/opencv_contrib#2958]
wechat_qrcode  perform better than orgin zxing ,do you have any plans provide it in java ? find pattern use connected cells algorithm. is there more explanation about it ,since i not good at c++ ,do you have any idea if android app want to use the ability of wechat_qrcode?  thanks very much 。。。

**Comment by berak** [comment]
it already generates java bindings:

https://github.com/opencv/opencv_contrib/blob/029c2833623ae658fb1820d5da30e5023134eaf5/modules/wechat_qrcode/CMakeLists.txt#L2

also, [there are javadocs](https://docs.opencv.org/master/javadoc/org/opencv/wechat_qrcode/package-summary.html)  for it
