### ISSUE TITLE
Possible memory leaks in fuzzy module

### ISSUE THREAD

**Issue by JAckLosingHeart** [opencv/opencv_contrib#2977]
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/fuzzy/src/fuzzy_F0_math.cpp#L125
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/fuzzy/src/fuzzy_F0_math.cpp#L126
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/fuzzy/src/fuzzy_F0_math.cpp#L127
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/fuzzy/src/fuzzy_F0_math.cpp#L253
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/fuzzy/src/fuzzy_F0_math.cpp#L254
https://github.com/opencv/opencv_contrib/blob/8eec886808b1352cdb746772ef6e001ff83d2774/modules/fuzzy/src/fuzzy_F0_math.cpp#L255
Looks like they are not de-allocated anywhere but I'm not sure about that.
Found this when running the opencv_test_fuzzy and reported by LeakSanitizer

**Comment by alalek** [comment]
Manual memory management (through new/delete) should be avoided.
These statements should be replaced by `std::vector` or `cv::AutoBuffer`
