### ISSUE TITLE
CMakeFiles/Makefile2:8642: recipe for target 'modules/tracking/CMakeFiles/opencv_tracking.dir/all' failed

### ISSUE THREAD

**Issue by AtariaLee** [opencv/opencv_contrib#2991]
##### System information (version)
- OpenCV = 4.5.2
- Operating System / Platform = Ubuntu 18.04

##### Detailed description

when i use `cmake--build.`to build opencv4.52 and opencv -contribute4.5.0 ,this error happend. And i dont find how to solve it,does someone konw what happend,and how to fix this problem? I would be very appreciated for your help!!!!!

##### Steps to reproduce
this is the details about this problem.
`CMakeFiles/Makefile2:8642: recipe for target 'modules/tracking/CMakeFiles/opencv_tracking.dir/all' failed
make[1]: *** [modules/tracking/CMakeFiles/opencv_tracking.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2`

before that ,there are many errors like this `In file included from /home/lee/OpenCV/opencv_contrib-4.5.0/modules/tracking/src/gtrTracker.hpp:47:0,
                 from /home/lee/OpenCV/opencv_contrib-4.5.0/modules/tracking/src/gtrTracker.cpp:42:
/home/lee/OpenCV/opencv-4.5.2/modules/video/include/opencv2/video/tracking.hpp:797:20: error: redefinition of ‘class cv::TrackerGOTURN’
 class CV_EXPORTS_W TrackerGOTURN : public Tracker
                    ^~~~~~~~~~~~~
`

**Comment by alalek** [comment]
>  opencv4.52 and opencv -contribute4.5.0

Different versions are not supported.

You should keep source code bases of opencv/opencv_contrib synchronized (the same git tag or head of the same branch).
Different versions are not tested for compatibility and may not work.
