### ISSUE TITLE
how to strip opencv_wechat_qrcode

### ISSUE THREAD

**Issue by jqctop1** [opencv/opencv_contrib#2996]
After compile with source code files, I got a final  so file which size is about 4M.

![image](https://user-images.githubusercontent.com/15994990/124592074-a1224780-de8f-11eb-9308-bff55b9f20fe.png)

But you can find that the size of  libwechatQrMod.so in WeChat apk is only 2M.

![image](https://user-images.githubusercontent.com/15994990/124592000-8e0f7780-de8f-11eb-87b7-4a3cd77c02dc.png)

What is the difference?  @dddzg

**Comment by dddzg** [comment]
The open source version is a little different with the code in wechat app. The code is refactored with OpenCV requirement and dependency lib(OpenCV image format, caffe model inference). So, it is hard to tell the difference between the size (4MB vs 2MB).
