### ISSUE TITLE
wechat qrcode module is unable to decode mini program codes of wechat

### ISSUE THREAD

**Issue by Miracle2333** [opencv/opencv_contrib#3022]
##### Detailed description

We tested the wechar_qrcode module and found that it was unable to decode mini program codes of wechat, things like pictures below.

![000382](https://user-images.githubusercontent.com/27708595/130025835-6a374945-8608-495a-b54e-d5be878227f5.jpg)
![000081](https://user-images.githubusercontent.com/27708595/130025905-f9315302-02d5-4370-8f7d-79b067983b6d.jpg)

We have checked the intermediate results, and found these codes could be recognized in the detection stage and their scores were quite high, like 0.99 or so. Is it possible that you didn't include the ability to decode these types of codes in the decode parts? By the way, the wechat qrcode scanner on our phone could decode these codes well. If so, we wonder if you could add the decoding functions specially for mini program codes in your moudule?

@dddzg

**Comment by dddzg** [comment]
We are sorry that the open-source verison only supports QRCode decoding.

**Comment by Miracle2333** [comment]
> We are sorry that the open-source verison only supports QRCode decoding.

All right. Any suggestion on how to decode mini program codes?😂
