### ISSUE TITLE
ArUco tutorial should contain camera parameters of example images

### ISSUE THREAD

**Issue by friederwC** [opencv/opencv_contrib#3045]
##### System information (version)
- OpenCV > 3.0

##### Detailed description

The tutorial comes with great code examples and the marker detection example can easily be tested with the image provided by the tutorial: https://docs.opencv.org/4.5.3/singlemarkersoriginal.jpg
However, for the pose estimation example, the camera parameters are required. Here it would be great if they were provided for the example image. The tutorial assumes, that one takes and uses their own image and calibrates their camera, but it would be nice if it was possible to follow the tutorial without taking pictures.

##### Steps to reproduce

Go to https://docs.opencv.org/4.5.3/d5/dae/tutorial_aruco_detection.html

**Comment by AleksandrPanov** [comment]
These camera parameters (from test_arucodetection.cpp) can be used:

```
    Size imgSize = inputImage.size();

    Mat cameraMatrix = Mat::eye(3, 3, CV_64FC1);
    cameraMatrix.at< double >(0, 0) = cameraMatrix.at< double >(1, 1) = 650;
    cameraMatrix.at< double >(0, 2) = imgSize.width / 2;
    cameraMatrix.at< double >(1, 2) = imgSize.height / 2;
    Mat distCoeffs(5, 1, CV_64FC1, Scalar::all(0));
```
![image](https://user-images.githubusercontent.com/22337800/142239279-3904a4b2-f88b-4614-8a33-76ac7c7da48a.png)

[repr_acuco.cpp.txt](https://github.com/opencv/opencv_contrib/files/7556235/repr_acuco.cpp.txt)

It remains to add the code to the tutorial and open PR.
