### ISSUE TITLE
[question] Can build opencv_contrib having just installed opencv_python?

### ISSUE THREAD

**Issue by vadimkantorov** [opencv/opencv_contrib#3073]
Basically I'd like to make just a few modifications and test them with installed opencv_python.

Can one build opencv_contrib without manually building the full opencv?

Thanks!

**Comment by berak** [comment]
> Does opencv_python ship OpenCV's shared libraries / headers?

no, you'll have to build from (github) src.

at least, there's a whitelist feature with cmake (it will only build the mentioned modules):

    cmake BUILD_LIST="core,imgproc,flann,img_hash"

please lookup your contrib modules CmakeLists.txt to see the needed dependancies, [e.g. here](https://github.com/opencv/opencv_contrib/blob/master/modules/img_hash/CMakeLists.txt#L3)
