### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'cudacodec'

### ISSUE THREAD

**Issue by i3587616** [opencv/opencv_contrib#3077]
success install pip install opencv-contrib-python

but when
cv2.cudacodec.createVideoWriter("tmp", (128, 128), 30)
it info AttributeError: module 'cv2.cv2' has no attribute 'cudacodec'
why ?
opencv-contrib-python contain cudacodec but why no module

**Comment by i3587616** [comment]
version is 4.5.3

**Comment by alalek** [comment]
CUDA is not distributed with `opencv-contrib-python`

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
