### ISSUE TITLE
Windows 10 x64 Julia 1.6.3 OpenCV 4.5.2 bindings are not working correctly

### ISSUE THREAD

**Issue by vladimir12345** [opencv/opencv_contrib#3084]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Windows 10 64 Bit
- Julia OpenCV bindings => Julia 1.6.3

##### Detailed description, Steps to reproduce

using Pkg
Pkg.add("OpenCV")
using OpenCV
const cv = OpenCV

img = cv.imread("myimg.jpg")     # it works right

cv.waitKey(Int32(5000)) # it waits correctly 5000ms, but it cannot be interrupted by the keyboard

cv.imshow("mywnd", img) # it opens a popup but freezes after that (no image inside the popup)

cv.imwrite("myimg2.jpg", img)     # it throws below error:

"ERROR: MethodError: no method matching var"#imwrite#245"(::CxxWrap.StdLib.StdVectorAllocated{Int32}, ::typeof(OpenCV.imwrite), ::String, ::OpenCV.Mat{UInt8})
Closest candidates are:
  var"#imwrite#245"(::Vector{Int32}, ::typeof(OpenCV.imwrite), ::String, ::Union{OpenCV.CxxMat, AbstractArray{T, 3} where T<:Union{Float32, Float64, Int16, Int32, Int8, UInt16, UInt8}}) at C:\julia\julia_pkg\artifacts\5ccd91240906e6ecaa95fe3dc591b1ce53d5b4db\OpenCV\src\cv_cxx_wrap.jl:2345
Stacktrace:
 [1] imwrite(filename::String, img::OpenCV.Mat{UInt8})
   @ OpenCV C:\julia\julia_pkg\artifacts\5ccd91240906e6ecaa95fe3dc591b1ce53d5b4db\OpenCV\src\cv_cxx_wrap.jl:2345
 [2] top-level scope
   @ REPL[9]:1"

**Comment by alalek** [comment]
> 4.5.2

outdated release
