### ISSUE TITLE
run python MarkerPrinter.py , get the wrong result!

### ISSUE THREAD

**Issue by xuwei1119** [opencv/opencv_contrib#3125]
when I run "python MarkerPrinter.py --chess --file "./chess.pdf" --size_x 8 --size_y 8 --square_length 0.02", I get chess.pdf(only 1kb), but when I open this pdf file, I get nothing. there is something wrong?

**Comment by AleksandrPanov** [comment]
Generated pdf file: [chess.pdf](https://github.com/opencv/opencv_contrib/files/7972972/chess.pdf)

**Comment by AleksandrPanov** [comment]
Tested on PC with Win10 and Ubuntu, pdf file opened successfully.
