### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'ximgproc'

### ISSUE THREAD

**Issue by ff12343** [opencv/opencv_contrib#3147]
##### System information (version)

- OpenCV => 4.5.4.60
- Operating System / Platform => Windows10 64 Bit
- Compiler => python3.7

##### Detailed description

I am installed opencv-python4.5.4.60, opencv-contrib-python4.5.4.60, opencv-python-headless 4.5.4.60 on conda env(python 3.7).

but when I run  cv2.ximgproc.createRightMatcher(left_matcher), AttributeError:
`AttributeError: module 'cv2' has no attribute 'ximgproc'`

opencv-python-headless and opencv-contrib-python are all needed, how should I do?

**Comment by ff12343** [comment]
![image](https://user-images.githubusercontent.com/42758082/148913672-20a1b41f-927d-4224-aab6-a2b2b611f2c9.png)
when I search the Installation package，It occurs warning Phenomenon！how should I do?

**Comment by LaurentBerger** [comment]
You cannot use opencv-python and opencv_contrib-python. uninstall both and install only opencv_contrib-python 

[Q: Do I need to install also OpenCV separately?

A: No, the packages are special wheel binary packages and they already contain statically built OpenCV binaries.](https://pypi.org/project/opencv-contrib-python/)

**Comment by livy-12138** [comment]
module 'cv2.ximgproc' has no attribute 'thinning'

**Comment by KirilIakovliev** [comment]
module 'cv2.ximgproc' has no attribute 'createSuperpixelLSC'

Any ideas?

**Comment by sturkmen72** [comment]
@KirilIakovliev what is the output of `print(cv2.getBuildInformation())`
