### ISSUE TITLE
Is there bug in hybird binarizer method in wechat qrcode?

### ISSUE THREAD

**Issue by HaoLiuHust** [opencv/opencv_contrib#3156]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

I have tested many qrcode, there is no qrcode is decoded with hybird binarizer method, and I get the output of this method, just like this issue: https://github.com/opencv/opencv_contrib/issues/3008

**Comment by HaoLiuHust** [comment]
@dddzg @alalek

**Comment by asmorkalov** [comment]
Could you provide image and code to reproduce the issue or OpenCV example options to do it.

**Comment by HaoLiuHust** [comment]
> Could you provide image and code to reproduce the issue or OpenCV example options to do it.

you can try it with https://github.com/opencv/opencv_contrib/blob/4.x/modules/wechat_qrcode/samples/qrcode_example.cpp , and output which binary method can decode sucessfully, you will see  hybird binarizer method can not decode any qrcode
![image](https://user-images.githubusercontent.com/7233091/153810762-04b298ae-345d-4290-83f5-8616435becdb.png)

**Comment by dddzg** [comment]
PR is welcomed.

**Comment by HaoLiuHust** [comment]
> PR is welcomed.

I am not famillar with this algorithm, I will try it。。。
