### ISSUE TITLE
python: 'cv2.img_hash_BlockMeanHash' object has no attribute 'compute'

### ISSUE THREAD

**Issue by doublex** [opencv/opencv_contrib#3171]
Works: opencv-contrib-python-headless-**4.5.4.60**
Fails: opencv-contrib-python-headless-**4.5.5.62**

Testcase:
````
import numpy, cv2   # pip3 install opencv-contrib-python-headless
frame = numpy.zeros((16,16,3), numpy.uint8)
hash_blockmean = cv2.img_hash_BlockMeanHash.create()
blockhash = hash_blockmean.compute(frame)
assert all(blockhash[0][i] == 0xff for i in range(32))
````
Console:
````
Traceback (most recent call last):
  File "/tmp/ab.py", line 4, in <module>
    blockhash = hash_blockmean.compute(frame)
AttributeError: 'cv2.img_hash_BlockMeanHash' object has no attribute 'compute'
````

**Comment by berak** [comment]
only current 4.5.5 pip release seems to be afflicted 
(with or without or headless)

self build master(4.5.5-dev) works fine on both win & colab
(and btw, why is master still 4.5.5-dev ? shouldn't it be 4.5.6-dev now ?)

**Comment by alalek** [comment]
Confirmed.

> `class CV_EXPORTS_W BlockMeanHash : public ImgHashBase`

`compute` is declared in base class. Something is broken in `LIMITED_API` mode.

---
`dir(hash_blockmean)` without `LIMITED_API`:

> `['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'compare', 'compute', 'create', 'getMean', 'setMode']
`

with `LIMITED_API`:

> `['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'create', 'getMean', 'setMode']`

**Comment by alalek** [comment]
Prepared a fix, please take a look: https://github.com/opencv/opencv/pull/21785

**Comment by asenyaev** [comment]
@alalek, I've tested it building `opencv-contrib-python` package with your fixes, the issue has disappeared. Thank you!

**Comment by doublex** [comment]
@alalek 
Thank you so much!

**Comment by Starry-OvO** [comment]
I found this problem also in my project, like 
```
'cv2.img_hash_AverageHash' object has no attribute 'compute'
```
This bug won't appear with `opencv-contrib-python` version `4.6.0.66` on my Windows PC, but on my Ubuntu server which is still using version `4.5.5.64` the bug still exists.
So I use a direct call (of course with lower performance)
```
img_hash_array = cv.img_hash.averageHash(img)
```
to fix the incompatibility between `opencv-contrib-python` version `4.6.0.66 (Windows)` and `4.5.5.64 (Ubuntu 20.04 LTS)`
