### ISSUE TITLE
Charuco seems inaccurate.

### ISSUE THREAD

**Issue by NMO13** [opencv/opencv_contrib#3175]
##### System information (version)

- opencv-python => 4.5.5
- Operating System / Platform => Linux 64 Bit
- Python => 3.9.7

##### Detailed description

I created a small script [here](https://github.com/NMO13/camera_calibration) which finds corners of some images containing a chessbaord pattern which I have made, calculates the fundamental matrix and visualizes epipolar lines. I used charuco for finding the corners. The problem: The epipolar lines seem always very off in the visualizations. Therefore I added `cv2.findChessboardCorners` in order to compare it with the charuco corner detection and found that it seems to be much more accurate when visualizing the epilines.

**Comment by classner** [comment]
Hi @NMO13 , @alalek ,

A thing I have done in the past is to play around with the corner refinement method. Best results (but most compute) I used to have with the Apriltag refinement. However, that is broken for me in the latest OpenCV release (installed 4.5.5.62 opencv-python and opencv-contrib-python, platform Windows 10, x64). When I use the pattern detector, it hangs indefinitely without returning a result.

**Comment by asmorkalov** [comment]
Related work: https://github.com/opencv/opencv_contrib/pull/3174

**Comment by asmorkalov** [comment]
Related issue with the algorithm hanging: https://github.com/opencv/opencv_contrib/issues/2816

**Comment by AleksandrPanov** [comment]
This PR https://github.com/opencv/opencv_contrib/pull/3174 could fix your issue. Could you attach the reproducer and images?

**Comment by asmorkalov** [comment]
@AleksandrPanov reproducer and images are located in linked repo. See description.

**Comment by AleksandrPanov** [comment]
@NMO13 thx for the very detailed description and nice code. There is a problem with `object points` for ChArUco. You created the chessboard with size **(7, 5)** and you created the ChArUco board with size = **(5, 7)** - `board = aruco.CharucoBoard_create(5, 7, square_length, marker_length, aruco_dict)`
(but in the image, you rotated the ChArUco board by 90 degrees). 
![charuco_object_points_order](https://user-images.githubusercontent.com/22337800/155003164-d8541ff0-9234-48ac-9dda-3be30b43f7e0.png)
// `object points` order of ChArUco.

![chessboard_object_points_order](https://user-images.githubusercontent.com/22337800/155005202-bc8cfe4c-0239-48fc-8757-65f4a705bb87.png)
// `object points` order of chessboard.

There are different `object points` orders for ChArUco and chessboard, in this case. You can use the field [chessboardCorners](https://docs.opencv.org/3.4/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html#a208edcbb778d3095cd5543660f6c4482) from the ChArUco board to avoid manually creating `object points`:
```
charuco_chessboard_corners = board.chessboardCorners
...
for counter in range(int(len(f)/2)):
    ...
    charuco_objpts.append(charuco_chessboard_corners)
    ...
F_charuco = calibrate(charuco_corners_list_left, charuco_corners_list_right, img_left.shape, charuco_objpts)
```
After the fix, everything works.
With `findChessboardCorners()` - error 0.686.
With `ChArUco` - error 0.298.

Also, attached is the working script.
[main.py.txt](https://github.com/opencv/opencv_contrib/files/8111275/main.py.txt)

Do you mind if photos from your repository can be used to improve the ArUco tutorial?

**Comment by AleksandrPanov** [comment]
[https://github.com/NMO13/camera_calibration](url)

**Comment by AleksandrPanov** [comment]
> Hi @NMO13 , @alalek ,
> 
> A thing I have done in the past is to play around with the corner refinement method. Best results (but most compute) I used to have with the Apriltag refinement. However, that is broken for me in the latest OpenCV release (installed 4.5.5.62 opencv-python and opencv-contrib-python, platform Windows 10, x64). When I use the pattern detector, it hangs indefinitely without returning a result.

@classner, could you attach a reproducer? [cv::aruco::CORNER_REFINE_APRILTAG](https://docs.opencv.org/4.x/d9/d6a/group__aruco.html#ggafce26321f39d331bc12032a72b90eda6a3e940dda27d11e803b40b51bde40f2c5) is working with these samples.

**Comment by AleksandrPanov** [comment]
This issue may be related to issue [opencv #8813](https://github.com/opencv/opencv/issues/8813).

**Comment by NMO13** [comment]
> @NMO13 thx for the very detailed description and nice code. There is a problem with `object points` for ChArUco. You created the chessboard with size **(7, 5)** and you created the ChArUco board with size = **(5, 7)** - `board = aruco.CharucoBoard_create(5, 7, square_length, marker_length, aruco_dict)` (but in the image, you rotated the ChArUco board by 90 degrees). ![charuco_object_points_order](https://user-images.githubusercontent.com/22337800/155003164-d8541ff0-9234-48ac-9dda-3be30b43f7e0.png) // `object points` order of ChArUco.
> 
> ![chessboard_object_points_order](https://user-images.githubusercontent.com/22337800/155005202-bc8cfe4c-0239-48fc-8757-65f4a705bb87.png) // `object points` order of chessboard.
> 
> There are different `object points` orders for ChArUco and chessboard, in this case. You can use the field [chessboardCorners](https://docs.opencv.org/3.4/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html#a208edcbb778d3095cd5543660f6c4482) from the ChArUco board to avoid manually creating `object points`:
> 
> ```
> charuco_chessboard_corners = board.chessboardCorners
> ...
> for counter in range(int(len(f)/2)):
>     ...
>     charuco_objpts.append(charuco_chessboard_corners)
>     ...
> F_charuco = calibrate(charuco_corners_list_left, charuco_corners_list_right, img_left.shape, charuco_objpts)
> ```
> 
> After the fix, everything works. With `findChessboardCorners()` - error 0.686. With `ChArUco` - error 0.298.
> 
> Also, attached is the working script. [main.py.txt](https://github.com/opencv/opencv_contrib/files/8111275/main.py.txt)
> 
> Do you mind if photos from your [repository](https://github.com/NMO13/camera_calibration) can be used to improve the ArUco tutorial?

Hi @AleksandrPanov, thanks for your effort and clear explanation!
Of course you can use my pictures.
