### ISSUE TITLE
aruco: documentation for Board class contradicts tutorial

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv_contrib#3197]
- OpenCV => 4.5.5 or thereabouts
- [documentation for aruco::Board](https://docs.opencv.org/4.x/d4/db2/classcv_1_1aruco_1_1Board.html)
- [tutorial for aruco::Board](https://docs.opencv.org/4.x/db/da9/tutorial_aruco_board_detection.html)

The tutorial states (emphasis mine)
> For each marker, its four corners are stored in the standard order, i.e. **in clockwise order** and starting with the **top left corner**.

The docs state (emphasis mine)
> array of object points of all the marker corners in the board each marker include its 4 corners **in CCW order**. For M markers, the size is Mx4.

My practical experience is that **the tutorial is right** and it even explains "standard order". The docs are wrong and incomplete there.

The API doc for `aruco::Board` should state the order clearly and correctly. If reference to "the standard order" is deemed sufficient, it should be defined in the API docs. API docs frequently refer to "clockwise" order without stating which corner is the first. That information can be inferred from the first aruco tutorial, where the top left corner is marked, and axes in the standard RGB coloring indicate this to be the -X+Y corner, order proceeding negatively around Z (i.e. clockwise looking at the marker).

Places of those docs:
- https://github.com/opencv/opencv_contrib/blob/4.x/modules/aruco/include/opencv2/aruco.hpp
- https://github.com/opencv/opencv_contrib/tree/4.x/modules/aruco/tutorials

**Comment by AleksandrPanov** [comment]
This PR fix your issue #3174.

**Comment by asmorkalov** [comment]
@crackwitz May we close the ticket then?
