### ISSUE TITLE
CharucoBoard_create regression / incompatible patterns (only even row count) with 4.6.0

### ISSUE THREAD

**Issue by stefan523** [opencv/opencv_contrib#3291]
##### System information (version)
OpenCV = 4.6.0 / 4.5.5

##### Detailed description

cv2.aruco.CharucoBoard_create creates a different pattern in 4.6.0 than in 4.5.5 for even row counts. This leads to backwards incompatibility with previous versions, previously manufactured targets, etc.

OpenCV 4.5.5:
![charuco_OpenCV-4 5 5](https://user-images.githubusercontent.com/108057787/175259962-8bb886fd-dc9c-4743-81af-98b4755a163c.png)

OpenCV 4.6.0:
![charuco_OpenCV-4 6 0](https://user-images.githubusercontent.com/108057787/175259996-cc203934-6755-43c9-8bae-8b4a871cb5b6.png)

Maybe this regression was introduced when resolving issue https://github.com/opencv/opencv_contrib/issues/2623 ? 

##### Steps to reproduce

```.py
import cv2

aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_5X5_1000)
charuco_board = cv2.aruco.CharucoBoard_create(
    squaresX = 5,
    squaresY = 4,
    squareLength = 4,
    markerLength = 3,
    dictionary = aruco_dict
)
img_board = charuco_board.draw((250,200), marginSize=0, borderBits=1)
cv2.imwrite('charuco_OpenCV-' + cv2.__version__ + '.png', img_board)
```

**Comment by alalek** [comment]
Behavior is aligned with chessboard: https://github.com/opencv/opencv/blob/4.x/doc/pattern.png

**Comment by stefan523** [comment]
> Behavior is aligned with chessboard: https://github.com/opencv/opencv/blob/4.x/doc/pattern.png

That pattern in that link is 10x7 (although it claims to be 9x6 in the caption...) and this looks the same in both versions.
![image](https://user-images.githubusercontent.com/108057787/175288358-b1077344-45a7-4d54-abab-6ba56be04df6.png)

Anyhow the change breaks backwards compatibiltiy (SW&HW).

It would help a lot to e.g. have a switch to enable the legacy pattern of pre4.6.0.

**Comment by catree** [comment]
About the chessboard pattern, this is indeed a `9x6` pattern since only corners from intersection are detected / used.

![image](https://user-images.githubusercontent.com/8229425/175417425-df40575f-5732-488e-99d2-1db142a515d2.png)

**Comment by catree** [comment]
Hmm, some more precision.

This was the code to generate the pattern (see https://github.com/opencv/opencv/pull/11046):
```bash
python gen_pattern.py -r 10 -c 7 -a A4 -T checkerboard -s 25
```

But when you are doing camera calibration (see https://github.com/opencv/opencv/blob/4.x/samples/cpp/calibration.cpp), you have to generate a `9x6` grid / corner points.

**Comment by gmedan** [comment]
> The legacy version not added to avoid using even templates, with increased re-projection error.

Why do you say that? What is this based on?

> it is recommended to use new patterns (with even row count) as the calibration might not work correctly on old patterns (with even row count)

Production code around the world relies on physical boards with even row counts, produced using pre-4.6.0 code, that cannot and will not be physically replaced to the new pattern. This renders opencv 4.6.0 unusable in many calibration/tracking systems, including ones that I developed and maintain. In #3301 the guy bought a board from [calib.io](https://calib.io), should he throw it out? Should calib.io discard their stock?

@AleksandrPanov I don't think you realize that this was a huge breaking change. A legacy flag **set to true by default** is the least that can be done to avoid breaking existing code when upgrading (speaking from experience here). @alalek what do you think?

**Comment by stefan523** [comment]
Now that 4.6.0 is out in the wild it should be worth to consider actively breaking API backward compatibility and not setting a default option, forcing developers to choose (legacy or new). Otherwise unsuspecting individuals might stumble over this issue for quite a while. Maybe someone is producing new targets with 4.6.0 now, which would break if a future version has the legacy flag set to true by default?

Either way it would be really appreciated to have the legacy functionality accessible without applying a patch manually and compiling opencv+contrib from source.

**Comment by jakobwilm** [comment]
I understand the reasoning behind the change, but I believe that backward compatibility (huge) trumps consistency here. I strongly support the opinion that a legacy switch (on by default) is needed. For developers printing patterns ad-hoc the change might not seem dramatic, but ChAruCo patterns are used in mission critical production software pipelines by many customers worldwide. No-one expects an OpenCV version update to break compatibility with older patterns. Considerable investments have been made into stock. Keeping separate pre- and post- 4.6.0 ChAruCo boards is wasteful in terms of time and resources.

Jakob // Calib.io

**Comment by stefan523** [comment]
I went ahead and created pull request https://github.com/opencv/opencv_contrib/pull/3305 with this patch. Legacy is set to "true" by default. Some small adjustments were necessary to get the unit tests working properly with both board types. All is pass now, and there are no fails regarding bad reprojection errors or similar. Changing or removing the default value of legacy would be simple enough if that would be the final verdict.

**Comment by ardiya** [comment]
I was calibrating with 4.6.0 and 8x11 board charuco board and always got huge reprojection error.

This bug is not easy to find.

Hope we can have a fix soon

**Comment by stefan523** [comment]
Andrew Martchenko showed a workaround in this comment:
https://github.com/opencv/opencv_contrib/issues/3367#issuecomment-1292874997

**Comment by gmedan** [comment]
opencv 4.7.0 is now released, with aruco moved to the main repo (not contrib). This problem was not addressed, and the legacy flag was not introduced. @stefan523 I think you should reopen the issue under the main repo and port your PR

**Comment by stefan523** [comment]
@gmedan
> opencv 4.7.0 is now released, with aruco moved to the main repo (not contrib). This problem was not addressed, and the legacy flag was not introduced. @stefan523 I think you should reopen the issue under the main repo and port your PR

Done:
https://github.com/opencv/opencv/pull/23152
https://github.com/opencv/opencv/pull/23153

**Comment by gmedan** [comment]
Kudos @stefan523!

**Comment by stefan523** [comment]
Fixed in main branch by https://github.com/opencv/opencv/pull/23153 for next OpenCV release 4.8.0.
