### ISSUE TITLE
BgSegm is not wrapped for Java

### ISSUE THREAD

**Issue by LgArcida** [opencv/opencv_contrib#330]
There a a lot of modules that cannot be enabled for Java developing.
The original question remains unanswered
http://answers.opencv.org/question/68081/opencv-30-contrib-java/

What are the steps to enable the contrib modules for Java?

**Comment by alalek** [comment]
Java bindings are not supported for this module, so they were disabled (Java bindings generation is broken here).

**Comment by LgArcida** [comment]
Will it be supported in the near future?

**Comment by samos123** [comment]
So our only option is to use javacv and javacpp-presets from here? https://github.com/bytedeco/javacpp-presets/tree/master/opencv
