### ISSUE TITLE
Dynamic Fusion testing parameters question

### ISSUE THREAD

**Issue by mush881212** [opencv/opencv_contrib#3304]
##### System information (version)
- OpenCV => 4.x
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

I tried the sample code of dynamic fusion sample (https://github.com/opencv/opencv_contrib/blob/4.x/modules/rgbd/samples/dynafu_demo.cpp) on these released data (https://github.com/opencv/opencv_extra/tree/master/testdata/cv/rgbd/dynafu), but it seems to have some problem with the result. The result is very noisy and seems to have some error mapping. I wonder if I can run the testing data with default parameters, or I need to set some parameters to get the correct result? 

Currently I run the testing data without modifying any parameters/codes, and the result of the 8th frame is shown below:
[https://drive.google.com/file/d/19jcb04o1uEGv5BWcEJq11hOgzVobdgnf/view?usp=sharing](url)
[https://drive.google.com/file/d/10-oXdsHKn_zNsG5jH4PPOwPb2j9a_3Lu/view?usp=sharing](url)
[https://drive.google.com/file/d/1WxWvt8nQXGckgVTmIElysFAaneC_5u-B/view?usp=sharing](url)

Thank for your amazing work!

**Comment by savuor** [comment]
I must say that current version of DynaFu in OpenCV is broken.
I was spending my time on fixing it by rewriting its cost function, jacobian and warp field but it's still does not work correctly.
There are no plans to fix DynaFu in the nearest future from my side, hope this will change sometime.
