### ISSUE TITLE
Wechat Qrcode crash when I detect some image

### ISSUE THREAD

**Issue by ccd0428** [opencv/opencv_contrib#3314]
When I use the API detectAndDecode in wechat_qrcode.h to detect the image 
![image](https://user-images.githubusercontent.com/9926973/181473131-b6fa46bc-f3c6-425b-a89e-d7760927cd91.png)
![image](https://user-images.githubusercontent.com/9926973/181473254-290546d7-bf92-41e0-bd90-ad40713c5336.png),
100%!!!!!!!
help!help!help!
wechater~~~

**Comment by scuzoutao** [comment]
meet the same crash too !!! this two pics has magic power, do you have any solusion to fix it?

**Comment by AleksandrPanov** [comment]
@ccd0428, @scuzoutao I use this C++ sample:
```
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core.hpp>
#include <opencv2/wechat_qrcode.hpp>
#include <iostream>
int main()
{
    cout << cv::getBuildInformation() << endl;
    std::string image_path = "img1.png";
    Mat src = imread(image_path);
    string path = "../downloads/wechat_qrcode/";
    auto qrcode = makePtr<wechat_qrcode::WeChatQRCode>(path+"detect.prototxt", path+"detect.caffemodel",
                                                                                                   path+"sr.prototxt", path+"sr.caffemodel");
    auto decoded_info = qrcode->detectAndDecode(src);
    cout << decoded_info.size();
}
```
There is no crash in my case (ubuntu 20.04, AMD ryzen 2700x). The process takes up about 130 megabytes of RAM. Could you describe your configuration? Are you using python?
