### ISSUE TITLE
GpuMat cost ~600M memory resource on TX2 while upload mono image with 640x480

### ISSUE THREAD

**Issue by panecho** [opencv/opencv_contrib#3344]
##### System information (version)
- OpenCV =>4.1
- Operating System / Platform =>Ubuntu18.04 / TX2
- Compiler =>catkin_make

##### Detailed description
My program takes ~600M memory resource after calling `upload()` function to upload a 640*480@U8C1 image to GPU.
Data in red box blow is **RSS** showed by **pidstat**
![image](https://user-images.githubusercontent.com/15884732/187184835-3681b580-dde1-4d28-ae2f-eac285142cb0.png)

Image with 640*480@U8C1 suppose takes ~1M, far less than 600M

##### Steps to reproduce

```
#include<iostream>
#include<chrono>
#include<thread>
#include <unistd.h>
#include <opencv2/core.hpp>
#include <opencv2/cudafeatures2d.hpp>

int main(int argc, char* argv[]){
    std::cout<<getpid()<<std::endl;
    using namespace std::chrono_literals;
    cv::Mat dummy_cpu_mat = cv::Mat::zeros(640, 480, CV_8UC1);
    cv::cuda::GpuMat dummy_gpu_mat;
    for(int i=0; i<20; i++){
        std::cout<<"."<<std::flush;
        std::this_thread::sleep_for(1000ms);
    }
    std::cout<<"\n upload ..."<<std::endl<<std::flush;
    dummy_gpu_mat.upload(dummy_cpu_mat);
    for(int i=0; i<20; i++){
        std::cout<<"."<<std::flush;
        std::this_thread::sleep_for(1000ms);
    }
    return 0;
}
```
By the way, sleep function here is helping to space enough time to check memory usage.

**Comment by cudawarped** [comment]
What happens when you upload/create two or n `GPUMat`s?

My suspicion is you are just seeing the memory used to create the CUDA context, and each additional `GPUMat` will use the expected amount of memory

**Comment by panecho** [comment]
> 
@cudawarped 
Yes, you almost probably right. Because two GpuMat increase little memory usage instead of 2*600M.
But same code cost only ~60M memory in other computer, I'm trying to find what make it different. 
So, If you was right,  Is there any access to limit memory cost of CUDA contex ？

**Comment by cudawarped** [comment]
Not that I'm aware of when using the runtime API maybe which OpenCv uses. It may be worth reading the [docs](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#initialization) to check.

600MB of device memory sounds like a lot some of it may be JIT compiled code have you compiled binary code for your compute capability?

-DCUDA_ARCH_BIN=

**Comment by panecho** [comment]
> 
Yes, I complied OpenCV with -DCUDA_ARCH_BIN=6.2.

**Comment by cudawarped** [comment]
> But same code cost only ~60M memory in other computer

I guess this could be due to what RSS reports or maybe the size of the OpenCV shared library or the linux version.  Either way if `cudaFree(0)` has the same impact on different machines (600MB on TX2 and 60MB on others) this is not related to OpenCV and this issue should probably be closed.

**Comment by panecho** [comment]
> 

cudaFree(0) costs about 35M in different machines.
So far as I know,  kernel functions contained in opencv shared library causes the memory cost, especially in cudafilter.so.
