### ISSUE TITLE
Missing Aruco Catkin Build Failed

### ISSUE THREAD

**Issue by ericahellscythe** [opencv/opencv_contrib#3358]
Hi I was following the instructions from a moveit tutorial.

```
mkdir -p ~/ws_moveit/src
cd ~/ws_moveit/src

wstool init .
wstool merge -t . https://raw.githubusercontent.com/ros-planning/moveit/master/moveit.rosinstall
wstool remove  moveit_tutorials  # this is cloned in the next section
wstool update -t .
git clone https://github.com/ros-planning/moveit_calibration.git
```

When I tried to catkin build, it failed. The error generated is found below. I found another closed issue posted in github moveit calibration but there was no solution to it hence this new post. I figured I needed to clone this repo but it still did not help. 

```
Errors     << moveit_calibration_plugins:cmake /home/arm-orin-01/nat_ws/logs/moveit_calibration_plugins/build.cmake.002.log
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenCV (missing: aruco) (found version "4.5.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/lib/aarch64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake:354 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)


cd /home/arm-orin-01/nat_ws/build/moveit_calibration_plugins; catkin build --get-env moveit_calibration_plugins | catkin env -si  /usr/bin/cmake /home/arm-orin-01/nat_ws/src/moveit_calibration/moveit_calibration_plugins --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/arm-orin-01/nat_ws/devel/.private/moveit_calibration_plugins -DCMAKE_INSTALL_PREFIX=/home/arm-orin-01/nat_ws/install; cd -

............................................
```

 Please advice thank you.

**Comment by asmorkalov** [comment]
Aruco module is part of [opencv_contrib](https://github.com/opencv/opencv_contrib) repository. It looks like it's missing from your OpenCV.

**Comment by asmorkalov** [comment]
Please use forum.opencv.org for questions.

**Comment by ericahellscythe** [comment]
Sorry about that, I will use that for questions next time.

On another note, I already have both opencv_contrib and moveit_calibration in my src package when I built it. 
I also have all the required rosdep installed successfully. 

Is there anything I'm doing wrong? Should the packages be elsewhere?
Catkin build can't seem to locate the aruco in opencv_contrib

**Comment by asmorkalov** [comment]
Yet another OpenCV instance may be installed somewhere. Please check CMakeCache.txt file for you project and ensure OpenCV_DIR location.

**Comment by Shillin123** [comment]
Hello, I want to ask did you solve it? I am now facing the same problem, really need your help. Thanks in advance!

**Comment by ericahellscythe** [comment]
> Hello, I want to ask did you solve it? I am now facing the same problem, really need your help. Thanks in advance!

Hi Yes I did! After you git clone the moveit_calibration, go into the moveit calibration folder, then moveit_calibration_plugin. Edit the cmakelist.txt:

> #find_package(OpenCV REQUIRED imgcodecs aruco)
> find_package(OpenCV 4)

You will also need to git clone opencv_contrib to your src folder/same workspace afterwards. 
Then open the opencv_contrib folder, go into the modules folder, then the aruco folder, and then the include folder. 
Copy the opencv2 folder found inside the include folder and paste the folder in the moveit calibration package inside moveit_calibration_plugins/handeye_calibration_target/include and every single sub folder inside the include folder too just to make sure the header file can find the aruco. 

I'm not sure exactly where to put the opencv2 folder so i pasted everywhere inside here. And this should solve this particular error.

**Comment by Shillin123** [comment]
yeah, it works now! Thanks for your help!
