### ISSUE TITLE
opencv_dnn dependency can't be resolved with NDK compile

### ISSUE THREAD

**Issue by shixpGit** [opencv/opencv_contrib#3456]
##### System information (version)
- OpenCV =4.5.5
- Operating System / Platform = x86_64 GNU/Linux
- Compiler = android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

##### Detailed description

I try to use cv::face in opencv-contrib, so I add -DOPENCV_EXTRA_MODULES_PATH=${my_opencv_contrib}/modules
then I got this:

...
-- Module **opencv_objdetect** disabled because **opencv_dnn** dependency can't be resolved!
-- Module **opencv_face** disabled because **opencv_objdetect** dependency can't be resolved!
...

##### Steps to reproduce

cmake \
-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
-DANDROID_NDK=${ANDROID_NDK} \
-DANDROID_SDK=${ANDROID_SDK} \
-DANDROID_SDK_TOOLS=${ANDROID_SDK_TOOLS} \
-DANDROID_ABI=arm64-v8a \
-DANDROID_TOOLCHAIN=clang \
-DANDROID_PLATFORM=android-26 \
-DANDROID_NATIVE_API_LEVEL=android-26 \
-DANDROID_STL=c++_shared \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_opencv_world=ON \
-DBUILD_ANDROID_EXAMPLES=OFF \
-DBUILD_ANDROID_PROJECTS=ON \
-DBUILD_ANDROID_SERVICE=OFF \
-DBUILD_CUDA_STUBS=OFF \
-DBUILD_DOCS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_FAT_JAVA_LIB=OFF \
-DBUILD_JAVA=OFF \
-DBUILD_PACKAGE=ON \
-DOPENCV_FORCE_3RDPARTY_BUILD=ON \
-DBUILD_opencv_gapi=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_TBB=OFF \
-DBUILD_TESTS=OFF \
-DBUILD_WITH_DEBUG_INFO=ON \
-DBUILD_WITH_DYNAMIC_IPP=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_ZLIB:BOOL=OFF \
-DBUILD_OPENJPEG:BOOL=OFF \
-DWITH_OPENJPEG=OFF \
-DWITH_ADE=OFF \
-DWITH_CUDA=OFF \
-DWITH_EIGEN=ON \
-DWITH_IMGCODEC_HDR=OFF \
-DWITH_IMGCODEC_PXM=OFF \
-DWITH_JPEG=ON \
-DWITH_LIBREALSENSE=OFF \
-DWITH_OPENEXR=OFF \
-DWITH_OPENMP=OFF \
-DWITH_PNG=OFF \
-DWITH_PROTOBUF=OFF \
-DWITH_PTHREADS_PF=OFF \
-DWITH_TBB=OFF \
-DWITH_TIFF=OFF \
-DWITH_CLP=OFF \
-DWITH_OPENCL_SVM=OFF \
-DWITH_IMGCODEC_SUNRAS=OFF \
-DWITH_IMGCODEC_SUNRASTER:BOOL=OFF \
-DWITH_JASPER:BOOL=OFF \
-DWITH_QUIRC:BOOL=OFF \
-DWITH_WEBP:BOOL=OFF \
-DWITH_ITT=OFF \
-D__ARM_NEON__=1 \
-DANDROID_ARM_NEON=1 \
-DBUILD_opencv_dnn=ON \
-DOPENCV_EXTRA_MODULES_PATH=${my_opencv_contrib}/modules \
..

**Comment by berak** [comment]
> -DWITH_PROTOBUF=OFF

the dnn module *needs* this to work.

**Comment by dkurt** [comment]
> > -DWITH_PROTOBUF=OFF
> 
> the dnn module _needs_ this to work.

> 

I've proposed a PR to build DNN without Protobuf for certain models formats: https://github.com/opencv/opencv/pull/23604
