### ISSUE TITLE
cuda TextureReference related API has been deprecated, any plan to move to cuda texture object related API?

### ISSUE THREAD

**Issue by thishome** [opencv/opencv_contrib#3564]
just as the title says. some cuda code in this repo uses texture reference related APIs for performance, is there a plan to move to new texture object API?

**Comment by cudawarped** [comment]
Which code are you refering to, there shouldn't be any using the old API since https://github.com/opencv/opencv_contrib/pull/3378 was merged?

**Comment by thishome** [comment]
sorry， I just checkout my local repo version, It's too old just before the merge, I have updated it. Thank you for all your efforts.
