### ISSUE TITLE
某些卷边的二维码图片无法识别

### ISSUE THREAD

**Issue by small-flyfish** [opencv/opencv_contrib#3571]
![0615_boxBackNo_BC0059151427cut](https://github.com/opencv/opencv_contrib/assets/54785741/28ab51f8-afdc-407e-ace6-1e0627df4f4e)
微信扫一扫是可以识别出二维码信息的。opencv开源的微信二维码检测无法识别
尝试了一些传统的图像处理方法，还是没有用
微信开源的二维码检测模型有最新的吗？
##### System information (version)
<!-- Example
- OpenCV => 4.5
- Operating System / Platform => ubuntu

**Comment by small-flyfish** [comment]
无法定位导致二维码未识别的原因，能不能调试微信开源的二维码模型呢？

**Comment by ShiqiYu** [comment]
It‘s not the new one in WeChat. The WeChat team did plan to contribute the new one, but they still did not.

**Comment by small-flyfish** [comment]
ok，thanks！
