### ISSUE TITLE
moments.cu(19): error: identifier "__shfl_xor_sync" is undefined

### ISSUE THREAD

**Issue by asmorkalov** [opencv/opencv_contrib#3612]
Build issue
```
/build/precommit_custom_linux/4.x/opencv_contrib/modules/cudaimgproc/src/cuda/moments.cu(19): error: identifier "__shfl_xor_sync" is undefined
          detected during:
            instantiation of "T cv::cuda::device::imgproc::butterflyWarpReduction(T) [with T=float]" 
(101): here
            instantiation of "void cv::cuda::device::imgproc::spatialMoments<TSrc,TMoments,coalesced,fourByteAligned,nMoments>(cv::cuda::PtrStepSz<TSrc>, __nv_bool, TMoments *, int) [with TSrc=uchar, TMoments=float, coalesced=true, fourByteAligned=false, nMoments=3]" 
(145): here
            instantiation of "void cv::cuda::device::imgproc::momentsDispatcherChar<TSrc, nMoments>::call(cv::cuda::PtrStepSz<TSrc>, cv::cuda::PtrStepSz<float>, __nv_bool, int, cudaStream_t) [with TSrc=uchar, nMoments=3]" 
(161): here
            instantiation of "void cv::cuda::device::imgproc::moments<TSrc,TMoments>(cv::cuda::PtrStepSzb, cv::cuda::PtrStepSzb, __nv_bool, int, int, cudaStream_t) [with TSrc=uchar, TMoments=float]" 
(168): here
```
CI link: https://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/100406/steps/compile%20release/logs/stdio

##### System information (version)
- OpenCV => 4.x
- Operating System / Platform => Linux
- Compiler => CUDA 8.0

**Comment by cudawarped** [comment]
@asmorkalov I can include version checks but that API was introduced in [CUDA 9.0](https://docs.nvidia.com/cuda/archive/9.0/cuda-c-programming-guide/index.html#warp-shuffle-functions) in Sept 2017 (> 6 years ago) previously I was told that version checks were only necessary if an api was under 5 years old.  For future reference (I'm thinking of the current NPP synchronization which will be depreciated in the next version of CUDA and replaced with the new [Application Managed Stream Context](https://docs.nvidia.com/cuda/archive/10.1/npp/index.html) API introduced in Feb 2019 in CUDA 10.1) how new does an api have to be for version checks to be applicable?

**Comment by asmorkalov** [comment]
Good question. We need to align with jetson boards first. CUDA is frozen there and cannot be easily updated. Let me finish with release activities and I'll return back.
