### ISSUE TITLE
Ogre.h cannot be found

### ISSUE THREAD

**Issue by LiChao1998** [opencv/opencv_contrib#3631]
##### System information (version)

- OpenCV version: 3.4.0
- Operating System / Platform: Ubuntu 18.04
- Compiler: gcc 7.5.0

##### Detailed description

When I build opencv 3.4.0 with opencv_contrib, the following error occurs, which says that Ogre.h cannot be found:
![image](https://github.com/opencv/opencv_contrib/assets/49675381/b7305eb0-d035-4f32-8fa7-c82061443301)
To test the Orge, I create the following file,
```
//test.cpp
#include <Ogre.h>
int main()
{
return 0;
}
```
and if I directly build with the command,
```
g++ test.cpp -o test
```
the same error occurs. It seems that Orge.h is not found because it is in the /usr/include/OGRE directory. But if I change #include <Ogre.h> to #include <OGRE/Ogre.h>, or run
```
g++ test.cpp -o test -I /usr/include/OGRE
```
, another error juts occurs, as follows:
![image](https://github.com/opencv/opencv_contrib/assets/49675381/513b829d-a384-40aa-8856-21c74ba0f309)
However, if I build test.cpp with cmake and make, where the CMakeLists.txt is like:
```
cmake_minimum_required (VERSION 2.8)

project(test)

find_package(OGRE REQUIRED)

include_directories(${OGRE_INCLUDE_DIRS})  
add_executable(ogre_test test.cpp)  
target_link_libraries(ogre_test ${OGRE_LIBS})
```
both errors are just gone. Still, if I change #include <Ogre.h> to #include <OGRE/Ogre.h>, the second error occurs.
##### Steps to reproduce
```
git clone https://github.com/opencv/opencv_contrib.git
cd opencv_contrib
git checkout 3.4.0

cd ..
git clone https://github.com/opencv/opencv.git
cd opencv
git checkout 3.4.0
mkdir build
cd build
cmake -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
make
```

**Comment by Kumataro** [comment]
Hello, OpenCV3 has been deprecated already, so please could you update to OpenCV4 ?(And OpenCV 3.4.0 is too old).

OpenCV try to find OGRE package. However between 3.4(including 3.4.0 tag) and 4.x branch, its CMake scripts are slightly changing. And OGRE version is important, however there are no information. Please could you share ?

4.x
https://github.com/opencv/opencv_contrib/blob/ba5c23ce7657d2e8aea8fcb0a234e7f7d1d081a0/modules/ovis/CMakeLists.txt#L1-L3

3.4
https://github.com/opencv/opencv_contrib/blob/f852576142dec4c99fbeb89902129192cda3e7b6/modules/ovis/CMakeLists.txt#L1-L3

3.4.0
https://github.com/opencv/opencv_contrib/blob/81ca8dab8697ae6acc5d8bc45f03b6b10f4d7d24/modules/ovis/CMakeLists.txt#L1-L3

---
In your environments, OpenCV detected OGRE package (so ovis module is available.)
pkg-config should be suggest OGRE include path and OGRE libraries.
However your compiler log shows include path is missing. I think library may be missing too. It is strange a little. 

Could you try to run standalone pkg-config to find OGRE ?

`pkg-config OGRE --modversion --cflags --libs`

And if possible, please could you try to get log of `cmake ...`  after `Found OGRE` ?

**Comment by LiChao1998** [comment]
Yes I can find the OGRE, and the version is 1.12.1.
![image](https://github.com/opencv/opencv_contrib/assets/49675381/ae0e2dbf-42a2-4818-886a-4ccb2e7f9f39)
This is the CMakeOutput.log when I run `cmake ..` for my test.cpp above.
[CMakeOutput.log](https://github.com/opencv/opencv_contrib/files/14096931/CMakeOutput.log)
Actually, I am trying to run an old repo, so OpenCV 4.x might be too new. BTW, I found that after I change the version of opencv and opencv_contrib to 3.3.0, the errors were strangely gone.

**Comment by LiChao1998** [comment]
Although OpenCV 3.3 is enough to run the repo, I wonder why the error occurs when using the version 3.4.0.

**Comment by Kumataro** [comment]
> Yes I can find the OGRE, and the version is 1.12.1.

Maybe you use not official release from ubuntu distributors. 

And OGRE 1.12 is not compatible with 1.10.
OpenCV3 may not be supported it.

https://github.com/OGRECave/ogre/blob/v1.12.1/CMake/InstallResources.cmake#L219-L222

>write_basic_package_version_file(
>    ${PROJECT_BINARY_DIR}/cmake/OGREConfigVersion.cmake 
>    VERSION ${OGRE_VERSION} 
>    COMPATIBILITY SameMajorVersion)


> (For image)

I'm sorry we have to separate `--modversion` and `--cflags --libs` options.

```bash
kmtr@ubuntu:~$ pkg-config OGRE --modversion
1.9.0
kmtr@ubuntu:~$ pkg-config OGRE --cflags --libs
-pthread -I/usr/include/OGRE -lOgreMain -lpthread
```

>This is the CMakeOutput.log when I run cmake .. for my test.cpp above.

Necessary information is console log of `cmake -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..` .
You should remove your `build` folder and clear at perfectory before this operation.


> Actually, I am trying to run an old repo, so OpenCV 4.x might be too new. 

This is OpenCV bug tracking, not Q&A forum. If you want to ask question, please use https://forum.opencv.org/
And if you want to use old OpenCV which is out of supporting,
we cannot help you in here, so it is better to close this "question" issue.

**Comment by LiChao1998** [comment]
Thank you for your answer, and I will close this issue since I can go to the forum.
