### ISSUE TITLE
CUDA Connected Components: Wrong dimension checks?

### ISSUE THREAD

**Issue by ArcherSmythe** [opencv/opencv_contrib#3693]
https://github.com/opencv/opencv_contrib/blob/6b5142ff657ca676ab35233556b49a532e75e2b7/modules/cudaimgproc/src/cuda/connectedcomponents.cu#L309

I suspect this conditional should be checking to see if both rows and columns are odd. If either one is even, there's space for the last_pixel data. If both are odd, you can't store the info in the pixel to the right or the pixel below because neither exist.

**Comment by cudawarped** [comment]
Can you supply a MRE where this causes the function to fail?

**Comment by ArcherSmythe** [comment]
No. I don't even have OpenCV installed. Try changing the unit test to use a 15x15 image instead of 16x16, and run that with compute sanitizer/memcheck. You shouldn't need to change the expected results, as the illegal address error should occur before the end of the first kernel.
