### ISSUE TITLE
cuda sgm sgbm_gpu->setSpeckleWindowSize(200);  sgbm_gpu->setSpeckleRange(1);   does not work

### ISSUE THREAD

**Issue by deepConnectionism** [opencv/opencv_contrib#3700]
![image](https://github.com/opencv/opencv_contrib/assets/20771771/6ae4516f-cbe8-464a-bfa1-e6eec18cf6b5)

There are patches in the sky that can't be removed?

我的参数如下：

```
sgbm_gpu = cv::cuda::createStereoSGM(0, 128, 10, 120, 5, cv::cuda::StereoSGM::MODE_HH4);
sgbm_gpu->setMinDisparity(0);
sgbm_gpu->setNumDisparities(128); 
int blockSize = 7; //5
sgbm_gpu->setBlockSize(blockSize);
sgbm_gpu->setP1(10);
sgbm_gpu->setP2(120);
sgbm_gpu->setUniquenessRatio(5);
sgbm_gpu->setPreFilterCap(0); 
sgbm_gpu->setSpeckleWindowSize(50); 
sgbm_gpu->setSpeckleRange(1);
sgbm_gpu->setMode(cv::cuda::StereoSGM::MODE_HH4);
sgbm_gpu->setDisp12MaxDiff(1);
```
Is there anything wrong with my data? Looking forward to your reply.

**Comment by cudawarped** [comment]
Not all of the CPU function has been implemented including [`setSpeckleRange()`](https://github.com/opencv/opencv_contrib/blob/b42682b4d151508af4729c8a5ef7da336e8fa525/modules/cudastereo/src/stereosgm.cpp#L56).
