### ISSUE TITLE
text API non exposed in python

### ISSUE THREAD

**Issue by previ** [opencv/opencv_contrib#393]
Question: is the text API extension (C++ class cv::text::OCRTesseract) exposed through python API?

**Comment by previ** [comment]
So it appears the cv::text module classes are not exported as Python, I am currently developing a very minimal solution based on two static functions: 

CV_EXPORT_W Ptr<OCRTesseract> createOCRTesseract(...);
CV_EXPORT_W string parseOCRTesseract(Ptr<OCRTesseract> ocr, Mat& image);

then build and install it with no errors but when I import cv2 in python, I get an error message like "undefined symbol createOCRTesseract".

Any hint?

**Comment by mshabunin** [comment]
Try to call it from *text& submodule: `cv2.text.createOCRTesseract`

**Comment by previ** [comment]
No luck, this is the exact error message:
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _Z13pyopencv_fromIN2cv3PtrINS0_4text12OCRTesseractEEEEP7_objectRKT_

**Comment by previ** [comment]
So I think I found the problem, but not the solution:
The undefined symbol refers to text::OCRTesseract C++ class, which is not exported to Python.
If I attempt to declare it as CV_EXPORTS_W, it generates lots of errors in the compile stage, as C++ to Python bindings are not properly defined.

I also tried to "mask" the reference to the OCRTesseract object and pass it as a void pointer (not the best solution but just to understand if it might work) but again no luck: the c++ - python bindings generator complains.

So I am stuck now, any help would be greatly appreciated.

**Comment by berak** [comment]
hi @previ , good news, i think it *is* possible, it just needs more effort

* the [base class needs to be exposed, too](https://gist.github.com/berak/ab78845cfe772dc42bb2#file-ocr-hpp-L65)

* wrap [OCRTesseract](https://gist.github.com/berak/ab78845cfe772dc42bb2#file-ocr-hpp-L89)

* add a [wrapper / overload for run()](https://gist.github.com/berak/ab78845cfe772dc42bb2#file-ocr-hpp-L116)

> here, we have to get rid of the raw pointers to various vectors, also since there is no valid std::string <-> cv::String for *non-const* references, just return it.

<pre>

Help on module cv2.text in cv2:

NAME
    cv2.text

FILE
    (built-in)

FUNCTIONS
    OCRTesseract_create(...)
        OCRTesseract_create([, datapath[, language[, char_whitelist[, oem[, psmo
de]]]]]) -> retval
...

>>> help(cv2.text.OCRTesseract_create())
OCRTesseract(33): Tesseract not found.
Help on text_OCRTesseract object:

class text_OCRTesseract(text_BaseOCR)
 |  Method resolution order:
 |      text_OCRTesseract
 |      text_BaseOCR
 |      __builtin__.object
 |
 |  Methods defined here:
 |
 |  __repr__(...)
 |      x.__repr__() <==> repr(x)
 |
 |  run(...)
 |      run(image, component_level) -> retval
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __new__ = <built-in method __new__ of type object>
 |      T.__new__(S, ...) -> a new object with type S, a subtype of T

>>> ocr = cv2.text.OCRTesseract_create()
OCRTesseract(33): Tesseract not found.
(ok, that's expected, i did not build with tesseract)

</pre>

**Comment by previ** [comment]
Oh, thank you very much, I am currently recompiling (on Raspberry Pi, it takes some time).

Before looking at your proposal, I put together a workaround which is not pretty at all, but it actually works:
[ocr.hpp](https://gist.github.com/previ/6793999bb946bda507ab)
[ocr_tesseract.cpp](https://gist.github.com/previ/ca0ba65184fd36f09130)

Apart from the python export (via three functions) I also introduced a small change in the API: I added ability to change the whitelist Tesseract paramenter at any run, In my use case this is necessary.

Thanks, again.
Roberto

**Comment by previ** [comment]
Hi, I am extending your solution for exporting to python to other OCR classes, OCRHMMDecoder and OCRBeamSearchDecoder.

Once finished, can I submit a pull request?

**Comment by lluisgomez** [comment]
Hi, Sorry for late answer ... 

Sure! Makes a lot of sense to have the text module exposed through the python API. 

Let me know if I can help somehow, but I have no previous experience with the python bindings generator...  In any case I'll take care of testing/checking your PR.

**Comment by previ** [comment]
I submitted a pull request:
https://github.com/Itseez/opencv_contrib/pull/416

It just passed build checks, let me know if I can do something else.

**Comment by pkmital** [comment]
There is also ERFilter inside the text module which is not wrapped.  I have opened a separate issue https://github.com/Itseez/opencv_contrib/issues/516 regarding that.

**Comment by sovrasov** [comment]
resolved in #416
