### ISSUE TITLE
Why opencv_world can not built together with extra modules

### ISSUE THREAD

**Issue by xialang2012** [opencv/opencv_contrib#421]
Hi, I use VS 2013 and Cmake-GUI to built Opencv 3.0 with opencv contrib modules. The problem is that if the either OPENCV_EXTRA_MODULES_PATH or BUILD_opencv_world was selected, the final built process can be done well. But if both of them were selected, the built would fail.
I have found an closed issue at https://github.com/Itseez/opencv_contrib/issues/91.

**Comment by mshabunin** [comment]
Try to build _opencv_contrib_world_ module instead:
```
cmake <some options> ..\opencv -DOPENCV_EXTRA_MODULES_PATH=..\opencv_contrib\modules -DBUILD_opencv_contrib_world=ON
