### ISSUE TITLE
text module not build for android

### ISSUE THREAD

**Issue by charlesxwang** [opencv/opencv_contrib#427]
Hi, I am trying to build opencv4android on Ubuntu 14, following this 
http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk

however, text module can not detect tesseract and lept libs.
here's my camke out put:
https://gist.github.com/happycharleswang/2af9671cbb0b455e649f

I installed tess and lept libs following this:
https://github.com/Itseez/opencv_contrib/tree/master/modules/text

why cmake can't find tess and lept?

**Comment by ajdroid** [comment]
Have you tried setting the paths in FindTesseract.cmake (inside opencv_contrib/modules/text)? If setting this works, it will mean that FindTesseract needs an update.

**Comment by happycharleswang** [comment]
I tried to set the paths in FindTesseract.cmake, by appending these:
set(Tesseract_INCLUDE_DIR /usr/local/include)
set(Tesseract_LIBRARY /usr/local/lib/libtesseract.so)
set(Lept_LIBRARY /usr/local/lib/liblept.so)
set(Tesseract_LIBS ${Tesseract_LIBRARY} ${Lept_LIBRARY})
set(Tesseract_FOUND 1)
==============================================================
The cmake outputs is here:
https://gist.github.com/happycharleswang/b6a8a7c7746551c6397e
(I am very curious, why it tried to find tesseract twice? see line 194 and 199)
==============================================================
After cmake, I issued make command, new errors are:
/home/charles/Programs/ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/lib/libtesseract.so: incompatible target
/home/charles/Programs/ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/lib/liblept.so: incompatible target
===================================================================
what does that mean? I am using the linux libs to android?
If yes, how to build tess lib for android?
Thanks.

**Comment by ajdroid** [comment]
You must build tesseract from source. If there is cmake support for
tesseract, you can cross compile it using one of the toolchains that come
with the android sdk.

Abhijat Biswas,
Final-year undergraduate (B.Tech)
Electronics and Communication Engineering
Indian Institute of Technology, Guwahati

Alt. email: abhijat@iitg.ernet.in  <abhijat@iitg.ernet.in>
Phone: +91-8721873441
