### ISSUE TITLE
MIL Tracker Implementation in 3.0.0 Has Memory Leaking

### ISSUE THREAD

**Issue by superxingzheng** [opencv/opencv_contrib#430]
I noticed obvious memory leaking when I was testing the MIL algorithm (https://github.com/Itseez/opencv_contrib/blob/master/modules/tracking/samples/tracker.cpp) with opencv and opencv_contrib both in 3.0.0. I probably won't have time to look into the source code. Hopefully some one who are familiar with this implementation can figure out where is the problem.

**Comment by lenlen** [comment]
Thanks @superxingzheng, but have you a report or log (as valgring) to address the memory leak?

**Comment by superxingzheng** [comment]
Sorry I didn't spend time to locate the leaking. I noticed the memory leaking in htop when the sample was running.@lenlen

**Comment by AdnaneKhan** [comment]
I also am experiencing a similar memory leak using the BOOSTING algorithm. It is occurring every time update is called.
