### ISSUE TITLE
new cnn_3dobj does not show up in cmake

### ISSUE THREAD

**Issue by berak** [opencv/opencv_contrib#440]
and thus won't get built.

see e.g. [here](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/1930/steps/cmake/logs/stdio)

**Comment by rmekdma** [comment]
Did you fill Caffe_INCLUDE_DIR, Caffe_LIBS entries correctly?

**Comment by berak** [comment]
@rmekdma no, there is no caffe installed here.

but it should still show up as "unavailable" , or write a message like

    Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags

**Comment by berak** [comment]
it's kinda irrelevant now.
