### ISSUE TITLE
Waldboost crash at 0 positive

### ISSUE THREAD

**Issue by bhack** [opencv/opencv_contrib#457]
https://github.com/Itseez/opencv_contrib/blob/master/modules/xobjdetect/src/waldboost.cpp#L335
doesn't handle 0 postive.

**Comment by mtamburrano** [comment]
is it possible that positive and/or negative images need to be of a minimum/maximum resolution?

**Comment by teng88** [comment]
how to define the parameter alpha in waldboost @shahurik

**Comment by teng88** [comment]
I have trained a model using this code, the detection rate is quite low
