### ISSUE TITLE
Using text module in Windows - how to deal with tesseract?

### ISSUE THREAD

**Issue by Marox44** [opencv/opencv_contrib#511]
Hello!

I was able to build _opencv_contrib_ along with _OpenCV_ itself using VS 2013 in Windows.
I was planning to try out the tesseract features in **text module**. 

Unfortunatelly, as I expected it doesn't find tesseract -> `OCRTesseract(00): Tesseract not found.`

I used the installer [mentioned on tesseract wiki here](https://github.com/tesseract-ocr/tesseract/wiki/Downloads)
It has installed correctly I think, on cmd `tesseract --version` I got :

```
tesseract 3.05.00dev
leptonica-1.72
libjpeg 9 : libpng 1.5.14 : libtiff 4.0.3 : zlib 1.2.5 : libopenjp2 2.1.0
```

It has been placed right here -> `C:\Program Files (x86)\Tesseract-OCR`

The problem is, that during `cmake` it logs `-- Tesseract: NO` two times, so I guess it simply can't find it.
There was something similar mentioned here: https://github.com/Itseez/opencv_contrib/issues/410 but it was still a Linux issue though.

The only thing I can suppose is the problem with `FindTesseract.cmake`. I've looked inside - it has only pathes for linux, and I don't really know how to change it properly in Windows, adapt the linux instructions or something  (and if it is even possible)

Thanks in advance :grinning:

**Comment by StevenPuttemans** [comment]
Maybe you can start your search [here](http://answers.opencv.org/question/61288/about-ocr-tesseract-documentation-on-opencv-300/). I suggest in the future that configuration questions are addressed at http://answers.opencv.org/questions.

**Comment by cesardelgadof** [comment]
Yo estoy compilando el modulo Text con Tesseract en Windows 10 y opencv 3.1
![build_text](https://cloud.githubusercontent.com/assets/11799571/12623345/b07d2b9e-c4f7-11e5-864d-03007ec2ccbb.png)

**Comment by cesardelgadof** [comment]
Pero tengo un error en el codigo fuente de "erfilter"
![error_text](https://cloud.githubusercontent.com/assets/11799571/12623782/c2e3eec4-c4f9-11e5-9ab5-bc96655ec7bb.png)

Parece que la funcion "min()" esta siendo tomada desde el archivo de cabecera "minwindef.h", pero deberia ser del archivo de cabecera "limits.h", esto no sucede con la funcion epsilon().

**Comment by alalek** [comment]
Try something from here: http://stackoverflow.com/questions/7449620/how-to-call-stdmin-when-min-has-been-defined-as-a-macro

**Comment by cesardelgadof** [comment]
Muchas Gracias!!. 
Esto si funciona, me ayudo mucho la linea de codigo "#undef min".

**Comment by hamdiwanis** [comment]
i have  a problem with that can u help me
![capture](https://cloud.githubusercontent.com/assets/11708544/12979618/f873f532-d0e0-11e5-8656-50641d451b14.PNG)

**Comment by cesardelgadof** [comment]
Primero tienes que descargar Leptonica: http://www.leptonica.com/download.html y luego compilar el codigo fuente.
Luego tienes que descargar Tesseract : https://github.com/tesseract-ocr/tesseract y compilar el codigo fuente. Tener en cuenta que Tesseract depende de Leptonica.

**Comment by hamdiwanis** [comment]
thanks for ur help but i already compiled the two  using this tut http://vorba.ch/2014/tesseract-3.03-vs2013.html and the problem still exist so where did i go wrong

**Comment by cesardelgadof** [comment]
Yo tengo las librerias precompiladas para Visual Studio 2015 x64. El modulo Text compilado con Tesseract .
![tesse](https://cloud.githubusercontent.com/assets/11799571/13037395/ccd902e0-d34d-11e5-8d0c-14ebf109f6d8.png)

**Comment by hamdiwanis** [comment]
i dont understand if u may explain more or just send me your compiled verision to use it

**Comment by cesardelgadof** [comment]
Aqui he creado un repositorio con los binarios de Opencv 3.1 compilado con Tesseract para Windows y Visual C++ 2015 64-bit. Espero te sirva, saludos!
https://github.com/cesardelgadof/OpenCVBinaries

**Comment by hamdiwanis** [comment]
first of all i cant be grateful enough thanks i'll try it and hope it work... Gracias :)

**Comment by cesardelgadof** [comment]
De nada. Pero tambien tienes que tener la carpeta tessdata que viene con Tesseract.
![image](https://cloud.githubusercontent.com/assets/11799571/13085563/d1f6ca04-d4ac-11e5-8556-b608a80db5ad.png)

**Comment by cesardelgadof** [comment]
Si esta carpeta teeseract no funciona, en esta carpeta se incluye la data entrenada para distintos lenguajes.

**Comment by cesardelgadof** [comment]
La data entrenada la puedes descargar de aqui.
https://github.com/UB-Mannheim/tesseract/wiki
Este es el instalador de Tesseract, aqui eliges los lenguajes para los que quieres trabajar.Por defecto esta en ingles.
![image](https://cloud.githubusercontent.com/assets/11799571/13085878/67c9a5e6-d4ae-11e5-99bc-4c407edf3985.png)
Luego de instalarlo, vas al directorio de instalacion y ya tienes el folder "tessdata", este lo puedes copiar el directorio de tu programa ejecutable
![image](https://cloud.githubusercontent.com/assets/11799571/13085955/ccde5dc8-d4ae-11e5-9004-3b615025317f.png)

**Comment by hamdiwanis** [comment]
and do i have to out the tessdata folder in a specific directory or just leave it as it was installed?

**Comment by cesardelgadof** [comment]
Create an Environment Variable:  TESSDATA_PREFIX
Colocas el directorio de "tessdata" como valor de la variable

**Comment by hamdiwanis** [comment]
than u very much and i hope i didn't annoy u with my questions :)

**Comment by thephuong010595** [comment]
Dear cesardelgadof,
I am using your OpenCVBinaries provided by you to create my own application using OpenCV and tesseract. Unfortunately, It has the same problem as Marox44. I tried so many way such as add variable, reinstall tesseract .... but the problem is still appear.
Can you help me with this sticky situation? I have been trying to search for 2 days and also rebuild openCV and tesseract but nothing's gonna change.
P/S: window 10 64x, VS 2015, openCV 3.2 and tesseract 3.05. 
Hope my question not annoy you! I'm really sorry for any inconvenience.
![problem](https://cloud.githubusercontent.com/assets/26022723/23330554/37aec894-fb83-11e6-8b8d-31831eadafb7.PNG)

**Comment by JohnTian** [comment]
When **cmake** the opencv & opencv_contrib project,  u need set the path to **tesseract_INCLUDE_DIR** and **tesseract_LIBRARY**.
Importantly, u also need to set the path of **Lept_LIBRARY**.
By the way, in your **tesseract_INCLUDE_DIR**, it must contain two subfolders: **tesseract** and **leptonica**
