### ISSUE TITLE
ERFilter Python Bindings?

### ISSUE THREAD

**Issue by pkmital** [opencv/opencv_contrib#516]
It does not seem like the ERFilter has python bindings.  It'd be great to be able to play with this in Python and replicate the text sample.

**Comment by lluisgomez** [comment]
@pkmital I've just created a Pull Request with a fist proposal for ERFilter python bindings. 
https://github.com/Itseez/opencv_contrib/pull/528
Lets see ...

**Comment by sovrasov** [comment]
resolved in #528
