### ISSUE TITLE
Does opencv_contrib_world compile?

### ISSUE THREAD

**Issue by fdncred** [opencv/opencv_contrib#525]
What's the trick to compiling opencv_contrib_world?  I successfully compliled opencv_world and all the extra modules in contrib but now i want to compile contrib_world but cmake says No when I try to Generate from cmake.
[cmake_log.txt](https://github.com/Itseez/opencv_contrib/files/99575/cmake_log.txt)

Here's an excerpt from the cmake gui log.

```
Configuring done
CMake Error at D:/Data/Src/Libraries/opencv/opencv/cmake/OpenCVUtils.cmake:769 (add_library):
  Cannot find source file:

    D:/Data/Src/Libraries/opencv/build/modules/xfeatures2d/CMakeFiles/cuda_compile.dir/src/cuda/$(Configuration)/cuda_compile_generated_surf.cu.obj

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  D:/Data/Src/Libraries/opencv/opencv/cmake/OpenCVModule.cmake:782 (ocv_add_library)
  D:/Data/Src/Libraries/opencv/opencv/cmake/OpenCVModule.cmake:729 (_ocv_create_module)
  D:/Data/Src/Libraries/opencv/opencv/cmake/OpenCVModule.cmake:938 (ocv_create_module)
  D:/Data/Src/Libraries/opencv/opencv_contrib/modules/contrib_world/CMakeLists.txt:30 (ocv_define_module)


CMake Error: CMake can not determine linker language for target: opencv_contrib_world
CMake Error in D:/Data/Src/Libraries/opencv/opencv_contrib/modules/contrib_world/CMakeLists.txt:
  Exporting the target "opencv_contrib_world" is not allowed since its linker
  language cannot be determined
```

The first error, complaining about a file that doesn't exist, is wrong.  That file exists in the Release configuration path exactly as it indicates.

I'm unsure about what to do with the other errors.

Full cmake log attached.

**Comment by alalek** [comment]
opencv_contrib_world build doesn't work.
Try to build static regular OpenCV modules and link with them (via `BUILD_SHARED_LIBS=OFF`) to eliminate large set of dependencies.

**Comment by gblikas** [comment]
@alalek So, what is the point of having opencv_contrib_world inside the main folder/project then? Could it be moved into some Archive folder, or something? The fact that it doesn't build is a big let-down.

**Comment by scimad** [comment]
Fixed by https://github.com/opencv/opencv/pull/8044, right @alalek ? Can close this one.

**Comment by alalek** [comment]
`contrib_world` was removed from modern OpenCV.
