### ISSUE TITLE
Memory leak in OCRHMMClassifierCNN

### ISSUE THREAD

**Issue by tolgabirdal** [opencv/opencv_contrib#529]
In file ocr_hmm_decoder.cpp, the function OCRHMMClassifierCNN has a memory leak. The predicted labels aren't de-allocated after copying to output vectors. This could be added as the last line:
```.cpp
delete[] p;
```
OCRBeamSearchClassifierCNN handles this issue by creating the vector as a pointer to already allocated "p" array.

**Comment by StevenPuttemans** [comment]
Could you provide a PR with the fix?

**Comment by sushruta** [comment]
bump @tolgabirdal, are you working on this?

Otherwise, I can make a quick PR to get this out ...

**Comment by tolgabirdal** [comment]
Please proceed. I am not currently updating this.
