### ISSUE TITLE
errors on build opencv with cvv module and qt5

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv_contrib#577]
```
OpenCV version: 3.x (current master branch 14.03.2016 ~15.00 GTM

Win 7 x64, VS 2013, cmake 3.4.3
Win XP x32, VS 2010, cmake 3.4.3
```

When checked both of parameters WITH_QT and BUILD_OPENCV_CVV:
    in Winodws 7 I receive 328 errors
    in Windows XP - 6261 errors. If this parameters chosen separate in the same configuration - build successful.

UPD. On Linux (xubuntu x86) build with the same paramerters is successful.

Archive of 2 log files obtained from msbuild
msbuild OpenCV.sln /flp:logfile=msvc2010_cvv.log /clp:parameters=ErrorsOnly /t:rebuild
in attachment.

[err_log.zip](https://github.com/Itseez/opencv_contrib/files/172757/err_log.zip)

**Comment by mshabunin** [comment]
Try to use latest _opencv_contrib_ version, there were some fixes to _cvv_ build process recently. 

AFAIK VS 2010 does not support C++11 and _cvv_ module uses them internally - try to add `-DBUILD_opencv_cvv=OFF` cmake option to disable the whole module (looks like we also need to determine such problems in cmake script automatically).

**Comment by Bleach665** [comment]
@mshabunin. Still 328 errors when building on Win7 x64, VS 2013, cmake 3.3.2, Opencv versoin - 3.1.0-638-g64a5126.

**Comment by mshabunin** [comment]
@Bleach665 , can you post here first 5 of them? Did you try to make a clean build (in fresh build directory)?

**Comment by Bleach665** [comment]
The build was absolutly clean. Configured by gui cmake 3.3.2. While configuring BUILD_DOCS, BUILD_PERF_TESTS and BUILD_TESTS entry was unchecked. WITH_QT was checked and OPENCV_EXTRA_MODULES_PATH specified. The rest remained in the default state. Build has been made through VS2013 x86 command prompt by command 
`msbuild OpenCV.sln /flp:logfile=msvc2013_cvv.log /clp:ErrorsOnly > msvc2013_cvv_err.log`

First errors:
e:\ocv\opencv_contrib\modules\cvv\src\controller\../util/util.hpp(75): error C2
610: 'cvv::util::Reference<T>::Reference(cvv::util::Reference<T> &&)' : is not
a special member function which can be defaulted (E:\ocv\opencv_contrib\modules
\cvv\src\controller\view_controller.cpp) [E:\ocv\build_x86\modules\cvv\opencv_c
vv.vcxproj]
e:\ocv\opencv_contrib\modules\cvv\src\controller\../util/util.hpp(77): error C2
610: 'cvv::util::Reference<T> &cvv::util::Reference<T>::operator =(cvv::util::R
eference<T> &&)' : is not a special member function which can be defaulted (E:\
ocv\opencv_contrib\modules\cvv\src\controller\view_controller.cpp) [E:\ocv\buil
d_x86\modules\cvv\opencv_cvv.vcxproj]
e:\ocv\opencv_contrib\modules\cvv\src\controller\../impl/call.hpp(102): error C
2610: 'cvv::impl::Call::Call(cvv::impl::Call &&)' : is not a special member fun
ction which can be defaulted (E:\ocv\opencv_contrib\modules\cvv\src\controller\
view_controller.cpp) [E:\ocv\build_x86\modules\cvv\opencv_cvv.vcxproj]
e:\ocv\opencv_contrib\modules\cvv\src\controller\../impl/call.hpp(105): error C
2610: 'cvv::impl::Call &cvv::impl::Call::operator =(cvv::impl::Call &&)' : is n
ot a special member function which can be defaulted (E:\ocv\opencv_contrib\modu
les\cvv\src\controller\view_controller.cpp) [E:\ocv\build_x86\modules\cvv\openc
v_cvv.vcxproj]
e:\ocv\opencv_contrib\modules\cvv\src\gui\../controller/view_controller.hpp(283
): fatal error C1903: unable to recover from previous error(s); stopping compil
ation (E:\ocv\opencv_contrib\modules\cvv\src\controller\view_controller.cpp) [E
:\ocv\build_x86\modules\cvv\opencv_cvv.vcxproj]

Full build log attaced in file msvc2013_cvv.l
[vs2013_cvv_logs.zip](https://github.com/Itseez/opencv_contrib/files/286529/vs2013_cvv_logs.zip)
og. And only errors in msvc2013_cvv_err.log.

**Comment by gylns** [comment]
@mshabunin It seems that "default generation of move constructor is unsupported in VS2013". Some similar problems from tiny-dnn [#231](https://github.com/tiny-dnn/tiny-dnn/issues/231).

**Comment by Bleach665** [comment]
In current version opencv this bug resolved.
