### ISSUE TITLE
Error on compiling: caffe/vision_layers.hpp: No such file or directory

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv_contrib#580]
I am getting compilation error 

In file included from /home/jason/opencv_contrib/modules/cnn_3dobj/src/precomp.hpp:45:0,
                 from /home/jason/opencv/build/modules/cnn_3dobj/opencv_cnn_3dobj_pch_dephelp.cxx:1:
/home/jason/opencv_contrib/modules/cnn_3dobj/include/opencv2/cnn_3dobj.hpp:68:35: fatal error: caffe/vision_layers.hpp: No such file or directory
 #include <caffe/vision_layers.hpp>
                                   ^
compilation terminated.

I checked the master branch of caffe https://github.com/BVLC/caffe, and no vision_layers.hpp exist. Please look into this. Thanks!

Edit: I am on Ubuntu 14.04

**Comment by alalek** [comment]
Workaround is to use older version of caffe, not the latest master.

**Comment by jasjuang** [comment]
Thanks for the quick response, I will do that for now. Hope to see a fix
that allow us to use the newest caffe in the future.

On Tue, Mar 15, 2016 at 9:16 AM, Alexander Alekhin <notifications@github.com
