### ISSUE TITLE
Need original paper reference in DisparityWLSFilter

### ISSUE THREAD

**Issue by gqphd** [opencv/opencv_contrib#587]
https://github.com/Itseez/opencv_contrib/blob/2de6ff576c75ab96e10f5b38dfcfeae013471b63/modules/ximgproc/include/opencv2/ximgproc/disparity_filter.hpp#L78

In this link, reference to original paper is needed. Otherwise, not many could understand the program and improve it, so, please.

**Comment by mshabunin** [comment]
References have been added [here](https://github.com/Itseez/opencv_contrib/commit/7c421ba2b39b8869a7b89cabdd167a3eb5e55963#diff-52ae9091791bac0bb959b7554ee3a53b), [documentation reference](http://docs.opencv.org/3.1.0/de/d13/classcv_1_1ximgproc_1_1FastGlobalSmootherFilter.html#details)

cc @sbokov

**Comment by gqphd** [comment]
Oh much thanks :+1:

**Comment by RoyiAvital** [comment]
Is there a way to contact @sbokov ?

**Comment by KeoChi** [comment]
Someone knows which paper this method "computeConfidenceMap()" came from?
