### ISSUE TITLE
Aruco detectMarkers crashing

### ISSUE THREAD

**Issue by anuppari** [opencv/opencv_contrib#595]
Using the latest source of opencv and the contrib modules on github, aruco detect markers crashes with the following error:

```
OpenCV Error: Assertion failed (mtype == type0 || (CV_MAT_CN(mtype) == CV_MAT_CN(type0) && ((1 << type0) & fixedDepthMask) != 0)) in create, file /home/ncr/Downloads/opencv-master/modules/core/src/matrix.cpp, line 2383
Exception :/home/ncr/Downloads/opencv-master/modules/core/src/matrix.cpp:2383: error: (-215) mtype == type0 || (CV_MAT_CN(mtype) == CV_MAT_CN(type0) && ((1 << type0) & fixedDepthMask) != 0) in function create
```

The relevant code I am trying to run is below, essentially verbatim of what is in the samples. It compiles fine, I can see the image fine in the window, but it crashes on the line where I call `detectMarkers`. Interestingly, it does not crash if there are no markers in the image, it only crashes if there is a marker. Through some basic outputting to the command line, I think it's crashing in the `_identifyCandidates` function in `aruco.cpp`, but I'm not sure.

Please let me know if there is any more information I can provide.

``` C++
...
cv::Ptr<cv::aruco::Dictionary> markerDictionary = cv::aruco::getPredefinedDictionary(cv::aruco::DICT_ARUCO_ORIGINAL);
cv::Ptr<cv::aruco::DetectorParameters> detectorParams = cv::aruco::DetectorParameters::create();
detectorParams->doCornerRefinement = true;

std::vector< std::vector<cv::Point2d> > markerCorners;
std::vector<int> markerIDs;
std::vector<cv::Vec3d> rvecs, tvecs;
cv::Mat testImage = cv::imread("/home/ncr/frame.jpg");
cv::imshow("window",testImage);
cv::waitKey(10);
cv::aruco::detectMarkers(testImage,markerDictionary,markerCorners,markerIDs,detectorParams);
...
```

**Comment by JSnader** [comment]
I can reproduce this error, but only by using
`std::vector< std::vector<cv::Point2d> > markerCorners;`
instead of 
`std::vector< std::vector<cv::Point2f> > markerCorners;`

It seems as though the function is expecting float value vectors, not doubles.  But I did get this error you speak of when working with my `estimatePoseBoard` so you now may have led me to a solution for myself.

Let us know if this was the issue you experienced and if this resolves it.

**Comment by AleksandrPanov** [comment]
detectMarkers() need `Point2f ` type for corners
type cast will be added in next PR
