### ISSUE TITLE
Handling To Remove Tracked Object in Tracking

### ISSUE THREAD

**Issue by wahgan** [opencv/opencv_contrib#619]
It seems that if the tracked objects disappears from the scene, the tracking model still produces the bounding box for the next frame (tested in KCF and MIL tracking). It can be one improvement for future to automatically delete the tracked objects which don't exist anymore on the scene.

**Comment by alalek** [comment]
check `.update()` call return value. Bounding box is valid if result is true.

duplicated issue for `MultiTracker` is here: #2377

**Comment by Damon2019** [comment]
I also met the same problem. Have you solved it?
