### ISSUE TITLE
xobjdetect: WaldBoost crash

### ISSUE THREAD

**Issue by berak** [opencv/opencv_contrib#633]
if WaldBoost::fit() runs [out of good negatives](https://github.com/Itseez/opencv_contrib/blob/master/modules/xobjdetect/src/waldboost.cpp#L320) (pos==0),
[data_neg](https://github.com/Itseez/opencv_contrib/blob/master/modules/xobjdetect/src/waldboost.cpp#L331) will get resized to 0 elements, causing an out of bounds exception in the [next iteration](https://github.com/Itseez/opencv_contrib/blob/master/modules/xobjdetect/src/waldboost.cpp#L234)

**Comment by bnascimento** [comment]
Does someone know what are good training positive and negatives number of samples?
