### ISSUE TITLE
vs2013 dnn googlenet work wrong in release mode

### ISSUE THREAD

**Issue by lzx1413** [opencv/opencv_contrib#667]
I just run the sample [dnn code](http://docs.opencv.org/3.1.0/d5/de7/tutorial_dnn_googlenet.html#gsc.tab=0) with vs2013 on win10 ,when running in debug mode the result is right,but when running in release mode,all the result possibilities become -1.#IND, does someone know the reason?thanks.

**Comment by ludv1x** [comment]
Hello @lzx1413 
I have checked described problem on my laptop (Windows 10 x64, VS 2013) and could not reproduce it.
Could you provide more details?

It's a [screenshot](https://dl.dropboxusercontent.com/u/62894726/GSoC/github/googlenet_vs13.png) with running example and VS version window.

**Comment by lzx1413** [comment]
[debug](https://www.dropbox.com/s/3l6sj0vl5ohkadp/vs_2013_debug.PNG?dl=0)
[release](https://www.dropbox.com/s/7b1vsdrzu898922/vs_2013_release.PNG?dl=0)
maybe there is something wrong when I compile the lib in release mode
