### ISSUE TITLE
compile error with cmake option BUILD_opencv_world on

### ISSUE THREAD

**Issue by mxmxlwlw** [opencv/opencv_contrib#677]
I compile opencv with extra modules. And turn the cmake option BUILD_opencv_world  on. However, the library can't be built. When I build without extra modules, everything's fine.
the compiler says it can't find “opencv2/xfeatures2d/cuda.hpp”.

**Comment by alalek** [comment]
For opencv_contrib there is `BUILD_opencv_contrib_world` option, but it doesn't work as expected also.

**Comment by mxmxlwlw** [comment]
@alalek Thank you for reply. Do you mean I can only compile opencv with extra modules when the BUILD_opencv_world and BUILD_opencv_contrib_world off?
