### ISSUE TITLE
LNK2019 Unresolved External Symbol

### ISSUE THREAD

**Issue by SumeetBatra** [opencv/opencv_contrib#685]
Hi,

I have OpenCV 3.1.0 installed. I also installed opencv_contrib-3.1.0 but am getting the following error trying to use xfeatures2d. 

```
Error   LNK2019 unresolved external symbol "public: static struct cv::Ptr<class cv::xfeatures2d::SIFT> __cdecl cv::xfeatures2d::SIFT::create(int,int,double,double,double)" (?create@SIFT@xfeatures2d@cv@@SA?AU?$Ptr@VSIFT@xfeatures2d@cv@@@3@HHNNN@Z) 

Breakpoint: Ptr<Feature2D> f2d = xfeatures2d::SIFT::create();
```

I did a little research and found that the opencv_contrib version needs to be the same as the opencv version. In my case it is, but I am still getting this error.  

UPDATE: I tried installing opencv 3.1.0 through the NuGet package manager and running the same code but got the same error.

**Comment by nickynine** [comment]
I am, facing the exact same problem.Opencv 3.1.0 , contrib 3.1.0.

**Comment by sinnuswong** [comment]
I am facing the exact same problem.
I am a chinese programmer.
error LNK2019: 无法解析的外部符号 "public: static struct cv::Ptr<class cv::xfeatures2d::SIFT> __cdecl cv::xfeatures2d::SIFT::create(int,int,double,double,double)" (?create@SIFT@xfeatures2d@cv@@SA?AU?$Ptr@VSIFT@xfeatures2d@cv@@@3@HHNNN@Z)，该符号在函数 main 中被引用
1>C:\Users\sinnus\Documents\Visual Studio 2015\Projects\Picture\x64\Debug\Picture.exe : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by Dikay900** [comment]
A compilable example of someone who has these problems would be highly appreciated.

System specs seems to be: Windows x64, VS 2015.

You can try the latest master of both opencv and opencv_contrib repo.

**Comment by lonewolf9277** [comment]
I'm facing the same issue. Please help. I cannot find the nonfree library either.

**Comment by Dikay900** [comment]
the nonfree library does not exist anymore with the beginning of opencv 3.
the used library mentioned here is xfeatures2d.

**Comment by sxp9646** [comment]
Any solutions? Ran into the exact same problem as described :(

**Comment by M-AMAIRI** [comment]
Hi , 

i have solved this error , just  make sure that you have included every .lib needed on your opencv project

**Comment by DimitarVel** [comment]
@M-AMAIRI I included all the libraries that were provided by the C-Make build. 
I do not have the full version (the one with SIFT, SURF etc) but i found a 3.4.2 opencv version that had these algorithms so i built them and included them in my includes folder. 
VS15 seems to be loading them fine, but i get this error during compilation.
