### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by harshmunshi** [opencv/opencv_contrib#690]
When I follow the steps and try to build it, I get the following error

CMake Error at /home/harsh/opencv_contrib/modules/xobjdetect/tools/waldboost_detector/CMakeLists.txt:16 (ocv_include_modules_recurse):
 Unknown CMake command "ocv_include_modules_recurse".

**Comment by arpit1997** [comment]
I don't know the exact source of error but i can suggest a few points to be considered;

- clone latest opencv_contrib repo
- try this command for your opencv installation 
``` bash
$ cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX-/usr/local -D \
PYTHON3_EXECUTABLE-/usr/bin/python3.4 -D PYTHON_INCLUDE_DIR=/usr/include/python3.4 -D \
PYTHON_INCLUDE_DIR2=/usr/include/x86_64-linux-gnu/python3.4m -D PYTHON_LIBRARY=/usr/lib/x86_64\
linux-gnu/libpython3.4m.so -D PYTHON3_NUMPY_INCLUDE_DIRS=/usr/lib/python3/dist- \
packages/numpy/core/include/ -D PYTHON3_PACKAGES_PATH=/usr/lib/python3/dist-packages -D 
WITH_VTK=OFF -D OPENCV_EXTRA_MODULES_PATH=/path/to/contrib/modules -D BUILD_NEW_PYTHON_SUPPORT=ON ..
```
Hope it helps

**Comment by harshmunshi** [comment]
it did :+1:
