### ISSUE TITLE
client server bind

### ISSUE THREAD

**Issue by vkoushik** [opencv/opencv_contrib#726]
Hi,

openCV 3.1
Xcode 7.3
Mas OSX 10.11.5

I implemented openCV in a command line tool project and i wanted to implement a client server interaction. I included all the required codes and i am getting an error in bind() method.Below is the code

if(bind(sockfd, (struct sockaddr *) &serv_addr,
         sizeof(serv_addr))<0)

The same line works fine in a simple c++ program but when i add the openCV library, it throws an error stating "invalid operands to binary expression ('_bind<int &,sockaddr *,unsigned long'> and 'int'"

Can you someone please help me with this issue?

Thank you

**Comment by kirill-kornyakov** [comment]
The issue doesn't seem to be relevant to OpenCV... You should better post your question to answers.opencv.org.
