### ISSUE TITLE
Plot module is undocumented

### ISSUE THREAD

**Issue by mshabunin** [opencv/opencv_contrib#728]
##### Detailed description

Plot module needs some documentation

**Comment by StevenPuttemans** [comment]
@nmoutinho promised a couple of months ago that he would look into it. Guess he did not find the time yet!

**Comment by nmoutinho** [comment]
@StevenPuttemans unfortunately I did not find the time to do it, but I will do it for sure. Sorry about that..

**Comment by StevenPuttemans** [comment]
No problem! Just wanted to see if it was still coming or not ;)
