### ISSUE TITLE
Module sfm in opencv_contrib

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#743]
Hi,

In opencv contrib there is a module called sfm which implement structure from motion using eigen glogs gflags and ceres solver.

I understand ceres solver( for levenberg  I think) for retroprojection, eigen may be for some matrix calculation, but why module need glogs and gflags?

thanks for your answer

@edgarriba

**Comment by edgarriba** [comment]
all the core maths are based in libmv which requires glogs and gflags. Probably this can be refactored, but I don't have too much time for that now.

Take a look at this: https://github.com/opencv/opencv_contrib/tree/master/modules/sfm/src/libmv_light/libmv

**Comment by Aozhi** [comment]
Hi,

May I ask that, can this module be used on android platform?

**Comment by terfendail** [comment]
@Aozhi Looks like there is an issue #775 with SFM configuration for Android. Also I suppose there could be some compilation and link issues while preparing dependencies required by libmv.
