### ISSUE TITLE
Aruco problem

### ISSUE THREAD

**Issue by mrdebug** [opencv/opencv_contrib#764]
I obtain this error:

Scanning dependencies of target opencv_aruco
[ 94%] Building CXX object modules/aruco/CMakeFiles/opencv_aruco.dir/src/aruco.cpp.o
/home/denis/Cpp/opencv-3.1.0/modules/opencv_contrib-master/modules/aruco/src/aruco.cpp: In function ‘double cv::aruco::calibrateCameraAruco(cv::InputArrayOfArrays, cv::InputArray, cv::InputArray, cv::Ptr<cv::aruco::Board>&, cv::Size, cv::InputOutputArray, cv::InputOutputArray, cv::OutputArrayOfArrays, cv::OutputArrayOfArrays, cv::OutputArray, cv::OutputArray, cv::OutputArray, int, cv::TermCriteria)’:
/home/denis/Cpp/opencv-3.1.0/modules/opencv_contrib-master/modules/aruco/src/aruco.cpp:1608:59: error: cannot convert ‘const cv::_OutputArray’ to ‘int’ for argument ‘8’ to ‘double cv::calibrateCamera(cv::InputArrayOfArrays, cv::InputArrayOfArrays, cv::Size, cv::InputOutputArray, cv::InputOutputArray, cv::OutputArrayOfArrays, cv::OutputArrayOfArrays, int, cv::TermCriteria)’
                            _perViewErrors, flags, criteria);

**Comment by StevenPuttemans** [comment]
Just tested, there has been a pull with some changes to the aruco module yesterday, but basically grabbing latest master branch of both opencv and opencv_contrib repo, led me to a 100% successfull compilation of the ARUCO module!

**Comment by KennethWilke** [comment]
I got this error as well using the 3.1.0 source release with the master branch of this repo. Will try using the master branch of the main opencv repo

**Comment by StevenPuttemans** [comment]
Well that is exactly the reason. Both repos neef to be in the same progress state. Else they mismatch, hence the errors...

**Comment by mrdebug** [comment]
I used the official OpenCV 3.1 release and the github contrib modules.

In data venerd� 26 agosto 2016 13:36:51, Steven Puttemans ha scritto:
> hence
-- 
www.denisgottardello.it
GMT+1
Skype: mrdebug

**Comment by mrdebug** [comment]
I have retryed just now having the same error.

In data venerd� 26 agosto 2016 23:04:09, Denis ha scritto:
> I used the official OpenCV 3.1 release and the github contrib modules.
> 
> In data venerd� 26 agosto 2016 13:36:51, Steven Puttemans ha scritto:
> > hence
-- 
www.denisgottardello.it
GMT+1
Skype: mrdebug

**Comment by StevenPuttemans** [comment]
> I used the official OpenCV 3.1 release

I guess you downloaded it from the download page? If so, skip that and take the latest branch from github for the main repo also! If that is not the issue, please some up every single step you performed for installing OpenCV, with the CMAKE output, so that we can start digging why it does not work for you!

**Comment by StevenPuttemans** [comment]
@KennethWilke 

> Edit: Will actually just use the 3.1.0 release of this repo! I think that makes more sense for my needs :D

Actually that does not make sense, since only a few days ago, major bugs in aruco module got fixed. So grab latest branch of both repos please!
