### ISSUE TITLE
Add Rect2D to Java bindings

### ISSUE THREAD

**Issue by elbaro** [opencv/opencv_contrib#767]
This is similar to the python case: https://github.com/opencv/opencv_contrib/issues/415

I tried to compile the `tracking` module for Java, and the generated `Tracker` java class looks like this:

```

    // C++:  bool init(Mat image, Rect2d boundingBox)
    //

    // Unknown type 'Rect2d' (I), skipping the function


    //
    // C++:  bool update(Mat image, Rect2d& boundingBox)
    //

    // Unknown type 'Rect2d' (O), skipping the function
```

**Comment by berak** [comment]
@elbaro , i don't have java around, so i can't test, but if you want to try, all it might need is another [entry for Rect2d here](https://github.com/opencv/opencv/blob/master/modules/java/generator/gen_java.py#L261) , just with double, not int.

```
    "Rect2d"    : { "j_type" : "Rect2d",  "jn_args" : (("double", ".x"), ("double", ".y"), ("double", ".width"), ("double", ".height")),
                  "jni_var" : "Rect %(n)s(%(n)s_x, %(n)s_y, %(n)s_width, %(n)s_height)", "jni_type" : "jdoubleArray",
                  "suffix" : "DDDD"},
```

**Comment by elbaro** [comment]
@berak Thank you. Here is extra changes I made:

1. set jni_var to Rect2d (not Rect)
2. add 'vector_Rect2d' with MatOfRect2d (refer to vector_Rect)
3. Add 'Rect2d' in line 829 (self.imports.add("org.opencv.core." + j_type)) so it is automatically imported in java files.
4.
- Go to modules/core/misc/java/src/java and Create 'core+Rect2d.java' and 'core+MatOfRect2d.java'
- Copy from core+Rect.java and core+MatOfRect.java respectively
- Change ints to doubles appropriately, CV_32S to CV_64F, and typenames to new ones.

5. define 'Mat_to_vector_Rect2d' and 'vector_Rect2d_to_Mat' in converters.cpp, .h, utils+Converters.java

6. cmake again to include new files

--------
It is surprising that trackers use Rect2d(double) instead of Rect(int). Does one really need to predict a bounding box in double coordinates (like 1/3 of one pixel) ?

**Comment by berak** [comment]
oh, thanks for ths feedback ;)

indeed, the tracker functionality has increased quite a lot, so it needed some more classes, again nice, that you tried it !

> Does one really need to predict a bounding box in double coordinates (like 1/3 of one pixel) ?

i don't have the slightest idea. probably it would have been more smart to use Rect2d internally, and have a simple Rect in the interface, but i guesss, the author did not see the nessecities, that come with wrapping to python or java, and now it's just the way it is ..

again, thanks a lot, and if it works - dare to make a pr from it !

**Comment by elbaro** [comment]
The change above compiles fine, but it crashes on Tracker.init().
I am not familiar with JNI but this is my guess:

In the generated file `build/modules/java/tracking.cpp`,
`Java_org_opencv_tracking_Tracker_create_10` returns `Tracker*`, not `Ptr<Tracker>*`.

So in the java, when you call `create` it actually represents the address of C++ Tracker object.

```
Ptr_Tracker _retval_ = cv::Tracker::create( n_trackerType );
Ptr_Tracker* curval = new Ptr_Tracker(_retval_);
return (jlong)curval->get(); // returns Tracker*, not Ptr<Tracker>*
```
And when you java call tracker.init(), the binding interprets the above address as the address of Ptr<Tracker>.

```
Ptr<cv::Tracker>* me = (Ptr<cv::Tracker>*) self;
```

The firewall doesn't let me commit or pr. Someone please take a look at this :/

**Comment by berak** [comment]
imho, you have to return `(jlong)curval` , not `(jlong)curval->get()`

**Comment by elbaro** [comment]
It seems there is a bug in the current Tracker class (C++).

This doesn't work:
```
Ptr<Tracker> tracker = Tracker.create("KCF");
tracker.init(mat, Rect2d(10,10,100,100));
Rect2d rect;
tracker.update(mat, rect);
printf("%.2f %.2f %.2f %.2f\n", rect.x, rect.y, rect.width, rect.height);
// print 0,0,0,0
```

This works:
```
MultiTracker mtracker("KCF");
mtracker.add(mat, Rect2d(10,10,100,100));
mtracker.update(mat);
Rect2d rect = mtracker.objects[0];
printf("%.2f %.2f %.2f %.2f\n", rect.x, rect.y, rect.width, rect.height);
// print 10,10,100,100
```

Actually the latest doc for Tracker.create only lists MIL and Boosting:
http://docs.opencv.org/master/d0/d0a/classcv_1_1Tracker.html#a504f56fb050c2ef0ad5bce144f1e7963

**Comment by elbaro** [comment]
I confirm that applying the above changes & using MultiTracker w/ KCF work.
Note that changing to `(jlong)curval` is a temporary fix because the file is auto-generated.

**Comment by berak** [comment]
can't reproduce your bug. (both print 10 10 100 100 here) also: Tracker::create, not Tracker.create

**Comment by IeiuniumLux** [comment]
@elbaro what sample code did you use to test/validate that MultiTracker w/ KCF works in Java?
