### ISSUE TITLE
Undeclared reference to reconstruct function

### ISSUE THREAD

**Issue by KSheth96** [opencv/opencv_contrib#779]
##### Detailed description

I am running your ditto example code provided in [the OpenCV reconstruct tutorial](http://docs.opencv.org/trunk/d4/d18/tutorial_sfm_scene_reconstruction.html) but i am getting the following error while doing make

"undefined reference to `cv::sfm::reconstruct(std::vector<std::string, std::allocator<std::string> >, cv::_OutputArray const&, cv::_OutputArray const&, cv::_InputOutputArray const&, cv::_OutputArray const&, bool)"

**Comment by berak** [comment]
you probably built without CERES, and the implementation of the reconstruct functions [was commented out](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/src/reconstruct.cpp#L38) ?

**Comment by mshabunin** [comment]
@KSheth96 , try to build OpenCV with _sfm_ module enabled (need to install _libceres_ and other dependencies) and `-DBUILD_EXAMPLES=ON` cmake option, it should produce the example you need.

**Comment by prudhvigurram** [comment]
@mshabunin I am new to opencv and was trying to implement scene_reconstruction code (https://docs.opencv.org/3.2.0/d4/d18/tutorial_sfm_scene_reconstruction.html)
Facing the same issue as @ksheth96 .
What do you mean by ' try to build OpenCV with sfm module enabled and -DBUILD_EXAMPLES=ON cmake option'. Can you please explain it step-wise?

**Comment by mshabunin** [comment]
@prudhvigurram , you should build OpenCV and all samples will be built automatically:
1. Install prerequisites: _cmake_, _make_, compiler (_gcc_/_clang_), development libraries needed by the _viz_ module (_libvtk6-dev_), development libraries needed by the _sfm_ module (_libceres-dev_
 or see the [instruction](https://docs.opencv.org/3.2.0/db/db8/tutorial_sfm_installation.html))
2. Clone OpenCV sources: `git clone https://github.com/opencv/opencv && git clone https://github.com/opencv/opencv_contrib`
3. Create empty build directory: `mkdir build && cd build`
4. Configure OpenCV: `cmake -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -DBUILD_EXAMPLES=ON ../opencv`
5. Build OpenCV: `cmake --build .`
Check `bin` fodler:
```
> ls -1 bin/*sfm*
bin/example_sfm_import_reconstruction
bin/example_sfm_match_reconstruct
bin/example_sfm_recon2v
bin/example_sfm_scene_reconstruction
bin/example_sfm_trajectory_reconstruccion
bin/opencv_test_sfm
> ./bin/example_sfm_scene_reconstruction ../opencv_contrib/modules/sfm/samples/data/images/dataset_files.txt 350 240 360
```

**Comment by prudhvigurram** [comment]
Thanks @mshabunin .. It worked. `cmake --build .` took a lot of time to build. I have created a master_openCV folder where i installed both opencv and opencv_contrib
