### ISSUE TITLE
SURF keypoints detector in Opencv 3.1 and in 2.4.13 produce different number of keypoints

### ISSUE THREAD

**Issue by Bleach665** [opencv/opencv_contrib#783]
With a difference of around 10-15%. Is this a bug? Describe the issue?

**Comment by savuor** [comment]
@Bleach665 please provide more info about your OS, the code you used and so on.
Did you use CUDA version of SURF? This could be related to #584

**Comment by Bleach665** [comment]
@savuor. Bug not reproduced..
