### ISSUE TITLE
limited functionality cv2.text

### ISSUE THREAD

**Issue by xtrntr** [opencv/opencv_contrib#798]
##### System information (version)\
- OpenCV => 3.1
- OS X El Capitan 10.11.6 
##### Detailed description

cv2.text has limited functionality. I installed tesseract through homebrew and verified that it works through the command line. I am unable to call certain functions i.e. computeNMChannels like in this example: https://github.com/opencv/opencv_contrib/blob/master/modules/text/samples/textdetection.py

**Comment by StevenPuttemans** [comment]
Did you actually rebuilt OpenCV with tesseract support enabled and ensured it found all files? If so please provide your CMAKE output!

**Comment by xtrntr** [comment]
I didn't do that. I used conda install -c menpo opencv3=3.1.0

**Comment by StevenPuttemans** [comment]
>> I didn't do that. I used conda install -c menpo opencv3=3.1.0 

Ah I guess there lies the issue. To be able to use all functionality from opencv text module, you need to download the opencv repo code, the opencv contrib repo code, run cmake and select the text module, then make sure cmake finds all paths to your tesseract installation and build opencv.

That binaries will then have all functionality available.

This functionality is not available through prebuilt packages.

**Comment by berak** [comment]
see also: https://github.com/opencv/opencv/issues/7329
