### ISSUE TITLE
face: bif outputs NaN values

### ISSUE THREAD

**Issue by berak** [opencv/opencv_contrib#802]
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw64

```
    cv::Mat fea;
    cv::Ptr<cv::face::BIF> bif = cv::face::createBIF();
    cv::Mat image(20, 20, CV_32F);
    cv::theRNG().fill(image, cv::RNG::UNIFORM, 0, 1);
    bif->compute(image, fea);
    cout << "fea = " << endl << " " << fea << endl << endl;

```

results in:

```
fea =
 [nan;
 0.042399365;
 0.03043396;
 nan;
 0.028167048;
 nan;
 nan;
 nan;
 nan;
 0.027863333;
 nan;
 0.022367189;
 nan;
 nan;
 0.03827234;
 nan;
 0.021351714;
 ...

```

see also: http://answers.opencv.org/question/103728/bio-inspired-features-returns-nans/

**Comment by savuor** [comment]
Moreover, on Linux x64 it breaks the test `CV_Face_BIF.can_compute` of `face` module.

**Comment by berak** [comment]
oh, i'll sure check that (missed, that it has tests at all)

**Comment by berak** [comment]
i would like to reopen this issue (is this possible ?), since there are still coming NaN's out of it, this time from [here](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/bif.cpp#L210)

![ex. image](http://answers.opencv.org/upfiles/14761319156247417.png)
with real images, it happens, that `sd/area < mean*mean` , so we get neg numbers, and the sqrt yields nan.
