### ISSUE TITLE
CMake error when adding *any* library from opencv-contrib

### ISSUE THREAD

**Issue by martingoedbloed** [opencv/opencv_contrib#810]
##### System information (version)
- OpenCV => 3.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
When compiling the opencv binaries, all goes well, when adding *any* library from opencv-contrib, the compiler can't find a specific source file (in the build directory, which is strange by itself)

Configuring done
CMake Error at D:/work/opencv-310/source/opencv/cmake/OpenCVUtils.cmake:831 (add_library):
  Cannot find source file:

    D:/work/opencv-310/build/modules/face/opencv_face_pch.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  D:/work/opencv-310/source/opencv/cmake/OpenCVModule.cmake:784 (ocv_add_library)
  D:/work/opencv-310/source/opencv/cmake/OpenCVModule.cmake:729 (_ocv_create_module)
  D:/work/opencv-310/source/opencv/cmake/OpenCVModule.cmake:940 (ocv_create_module)
  D:/work/opencv-310/source/opencv_contrib/modules/face/CMakeLists.txt:2 (ocv_define_module)

CMake Error: CMake can not determine linker language for target: opencv_face
CMake Error in D:/work/opencv-310/source/opencv_contrib/modules/face/CMakeLists.txt:
  Exporting the target "opencv_face" is not allowed since its linker language
  cannot be determined

##### Steps to reproduce
Download opencv & opencv-contrib.
Start CMake, and set source to opencv
Hit configure & Generate (no errors)

Configure OPENCV_EXTRA_MODULES_PATH -> opencv-contrib
Hit configure, and deselect all new libraries found
Hit configure + generate -> no error

Select *any* (ie Face) library, 
Hit configure + generate -> ERROR (a specific sourcefile can't be found in the target/build directory (see error above).

**Comment by martingoedbloed** [comment]
Was unable to reproduce on my 2nd pc......
What I've found out, that on the working PC, in the /build/modules/face/ a lot of files where created, and on the pc having the issue, none where created.

Guess found the reason of the error message, any idea for the RC?

**Comment by cesardelgadof** [comment]
@martingoedbloed Hi!, I have a prebuilt project https://github.com/cesardelgadof/OpenCVBinaries maybe it be useful for you

**Comment by martingoedbloed** [comment]
Tthanks @cesardelgadof .

I've been able to build all the modules myself on another pc, for now I think windows10 or my 'environment' is to blame.

Issue closed.

**Comment by happynear** [comment]
@martingoedbloed Can you describe how you solved it? I just came across the same problem.

**Comment by martingoedbloed** [comment]
Hi, didn't solve it, my office workstation is windows7, guess it has todo with windows 10 (but others might disagree).
Try a vanilla installation on a virtual machine, to reproduce the error?

**Comment by darkdragon-001** [comment]
As I found out `_pch` stands for _precompiled header_. OpenCV has an option called `ENABLE_PRECOMPILED_HEADERS` which controls this behavior. For some reason, it was always set to `OFF` - even manually adding/overwriting this variable did not work. The current value of this variable can be seen in the output of the _Configure_ step in the section `C/C++: Precompiled headers: ON|OFF`.

**Restaring** the CMakeGUI and cleaning the `build` folder did the trick for me!

**Comment by gblikas** [comment]
So, I think I figured out the "solution" based on what @darkdragon-001 had mentioned and the debug output. This only works for cmake cli, though and I am running it on the OpenCV320 release-tag from their website, and am on Windows 64bit. 

To successfully get around this problem try the following: 
- Make a clean "build" directory. 
- Go to that directory perform `cmake -G<type> -DBUILD_opencv_ts=OFF -DOPENCV_EXTRA_MODULES_PATH=<path> <path to cmakelists.txt>/`
- Then run `cmake -G<type> -DBUILD_opencv_world=ON -DBUILD_opencv_ts=OFF -DOPENCV_EXTRA_MODULES_PATH=<path> <path to cmakelists.txt>/`

By first not turning the opencv_world lib on, you generate the pch files that it requires-- Here @darkdragon-001  noticed that eph is enabled. Which is just dumb. Secondly, then, by turning on opencv_worldXXX the pch files exist in cache, and so their is no complaint from the cmake generator. 

The reason for turning off the _ts modules is that for some reason a core file is missing. I am not sure why, though. 

This is really not a good solution... And I am surprised no dev realized this in taging OpenCV 320 for release on Windows.
