### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Silur** [opencv/opencv_contrib#815]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Arch Linux x86_64
- Compiler => gcc 6.2.1

##### Detailed description

make build fails with following message `/usr/include/c++/6.1.1/cstdlib:75:25: fatal error: stdlib.h: No such file or directory #include_next <stdlib.h>`

##### Steps to reproduce
```
$ cd <opencv_build_directory>
$ cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>
$ make -j5
```

**Comment by alalek** [comment]
Try latest master, there are several workarounds for this GCC bug.

**Comment by Silur** [comment]
this is from the latest master, cloned like 30 min ago. what are these "several workarounds"?

**Comment by alalek** [comment]
The latest fix is here: https://github.com/opencv/opencv/pull/7390
Add dump of CMake output (stdout) and failed command line (via `make VERBOSE=1`).
