### ISSUE TITLE
Modules Aruco

### ISSUE THREAD

**Issue by DrN22** [opencv/opencv_contrib#816]
Hello,
In this modules Aruco have a aruco,charuco,dictionary. But I need cvdrawingutils.h,aruco.h,markerdetector itp. 

I can not add other extensions. Please pomórzcie me with this, if someone has opencv_contrib with full module aruco asked me about him. I am new to this topic. And it needs to generate markers and then to recognize them with the location.

I use tutorial: [GUIDE](https://putuyuwono.wordpress.com/2015/04/23/building-and-installing-opencv-3-0-on-windows-7-64-bit/)

- Operating System  => Windows 10 64 Bit
- Compiler => Visual Studio 2013

**Comment by alalek** [comment]
Usage help should be asked on Q/A User forum: http://answers.opencv.org
