### ISSUE TITLE
Which modules are available in Java in opencv_contrib?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv_contrib#818]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

I saw in some of the modules cmake.txt file has Java name to create wrapper for Java, but in most of them there is no Java name. The question is can we manually add this to the CMake file? If yes, then in which modules are available to support Java.

**Comment by abratchik** [comment]
whatever modules are marked with java are available )) Others are not by default. IMHO adding java support to all modules without proper rationalization of interfaces will just increase compile time and chances for broken builds.
