### ISSUE TITLE
opencv_dnn produce errors when a thirdparty also links against protobuf

### ISSUE THREAD

**Issue by agilmor** [opencv/opencv_contrib#823]
##### System information (version)

- OpenCV => 3.1 (and probably 3.0)
- Operating System / Platform => Debian Jessie (and others)
- Compiler => Gcc 4.9 (and probably others)
##### Detailed description

When using OpenCV DNN with Caffe, both linking against Protobuf the following error apears:

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1272] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
```

And then a `std::terminate` is thrown by protobuf.

Some people reported that its a problem with dynamic linking against Protobuf, but in my experience it also happen using static linking.

I'm not sure if the problem is in OpenCV, in Protobuf, or in Caffe.
But [the current workaround is disable OpenCV DNN](https://github.com/BVLC/caffe/issues/1917#issuecomment-214501151).
Is the problem really there, in opencv_dnn? Can we solve it?
##### Steps to reproduce

Build OpenCV with DNN.
Build Caffe with pycaffe or matcaffe.
In caffe, just run something like:

```
$ matlab -nodesktop -r "addpath ./matlab/; caffe.set_mode_cpu();"
```

And you will get the `std::terminate`.

Similar commands with pycaffe also reproduce this error.

Thanks!

PS: This comes from https://github.com/opencv/opencv/issues/7425

**Comment by mshabunin** [comment]
Can you please check whether the problem persists with the latest OpenCV version? Can you provide reproducing example in Python or C++?

**Comment by arrybn** [comment]
@agilmor, there are modules in contrib, which try to use system protobuf and load caffe.proto: dnn_modern and cnn_3dobj. But dnn module builds its own version of protobuf, so there shouldn't be any conflicts with system protobuf. Try to disable dnn_modern and cnn_3dobj modules in your build (-DBUILD_opencv_cnn_3dobj=OFF -DBUILD_opencv_dnn_modern=OFF as options for cmake) and please let me know about results

**Comment by dkurt** [comment]
@agilmor , also the latest Caffe changes might help, https://github.com/BVLC/caffe/pull/5624.

**Comment by basvandijk** [comment]
In NixOS we also run into the same `File already exists in database: caffe.proto` error. We currently [disable](https://github.com/NixOS/nixpkgs/pull/30646/files#diff-6dc973a689bf881234a645ba74c91ba0R215) the `dnn_modern` and `cnn_3dob` modules to work around this issue.

@dkurt I tried building with the latest caffe which includes the `cmake: rename libproto.a -> libcaffeproto.a` patch but that didn't help unfortunately.

**Comment by dkurt** [comment]
@basvandijk, we're going to avoid protobuf dependency by own parser, https://github.com/opencv/opencv_contrib/pull/1291 + https://github.com/opencv/opencv/pull/9106. You may try it if you want to use DNN module.

**Comment by alalek** [comment]
Migrate here: https://github.com/opencv/opencv/issues/7425
