### ISSUE TITLE
Tracking module for Java is unusable

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv_contrib#826]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
##### Detailed description

I have build the OpenCV with extra modules, because I want to use the tracking module of the contrib modules, so I have add the word "java" in the CMakeLists.txt file, the build process was successfully done. But when I open the MultiTracker class, except the constructor all the method was commented. What is wrong with this module, is it not available in Java? BTW I want to ask which modules are available now in Java? It was also mentioned before. Can we modify the CMake file for Java? If yes, then to which module we can modify Or it is possible for all modules?

**Comment by abratchik** [comment]
I guess this is possible but there is one issue. Not all C++ types are automatically supported by java generator. This means that corresponding methods of that type will be skipped during generation, which sometimes will be leading to empty interface like in your example. The same is applicable to parameters.
The other issue is - C++ classes, which need to be exposed through java and python, should be declared with proper qualifiers - it tells to wrapper generators which methods need to be exposed.
Summarizing, if you just add "java" to cmake this should not break anything but resulting API you will get may not be useable.

**Comment by Bahramudin** [comment]
Thanks! But one thing that, can we hope to the modules that can have java wrapper in the feature? Because here is lot of friends which they are using Java for computer vision, there are lot of good algorithm such as text, tracking, opticalFlow ... which we hope to have the Java wrapper.

**Comment by abratchik** [comment]
I think adding classes of your interest to java is actually not that difficult and you can do it by yourself. To my awareness all major issues with java generator are now fixed so you may wanna check [this](https://github.com/opencv/opencv/wiki/How_to_contribute) and [this](http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_bindings/py_bindings_basics/py_bindings_basics.html) and do your contribution to OpenCV )). The last link is about Python but concept of wrappers is the same for java.

**Comment by Bahramudin** [comment]
The Worst case is really not easy for me, because I am not very good in C++, I am a Java Lover. Anyway Thanks for your beautiful explanation. I will follow your suggestions and see what will happens.

**Comment by berak** [comment]
related: https://github.com/opencv/opencv_contrib/issues/767

**Comment by mshabunin** [comment]
The opencv/opencv#7947 has added necessary support, so this Java wrappers for this module can be turned on.

**Comment by sturkmen72** [comment]
https://github.com/opencv/opencv_contrib/pull/986
