### ISSUE TITLE
How to use Cmake-gui to configure part of the opencv_contrib model?? 

### ISSUE THREAD

**Issue by chibai** [opencv/opencv_contrib#835]
-DBUILD_opencv_legacy=OFF <opencv_source_directory>
this is the command tutorial

I guess, in the Cmake-gui, i should "add an entry"
now here's some problems 
what's the name of the entry?
BUILD_opencv_legacy   or   DBUILD_opencv_legacy=OFF
what's the type of the type of the entry?
BOOL? PATH or STRING??
what is the value??
FALSE or <opencv_source_directory>?

**Comment by alalek** [comment]
This is wrong place to describe how CMake works.
Questions about OpenCV installation/usage you can ask on OpenCV Q/A forum: http://answers.opencv.org
