### ISSUE TITLE
 AttributeError: module 'cv2.text' has no attribute 'computeNMChannels'

### ISSUE THREAD

**Issue by skrizanovic** [opencv/opencv_contrib#842]
##### System information (version)
- OpenCV => 3.1.0
- Operating System / Platform => Ubuntu
Followed this guide to build and make the CV project http://www.pyimagesearch.com/2015/07/20/install-opencv-3-0-and-python-3-4-on-ubuntu/

##### Detailed description

Tried to use the sample opencv_contrib/modules/text/samples/detect_er_chars.py to detect text in an image block and I got the following error; AttributeError: module 'cv2.text' has no attribute 'computeNMChannels'. 

I have tried running help(cv2.text) and I can not see the method.

**Comment by albertyou2** [comment]
hi @skrizanovic 
Have you found the solution ? I also meet this problem and has no idea how to handle it.

**Comment by MinghuaJiang** [comment]
You can try download opencv master version to fix the problem.

**Comment by imenmelkibhm** [comment]
I faced the same problem yesterday and solved it by downloadind the same version for both OpenCV and opencv-contrib from the github repo. However when testing the sample (on one of the provided jpg files) I got a segmentation fault. Does any one have an idea how to solve this problem?

**Comment by MinghuaJiang** [comment]
I already created a issue for it,  you can wait for feedback for that.

**Comment by imenmelkibhm** [comment]
Thanks @MinghuaJiang! I have juste to precise that the cpp code works fine..

**Comment by pevogam** [comment]
@mshabunin : Do you mind explaining why you marked this issue as invalid? I encounter the same problem as described above (also checked out to master). The example script in 'opencv_contrib/modules/text/samples/textdetection.py' makes python calls, none of which are available in `cv2.text`. I found proper macros in the erfilter.cpp and found erfilter.hpp in the exported headers (build/modules/python2/headers.txt) but can't really find its methods anywhere from the python bindings.

**Comment by mshabunin** [comment]
@pevogam , because the sample mentioned in the description does not contain any calls to `computeNMChannels` and other users reported that it works with latest master versions.

I've just checked that both samples works fine.
Also:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> help(cv2.text.computeNMChannels)   
Help on built-in function computeNMChannels:

computeNMChannels(...)
    computeNMChannels(_src[, _channels[, _mode]]) -> _channels
```
Make sure you have the _text_ module enabled: run `bin/opencv_version -v` or `cv2.getBuildInformation()` and check that _text_ is in the `To be built:` list.

**Comment by pevogam** [comment]
Thanks for the clarification. Redoing everything made it work for me and I hope that your information above will still be useful to others.
