### ISSUE TITLE
Add Harris-Laplace / Hessian-Laplace detectors?

### ISSUE THREAD

**Issue by Yorwba** [opencv/opencv_contrib#851]
I need the Harris-Laplace / Hessian-Laplace affine feature detectors for a project and found [an old set of patches](http://code.opencv.org/issues/1053) implementing the Harris-Laplace detector, that was apparently never merged.
I plan to massage the patches into shape for use with current versions of OpenCV but I'm unsure whether I should aim for inclusion in (presumably the xfeatures2d module of) OpenCV or whether I should choose a more standalone approach.
Since I do not know why the patches weren't merged when they were submitted, I would like to know whether you would accept the contribution if I made a PR, or whether these feature detectors won't be included in OpenCV for some reason.

**Comment by StevenPuttemans** [comment]
I do not think that if you get a stable working release, that inclusion is not possible. Like suggested, go for inclusion inside xfeatures2d, which is best approach for new feature detectors.

Good luck with the PR!

**Comment by alalek** [comment]
Thank you! #933
