### ISSUE TITLE
Sfm module on windows using VS 2015

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#853]
Hi,

Building SFM module with VS2015
For multiview project M_PI is undefined. Preprocessor definition _USE_MATH_DEFINES can be add using VS 2015 (windows 10)

**Comment by terfendail** [comment]
@LaurentBerger 
Could you please provide your CMake and build output and describe used prerequisites and libraries?
I've successfully build SFM with VS2015(Win 10). Additional investigation shows that M_PI constant was defined in `Eigen/Geometry` file in my case.

**Comment by LaurentBerger** [comment]
Sorry for delay : 
Cmake output in GUI : 
FP16: Compiler support is available
A library with BLAS API not found. Please specify library location.
LAPACK requires BLAS
A library with LAPACK API not found. Please specify library location.
found IPP (ICV version): 9.0.1 [9.0.1]
at: F:/lib/opencv/3rdparty/ippicv/unpack/ippicv_win
CUDA detected: 7.5
CUDA NVCC target flags: -gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-D_FORCE_INLINES
Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
Could NOT find Matlab (missing:  MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
Caffe:   NO
Protobuf:   NO
Glog:   NO
Found required Ceres dependency: Eigen version 3.3.0 in F:/lib/eigen-eigen
No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
Found installed version of glog: F:/lib/glog
Detected glog version: 0.3.4
Found required Ceres dependency: Glog in 
Found Ceres version: 1.12.0 installed in: C:/Program Files/Ceres with components: [SchurSpecializations, OpenMP]
Checking SFM deps... TRUE
Tesseract:   NO
Check contents of vgg_generated_48.i ...
Check contents of vgg_generated_64.i ...
Check contents of vgg_generated_80.i ...
Check contents of vgg_generated_120.i ...
Check contents of boostdesc_bgm.i ...
Check contents of boostdesc_bgm_bi.i ...
Check contents of boostdesc_bgm_hd.i ...
Check contents of boostdesc_binboost_064.i ...
Check contents of boostdesc_binboost_128.i ...
Check contents of boostdesc_binboost_256.i ...
Check contents of boostdesc_lbgm.i ...
Found required Ceres dependency: Eigen version 3.3.0 in F:/lib/eigen-eigen
No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
Found installed version of glog: F:/lib/glog
Detected glog version: 0.3.4
Found required Ceres dependency: Glog in 
Found Ceres version: 1.12.0 installed in: C:/Program Files/Ceres with components: [SchurSpecializations, OpenMP]
Checking SFM deps... TRUE

General configuration for OpenCV 3.1.0-dev =====================================
  Version control:               3.1.0-1795-g5985d71

  Extra modules:
    Location (extra):            F:/lib/opencv_contrib/modules
    Version control (extra):     3.1.0-497-gb44a47a

  Platform:
    Timestamp:                   2016-12-01T18:07:26Z
    Host:                        Windows 10.0.14393 AMD64
    CMake:                       3.7.0-rc2
    CMake generator:             Visual Studio 14 2015 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
    MSVC:                        1900

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24215.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /wd4324 /wd4275 /wd4589 /MP12  /MD /O2 /Ob2 /DNDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /wd4324 /wd4275 /wd4589 /MP12  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP12  /MD /O2 /Ob2 /DNDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP12  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO  /debug
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          comctl32 gdi32 ole32 setupapi ws2_32 vfw32 correspondence multiview numeric glog::glog gflags_shared simple_pipeline cudart nppc nppi npps cufft -LIBPATH:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5/lib/x64
    3rdparty dependencies:       zlib libjpeg libwebp libpng libtiff libjasper IlmImf libprotobuf

  OpenCV modules:
    To be built:                 cudev core cudaarithm flann imgproc ml reg surface_matching video cudabgsegm cudafilters cudaimgproc cudawarping dnn fuzzy imgcodecs photo shape videoio cudacodec highgui objdetect plot ts xobjdetect xphoto bgsegm bioinspired dpm face features2d line_descriptor saliency text calib3d ccalib cudafeatures2d cudalegacy cudaobjdetect cudaoptflow cudastereo datasets rgbd stereo superres tracking videostab xfeatures2d ximgproc aruco optflow phase_unwrapping sfm stitching structured_light
    Disabled:                    world contrib_world
    Disabled by dependency:      -
    Unavailable:                 java python2 python3 viz cnn_3dobj cvv hdf matlab

  Non-free algorithms are enabled

  Windows RT support:            NO

  GUI: 
    QT:                          NO
    Win32 UI:                    YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver 0.3.1)
    PNG:                         build (ver 1.6.24)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    Video for Windows:           YES
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES (prebuilt binaries)
      codec:                     YES (ver 57.48.101)
      format:                    YES (ver 57.41.100)
      util:                      YES (ver 55.28.100)
      swscale:                   YES (ver 4.1.100)
      resample:                  NO
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    DirectShow:                  YES
    Media Foundation:            NO
    XIMEA:                       NO
    Intel PerC:                  NO

  Parallel framework:            Concurrency

  Other third-party libraries:
    Use IPP:                     9.0.1 [9.0.1]
         at:                     F:/lib/opencv/3rdparty/ippicv/unpack/ippicv_win
    Use IPP Async:               NO
    Use Lapack:                  NO
    Use Eigen:                   YES (ver 3.3.0)
    Use Cuda:                    YES (ver 7.5)
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

  NVIDIA CUDA
    Use CUFFT:                   YES
    Use CUBLAS:                  NO
    USE NVCUVID:                 NO
    NVIDIA GPU arch:             20 30 35 37 50 52
    NVIDIA PTX archs:
    Use fast math:               NO

  OpenCL:                        <Dynamic loading of OpenCL library>
    Include path:                F:/lib/opencv/3rdparty/include/opencl/1.2
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO

  Python 2:
    Interpreter:                 NO

  Python 3:
    Interpreter:                 F:/Program Files/LibreOffice 5/program/python.exe (ver 3.3.5)

  Python (for build):            F:/Program Files/LibreOffice 5/program/python.exe

  Java:
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        Matlab not found or implicitly disabled

  Documentation:
    Doxygen:                     C:/Program Files/doxygen/bin/doxygen.exe (ver 1.8.11)

  Tests and samples:
    Tests:                       YES
    Performance tests:           YES
    C/C++ Examples:              NO

  Install path:                  F:/lib/opencv/static2015/install

  cvconfig.h is in:              F:/lib/opencv/static2015
-----------------------------------------------------------------

Configuring done

**Comment by LaurentBerger** [comment]
If I compile multiview I still have an error with M_PI

**Comment by LaurentBerger** [comment]
Constant M_PI deleted in eigen https://bitbucket.org/eigen/eigen/commits/0dfb2d5d3d33d9c44b5cfbd6c5fb68768c05c88a#general-comments

**Comment by terfendail** [comment]
I'm using Eigen 3.2.9 that define M_PI. So it looks like the definition gone starting from Eigen branch 3.3.
The latest commit related to Eigen i've found in libmv updates to Eigen 3.2.7(while geometry retain the same from 3.1.2 to 3.2.9)

**Comment by LaurentBerger** [comment]
it was this commit https://bitbucket.org/eigen/eigen/commits/0dfb2d5d3d33d9c44b5cfbd6c5fb68768c05c88a#general-comments
