### ISSUE TITLE
cmake failing with hash mismatch 

### ISSUE THREAD

**Issue by aliyesami** [opencv/opencv_contrib#859]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

 am trying to build opencv but cmake is failing with the following error , i have had this before and i could find the files and manually put them on the server but this time this file "bootdesc_bgm.i" is no where to be found , please help. I even upgraded my cmake to 3.0 . 

cmake command I am using is 

`cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_NEW_PYTHON_SUPPORT=ON -DWITH_TBB=ON -DBUILD_TBB=ON -DWITH_OPENGL=ON -DWITH_EIGEN=ON -DFFMPEG_INCLUDE_DIR=/usr/local/include -DOPENCV_EXTRA_MODULES_PATH=/root/opencv_contrib/modules -DBUILD_opencv_legacy=OFF ..`

**Comment by alalek** [comment]
These files are here: https://github.com/opencv/opencv_3rdparty/tree/contrib_xfeatures2d_boostdesc_20161012
