### ISSUE TITLE
example_text_end_to_end_recognition malloc: *** error : pointer being freed was not allocated

### ISSUE THREAD

**Issue by LABCAO** [opencv/opencv_contrib#870]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => OS X EI Capitan
- Compiler => Xcode Version 7.3.1

##### Detailed description

While running end_to_end_recognition.cpp, encountered error: "Default classifier file not found!" in ERClassifierNM1.

**Comment by sovrasov** [comment]
@LABCAO please attach additional information.
The sample `end_to_end_recognition` works only if startup folder contains `trained_classifierNM1.xml` and `trained_classifierNM2.xml`.

**Comment by LABCAO** [comment]
When the startup folder contains trained_classifierNM1.xml and trained_classifierNM2.xml, I would encounter this error:

A demo program of End-to-end Scene Text Detection and Recognition: 
Shows the use of the Tesseract OCR API with the Extremal Region Filter algorithm described in:
Neumann L., Matas J.: Real-Time Scene Text Localization and Recognition, CVPR 2012

IMG_W=600
IMG_H=629
example_text_end_to_end_recognition(19607,0x7fff74c04000) malloc: *** error for object 0x82f589602d20: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by LABCAO** [comment]
Problem no longer exists after applying fixes for issue #872. Thanks a lot!!

**Comment by sovrasov** [comment]
Resolved in #876
