### ISSUE TITLE
cannot build successfully one of the file under opencv_contrib after checking out head version

### ISSUE THREAD

**Issue by MinghuaJiang** [opencv/opencv_contrib#877]
/home/cutehuazai/opencv_contrib/modules/tracking/src/unscented_kalman.cpp: In member function ‘cv::Mat cv::tracking::UnscentedKalmanFilterImpl::getSigmaPoints(const cv::Mat&, const cv::Mat&, double)’:
/home/cutehuazai/opencv_contrib/modules/tracking/src/unscented_kalman.cpp:250:9: error: ‘choleskyDecomposition’ was not declared in this scope
         choleskyDecomposition<double>(
         ^
/home/cutehuazai/opencv_contrib/modules/tracking/src/unscented_kalman.cpp:250:31: error: expected primary-expression before ‘double’
         choleskyDecomposition<double>(
                               ^
/home/cutehuazai/opencv_contrib/modules/tracking/src/unscented_kalman.cpp:254:9: error: ‘choleskyDecomposition’ was not declared in this scope
         choleskyDecomposition<float>(
         ^
/home/cutehuazai/opencv_contrib/modules/tracking/src/unscented_kalman.cpp:254:31: error: expected primary-expression before ‘float’
         choleskyDecomposition<float>(
                               ^

**Comment by alalek** [comment]
opencv and opencv_contrib should be "in sync"
