### ISSUE TITLE
dnn protobuf compilation error: No suitable threading library available

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv_contrib#878]
- OpenCV => Latest
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

##### Steps to reproduce

after cloning opencv and opencv_contrib

``````
cd opencv && mkdir build && cd build
ccmake ..
``````
Input extra module path and reconfigure, dnn should be enabled by default

``````
make
``````

Error message:

``````
[ 43%] Building CXX object modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/sources/protobuf-3.1.0/src/google/protobuf/stubs/common.cc.o
/home/jasjuang/opencv_contrib/modules/dnn/3rdparty/protobuf/sources/protobuf-3.1.0/src/google/protobuf/stubs/common.cc:51:2: error: #error "No suitable threading library available."
 #error "No suitable threading library available."
  ^
/home/jasjuang/opencv_contrib/modules/dnn/3rdparty/protobuf/sources/protobuf-3.1.0/src/google/protobuf/stubs/common.cc: In function ‘void google::protobuf::ShutdownProtobufLibrary()’:
/home/jasjuang/opencv_contrib/modules/dnn/3rdparty/protobuf/sources/protobuf-3.1.0/src/google/protobuf/stubs/common.cc:441:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < internal::shutdown_functions->size(); i++) {
                     ^
modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/build.make:326: recipe for target 'modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/sources/protobuf-3.1.0/src/google/protobuf/stubs/common.cc.o' failed
make[2]: *** [modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/sources/protobuf-3.1.0/src/google/protobuf/stubs/common.cc.o] Error 1
CMakeFiles/Makefile2:6966: recipe for target 'modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all' failed
make[1]: *** [modules/dnn/3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
``````

**Comment by alalek** [comment]
Try to build from scratch (clean build directory).
If it doesn't work on your machine then try to debug [this part of CMake code](https://github.com/opencv/opencv_contrib/blob/afd8a833c2188b8db525671520e5c64ebcdff232/modules/dnn/3rdparty/protobuf/CMakeLists.txt#L6-L9).

**Comment by jasjuang** [comment]
Just want to report back that when I delete the build folder and rebuild the same compilation error shows up. Still trying to make it work

**Comment by kevgeo** [comment]
Hey jasjuang, were you able to solve your problem? During your cmake, were there any warnings about missing protobuf files?

**Comment by jasjuang** [comment]
I still cannot compile. protobuf is found during cmake, when I type `ccmake ..` Protobuf_LIBS is /usr/lib/x86_64-linux-gnu/libprotobuf.so

**Comment by jasjuang** [comment]
I think some recent commits fixes this. I am able to compile with dnn without any error now.

**Comment by kevgeo** [comment]
Awesome

**Comment by MaxChu719** [comment]
i got the same error even if i used the latest code form git.
