### ISSUE TITLE
Memory leak and bug in Structured Edge Detector

### ISSUE THREAD

**Issue by ofrimasad** [opencv/opencv_contrib#881]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

We found a bug in Structured Edge Detector which also creates a memory leak.
in structured_edge_detection.cpp line 246 the code is:
      `pHist[cvRound((j/pSize + pPhase[j])*nBins)] += pMagn[j] / CV_SQR(pSize);`

this creates an unintentional writing to memory outside the histogram Mat as well as introducing an error in the histogram itself.
when pPhase[j] > 0.875 the cvRound causes the pointer to point to the adjacent pixel.

our solution was to change the code:
      `pHist[cvRound((j / pSize + pPhase[j] * 0.9999 - 0.124999)*nBins)] += pMagn[j] / CV_SQR(pSize);`

##### Steps to reproduce

reproducing the bug is straight forward. 
to reproduce the memory leak, one must use an image where the value of one of the four lower right pixels of the phase Mat has a value > 0.875.

**Comment by sovrasov** [comment]
@ofrimasad your solution is suitable only in case of `nBins == 4`. More common way is usage of `1.-0.5/nBins` as a barrier value of `pPhase[j]` instead of 0.875.
