### ISSUE TITLE
Fast/Faster-rcnn 

### ISSUE THREAD

**Issue by PiSimo** [opencv/opencv_contrib#886]
Hi, can I load caffe's fast-rcnn or faster-rcnn models with the new dnn api ?

**Comment by dkurt** [comment]
Please let us know if these models or some of their parts (i.e. ROIPooling) are actual at this moment.

**Comment by dkurt** [comment]
@PiSimo, Faster-RCNN model is working for now by https://github.com/opencv/opencv/pull/10306
/cc @chl916185
