### ISSUE TITLE
In the README.md, the cmake commands need a space.

### ISSUE THREAD

**Issue by spankr** [opencv/opencv_contrib#889]
When looking at the README.md on master, there is whitespace missing in the commands to cmake.

```
$ cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>
```
should be
```
$ cmake -D OPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>
```

There are a couple spots that could be updated.

**Comment by berak** [comment]
see also: https://github.com/opencv/opencv/issues/7437
