### ISSUE TITLE
Error while making forward() for concat layer with module/dnn

### ISSUE THREAD

**Issue by cw1204772** [opencv/opencv_contrib#890]
##### System information (version)

- OpenCV =>  3.1
- Operating System / Platform => Ubuntu 14.04

##### Detailed description
I was running a c++ program with opencv dnn module which previously work. The code is as follow:
```
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/dnn.hpp>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <string>

using namespace std;
using namespace cv;
using namespace cv::dnn;

int main(int argc, char** argv)
{
	// Caffe
	Ptr<dnn::Importer> importer;
	importer = dnn::createCaffeImporter("jstl_dgd_deploy_inference.prototxt", "jstl_dgd_inference.caffemodel");
	dnn::Net net;
	importer->populateNet(net);
	importer.release();
	Mat img_56_144, img_signed, img_sub, featureMat;
	dnn::Blob inputBlob, fc7;

	Mat img = imread("space_shuttle.jpg");
	resize(img, img_56_144, Size(56, 144));
	img_56_144.convertTo(img_signed, CV_16S);
	img_sub = img_signed - Scalar(102, 102, 101);
	inputBlob = dnn::Blob::fromImages(img_sub);
	net.setBlob(".data", inputBlob);
	net.forward();
	fc7 = net.getBlob("fc7");
	featureMat = fc7.matRefConst();
}
```
Note that the caffemodel and prototxt can be download from here:
https://drive.google.com/drive/folders/0B67_d0rLRTQYZnB5ZUZpdTlxM0k

And I got this error message at execution time:
```
OpenCV Error: Assertion failed (dims <= 3) in checkContinuous, file /home/cw1204772/Library/opencv-3.1.0/modules/core/src/ocl.cpp, line 4884
OpenCV Error: Assertion failed (The following error occured while making forward() for layer "inception_1b/output": dims <= 3) in checkContinuous, file /home/cw1204772/Library/opencv-3.1.0/modules/core/src/ocl.cpp, line 4884
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/cw1204772/Library/opencv-3.1.0/modules/core/src/ocl.cpp:4884: error: (-215) The following error occured while making forward() for layer "inception_1b/output": dims <= 3 in function checkContinuous

Aborted (core dumped)
```
The only thing I do between the last success execution and this one is that I install Caffe and related dependency, such as Cuda 8. The error occurs at the Concat layer of dnn module. But I haven't change the code nor the DNN prototxt and caffemodel after last success execution. Seems like recompiling and reinstalling the newest Opencv 3.1 didn't solve the issue. Can devs look into this issue?

Btw, I've run the sample test "caffe_googlenet.cpp" in modules/dnn/samples, and it run without an error. So I really don't know what cause this error.

**Comment by mshabunin** [comment]
Try to set environment variable `OPENCV_OPENCL_DEVICE` to `disabled` and run application again.

**Comment by cw1204772** [comment]
It works! Thank you very much for the fix.

However I still wonder why would OpenCL cause the problem?
I traced the code and know that OpenCV uses a different ```copy``` method when OpenCL is defined
Is it because OpenCL can only process data of dimension <= 3 ?

**Comment by arrybn** [comment]
Now OpenCL was disabled and usage of it was removed from the code, so I close this issue
