### ISSUE TITLE
The error when building OpenCV with extra modules

### ISSUE THREAD

**Issue by w86742756** [opencv/opencv_contrib#894]
hello, I have a problem when i want to build extra modules of Opencv, I got this error
CMake Error at C:/opencv/opencv_contrib-master/modules/text/CMakeLists.txt:22 (ocv_add_testdata):
  Unknown CMake command "ocv_add_testdata".

Do you konw how to solve this poblem? Thanks!

**Comment by alalek** [comment]
You should keep both opencv/opencv_contrib repositories "in sync".

**Comment by w86742756** [comment]
sorry, I don't quit understand. Do you mean this?
CMake Error at C:/opencv/opencv_contrib/modules/text/CMakeLists.txt:22 (ocv_add_testdata):
  Unknown CMake command "ocv_add_testdata".

**Comment by alalek** [comment]
I mean you should run git fetch/pull for **both** opencv/opencv_contrib repositories.
For more questions please please refer to GitHub manuals at first.

**Comment by w86742756** [comment]
ok. Thanks a lot

**Comment by kypskl** [comment]
15 days after i still don't understand you mean ..?

**Comment by vsmelov** [comment]
still get this error after git sync

git clone https://github.com/opencv/opencv.git
cd opencv
git checkout 3.1.0

git clone https://github.com/opencv/opencv_contrib.git
cd opencv_contrib
git checkout 3.1.0

**Comment by mshabunin** [comment]
@vsmelov , [modules/text/CMakeLists.txt](https://github.com/opencv/opencv_contrib/blob/3.1.0/modules/text/CMakeLists.txt) does not contain `ocv_add_testdata` command in version 3.1.0, it means something is wrong with your opencv_contrib repository.

**Comment by kypskl** [comment]
@mshabunin you are right , the text file must not contain ocv_add_tesdata command however I did not realize that since i delete it from the text file .
Thx for reply

**Comment by pyAddict** [comment]
Just comment these line no 22,23,24 from CMakeLists.txt

**Comment by Chan5myae** [comment]
Please help
modules/surface_matching/CMakeFiles/opencv_surface_matching.dir/all 
How to solve this error massage
