### ISSUE TITLE
Trouble running dnn module sample program

### ISSUE THREAD

**Issue by kevgeo** [opencv/opencv_contrib#895]
##### System information (version)
Example
- OpenCV => 3.1.0
- Operating System / Platform => Ubuntu 14.04
- Compiler => g++ 4.8.4

##### Detailed description
I am using Opencv 3.1.0 on ubuntu 14.04. I have successfully built Opencv and wanted to try reading a caffe model and classifying.

I used the program and models from this [tutorial](http://docs.opencv.org/trunk/d5/de7/tutorial_dnn_googlenet.html)

I am able to compile the program but running it gives me the error below-

`OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "bvlc_googlenet.prototxt") iReadProtoFromTextFile, file /home/kevmepls/opt/opencv_contrib/modules/dnn/src/caffe/caffe_io.cpp, line 1077
Can't load network by using the following files: 
prototxt:   bvlc_googlenet.prototxt
caffemodel: bvlc_googlenet.caffemodel
bvlc_googlenet.caffemodel can be downloaded here:
http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel`

All the models and picture are with the program in the same folder. I can't seem to understand why this error is coming?

##### Steps to reproduce
Cmake command to build Opencv 3.1.0.

`cmake -DCMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=~/opt/opencv_contrib/modules -D BUILD_EXAMPLES=ON -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 -D WITH_OPENGL=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D WITH_CAFFE=ON ..`

**Comment by kevgeo** [comment]
Sorry guys, it was a silly mistake. There was a space in the beginning of the caffemodel file name, so it couldn't read it. Later I got another error about failing to parse NetParameter file, so I had to download the caffemodel again and it got solved.

Now I have another error, so if I will spend some time to see if there is a similar error online, or else I will put it as a separate issue.

**Comment by Gru-Preet** [comment]
How, to solve this issue, in my case there is no space, but getting an error:
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "bvlc_googlenet.prototxt" i
n function 'cv::dnn::ReadProtoFromTextFile'

**Comment by tlylt** [comment]
Also faced the same issue initially. Realized its a stupid mistake: even though you may be editing and running the py script, you may not have cd into the directory you want to be in for the relative path to work.   
e.g. ' open('xyz.caffeemodel')' , if you are not already in the directory with that file, you are providing the wrong file path to the program. 
SOL: 
either on command line cd into the directory you should be in, or use the absolute path to the file you want to open, such as open('c:/user/project/'xyz.caffemodel')
Hope this helps for future careless souls ;)
