### ISSUE TITLE
Floating point exception- Running sample program dnn module

### ISSUE THREAD

**Issue by kevgeo** [opencv/opencv_contrib#896]
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => Ubuntu 14.04
- Compiler => G++ 4.8.4

##### Detailed description
I am using Opencv 3.1.0 on ubuntu 14.04. I have successfully built Opencv and wanted to try reading a caffe model and classifying.

I used the program and models from this [tutorial](http://docs.opencv.org/trunk/d5/de7/tutorial_dnn_googlenet.html)

I am able to compile the program but running it gives me the error below-
`Attempting to upgrade input file specified using deprecated V1LayerParameter: bvlc_googlenet.caffemodel
Successfully upgraded file specified using deprecated V1LayerParameter
Floating point exception (core dumped)`

The floating point exception is coming from line 109 in net.forward() method. I am not able to understand why this problem is coming up? 

##### Steps to reproduce

Cmake command to build Opencv 3.1.0.-
`cmake -DCMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=~/opt/opencv_contrib/modules -D BUILD_EXAMPLES=ON -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 -D WITH_OPENGL=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D Caffe_INCLUDE_DIR=/home/kevmepls/Documents/DeepLearning_Caffe/caffe/include/caffe -DCaffe_LIBS=../../usr/lib/x86_64-linux-gnu ..`

**Comment by kevgeo** [comment]
Does anyone have any clue why it is coming up?

**Comment by CamNZ** [comment]
Floating point exceptions happen when an illegal operation is performed on a floating point number, commonly when a float is divided by zero. I have seen a similar error in caffe before, when batch size has not been set (causing a division by zero). Will take a closer look at your problem when I get back to my computer after the weekend.

**Comment by CamNZ** [comment]
Can you share your code? (Or is it an exact copy from the tutorial)

**Comment by kevgeo** [comment]
Hi CamNZ, it's an exact copy of the tutorial

**Comment by kevgeo** [comment]
@CamNZ , could you figure out the error?

**Comment by CamNZ** [comment]
@kevgeo, I could not reproduce the error using the configuration you provided. The network worked as normal. My only advice would be trying to compile opencv-dnn again from the latest release, and double check all the dependencies are met. Sorry I could not be of more help. Let us know if you get it working. My console output:
`Attempting to upgrade input file specified using deprecated V1LayerParameter: bvlc_googlenet.caffemodel
Successfully upgraded file specified using deprecated V1LayerParameter
Best class: #812 'space shuttle'
Probability: 99.9813%
`

**Comment by kevgeo** [comment]
Oh, okay I have already rebuilt twice and still the same error. I guess it doesn't hurt to try again. Thanks for the help CamNZ :) .

**Comment by sturkmen72** [comment]
i think this can be closed down
