### ISSUE TITLE
file not found error "boostdesc_lbgm.i"

### ISSUE THREAD

**Issue by miracle0419** [opencv/opencv_contrib#907]
curl https://raw.githubusercontent.com/opencv/opencv_3rdparty/0ae0675534aa318d9668f2a179c2a052/boostdesc_lbgm.i

404: Not Found

**Comment by berak** [comment]
they're all [here](https://github.com/opencv/opencv_3rdparty/tree/contrib_xfeatures2d_boostdesc_20161012)

direct link: https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_lbgm.i

**Comment by sovrasov** [comment]
@miracle0419 if you have a problem please follow guidelines when describing it.

**Comment by miracle0419** [comment]
Thanks a lot...^^
