### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by titopuertolara** [opencv/opencv_contrib#909]
HI
after make all i got this error:

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libprotobuf.so', needed by 'lib/libopencv_dnn.so.3.2.0'.  Stop.
CMakeFiles/Makefile2:4869: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/all' failed
make[1]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
Makefile:160: recipe for target 'all' failed

can somebody help me?

thanks

**Comment by sovrasov** [comment]
System information should be added.

As far as I know protobuf sources have been added to opencv 3rd party repo and CMake should not try to use other protubuf installations. Try to build latest master from scratch.
