### ISSUE TITLE
Freetype2: returns the maximum advanced point

### ISSUE THREAD

**Issue by Glandos** [opencv/opencv_contrib#927]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Linux
- Compiler => ❔ 

##### Detailed description
Currently, the `putText` has no other output than the printed text. It could be a great feature if the `mOrg` point is returned, either in the input parameter or in the return value, since it will be useful to print more text, either on the same line or on another line.

**Comment by Kumataro** [comment]
Thank you for your suggestion ! 
I consider about cv::putText()/getTextSize() API design and feel that to add freetype2::getTextSize() function may be good.

The use cases are following.
UC1) Text drawing continued on the same line last time.
UC2) Text drawing while breaking each line at equal intervals
UC3) Text drawing while breaking each line at intervals where each line does not overlap.

In the imgproc module, UC1/UC2/UC3 can be realized by combining cv: putText() and cv::getTextSize ().

In the freetype2 module, mOrg is the origin information and does not include height information of text drawing. 
Therefore, even if freetype2 module provides mOrg information with cv :: putText(), UC1 and UC2 can be realized, but it is difficult to realize UC3.

Adding freetype2::getTextSize() function may be good.

This function can be provide the size information before drawing text, so it is able to help drawing text with centering and left-aligned.

UC4) Text drawing with Centering. (Optionally)
UC5) Text drawing with Left-aligned. (Optionally)

**Comment by Kumataro** [comment]
I think the getTextSize () function is satisfied with your proposal. Similar to the getTextSize () function of imgproc, this getTextSize () function returns the drawing boundary box of the text above the baseline and the height of the baseline. ,

UC 1) Using the origin with the width of the boundary box added, the next text is drawn following the same line.

UC 2) Using the origin with fontHeight added, the next text will be drawn on the next line at the same interval.

UC 3) Using the origin with the height and baseline of the boundary box added, the next text is drawn on the next line at intervals that do not overlap the previous line.
