### ISSUE TITLE
module contrib_world becomes empty 

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv_contrib#932]
##### System information (version)

- OpenCV => OpenCV 3.2
- Operating System / Platform => Windows 7 Pro (64bit)
- Compiler => VS2012 Professional
- CMake => 3.6.1
- CUDA => disabled

##### Detailed description
- When I try to build ```contrib_world```, the generated project is empty.
- I tried on VS2012, but I think this is related to CMake
- I found a possible cause of the issue, but I'm not good enough to fix it, so I hope someone can help me.

##### Steps to reproduce

```
cmake -DWITH_CUDA=OFF -DBUILD_opencv_world=ON -DOPENCV_EXTRA_MODULES_PATH=C:\\path\\to\\opencv_contrib\\modules -DBUILD_opencv_contrib_world=ON .. 
```

- Now, when I open ```OpenCV.sln```, the ```contrib_world``` project is empty
- It has no sub directory, not source code, no header.
- BTW, previous command worked well against OpenCV 3.1.

##### further more detail
- I looked in to cmake files with trace, and I realized some error where dumped from cmake when trying cmake on OpenCV 3.2

```
CMake Error at C:/path/to/opencv/cmake/OpenCVUtils.cmake:911 (add_library):
  Cannot find source file:

    C:/path/to/opencv/build-world/modules/aruco/opencv_aruco_pch.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  C:/path/to/opencv/cmake/OpenCVModule.cmake:784 (ocv_add_library)
  C:/path/to/opencv/cmake/OpenCVModule.cmake:729 (_ocv_create_module)
  C:/path/to/opencv/cmake/OpenCVModule.cmake:940 (ocv_create_module)
  C:/path/to/opencv_contrib/modules/aruco/CMakeLists.txt:2 (ocv_define_module)
``` 

- And it repeats same message for all modules in ```opencv_contrib``` to be built from ```contrib_world```
- I traced back a bit, and I think the cause is in macro ```GET_NATIVE_PRECOMPILED_HEADER``` in [```opencv/cmake/OpenCVPCHSupport.cmake```]( https://github.com/alalek/opencv/blob/b640e728777d92157d6d6d9b422d2c9d19423442/cmake/OpenCVPCHSupport.cmake#L304 )
- In OpenCV 3.1, cmake will generate an empty PCH.cpp, as below.

```
MACRO(GET_NATIVE_PRECOMPILED_HEADER _targetName _input)

    if(CMAKE_GENERATOR MATCHES "^Visual.*$")
        set(_dummy_str "#include \"${_input}\"\n")

        set(${_targetName}_pch ${CMAKE_CURRENT_BINARY_DIR}/${_targetName}_pch.cpp)
        if(EXISTS ${${_targetName}_pch})
            # Check if contents is the same, if not rewrite
            # todo
        else()
            FILE(WRITE ${${_targetName}_pch} ${_dummy_str})
        endif()
    endif()

ENDMACRO(GET_NATIVE_PRECOMPILED_HEADER)
```

- On the other hand, in OpenCV 3.2, the dummy file generation part has been removed

```
MACRO(GET_NATIVE_PRECOMPILED_HEADER _targetName _input)

    if(CMAKE_GENERATOR MATCHES "^Visual.*$")
        set(${_targetName}_pch ${CMAKE_CURRENT_BINARY_DIR}/${_targetName}_pch.cpp)
    endif()

ENDMACRO(GET_NATIVE_PRECOMPILED_HEADER)
```

- This modification has been committed in opencv/opencv@b640e728777d92157d6d6d9b422d2c9d19423442 
- This is the furthest I could figure out, and I hope some one who is better in cmake than me can find a good solution ( or point that I'm wrong )

best

**Comment by alalek** [comment]
1. For "world" build there are a lot of precomp.hpp files, so only misuse errors are expected. You need to disable precompiled headers.
2. There are several issues with contrib_world module. Only static build may work somehow (some time ago). Shared library produces cyclic dependencies error or invalid binary (on Linux). To try it you probably need `OPENCV_ENABLE_OBJECT_TARGETS=ON` CMake variable.

**Comment by tomoaki0705** [comment]
This issue is too old.
I'll close it
