### ISSUE TITLE
Aruco board pose estimation instability due to initial guess in SolvePNP

### ISSUE THREAD

**Issue by jonnew** [opencv/opencv_contrib#942]
##### System information (version)
- OpenCV => 0c8e0696401a4d5ced11c4c4cbedf014ccffc75a
- Operating System / Platform => Ubuntu 14.04
- Compiler => clang-3.8

##### Detailed description
The changes introduced in ea3d341415be3c6028017271255de24d3757ec83 seem to cause instabilities in `aruco::estimatePoseBoard()`. 

##### Steps to reproduce
1. Compile with the latest opencv_contrib
2. Do arucoboard dection and estimatePoseBoard();
3. The detected pose will sometimes be correct but will often jump around wildly

To fix, I simply comment out the changes introduced in ea3d341415be3c6028017271255de24d3757ec83. Namely starting [here](https://github.com/opencv/opencv_contrib/blob/6891d7788f94ca0f367b50c44737be8e0903defe/modules/aruco/src/aruco.cpp#L1253) I make these changes:

```.cpp
 _rvec.create(3, 1, CV_64FC1);
 _tvec.create(3, 1, CV_64FC1);

//bool useExtrinsicGuess = false;

 //if (_rvec.empty() || _tvec.empty())
 //{
 //    _rvec.create(3, 1, CV_64FC1);
 //    _tvec.create(3, 1, CV_64FC1);
 //    useExtrinsicGuess = false;
 //}
 solvePnP(objPoints, imgPoints, _cameraMatrix, _distCoeffs, _rvec, _tvec);// useExtrinsicGuess);

 // divide by four since all the four corners are concatenated in the array for each marker
 return (int)objPoints.total() / 4;
```
After this, the pose is much more accurate and less jumpy.

##### Example
This can be tested by making these changes to the code while running the provided board tracking example. Just compare the estimated pose before and after `https://github.com/opencv/opencv_contrib/blob/master/modules/aruco/samples/detect_board.cpp

**Comment by sovrasov** [comment]
Why not pass zero-sized Mats into function? If you are passing Mats with random rubbish, of course results are going to be bad.

**Comment by mshabunin** [comment]
@jonnew , can you please illustrate the issue with standalone example app or even a test?

**Comment by jonnew** [comment]
@mshabunin How am i to do that when it inolves actually tracking a board and looking at the results?

**Comment by jonnew** [comment]
Basically, even when the markers are all found, the estimated pose is completely incorrect. If I make my changes, things go back to normal. Anyone with the Aruco library should be able to try this.

**Comment by jonnew** [comment]
@mshabunin OK, I've put a link to the board detection example in my original issue.

**Comment by jonnew** [comment]
@sovrasov Can you be more explicit? I don't know what Mats or what functions you are referring to. Thanks.

**Comment by jonnew** [comment]
@mshabunin I will create a couple videos of the problem when i get into work.

**Comment by mshabunin** [comment]
@jonnew , can you provide command line parameters you used? Video is not necessary.

**Comment by jonnew** [comment]
@mshabunin Here you go:
```
./example_aruco_detect_board -ci=0 -d=0 --dp=/home/jon/public/opencv_contrib/modules/aruco/samples/detector_params.yml -h=3 -l=0.024 -s=0.004 -w=3 -c=./lala.yaml
```
lala.yaml contains my `camera_matrix` and `distortion_coefficients`. I confirmed these were actually being loaded using gdb. Board detection works fine (boxes drawn around all the markers).

**Comment by sovrasov** [comment]
I meant that you are probably passing to `aruco::estimatePoseBoard` not empty rvec and tvec filled with inappropriate values and got strange results, instead of passing empty rvec and tvec. If you don't want to use initial guess just follow the documentation. There is no bug in this case (maybe 'example_aruco_detect_board' doesn't consists with latest changes and shold be updated).
But may be you have an appropriate initial guess for rvec and tvec but results are incorrect. In this case this is fault of the aruco module.

**Comment by jonnew** [comment]
@sovrasov  No. the initial guess is ignored when `useExtrinsicGuess` parameter of the `solvePnP()` is set to false (default value, this is the case in my changes since I commented the `useExtrinsicGuess` out of the function call). As I stated, my changes _fix_ the problem. Using the previous results of rvec and tvec, as is the current Aruco lib makes things worse. The examples are  already using the the latest changes.

**Comment by mshabunin** [comment]
@jonnew , I took a look at the _detect_board.cpp_ sample and found that _rvec_ and _tvec_ are not initialized for each frame:
```.cpp
/* 192 */ Vec3d rvec, tvec;
//...
/* 206 */ aruco::estimatePoseBoard(corners, ids, board, camMatrix, distCoeffs, rvec, tvec);
``
It means that it should go into the _if_ block, create new _rvec_ and _tvec_ and  set _useExtrinsicGuess_ to _false_ which is equivalent to the previous behavior, but it does not do it because `.empty()` returns `false`. This is so because `Vec3d` is never empty it always has 3 elements. Thus I guess we need to modify this condition (`_rvec.empty() || _tvec.empty()`). What do you think?

**Comment by catree** [comment]
Maybe adding `useExtrinsicGuess ` as an explicit argument to `estimatePoseBoard` would solve the issue?

**Comment by jonnew** [comment]
This seems to address the issue. Thank you all.

**Comment by Yeshasvitvs** [comment]
@jonnew Its a bit unrelated to the topic here but may be you can help. I am trying to use single marker pose estimation and the values are changing wildy as 
Marker ID 2 : [-1.11133e+06, -918896, 3.3727e+06] , [-3.22862e+08, 4.49601e+08, -5.05835e+08]
Any suggestions on what is going wrong and where to look?  

P:S, I am using opencv-3.1.0 and opecv_contrib-3.1.0
Inside the aruco module, in aruco.cpp file I modified the call to SolvePNP in SinglePoseEstimationPrallel class as (added the if part setting useExtrinsicGuess true)

if(!rvecs.empty())
          {
            //std::cout << "SolvePNP called with previous pose estimates" << std::endl;
            cv::solvePnP(markerObjPoints, corners.getMat(i), cameraMatrix, distCoeffs,
                    rvecs.at<Vec3d>(0, i), tvecs.at<Vec3d>(0, i),true);
          }
          else
          {
            solvePnP(markerObjPoints, corners.getMat(i), cameraMatrix, distCoeffs,
                    rvecs.at<Vec3d>(0, i), tvecs.at<Vec3d>(0, i));
          }

**Comment by Yeshasvitvs** [comment]
@jonnew  I am not using aruco board but single marker pose estimation. Also I am using opencv-3.1.0 with aruco enabled and setting the useExtrinsicGuess flag stabilizes z axis flipping but pose values are jumping a lot.

**Comment by jonnew** [comment]
@Yeshasvitvs If you are having the same problem as me, then `useExtrinsicGuess` should be set to `false` to correct instabilities in pose estimation. The problem was that that providing this information to `SolvePNP` was making it converge on an incorrect solution. Other issues may simply be with your ability to detect the board properly -- .e.g think about how the resolution of you camera, the size of the marker, and its distance from the camera translate into detect-ability. There are minimal specifications for these parameters provided in the original Aruco papers I beleive.

**Comment by Yeshasvitvs** [comment]
@jonnew After a lot of struggling, I made peace with the values I get from SolvePnP using CV_ITERATIVE flag and useExtrinsicGuess false. Now I am trying to verify the marker pose values using matlab plots but I have some problems in using the rvecs from solvePnP. I went through some posts on using the output vectors of SolvePnP and accordingly I converted rvecs using rodrigues rotation formula. Yet the pose value of the object is not as It is viewed from the camera. The first figure shows the axes of the marker in gazebo and the pose values computed using SolvePnP. The second figure shows the matlab plots, dotted lines are world coordinate axes, camera coordinates shown with arrows and the object coordinates shown without arrows. In theory the object coordinate systems should be as seen in the first picture, but I cant get it right. Please let me know if I am handling the pose values wrong. Thank you 
![asdasda](https://cloud.githubusercontent.com/assets/6505998/24634439/4da624ae-18ce-11e7-8772-9eab117a5f42.png)
![pose](https://cloud.githubusercontent.com/assets/6505998/24634440/4da73394-18ce-11e7-9ce2-43ed62807935.jpg)

**Comment by Yeshasvitvs** [comment]
@jonnew found the problem, the gazebo camera frame is defined differently from the standard camera frame definition which is assumed in estimating the marker pose.
