### ISSUE TITLE
Is the matlab module still need some work?

### ISSUE THREAD

**Issue by jinglingzhua** [opencv/opencv_contrib#946]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

it seems that
the module can't compile with opencv_world, although a small modification could fix it.
those member functions such as Bridge::toSize(), Bridge::toPoint(), just return the default construct result (0,0)
is these ture? or do i miss something?

**Comment by anuppari** [comment]
I have the same issue. None of bridge type conversions seem to do anything, resulting in errors when trying to use the opencv functions. For example, `cv.findChessboardCorners` requires a size argument, but the `Bridge::toSize()` seems to only feed in the `cv::Size(0,0)`.
