### ISSUE TITLE
Can I build and publish a python wheel package to pypi?

### ISSUE THREAD

**Issue by codeskyblue** [opencv/opencv_contrib#948]
Sorry to ask question here. just hard to sign a user in http://answers.opencv.org because of bad network.

I know there are some non-free algorithm. but this repo lincense is BSD. which confused me about is it ok to publish to pypi as an python package?

**Comment by mshabunin** [comment]
There is `OPENCV_ENABLE_NONFREE` cmake option: https://github.com/opencv/opencv/search?utf8=%E2%9C%93&q=OPENCV_ENABLE_NONFREE
But SIFT and SURF are not guarded properly at this moment: https://github.com/opencv/opencv_contrib/search?utf8=%E2%9C%93&q=OPENCV_ENABLE_NONFREE

As I know, these algorithm are patented and can not be used

**Comment by codeskyblue** [comment]
interesting thing is that the code is public. so can the build binary be also publish?
