### ISSUE TITLE
xphoto inpaint crush

### ISSUE THREAD

**Issue by saedrna** [opencv/opencv_contrib#965]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Mac OS(installed with homebrew) and Windows(installed with cmake)
- Compiler => clang(mac os) and msvc 2015 (windows)

##### Detailed description

Sometimes the xphoto::inpaint function will crash with exception ```Exception: EXC_BAD_ACCESS (code=1, address=0x11ef10ffc)``` . But not for all the images.

##### Steps to reproduce
I have upload a project with images below. And here is the code.

```
#include <iostream>
#include <string>
#include <vector>

#include <opencv2/core.hpp>
#include <opencv2/xphoto.hpp>
#include <opencv2/highgui.hpp>

using namespace std;
using namespace cv;

void inpaint_rgb() {
    string path_mask = "mask1.png";
    string path_gt = "1.png";
    string path_img = path_gt;
    string path_inpaint = "result-1.png";

    Mat gt = cv::imread(path_gt, cv::IMREAD_GRAYSCALE);
    Mat mask = cv::imread(path_mask, cv::IMREAD_GRAYSCALE);
    Mat img = cv::imread(path_img, cv::IMREAD_COLOR);

    img.setTo(cv::Scalar(0,0,0), mask == 255);
    Mat inpainted;
    mask = 255 - mask;
    cv::xphoto::inpaint(img, mask, inpainted, 0);
    cv::imwrite(path_inpaint, inpainted);
}

int main() {
    inpaint_rgb();
    return 0;
}
```

[inpaint.zip](https://github.com/opencv/opencv_contrib/files/721644/inpaint.zip)

**Comment by savuor** [comment]
@saedrna this code produces an error very rarely, usually it works with no problem.
Also I failed to reproduce this on Linux.
Will keep trying to catch a problem.

**Comment by saedrna** [comment]
Yes, really weird. Because previously, when I debug this code, I came into exceptions and the code stop in somewhere in annf.hpp, in Visual Studio 2015. But today, (when I want to show you where is the code) the program runs fine.

Also on Mac, not all the images will produce the exception, when using a [inpaint benchmark dataset](https://www.mmk.ei.tum.de/tumiid/).

I will keep you informed when I manage to locate an error.

**Comment by saedrna** [comment]
I have successfully build the debug version of opencv_contrib and here is more debug information.

The problem is located in the following function, and the value x itself is bad allocated. Although this is on Mac, I remember the problem is the same for Windows VS 2015.

```
class KDTreeComparator
    {
        const KDTree <Tp, cn> *main; // main class
        int dimIdx; // dimension to compare

    public:
        bool operator () (const int &x, const int &y) const
        {
            cv::Vec <Tp, cn> u = main->data[main->idx[x]];
            cv::Vec <Tp, cn> v = main->data[main->idx[y]];

            return  u[dimIdx] < v[dimIdx];
        }

        KDTreeComparator(const KDTree <Tp, cn> *_main, int _dimIdx)
            : main(_main), dimIdx(_dimIdx) {}
    };
```

<img width="641" alt="2" src="https://cloud.githubusercontent.com/assets/3850191/22237699/7423f780-e248-11e6-81f1-422d209cf323.png">

This functor is used in the nth_element function, idx seems to a growing sequence and here is something not consistent. (left = 0, right = 153601). Because I do not quite understand the algorithm, I can not go any further. Hope this will help.

```
  std::nth_element(/**/
            idx.begin() +  _left,
            idx.begin() +    nth,
            idx.begin() + _right, comp
                         /**/);
```

<img width="190" alt="3" src="https://cloud.githubusercontent.com/assets/3850191/22237862/5c8ea4c0-e249-11e6-95c4-e2d8eac5f89d.png">

**Comment by saedrna** [comment]
Here is an dataset that will cause problem. 

The problem is another space, where whs is 12 channel but kdtree requires 24, and crash in the constructor.
![image](https://cloud.githubusercontent.com/assets/3850191/22822831/f4c5fe9e-efbb-11e6-90ba-1f27cc0fa029.png)

![image](https://cloud.githubusercontent.com/assets/3850191/22822864/256db302-efbc-11e6-8383-632378b37b72.png)


The code is below. And the dataset is attached.
```
#include "stdafx.h"
#include <iostream>
#include <string>
#include <vector>

#include <opencv2/core.hpp>
#include <opencv2/xphoto.hpp>
#include <opencv2/highgui.hpp>

using namespace std;
using namespace cv;

int main() {

    string path_mask = "mask.tif";
    string path_image = "img.tif";

    Mat img = cv::imread(path_image, cv::IMREAD_UNCHANGED);
    Mat mask = cv::imread(path_mask, cv::IMREAD_UNCHANGED);

    Mat inpainted;
    xphoto::inpaint(img, mask, inpainted, 0);

    cv::imshow("inpaint", inpainted);
    cv::waitKey();

    return 0;
}
```
[inpaint.zip](https://github.com/opencv/opencv_contrib/files/766335/inpaint.zip)

**Comment by savuor** [comment]
@saedrna I confirm the bug, it is reproduced, now investigating it

**Comment by alalek** [comment]
@kznsq Feel free to prepare Pull Request (bugfix patches should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into 3.4 branch first)
