### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by sadegh01** [opencv/opencv_contrib#966]
##### System information (version)
OpenCV => 3.2
Operating System / Platform => Centos 7 x64
Compiler => gcc4.8.5

which version of  opencv_contrib is compatible with opencv3.2 I tested  opencv_contrib-3.1.0 and 
opencv_contrib-3.2.0-rc and opencv_contrib-3.2.0 . I got Error on all . I used 
-D OPENCV_EXTRA_MODULES_PATH switch

**Comment by mshabunin** [comment]
The compatible version is 3.2.0. If you have any problems with a build, please try to clean build directory first or search for similar issues marked as _"build"_ in [main repository](https://github.com/opencv/opencv/issues?q=is%3Aopen+is%3Aissue+label%3A%22category%3A+build%2Finstall%22) and in [contrib repository](https://github.com/opencv/opencv_contrib/issues?q=is%3Aopen+is%3Aissue+label%3A%22category%3A+build%2Finstall%22) or try to ask [on forum](http://answers.opencv.org).

If you are sure there is a problem with build scripts, then please add more details and reopen this issue.
