### ISSUE TITLE
Downloading Wrong version of vgg_generated_XX

### ISSUE THREAD

**Issue by sadegh01** [opencv/opencv_contrib#967]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
I want to Compile opencv3.2.0 with opencv_contrib3.2.0 . I add these flags 
-D OPENCV_EXTRA_MODULES_PATH=../modules/opencv_contrib-3.2.0/modules  
-DINSTALL_CREATE_DISTRIB=ON
 -DBUILD_opencv_world=OFF
but i get these Errors 
CMake Warning at cmake/OpenCVUtils.cmake:1020 (message):
  Download: Local copy of vgg_generated_48.i has invalid MD5 hash:
  d41d8cd98f00b204e9800998ecf8427e (expected:
  e8d0dcd54d1bcfdc29203d011a797179)
Call Stack (most recent call first):
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/download_vgg.cmake:13 (ocv_download)
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/download_vgg.cmake:20 (vgg_download)
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/CMakeLists.txt:4 (include)

-- Downloading vgg_generated_48.i...
CMake Error at cmake/OpenCVUtils.cmake:1043 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/sadegh/core/FINAL/opencv-3.2.0/modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/.download/e8d0dcd54d1bcfdc29203d011a797179/vgg_generated_48.i]
      expected hash: [e8d0dcd54d1bcfdc29203d011a797179]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]

Call Stack (most recent call first):
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/download_vgg.cmake:13 (ocv_download)
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/download_vgg.cmake:20 (vgg_download)
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/CMakeLists.txt:4 (include)

CMake Error at cmake/OpenCVUtils.cmake:1047 (message):
  Failed to download vgg_generated_48.i.  Status=7;"Couldn't connect to
  server"
Call Stack (most recent call first):
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/download_vgg.cmake:13 (ocv_download)
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/cmake/download_vgg.cmake:20 (vgg_download)
  modules/opencv_contrib-3.2.0/modules/xfeatures2d/CMakeLists.txt:4 (include)
Would you plese help me to fnd out how to correct these errors ?
Thanksin Advance

**Comment by sadegh01** [comment]
why you Closed My question ?  I can not find the answer and the duplicate label you mentioned is completely irrelevant.The Download Files from repository has wrong MD5 . how Can  solve this on my PC ?

**Comment by mshabunin** [comment]
@sadegh01 , there is similar issue #832

**Comment by alalek** [comment]
"Duplicate" means that you should find search "button" and check for similar issues - all good reporters must do this before creation of new issues.
https://github.com/opencv/opencv/issues/5973
https://github.com/opencv/opencv/issues/6122
https://github.com/opencv/opencv/issues/5546

**Comment by show0k** [comment]
@sadegh01 Did you pass through this issue ?
My wrong hash is exactly the same than yours, so it is not a corrupted download issue as suggested in "Dublicate" propositions.

**Comment by mshabunin** [comment]
@show0k , `d41d8cd98f00b204e9800998ecf8427e` is a hash for empty string: http://stackoverflow.com/questions/10909976/why-do-seemingly-empty-files-and-strings-produce-md5sums

It means cmake can not download the file.

**Comment by show0k** [comment]
It works now (without any change), and I was not behind proxy before... Thanks for the answer.

**Comment by lubyagin** [comment]
It works after downloading .i files from https://github.com/cbalint13/opencv-dlco/tree/master/workspace/opencv (warnings about MD5 mismatch)

**Comment by aleb** [comment]
I downloaded the vgg*.i files to `opencv_contrib/modules/xfeatures2d/src` but when running cmake it tries to download them again. Where exactly did you download them?

**Comment by mshabunin** [comment]
Downloaded files are stored in `opencv/.cache` folder in form `<tag>/<md5>-<filename>.<ext>`:
```
opencv/.cache/
    └── vgg
        ├── 151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
        ├── 7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
        ├── 7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
        └── e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
```

**Comment by aleb** [comment]
I managed to make it work with OpenCV 3.2.0 on Jetson TK1 like this:
Download the files:
```
git clone https://github.com/opencv/opencv_3rdparty.git
cd opencv_3rdparty.git
# The two SHA are from opencv_contrib/modules/xfeatures2d/cmake/download_*.cmake:
# set(OPENCV_3RDPARTY_COMMIT "34e4206aef44d50e6bbcd0ab06354b52e7466d26")
# set(OPENCV_3RDPARTY_COMMIT "fccf7cd6a4b12079f73bbfb21745f9babcd4eb1d")
git checkout 34e4206aef44d50e6bbcd0ab06354b52e7466d26 && cp *.i /tmp
git checkout fccf7cd6a4b12079f73bbfb21745f9babcd4eb1d && cp *.i /tmp
```

Copy them to both the cache dir and the src dir:
```
rm -f opencv/.cache/vgg/*; for i in vgg_generated_120.i  vgg_generated_48.i vgg_generated_64.i  vgg_generated_80.i boostdesc_bgm.i  boostdesc_bgm_bi.i  boostdesc_bgm_hd.i  boostdesc_binboost_064.i  boostdesc_binboost_128.i  boostdesc_binboost_256.i  boostdesc_lbgm.i; do cp /tmp/$i opencv_contrib/modules/xfeatures2d/src; cp /tmp/$i opencv/.cache/vgg/$(md5sum /tmp/$i | cut -d' ' -f1)-$i; done
```

**Comment by mshabunin** [comment]
BTW, you can also use `<build-dir>/CMakeDownloadLog.txt` to determine which files should be downloaded and where to put them.

**Comment by mshabunin** [comment]
Here is a command which will manually download all files which cmake tried to get:
```
cd <build_dir>
grep cmake_download CMakeDownloadLog.txt | sed 's/#cmake_download//' | xargs -r -L 1 wget -O
```
