### ISSUE TITLE
new errors on build in vs2010

### ISSUE THREAD

**Issue by oqtvs** [opencv/opencv_contrib#975]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform = Windows 32 Bit
- Compiler = Visual Studio 2010

##### Detailed description
Hi, I was trying to build opencv with xfeatures2d module while using Visual Studio 2010 and i got the following errors:
```
41>..\..\..\..\opencv_contrib\modules\xfeatures2d\src\pct_signatures.cpp(400): error C2668: 'cv::sqrt' : ambiguous call to overloaded function
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(589): could be 'long double sqrt(long double)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(541): or       'float sqrt(float)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(127): or       'double sqrt(double)'
41>          while trying to match the argument list '(const int)'

41>..\..\..\..\opencv_contrib\modules\xfeatures2d\src\harris_lapace_detector.cpp(107): error C2668: 'log' : ambiguous call to overloaded function
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(575): could be 'long double log(long double)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(527): or       'float log(float)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(120): or       'double log(double)'

41>..\..\..\..\opencv_contrib\modules\xfeatures2d\src\boostdesc.cpp(235): error C3861: 'round': identifier not found
```

I think these errors are caused by the use of an older C++ standard(C++98).

Does the opencv_contrib repository continues to follow the OpenCV Coding Style Guide (http://code.opencv.org/projects/opencv/wiki/Coding_Style_Guide)?

> ie: Formally, the code must comply with the C++ 98 standard

If so maybe this is an issue.

Also while I was searching for an already posted issue into this matter I noticed (https://github.com/opencv/opencv_contrib/issues/754) that deals with problems with builds with visual studio 2010. So i was wondering, is there an automatic build system for opencv that deals with this checks?

Thank you all in advance!

**Comment by alalek** [comment]
There are no automatic builds with MSVC2010 compiler, because this version is not supported anymore by OpenCV team.
Feel free to provide a fix, we will take a look on it. And if it doesn't break anything - we'll accept it.
