### ISSUE TITLE
tracking code causes std::bad_alloc error

### ISSUE THREAD

**Issue by simon1tan** [opencv/opencv_contrib#976]
Getting this error when I run multitracker.py  and tracker.py:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

This is tirggered when this code is executed:
    ok = tracker.add(image, (bbox1,bbox2))

tracker.cpp and multitracker.cpp both run fine. My video is 1.1MB. I have about 1GB memory available so don't think it's a memory issue. Running opencv-3.2.0, Ubuntu 16, python2.7.12

**Comment by sovrasov** [comment]
To reproduce this the video and system information are required.

**Comment by leferrad** [comment]
The same is happen with me. I think it's something related to the bbox passed as argument. I've tried to do it by specifying both a rectangle (x0, y0, x1, y1) and a ROI (x0,y0,height,width) but it still failing. It was done based on these links:

https://www.learnopencv.com/object-tracking-using-opencv-cpp-python/
http://answers.opencv.org/question/43713/confuse-with-the-roi-rect-parameter/

Please let me know about possible causes, either a misuse of the function or a possible bug of the module.

**Comment by giovannicaprio** [comment]
Any luck solving this out?

**Comment by Jack8861** [comment]
So, basically its the bounding box format which caused the problem

(xmin,ymin,boxwidth,boxheight)

I got to know about it here:
https://stackoverflow.com/questions/49301389/boundingbox-defintion-for-opencv-object-tracking
