### ISSUE TITLE
opencv_contrib configuration failed

### ISSUE THREAD

**Issue by Herschelpu** [opencv/opencv_contrib#984]
I am trying to build extra module of opencv (in fact I need to use aruco)
so i used the following command in /home/pi/opencv_3.0/opencv-3.1.0/build directory:

cmake -D OPENCV_EXTRA_MODULES_PATH=/home/pi/opencv_3.0/opencv-3.1.0/source/modules/opencv_contrib/modules  /home/pi/opencv_3.0/opencv-3.1.0

the error shows like this:

-- Detected version of GNU GCC: 49 (409)
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-video-1.0'
--   No package 'gstreamer-video-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Checking for module 'gstreamer-base-0.10'
--   No package 'gstreamer-base-0.10' found
-- Checking for module 'gstreamer-video-0.10'
--   No package 'gstreamer-video-0.10' found
-- Checking for module 'gstreamer-app-0.10'
--   No package 'gstreamer-app-0.10' found
-- Checking for module 'gstreamer-riff-0.10'
--   No package 'gstreamer-riff-0.10' found
-- Checking for module 'gstreamer-pbutils-0.10'
--   No package 'gstreamer-pbutils-0.10' found
-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - not found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- Looking for libavformat/avformat.h
-- Looking for libavformat/avformat.h - found
-- Looking for ffmpeg/avformat.h
-- Looking for ffmpeg/avformat.h - not found
-- Checking for module 'libgphoto2'
--   No package 'libgphoto2' found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- To enable PlantUML support, set PLANTUML_JAR environment variable or pass -DPLANTUML_JAR=<filepath> option to cmake
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.9", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython2.7.so (found suitable exact version "2.7.9") 
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4.2", minimum required is "3.4") 
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.4m.so (found suitable exact version "3.4.2") 
-- Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Could NOT find Matlab (missing:  MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- Caffe:   NO
-- Protobuf:   NO
-- Glog:   NO
-- freetype2:   YES
-- harfbuzz:    YES
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS HDF5_HL_LIBRARIES) 
-- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
-- freetype2:   YES
-- harfbuzz:    YES
-- Checking for modules 'tesseract;lept'
--   No package 'tesseract' found
--   No package 'lept' found
-- Tesseract:   NO
CMake Error at source/modules/opencv_contrib/modules/text/CMakeLists.txt:22 (ocv_add_testdata):
  Unknown CMake command "ocv_add_testdata".

-- Configuring incomplete, errors occurred!
See also "/home/pi/opencv_3.0/opencv-3.1.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/opencv_3.0/opencv-3.1.0/build/CMakeFiles/CMakeError.log".

is there anything that I haven't installed or incorrect? I'm new to opencv and linux...
urgently need help ...

**Comment by alalek** [comment]
You should keep source code of both repositories opencv and opencv_contrib "in sync". Different versions are not supported.

**Comment by Herschelpu** [comment]
thank you but I had tried to keep opencv and opencv_contrib in parallel directories, same problem happened. So I changed the address of opencv_contrib but nothing helped.
