### ISSUE TITLE
how to create trained_classifierNM1.xml file

### ISSUE THREAD

**Issue by hoangtocdo90** [opencv/opencv_contrib#992]
Hi guys!
thank for come in 🗡 
i'm new for opencv. i'm testing opencv.text module with tesseract. Everythings is ok but when i try to process with non english ocr images, doesn't catch any non english char, i;m thinking maybe need train some things  in this xml file.
Some body can tell me how to create it  for non english.
Thanks you ~~

**Comment by Chenhui2018** [comment]
Hello @hoangtocdo90, did you solve the problem? As far as I know, the "trained_classifierNM1.xml" was created by Boost with 8 features, you can check the paper 

"Real-Time Scene Text Localization and Recognition - Luka ´s Neumann Ji ˇ ˇ r´ ı Matas" 

for detail. free to download.

My problem is what is the training set for "trained_classifierNM1.xml".
any information is helpful, thanks for sharing!
