### ISSUE TITLE
Build bot does not build sfm module

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv_contrib#993]
When checking the build logs, it seems that the sfm module is not build and thus not incorporated in the CI.

E.g. 
http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_windows64/builds/10031/steps/cmake/logs/stdio
> Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags

and the corresponding linux build (where at least Eigen is found):
http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/10032/steps/cmake/logs/stdio
> Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags

This also corresponds with the finding that we are currently unavailable to build SFM because the Cmake does not find the required dependencies and aborts. We use MSVC2013 x64 which should work since PR #789

**Comment by sovrasov** [comment]
Probably glog/gflags detection was broken again in #824

**Comment by PhilLab** [comment]
@sovrasov Thanks for fixing this. Do you have any idea, why it fails for Windows?

> Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags

http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_windows64/builds/10129/steps/cmake/logs/stdio

**Comment by sovrasov** [comment]
I think glog/gflags and Eigen are not installed on the Windows slave.
